In [1]:
import pandas as pd

In [4]:
data=pd.read_excel("../data/Dataset EP Elections at Constituency Level, 1979-2019_Caramani.xlsx")
data

,country,constituency,year,party,party_original,coalition,ep_affiliation,seats_total,seats,eligible,votes_total,votes_valid,votes,votes_share,electoral_formula,source1,source2,source3,notes
0,Austria,National,2019,Austrian People's Party,Österreichische Volkspartei,.,EPP,18,7,6416177,3834662,3779764,1305956,34.551258,D'Hondt,NaN,NaN,NaN,NaN
1,Austria,National,2019,Social Democratic Party,Sozialdemokratische Partei Österreichs,.,S&D,18,5,6416177,3834662,3779764,903151,23.894375,D'Hondt,https://en.wikipedia.org/wiki/2019_European_Pa...,NaN,NaN,NaN
2,Austria,National,2019,Freedom Party of Austria,Freiheitliche Partei Österreichs,.,ID,18,3,6416177,3834662,3779764,650114,17.199857,D'Hondt,https://www.bmi.gv.at/412/Europawahlen/Europaw...,NaN,NaN,NaN
3,Austria,National,2019,The Greens,Die Grünen,.,Greens/EFA,18,2,6416177,3834662,3779764,532193,14.080059,D'Hondt,NaN,NaN,NaN,NaN
4,Austria,National,2019,The New Austria and Liberal Forum,Das Neue Österreich und Liberales Forum,.,Renew Europe,18,1,6416177,3834662,3779764,319024,8.440315,D'Hondt,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4593,United Kingdom,Yorkshire South West,1979,Others,Others,.,.,1,0,501477,.,145480,0,0.000000,First past the post,NaN,NaN,NaN,"votes_total not available, turnout values do m..."
4594,United Kingdom,Yorkshire West,1979,Conservative Party,Conservative Party,.,.,1,0,497379,.,165567,73555,44.426124,First past the post,NaN,NaN,NaN,"votes_total not available, turnout values do m..."
4595,United Kingdom,Yorkshire West,1979,Labour Party,Labour Party,.,S,1,1,497379,.,165567,76552,46.236267,First past the post,NaN,NaN,NaN,"votes_total not available, turnout values do m..."
4596,United Kingdom,Yorkshire West,1979,Liberal Democrats,Liberal Democrats,.,.,1,0,497379,.,165567,15460,9.337610,First past the post,NaN,NaN,NaN,"votes_total not available, turnout values do m..."
4597,United Kingdom,Yorkshire West,1979,Others,Others,.,.,1,0,497379,.,165567,0,0.000000,First past the post,NaN,NaN,NaN,"votes_total not available, turnout values do m..."

In [6]:
partys_elected=data[data["seats"]>0]
partys_elected

,country,constituency,year,party,party_original,coalition,ep_affiliation,seats_total,seats,eligible,votes_total,votes_valid,votes,votes_share,electoral_formula,source1,source2,source3,notes
0,Austria,National,2019,Austrian People's Party,Österreichische Volkspartei,.,EPP,18,7,6416177,3834662,3779764,1305956,34.551258,D'Hondt,NaN,NaN,NaN,NaN
1,Austria,National,2019,Social Democratic Party,Sozialdemokratische Partei Österreichs,.,S&D,18,5,6416177,3834662,3779764,903151,23.894375,D'Hondt,https://en.wikipedia.org/wiki/2019_European_Pa...,NaN,NaN,NaN
2,Austria,National,2019,Freedom Party of Austria,Freiheitliche Partei Österreichs,.,ID,18,3,6416177,3834662,3779764,650114,17.199857,D'Hondt,https://www.bmi.gv.at/412/Europawahlen/Europaw...,NaN,NaN,NaN
3,Austria,National,2019,The Greens,Die Grünen,.,Greens/EFA,18,2,6416177,3834662,3779764,532193,14.080059,D'Hondt,NaN,NaN,NaN,NaN
4,Austria,National,2019,The New Austria and Liberal Forum,Das Neue Österreich und Liberales Forum,.,Renew Europe,18,1,6416177,3834662,3779764,319024,8.440315,D'Hondt,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4578,United Kingdom,Wight and Hampshire East,1979,Conservative Party,Conservative Party,.,ED,1,1,575991,.,198563,128414,64.671666,First past the post,NaN,NaN,NaN,"votes_total not available, turnout values do m..."
4582,United Kingdom,Yorkshire North,1979,Conservative Party,Conservative Party,.,ED,1,1,483639,.,166684,98464,59.072256,First past the post,NaN,NaN,NaN,"votes_total not available, turnout values do m..."
4587,United Kingdom,Yorkshire South,1979,Labour Party,Labour Party,.,S,1,1,530714,.,143171,83490,58.314882,First past the post,NaN,NaN,NaN,"votes_total not available, turnout values do m..."
4591,United Kingdom,Yorkshire South West,1979,Labour Party,Labour Party,.,S,1,1,501477,.,145480,75473,51.878609,First past the post,NaN,NaN,NaN,"votes_total not available, turnout values do m..."
4595,United Kingdom,Yorkshire West,1979,Labour Party,Labour Party,.,S,1,1,497379,.,165567,76552,46.236267,First past the post,NaN,NaN,NaN,"votes_total not available, turnout values do m..."

In [7]:
partys_elected.groupby("year").count()

,country,constituency,party,party_original,coalition,ep_affiliation,seats_total,seats,eligible,votes_total,votes_valid,votes,votes_share,electoral_formula,source1,source2,source3,notes
year,,,,,,,,,,,,,,,,,,
1979,158,158,158,158,158,158,158,158,158,158,158,158,158,158,7,1,0,89
1981,6,6,6,6,6,6,6,6,6,6,6,6,6,6,1,1,0,0
1984,158,158,158,158,158,158,158,158,158,158,158,158,158,158,6,2,0,90
1987,12,12,12,12,12,12,12,12,12,12,12,12,12,12,2,0,0,0
1989,110,110,110,110,110,110,110,110,110,110,110,110,110,110,10,2,0,13
1994,114,114,114,114,114,114,114,114,114,114,114,114,114,114,11,2,0,12
1996,12,12,12,12,12,12,12,12,12,12,12,12,12,12,0,0,0,0
1999,182,182,182,182,182,182,182,182,182,182,182,182,182,182,14,2,1,12
2004,300,300,300,300,300,300,300,300,300,300,300,300,300,300,59,4,1,23
2007,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0,0,0,1
2009,286,286,286,286,286,286,286,286,286,286,286,286,286,286,15,1,0,22
2013,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,0,0,0
2014,302,302,302,302,302,302,302,302,302,302,302,302,302,302,12,5,1,24
2019,260,260,260,260,260,260,260,260,260,260,260,260,260,260,71,6,3,35

In [11]:
eu_partys_per_year=partys_elected[["year","ep_affiliation"]].drop_duplicates()
eu_partys_per_year

      year ep_affiliation
0     2019            EPP
1     2019            S&D
2     2019             ID
3     2019     Greens/EFA
4     2019   Renew Europe
...    ...            ...
3295  2014          G/EFA
3316  1999            EPP
3377  2019              .
3467  2014        GUE/NFL
3468  2014   Non inscrits

[138 rows x 2 columns]

In [12]:
eu_partys_per_year.groupby("year").count()

      ep_affiliation
year
1979               8
1981               4
1984               9
1987               8
1989              15
1994              14
1996               7
1999              12
2004              13
2007               4
2009              13
2013               3
2014              16
2019              12