In [6]:
import pandas as pd
import glob
import yfinance

In [7]:
list_of_emerging_markets = [
    "Afghanistan", "Albania", "Algeria", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Azerbaijan", 
    "Bahamas, The", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belize", "Benin", "Bhutan", "Bolivia", 
    "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", 
    "Cabo Verde", "Cambodia", "Cameroon", "Central African Republic", "Chad", "Chile", "China, People's Republic of", 
    "Colombia", "Comoros", "Congo, Dem. Rep. of the", "Congo, Republic of", "Costa Rica", "Curacao", "Côte d'Ivoire", 
    "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", 
    "Eswatini", "Ethiopia", "Fiji", "Gabon", "Gambia, The", "Georgia", "Ghana", "Grenada", "Guatemala", "Guinea", 
    "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "India", "Indonesia", "Iran", "Iraq", "Jamaica", 
    "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyz Republic", "Lao P.D.R.", "Lebanon", 
    "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Marshall Islands", 
    "Mauritania", "Mauritius", "Mexico", "Micronesia, Fed. States of", "Moldova", "Mongolia", "Montenegro", 
    "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Nicaragua", "Niger", "Nigeria", 
    "North Macedonia", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", 
    "Poland", "Qatar", "Romania", "Russian Federation", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", 
    "Saint Vincent and the Grenadines", "Samoa", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", 
    "Sint Maarten", "Solomon Islands", "Somalia", "South Africa", "South Sudan, Republic of", "Sri Lanka", "Sudan", 
    "Suriname", "Syria", "São Tomé and Príncipe", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", 
    "Tonga", "Trinidad and Tobago", "Tunisia", "Turkmenistan", "Tuvalu", "Türkiye, Republic of", "Uganda", "Ukraine", 
    "United Arab Emirates", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "West Bank and Gaza", 
    "Yemen", "Zambia", "Zimbabwe"
]

In [8]:
files=glob.glob('../data/*.xlsx')
files

['../data/GrossDebt_allcountries.xlsx', '../data/GPD_allcountries.xlsx']

In [9]:
data=pd.read_excel(files[1], engine='openpyxl')

In [10]:
data.columns

Index(['GDP, current prices (Billions of U.S. dollars)',
                                                   1980,
                                                   1981,
                                                   1982,
                                                   1983,
                                                   1984,
                                                   1985,
                                                   1986,
                                                   1987,
                                                   1988,
                                                   1989,
                                                   1990,
                                                   1991,
                                                   1992,
                                                   1993,
                                                   1994,
                                                   1995,
                                                   1996,
                                                   1997,
                                                   1998,
                                                   1999,
                                                   2000,
                                                   2001,
                                                   2002,
                                                   2003,
                                                   2004,
                                                   2005,
                                                   2006,
                                                   2007,
                                                   2008,
                                                   2009,
                                                   2010,
                                                   2011,
                                                   2012,
                                                   2013,
                                                   2014,
                                                   2015,
                                                   2016,
                                                   2017,
                                                   2018,
                                                   2019,
                                                   2020,
                                                   2021,
                                                   2022,
                                                   2023,
                                                   2024,
                                                   2025,
                                                   2026,
                                                   2027,
                                                   2028,
                                                   2029,
                                                   2030],
      dtype='object')

In [11]:
emerging_markets=data[data["GDP, current prices (Billions of U.S. dollars)"].isin(list_of_emerging_markets)]
emerging_markets

,"GDP, current prices (Billions of U.S. dollars)",1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030
1,Afghanistan,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,14.278,14.501,17.248,no data,no data,no data,no data,no data,no data,no data
2,Albania,1.969,2.256,2.323,2.347,2.317,2.366,2.617,2.597,2.56,...,18.086,19.185,23.388,27.259,28.372,29.743,31.382,33.354,35.462,37.683
3,Algeria,45.957,48.156,48.599,51.582,55.906,66.346,66.783,68.698,56.07,...,185.85,225.709,247.789,264.913,268.885,269.435,274.52,279.983,285.271,290.941
5,Angola,8.73,8.17,8.17,8.514,9.025,11.119,10.411,11.9,12.909,...,84.375,142.442,109.764,115.946,113.343,109.384,112.743,118.534,125.036,132.281
6,Antigua and Barbuda,0.132,0.149,0.166,0.185,0.212,0.246,0.298,0.347,0.411,...,1.602,1.867,2.006,2.225,2.373,2.493,2.606,2.723,2.846,2.974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,Vietnam,35.357,17.617,23.369,35.204,61.171,19.045,43.009,53.385,29.501,...,370.076,411.068,433.008,459.472,490.97,518.999,553.437,589.412,626.91,666.539
193,West Bank and Gaza,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,18.109,19.166,17.848,no data,no data,no data,no data,no data,no data,no data
194,Yemen,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,19.394,23.534,19.412,19.101,17.401,17.285,18.762,21.713,23.602,25.717
195,Zambia,4.246,4.385,4.232,3.653,3.003,2.848,1.962,2.431,4.095,...,22.096,29.164,27.578,26.326,28.91,34.237,40.161,43.668,47.092,50.669
196,Zimbabwe,no data,no data,no data,no data,no data,no data,no data,no data,no data,...,36.016,32.613,35.144,35.224,38.172,39.491,40.925,42.34,43.836,45.384

In [12]:
emerging_markets[emerging_markets.columns[1:]]=emerging_markets[emerging_markets.columns[1:]].apply(pd.to_numeric, errors='coerce')
emerging_markets

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_2859/3544614666.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emerging_markets[emerging_markets.columns[1:]]=emerging_markets[emerging_markets.columns[1:]].apply(pd.to_numeric, errors='coerce')

,"GDP, current prices (Billions of U.S. dollars)",1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030
1,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.278,14.501,17.248,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,1.969,2.256,2.323,2.347,2.317,2.366,2.617,2.597,2.560,...,18.086,19.185,23.388,27.259,28.372,29.743,31.382,33.354,35.462,37.683
3,Algeria,45.957,48.156,48.599,51.582,55.906,66.346,66.783,68.698,56.070,...,185.850,225.709,247.789,264.913,268.885,269.435,274.520,279.983,285.271,290.941
5,Angola,8.730,8.170,8.170,8.514,9.025,11.119,10.411,11.900,12.909,...,84.375,142.442,109.764,115.946,113.343,109.384,112.743,118.534,125.036,132.281
6,Antigua and Barbuda,0.132,0.149,0.166,0.185,0.212,0.246,0.298,0.347,0.411,...,1.602,1.867,2.006,2.225,2.373,2.493,2.606,2.723,2.846,2.974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,Vietnam,35.357,17.617,23.369,35.204,61.171,19.045,43.009,53.385,29.501,...,370.076,411.068,433.008,459.472,490.970,518.999,553.437,589.412,626.910,666.539
193,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.109,19.166,17.848,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.394,23.534,19.412,19.101,17.401,17.285,18.762,21.713,23.602,25.717
195,Zambia,4.246,4.385,4.232,3.653,3.003,2.848,1.962,2.431,4.095,...,22.096,29.164,27.578,26.326,28.910,34.237,40.161,43.668,47.092,50.669
196,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.016,32.613,35.144,35.224,38.172,39.491,40.925,42.340,43.836,45.384

In [13]:
emerging_markets_top51=emerging_markets.sort_values(by=2025,ascending=False).head(51)
emerging_markets_top51.rename(columns={ "GDP, current prices (Billions of U.S. dollars)":"Country"}, inplace=True)

In [14]:
gross_debt=pd.read_excel(files[0], engine='openpyxl')
gross_debt[gross_debt.columns[1:]]=gross_debt[gross_debt.columns[1:]].apply(pd.to_numeric, errors='coerce')
gross_debt.rename(columns={ "General government gross debt (Percent of GDP)":"Country"}, inplace=True)
gross_debt

,Country,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.1,10.6,8.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,74.8,65.2,58.4,55.7,54.3,53.5,52.7,51.9,51.0,50.1
3,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55.1,48.1,47.7,46.2,57.8,67.0,73.5,77.8,81.3,84.4
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.6,38.9,35.5,33.2,32.0,30.9,30.0,29.5,29.0,28.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,Middle East and Central Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51.9,44.8,45.7,45.4,47.9,49.4,49.9,50.3,50.4,50.3
224,Other advanced economies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49.4,48.2,49.6,50.4,51.1,51.3,51.1,51.0,50.9,50.9
225,Sub-Saharan Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.4,56.7,60.4,61.1,61.5,60.4,59.1,57.8,56.4,54.9
226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,"©IMF, 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
emerging_markets_debts=pd.merge(emerging_markets_top51, gross_debt, how='inner', left_on='Country', right_on='Country',suffixes=['_gdp', '_debts'])
emerging_markets_debts.sort_values(by="2025_debts",ascending=True)

,Country,1980_gdp,1981_gdp,1982_gdp,1983_gdp,1984_gdp,1985_gdp,1986_gdp,1987_gdp,1988_gdp,...,2021_debts,2022_debts,2023_debts,2024_debts,2025_debts,2026_debts,2027_debts,2028_debts,2029_debts,2030_debts
46,Turkmenistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.7,5.8,4.7,4.6,4.5,4.4,4.2,4.1,4.0,4.0
31,Kuwait,NaN,25.249,21.583,20.871,21.700,21.445,17.904,22.368,20.690,...,7.2,2.9,3.2,3.0,7.4,10.8,15.3,19.4,23.5,24.4
50,"Congo, Dem. Rep. of the",68.606,59.726,64.939,52.378,34.951,31.943,35.840,33.932,39.314,...,24.7,22.6,25.1,19.3,16.3,13.8,11.5,9.2,7.2,5.8
3,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.5,18.5,19.5,20.3,21.4,22.5,23.7,24.7,25.9,27.2
23,Kazakhstan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.1,23.5,23.0,24.8,25.4,27.9,29.9,31.8,33.5,34.6
5,"Türkiye, Republic of",96.596,97.865,88.918,84.968,82.642,92.827,102.337,118.926,125.032,...,40.4,30.8,29.3,26.0,26.7,27.1,27.1,26.5,26.1,25.8
36,Guatemala,7.718,8.431,8.539,8.864,9.276,10.951,5.921,6.857,7.426,...,30.6,29.0,27.2,26.5,27.2,27.7,28.1,28.3,28.3,28.3
38,Bulgaria,37.751,40.718,42.467,43.641,46.358,39.692,35.130,40.721,66.546,...,22.4,21.5,21.9,23.4,28.0,29.5,31.2,32.9,34.6,36.5
10,United Arab Emirates,41.725,46.461,43.205,39.588,39.245,38.519,30.526,33.519,34.069,...,36.3,32.1,32.4,32.1,32.8,32.6,32.0,31.5,31.0,31.0
32,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.7,30.5,32.2,32.6,33.0,32.9,32.3,32.0,31.2,30.7
13,Vietnam,35.357,17.617,23.369,35.204,61.171,19.045,43.009,53.385,29.501,...,39.2,34.9,34.4,32.9,33.6,34.9,35.6,36.1,36.6,37.1
22,Peru,20.190,24.398,24.259,18.863,19.442,16.823,25.241,41.681,32.978,...,36.1,34.0,33.0,32.8,33.7,34.7,35.5,35.9,35.9,36.0
7,Saudi Arabia,164.540,184.292,153.240,129.181,119.631,103.894,86.886,85.582,88.138,...,28.6,23.8,26.2,29.9,34.8,38.5,40.9,42.9,44.5,45.9
41,Oman,7.269,8.849,9.285,9.733,10.726,11.916,9.433,9.890,9.613,...,61.9,41.7,37.5,35.5,35.4,33.9,32.2,30.6,30.2,29.5
21,Iran,95.846,101.481,125.800,156.927,161.721,180.541,208.928,277.019,311.932,...,42.4,36.9,33.5,36.8,39.9,41.9,43.2,44.3,45.1,45.3
14,Bangladesh,24.775,26.355,24.678,23.904,26.817,28.819,29.639,32.449,34.914,...,35.6,37.9,39.3,40.1,40.3,40.7,41.7,42.8,43.1,43.9
27,Qatar,6.665,7.374,6.467,5.506,5.708,5.339,4.214,4.441,4.260,...,58.4,42.6,43.7,40.8,40.5,39.3,37.2,36.4,36.2,35.4
6,Indonesia,99.296,110.848,113.799,103.149,107.218,107.062,101.220,95.214,107.279,...,41.1,40.1,39.6,40.2,41.0,41.0,41.0,40.9,40.8,40.6
37,Ethiopia,7.385,7.578,7.973,8.863,8.375,9.808,10.188,10.890,11.285,...,53.8,46.9,38.7,32.3,41.8,37.0,34.6,32.7,31.0,29.5
20,Chile,29.032,34.374,25.630,20.819,20.246,17.360,18.662,22.010,25.947,...,36.4,37.9,39.4,42.0,43.0,43.4,43.2,43.5,43.5,44.3
44,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53.6,50.9,45.7,44.5,44.4,44.1,44.3,44.0,43.7,43.2
48,Tanzania,10.873,13.005,14.932,15.294,13.915,12.556,15.874,7.821,7.474,...,43.4,44.9,47.4,48.2,47.1,45.8,44.3,42.9,41.5,40.4
25,Iraq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,54.7,39.0,42.1,42.9,50.2,56.0,58.2,60.4,62.4,64.0
29,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.8,40.4,48.7,52.9,52.5,51.6,49.1,47.6,46.4,45.4
24,Algeria,45.957,48.156,48.599,51.582,55.906,66.346,66.783,68.698,56.070,...,55.1,48.1,47.7,46.2,57.8,67.0,73.5,77.8,81.3,84.4
43,Côte d'Ivoire,13.877,11.502,10.320,9.312,9.284,9.470,12.675,13.944,14.092,...,50.2,56.0,57.5,59.3,58.1,56.4,54.9,53.1,52.0,50.7
12,Philippines,37.082,40.735,42.441,37.953,35.860,34.973,34.129,37.932,43.293,...,57.0,57.4,56.5,57.1,58.1,58.1,57.2,55.8,54.2,52.5
45,Panama,4.253,4.814,5.319,5.461,5.700,6.030,6.266,6.294,5.441,...,54.4,52.7,51.5,56.6,58.1,58.3,57.9,57.0,55.7,54.0
34,Dominican Republic,8.672,9.698,9.141,9.461,14.870,6.496,7.891,8.305,7.605,...,62.8,59.6,60.5,58.8,58.2,57.1,55.5,53.5,51.3,49.1
42,Costa Rica,4.854,2.636,2.619,3.162,3.678,3.941,4.425,4.554,4.636,...,67.6,63.0,61.1,59.8,59.7,59.0,57.9,56.7,55.3,53.7
16,Colombia,46.501,50.661,54.252,53.920,53.257,48.581,48.648,50.640,54.592,...,64.4,61.3,55.5,61.3,59.7,59.9,59.9,59.8,59.4,58.9
4,Mexico,242.153,311.012,225.706,184.010,217.001,230.272,159.434,174.840,213.893,...,56.7,53.8,52.8,58.4,60.7,61.1,61.1,61.1,61.2,61.3
8,Poland,56.908,53.921,65.520,75.792,75.893,71.137,74.053,64.040,68.963,...,53.0,48.8,49.7,55.3,60.7,64.3,65.7,66.8,67.2,67.7
18,Romania,46.053,55.319,55.375,48.401,39.111,48.286,52.290,58.477,60.538,...,51.5,51.7,52.1,57.2,61.6,65.7,68.9,71.5,73.7,75.7
39,Angola,8.730,8.170,8.170,8.514,9.025,11.119,10.411,11.900,12.909,...,74.3,56.1,71.4,62.5,64.5,63.9,62.7,61.5,59.9,57.2
11,Thailand,33.422,35.999,37.799,41.366,43.179,40.185,44.520,52.204,63.704,...,58.3,60.5,62.3,63.2,64.5,66.0,67.0,67.6,68.1,68.3
47,Ghana,38.684,61.487,70.954,49.337,17.998,15.970,15.086,12.692,13.566,...,79.2,85.7,76.4,70.5,66.4,62.7,59.9,57.0,54.1,52.0
33,Kenya,13.449,12.667,12.196,11.279,11.703,11.646,13.832,15.163,15.721,...,68.2,67.8,73.0,65.6,68.3,70.2,69.8,68.1,66.2,64.4
49,Uruguay,12.217,13.636,11.147,6.119,5.819,5.686,7.059,8.832,9.137,...,64.1,59.9,64.0,68.7,68.5,68.3,68.0,67.9,67.7,67.4
30,Morocco,23.807,19.329,19.510,17.635,16.130,16.280,21.497,23.713,28.080,...,69.4,71.5,69.5,70.0,68.9,67.7,66.8,66.2,65.6,65.1
15,Malaysia,26.757,27.321,29.278,32.745,37.087,34.090,30.303,34.529,37.845,...,69.2,65.5,69.7,70.4,70.1,69.8,70.1,70.4,70.6,70.8
9,Argentina,233.696,189.802,94.250,116.267,130.544,98.599,118.565,121.561,142.386,...,81.0,84.5,155.4,85.3,73.1,68.2,65.1,63.3,59.3,55.7
26,Hungary,23.117,23.706,24.142,21.910,21.243,21.511,24.778,27.233,29.800,...,76.2,73.9,73.0,73.5,73.5,73.4,73.5,73.4,73.4,73.2
17,South Africa,89.412,93.150,85.897,96.205,84.838,64.481,73.399,96.533,104.010,...,68.7,70.8,73.4,76.4,79.6,81.7,83.7,85.5,87.1,88.7
1,India,186.170,193.153,200.035,218.218,211.843,233.520,248.398,278.864,294.479,...,83.5,82.2,81.2,81.3,80.4,79.6,78.8,77.9,76.9,75.8
19,Egypt,23.523,25.760,30.479,37.254,41.888,48.841,54.076,77.359,92.530,...,89.9,88.5,95.9,90.9,86.6,85.1,82.0,78.7,75.3,71.4
2,Brazil,145.819,167.583,179.166,143.652,142.957,226.938,263.256,286.539,320.105,...,88.9,83.9,84.0,87.3,92.0,96.0,98.1,99.1,99.4,99.4
0,"China, People's Republic of",303.550,289.215,285.139,306.013,314.832,310.709,301.471,328.305,409.363,...,70.1,75.5,82.0,88.3,96.3,102.3,105.9,109.2,112.6,116.0
28,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.9,77.7,82.3,89.8,110.0,108.5,103.5,100.1,96.2,92.1
35,Ecuador,16.116,16.501,16.474,14.478,15.408,18.020,13.222,12.355,11.749,...,61.8,57.2,54.3,55.0,NaN,NaN,NaN,NaN,NaN,NaN
40,Venezuela,69.841,78.367,79.998,79.672,57.826,59.865,60.877,46.854,60.378,...,254.2,164.4,138.5,164.3,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#welche etfs haben innerhalb eines jahres egal wann ein plus abgeworfen

#welche etfs

In [17]:
emerging_markets_debts["change_of_debts_current"]=emerging_markets_debts["2025_debts"]-emerging_markets_debts["2015_debts"]
emerging_markets_debts["change_of_debts_future"]=emerging_markets_debts["2030_debts"]-emerging_markets_debts["2025_debts"]
emerging_markets_debts

,Country,1980_gdp,1981_gdp,1982_gdp,1983_gdp,1984_gdp,1985_gdp,1986_gdp,1987_gdp,1988_gdp,...,2023_debts,2024_debts,2025_debts,2026_debts,2027_debts,2028_debts,2029_debts,2030_debts,change_of_debts_current,change_of_debts_future
0,"China, People's Republic of",303.550,289.215,285.139,306.013,314.832,310.709,301.471,328.305,409.363,...,82.0,88.3,96.3,102.3,105.9,109.2,112.6,116.0,55.5,19.7
1,India,186.170,193.153,200.035,218.218,211.843,233.520,248.398,278.864,294.479,...,81.2,81.3,80.4,79.6,78.8,77.9,76.9,75.8,11.4,-4.6
2,Brazil,145.819,167.583,179.166,143.652,142.957,226.938,263.256,286.539,320.105,...,84.0,87.3,92.0,96.0,98.1,99.1,99.4,99.4,20.3,7.4
3,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.5,20.3,21.4,22.5,23.7,24.7,25.9,27.2,6.1,5.8
4,Mexico,242.153,311.012,225.706,184.010,217.001,230.272,159.434,174.840,213.893,...,52.8,58.4,60.7,61.1,61.1,61.1,61.2,61.3,9.7,0.6
5,"Türkiye, Republic of",96.596,97.865,88.918,84.968,82.642,92.827,102.337,118.926,125.032,...,29.3,26.0,26.7,27.1,27.1,26.5,26.1,25.8,-0.5,-0.9
6,Indonesia,99.296,110.848,113.799,103.149,107.218,107.062,101.220,95.214,107.279,...,39.6,40.2,41.0,41.0,41.0,40.9,40.8,40.6,14.0,-0.4
7,Saudi Arabia,164.540,184.292,153.240,129.181,119.631,103.894,86.886,85.582,88.138,...,26.2,29.9,34.8,38.5,40.9,42.9,44.5,45.9,29.1,11.1
8,Poland,56.908,53.921,65.520,75.792,75.893,71.137,74.053,64.040,68.963,...,49.7,55.3,60.7,64.3,65.7,66.8,67.2,67.7,9.6,7.0
9,Argentina,233.696,189.802,94.250,116.267,130.544,98.599,118.565,121.561,142.386,...,155.4,85.3,73.1,68.2,65.1,63.3,59.3,55.7,20.5,-17.4
10,United Arab Emirates,41.725,46.461,43.205,39.588,39.245,38.519,30.526,33.519,34.069,...,32.4,32.1,32.8,32.6,32.0,31.5,31.0,31.0,16.7,-1.8
11,Thailand,33.422,35.999,37.799,41.366,43.179,40.185,44.520,52.204,63.704,...,62.3,63.2,64.5,66.0,67.0,67.6,68.1,68.3,21.9,3.8
12,Philippines,37.082,40.735,42.441,37.953,35.860,34.973,34.129,37.932,43.293,...,56.5,57.1,58.1,58.1,57.2,55.8,54.2,52.5,18.4,-5.6
13,Vietnam,35.357,17.617,23.369,35.204,61.171,19.045,43.009,53.385,29.501,...,34.4,32.9,33.6,34.9,35.6,36.1,36.6,37.1,-12.5,3.5
14,Bangladesh,24.775,26.355,24.678,23.904,26.817,28.819,29.639,32.449,34.914,...,39.3,40.1,40.3,40.7,41.7,42.8,43.1,43.9,12.1,3.6
15,Malaysia,26.757,27.321,29.278,32.745,37.087,34.090,30.303,34.529,37.845,...,69.7,70.4,70.1,69.8,70.1,70.4,70.6,70.8,13.1,0.7
16,Colombia,46.501,50.661,54.252,53.920,53.257,48.581,48.648,50.640,54.592,...,55.5,61.3,59.7,59.9,59.9,59.8,59.4,58.9,9.3,-0.8
17,South Africa,89.412,93.150,85.897,96.205,84.838,64.481,73.399,96.533,104.010,...,73.4,76.4,79.6,81.7,83.7,85.5,87.1,88.7,34.4,9.1
18,Romania,46.053,55.319,55.375,48.401,39.111,48.286,52.290,58.477,60.538,...,52.1,57.2,61.6,65.7,68.9,71.5,73.7,75.7,22.2,14.1
19,Egypt,23.523,25.760,30.479,37.254,41.888,48.841,54.076,77.359,92.530,...,95.9,90.9,86.6,85.1,82.0,78.7,75.3,71.4,2.8,-15.2
20,Chile,29.032,34.374,25.630,20.819,20.246,17.360,18.662,22.010,25.947,...,39.4,42.0,43.0,43.4,43.2,43.5,43.5,44.3,25.6,1.3
21,Iran,95.846,101.481,125.800,156.927,161.721,180.541,208.928,277.019,311.932,...,33.5,36.8,39.9,41.9,43.2,44.3,45.1,45.3,2.9,5.4
22,Peru,20.190,24.398,24.259,18.863,19.442,16.823,25.241,41.681,32.978,...,33.0,32.8,33.7,34.7,35.5,35.9,35.9,36.0,9.8,2.3
23,Kazakhstan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.0,24.8,25.4,27.9,29.9,31.8,33.5,34.6,3.5,9.2
24,Algeria,45.957,48.156,48.599,51.582,55.906,66.346,66.783,68.698,56.070,...,47.7,46.2,57.8,67.0,73.5,77.8,81.3,84.4,50.1,26.6
25,Iraq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,42.1,42.9,50.2,56.0,58.2,60.4,62.4,64.0,1.9,13.8
26,Hungary,23.117,23.706,24.142,21.910,21.243,21.511,24.778,27.233,29.800,...,73.0,73.5,73.5,73.4,73.5,73.4,73.4,73.2,-2.2,-0.3
27,Qatar,6.665,7.374,6.467,5.506,5.708,5.339,4.214,4.441,4.260,...,43.7,40.8,40.5,39.3,37.2,36.4,36.2,35.4,5.0,-5.1
28,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,82.3,89.8,110.0,108.5,103.5,100.1,96.2,92.1,30.7,-17.9
29,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.7,52.9,52.5,51.6,49.1,47.6,46.4,45.4,31.5,-7.1
30,Morocco,23.807,19.329,19.510,17.635,16.130,16.280,21.497,23.713,28.080,...,69.5,70.0,68.9,67.7,66.8,66.2,65.6,65.1,10.5,-3.8
31,Kuwait,NaN,25.249,21.583,20.871,21.700,21.445,17.904,22.368,20.690,...,3.2,3.0,7.4,10.8,15.3,19.4,23.5,24.4,2.8,17.0
32,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,32.2,32.6,33.0,32.9,32.3,32.0,31.2,30.7,26.3,-2.3
33,Kenya,13.449,12.667,12.196,11.279,11.703,11.646,13.832,15.163,15.721,...,73.0,65.6,68.3,70.2,69.8,68.1,66.2,64.4,22.5,-3.9
34,Dominican Republic,8.672,9.698,9.141,9.461,14.870,6.496,7.891,8.305,7.605,...,60.5,58.8,58.2,57.1,55.5,53.5,51.3,49.1,13.4,-9.1
35,Ecuador,16.116,16.501,16.474,14.478,15.408,18.020,13.222,12.355,11.749,...,54.3,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Guatemala,7.718,8.431,8.539,8.864,9.276,10.951,5.921,6.857,7.426,...,27.2,26.5,27.2,27.7,28.1,28.3,28.3,28.3,2.4,1.1
37,Ethiopia,7.385,7.578,7.973,8.863,8.375,9.808,10.188,10.890,11.285,...,38.7,32.3,41.8,37.0,34.6,32.7,31.0,29.5,-8.9,-12.3
38,Bulgaria,37.751,40.718,42.467,43.641,46.358,39.692,35.130,40.721,66.546,...,21.9,23.4,28.0,29.5,31.2,32.9,34.6,36.5,2.6,8.5
39,Angola,8.730,8.170,8.170,8.514,9.025,11.119,10.411,11.900,12.909,...,71.4,62.5,64.5,63.9,62.7,61.5,59.9,57.2,14.1,-7.3
40,Venezuela,69.841,78.367,79.998,79.672,57.826,59.865,60.877,46.854,60.378,...,138.5,164.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Oman,7.269,8.849,9.285,9.733,10.726,11.916,9.433,9.890,9.613,...,37.5,35.5,35.4,33.9,32.2,30.6,30.2,29.5,21.5,-5.9
42,Costa Rica,4.854,2.636,2.619,3.162,3.678,3.941,4.425,4.554,4.636,...,61.1,59.8,59.7,59.0,57.9,56.7,55.3,53.7,19.9,-6.0
43,Côte d'Ivoire,13.877,11.502,10.320,9.312,9.284,9.470,12.675,13.944,14.092,...,57.5,59.3,58.1,56.4,54.9,53.1,52.0,50.7,28.9,-7.4
44,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.7,44.5,44.4,44.1,44.3,44.0,43.7,43.2,-22.7,-1.2
45,Panama,4.253,4.814,5.319,5.461,5.700,6.030,6.266,6.294,5.441,...,51.5,56.6,58.1,58.3,57.9,57.0,55.7,54.0,23.8,-4.1
46,Turkmenistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.7,4.6,4.5,4.4,4.2,4.1,4.0,4.0,-10.0,-0.5
47,Ghana,38.684,61.487,70.954,49.337,17.998,15.970,15.086,12.692,13.566,...,76.4,70.5,66.4,62.7,59.9,57.0,54.1,52.0,12.5,-14.4
48,Tanzania,10.873,13.005,14.932,15.294,13.915,12.556,15.874,7.821,7.474,...,47.4,48.2,47.1,45.8,44.3,42.9,41.5,40.4,7.6,-6.7
49,Uruguay,12.217,13.636,11.147,6.119,5.819,5.686,7.059,8.832,9.137,...,64.0,68.7,68.5,68.3,68.0,67.9,67.7,67.4,10.7,-1.1
50,"Congo, Dem. Rep. of the",68.606,59.726,64.939,52.378,34.951,31.943,35.840,33.932,39.314,...,25.1,19.3,16.3,13.8,11.5,9.2,7.2,5.8,-9.2,-10.5

In [18]:
emerging_markets_debts["change_of_debts_current_yony"]=((100+emerging_markets_debts["change_of_debts_current"])/100)**(1/10)
emerging_markets_debts["change_of_debts_future_yony"]=((100+emerging_markets_debts["change_of_debts_future"])/100)**(1/5)

In [19]:
emerging_markets_debts=emerging_markets_debts.sort_values(by="2023_gdp", ascending=False)
emerging_markets_debts

,Country,1980_gdp,1981_gdp,1982_gdp,1983_gdp,1984_gdp,1985_gdp,1986_gdp,1987_gdp,1988_gdp,...,2025_debts,2026_debts,2027_debts,2028_debts,2029_debts,2030_debts,change_of_debts_current,change_of_debts_future,change_of_debts_current_yony,change_of_debts_future_yony
0,"China, People's Republic of",303.550,289.215,285.139,306.013,314.832,310.709,301.471,328.305,409.363,...,96.3,102.3,105.9,109.2,112.6,116.0,55.5,19.7,1.045137,1.036618
1,India,186.170,193.153,200.035,218.218,211.843,233.520,248.398,278.864,294.479,...,80.4,79.6,78.8,77.9,76.9,75.8,11.4,-4.6,1.010854,0.990626
2,Brazil,145.819,167.583,179.166,143.652,142.957,226.938,263.256,286.539,320.105,...,92.0,96.0,98.1,99.1,99.4,99.4,20.3,7.4,1.018654,1.014380
3,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,22.5,23.7,24.7,25.9,27.2,6.1,5.8,1.005939,1.011340
4,Mexico,242.153,311.012,225.706,184.010,217.001,230.272,159.434,174.840,213.893,...,60.7,61.1,61.1,61.1,61.2,61.3,9.7,0.6,1.009301,1.001197
6,Indonesia,99.296,110.848,113.799,103.149,107.218,107.062,101.220,95.214,107.279,...,41.0,41.0,41.0,40.9,40.8,40.6,14.0,-0.4,1.013189,0.999199
5,"Türkiye, Republic of",96.596,97.865,88.918,84.968,82.642,92.827,102.337,118.926,125.032,...,26.7,27.1,27.1,26.5,26.1,25.8,-0.5,-0.9,0.999499,0.998193
7,Saudi Arabia,164.540,184.292,153.240,129.181,119.631,103.894,86.886,85.582,88.138,...,34.8,38.5,40.9,42.9,44.5,45.9,29.1,11.1,1.025871,1.021275
8,Poland,56.908,53.921,65.520,75.792,75.893,71.137,74.053,64.040,68.963,...,60.7,64.3,65.7,66.8,67.2,67.7,9.6,7.0,1.009209,1.013624
9,Argentina,233.696,189.802,94.250,116.267,130.544,98.599,118.565,121.561,142.386,...,73.1,68.2,65.1,63.3,59.3,55.7,20.5,-17.4,1.018823,0.962490
11,Thailand,33.422,35.999,37.799,41.366,43.179,40.185,44.520,52.204,63.704,...,64.5,66.0,67.0,67.6,68.1,68.3,21.9,3.8,1.020000,1.007487
10,United Arab Emirates,41.725,46.461,43.205,39.588,39.245,38.519,30.526,33.519,34.069,...,32.8,32.6,32.0,31.5,31.0,31.0,16.7,-1.8,1.015564,0.996374
14,Bangladesh,24.775,26.355,24.678,23.904,26.817,28.819,29.639,32.449,34.914,...,40.3,40.7,41.7,42.8,43.1,43.9,12.1,3.6,1.011488,1.007099
12,Philippines,37.082,40.735,42.441,37.953,35.860,34.973,34.129,37.932,43.293,...,58.1,58.1,57.2,55.8,54.2,52.5,18.4,-5.6,1.017033,0.988540
13,Vietnam,35.357,17.617,23.369,35.204,61.171,19.045,43.009,53.385,29.501,...,33.6,34.9,35.6,36.1,36.6,37.1,-12.5,3.5,0.986736,1.006904
15,Malaysia,26.757,27.321,29.278,32.745,37.087,34.090,30.303,34.529,37.845,...,70.1,69.8,70.1,70.4,70.6,70.8,13.1,0.7,1.012386,1.001396
19,Egypt,23.523,25.760,30.479,37.254,41.888,48.841,54.076,77.359,92.530,...,86.6,85.1,82.0,78.7,75.3,71.4,2.8,-15.2,1.002765,0.967563
17,South Africa,89.412,93.150,85.897,96.205,84.838,64.481,73.399,96.533,104.010,...,79.6,81.7,83.7,85.5,87.1,88.7,34.4,9.1,1.030006,1.017572
21,Iran,95.846,101.481,125.800,156.927,161.721,180.541,208.928,277.019,311.932,...,39.9,41.9,43.2,44.3,45.1,45.3,2.9,5.4,1.002863,1.010574
16,Colombia,46.501,50.661,54.252,53.920,53.257,48.581,48.648,50.640,54.592,...,59.7,59.9,59.9,59.8,59.4,58.9,9.3,-0.8,1.008932,0.998395
29,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,52.5,51.6,49.1,47.6,46.4,45.4,31.5,-7.1,1.027762,0.985379
18,Romania,46.053,55.319,55.375,48.401,39.111,48.286,52.290,58.477,60.538,...,61.6,65.7,68.9,71.5,73.7,75.7,22.2,14.1,1.020251,1.026732
20,Chile,29.032,34.374,25.630,20.819,20.246,17.360,18.662,22.010,25.947,...,43.0,43.4,43.2,43.5,43.5,44.3,25.6,1.3,1.023055,1.002587
25,Iraq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,50.2,56.0,58.2,60.4,62.4,64.0,1.9,13.8,1.001884,1.026192
22,Peru,20.190,24.398,24.259,18.863,19.442,16.823,25.241,41.681,32.978,...,33.7,34.7,35.5,35.9,35.9,36.0,9.8,2.3,1.009393,1.004558
23,Kazakhstan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.4,27.9,29.9,31.8,33.5,34.6,3.5,9.2,1.003446,1.017758
24,Algeria,45.957,48.156,48.599,51.582,55.906,66.346,66.783,68.698,56.070,...,57.8,67.0,73.5,77.8,81.3,84.4,50.1,26.6,1.041449,1.048303
26,Hungary,23.117,23.706,24.142,21.910,21.243,21.511,24.778,27.233,29.800,...,73.5,73.4,73.5,73.4,73.4,73.2,-2.2,-0.3,0.997778,0.999399
27,Qatar,6.665,7.374,6.467,5.506,5.708,5.339,4.214,4.441,4.260,...,40.5,39.3,37.2,36.4,36.2,35.4,5.0,-5.1,1.004891,0.989585
28,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,110.0,108.5,103.5,100.1,96.2,92.1,30.7,-17.9,1.027135,0.961321
31,Kuwait,NaN,25.249,21.583,20.871,21.700,21.445,17.904,22.368,20.690,...,7.4,10.8,15.3,19.4,23.5,24.4,2.8,17.0,1.002765,1.031899
37,Ethiopia,7.385,7.578,7.973,8.863,8.375,9.808,10.188,10.890,11.285,...,41.8,37.0,34.6,32.7,31.0,29.5,-8.9,-12.3,0.990722,0.974092
30,Morocco,23.807,19.329,19.510,17.635,16.130,16.280,21.497,23.713,28.080,...,68.9,67.7,66.8,66.2,65.6,65.1,10.5,-3.8,1.010035,0.992282
35,Ecuador,16.116,16.501,16.474,14.478,15.408,18.020,13.222,12.355,11.749,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Dominican Republic,8.672,9.698,9.141,9.461,14.870,6.496,7.891,8.305,7.605,...,58.2,57.1,55.5,53.5,51.3,49.1,13.4,-9.1,1.012655,0.981099
39,Angola,8.730,8.170,8.170,8.514,9.025,11.119,10.411,11.900,12.909,...,64.5,63.9,62.7,61.5,59.9,57.2,14.1,-7.3,1.013278,0.984954
33,Kenya,13.449,12.667,12.196,11.279,11.703,11.646,13.832,15.163,15.721,...,68.3,70.2,69.8,68.1,66.2,64.4,22.5,-3.9,1.020501,0.992075
41,Oman,7.269,8.849,9.285,9.733,10.726,11.916,9.433,9.890,9.613,...,35.4,33.9,32.2,30.6,30.2,29.5,21.5,-5.9,1.019665,0.987911
36,Guatemala,7.718,8.431,8.539,8.864,9.276,10.951,5.921,6.857,7.426,...,27.2,27.7,28.1,28.3,28.3,28.3,2.4,1.1,1.002374,1.002190
32,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33.0,32.9,32.3,32.0,31.2,30.7,26.3,-2.3,1.023624,0.995357
38,Bulgaria,37.751,40.718,42.467,43.641,46.358,39.692,35.130,40.721,66.546,...,28.0,29.5,31.2,32.9,34.6,36.5,2.6,8.5,1.002570,1.016450
40,Venezuela,69.841,78.367,79.998,79.672,57.826,59.865,60.877,46.854,60.378,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Costa Rica,4.854,2.636,2.619,3.162,3.678,3.941,4.425,4.554,4.636,...,59.7,59.0,57.9,56.7,55.3,53.7,19.9,-6.0,1.018314,0.987701
45,Panama,4.253,4.814,5.319,5.461,5.700,6.030,6.266,6.294,5.441,...,58.1,58.3,57.9,57.0,55.7,54.0,23.8,-4.1,1.021579,0.991662
44,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.4,44.1,44.3,44.0,43.7,43.2,-22.7,-1.2,0.974581,0.997588
47,Ghana,38.684,61.487,70.954,49.337,17.998,15.970,15.086,12.692,13.566,...,66.4,62.7,59.9,57.0,54.1,52.0,12.5,-14.4,1.011848,0.969382
43,Côte d'Ivoire,13.877,11.502,10.320,9.312,9.284,9.470,12.675,13.944,14.092,...,58.1,56.4,54.9,53.1,52.0,50.7,28.9,-7.4,1.025712,0.984741
48,Tanzania,10.873,13.005,14.932,15.294,13.915,12.556,15.874,7.821,7.474,...,47.1,45.8,44.3,42.9,41.5,40.4,7.6,-6.7,1.007352,0.986226
49,Uruguay,12.217,13.636,11.147,6.119,5.819,5.686,7.059,8.832,9.137,...,68.5,68.3,68.0,67.9,67.7,67.4,10.7,-1.1,1.010217,0.997790
46,Turkmenistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.5,4.4,4.2,4.1,4.0,4.0,-10.0,-0.5,0.989519,0.998998
50,"Congo, Dem. Rep. of the",68.606,59.726,64.939,52.378,34.951,31.943,35.840,33.932,39.314,...,16.3,13.8,11.5,9.2,7.2,5.8,-9.2,-10.5,0.990395,0.978058

In [23]:
emerging_markets_debts["Country"].tolist()

["China, People's Republic of",
 'India',
 'Brazil',
 'Russian Federation',
 'Mexico',
 'Indonesia',
 'Türkiye, Republic of',
 'Saudi Arabia',
 'Poland',
 'Argentina',
 'Thailand',
 'United Arab Emirates',
 'Bangladesh',
 'Philippines',
 'Vietnam',
 'Malaysia',
 'Egypt',
 'South Africa',
 'Iran',
 'Colombia',
 'Nigeria',
 'Romania',
 'Chile',
 'Iraq',
 'Peru',
 'Kazakhstan',
 'Algeria',
 'Hungary',
 'Qatar',
 'Ukraine',
 'Kuwait',
 'Ethiopia',
 'Morocco',
 'Ecuador',
 'Dominican Republic',
 'Angola',
 'Kenya',
 'Oman',
 'Guatemala',
 'Uzbekistan',
 'Bulgaria',
 'Venezuela',
 'Costa Rica',
 'Panama',
 'Serbia',
 'Ghana',
 "Côte d'Ivoire",
 'Tanzania',
 'Uruguay',
 'Turkmenistan',
 'Congo, Dem. Rep. of the']

In [24]:
country_to_iso2_german = {
    "China, People's Republic of": ":CN: China",
    "India": ":IN: Indien",
    "Brazil": ":BR: Brasilien",
    "Russian Federation": ":RU: Russland",
    "Mexico": ":MX: Mexiko",
    "Indonesia": ":ID: Indonesien",
    "Türkiye, Republic of": ":TR: Türkei",
    "Saudi Arabia": ":SA: Saudi-Arabien",
    "Poland": ":PL: Polen",
    "Argentina": ":AR: Argentinien",
    "Thailand": ":TH: Thailand",
    "United Arab Emirates": ":AE: Vereinigte Arabische Emirate",
    "Bangladesh": ":BD: Bangladesch",
    "Philippines": ":PH: Philippinen",
    "Vietnam": ":VN: Vietnam",
    "Malaysia": ":MY: Malaysia",
    "Egypt": ":EG: Ägypten",
    "South Africa": ":ZA: Südafrika",
    "Iran": ":IR: Iran",
    "Colombia": ":CO: Kolumbien",
    "Nigeria": ":NG: Nigeria",
    "Romania": ":RO: Rumänien",
    "Chile": ":CL: Chile",
    "Iraq": ":IQ: Irak",
    "Peru": ":PE: Peru",
    "Kazakhstan": ":KZ: Kasachstan",
    "Algeria": ":DZ: Algerien",
    "Hungary": ":HU: Ungarn",
    "Qatar": ":QA: Katar",
    "Ukraine": ":UA: Ukraine",
    "Kuwait": ":KW: Kuwait",
    "Ethiopia": ":ET: Äthiopien",
    "Morocco": ":MA: Marokko",
    "Ecuador": ":EC: Ecuador",
    "Dominican Republic": ":DO: Dominikanische Republik",
    "Angola": ":AO: Angola",
    "Kenya": ":KE: Kenia",
    "Oman": ":OM: Oman",
    "Guatemala": ":GT: Guatemala",
    "Uzbekistan": ":UZ: Usbekistan",
    "Bulgaria": ":BG: Bulgarien",
    "Venezuela": ":VE: Venezuela",
    "Costa Rica": ":CR: Costa Rica",
    "Panama": ":PA: Panama",
    "Serbia": ":RS: Serbien",
    "Ghana": ":GH: Ghana",
    "Côte d'Ivoire": ":CI: Elfenbeinküste",
    "Tanzania": ":TZ: Tansania",
    "Uruguay": ":UY: Uruguay",
    "Turkmenistan": ":TM: Turkmenistan",
    "Congo, Dem. Rep. of the": ":CD: Demokratische Republik Kongo"
}

In [25]:
emerging_markets_debts["iso2"]=emerging_markets_debts["Country"].map(country_to_iso2_german)

In [26]:
emerging_markets_debts["2024_gdp_mio"]=emerging_markets_debts["2024_gdp"]*1000000

In [27]:
emerging_markets_debts_red=emerging_markets_debts[["iso2","Country", "2023_gdp","2024_gdp_mio","2025_gdp","2024_debts"]]
emerging_markets_debts_red

,iso2,Country,2023_gdp,2024_gdp_mio,2025_gdp,2024_debts
0,:CN: China,"China, People's Republic of",18270.351,1.874801e+10,19231.705,88.3
1,:IN: Indien,India,3638.490,3.909097e+09,4187.017,81.3
2,:BR: Brasilien,Brazil,2191.137,2.171337e+09,2125.958,87.3
3,:RU: Russland,Russian Federation,2059.762,2.161205e+09,2076.396,20.3
4,:MX: Mexiko,Mexico,1793.799,1.852723e+09,1692.640,58.4
6,:ID: Indonesien,Indonesia,1371.169,1.396300e+09,1429.743,40.2
5,:TR: Türkei,"Türkiye, Republic of",1130.062,1.322405e+09,1437.406,26.0
7,:SA: Saudi-Arabien,Saudi Arabia,1067.583,1.085358e+09,1083.749,29.9
8,:PL: Polen,Poland,809.706,9.085830e+08,979.960,55.3
9,:AR: Argentinien,Argentina,645.511,6.321450e+08,683.533,85.3
11,:TH: Thailand,Thailand,515.906,5.264110e+08,546.224,63.2
10,:AE: Vereinigte Arabische Emirate,United Arab Emirates,514.130,5.370790e+08,548.598,32.1
14,:BD: Bangladesch,Bangladesh,451.534,4.510960e+08,467.218,40.1
12,:PH: Philippinen,Philippines,437.055,4.616170e+08,497.495,57.1
13,:VN: Vietnam,Vietnam,433.008,4.594720e+08,490.970,32.9
15,:MY: Malaysia,Malaysia,399.705,4.196170e+08,444.984,70.4
19,:EG: Ägypten,Egypt,393.828,3.831090e+08,347.342,90.9
17,:ZA: Südafrika,South Africa,380.592,4.001910e+08,410.338,76.4
21,:IR: Iran,Iran,372.820,4.013570e+08,341.013,36.8
16,:CO: Kolumbien,Colombia,366.292,4.185420e+08,427.766,61.3
29,:NG: Nigeria,Nigeria,363.816,1.876400e+08,188.271,52.9
18,:RO: Rumänien,Romania,350.847,3.841480e+08,403.395,57.2
20,:CL: Chile,Chile,335.627,3.302100e+08,343.823,42.0
25,:IQ: Irak,Iraq,270.799,2.774780e+08,258.020,42.9
22,:PE: Peru,Peru,267.482,2.890700e+08,303.293,32.8
23,:KZ: Kasachstan,Kazakhstan,261.840,2.848100e+08,300.538,24.8
24,:DZ: Algerien,Algeria,247.789,2.649130e+08,268.885,46.2
26,:HU: Ungarn,Hungary,214.098,2.230600e+08,237.070,73.5
27,:QA: Katar,Qatar,213.003,2.214520e+08,222.776,40.8
28,:UA: Ukraine,Ukraine,178.763,1.904260e+08,205.742,89.8
31,:KW: Kuwait,Kuwait,163.716,1.585680e+08,153.101,3.0
37,:ET: Äthiopien,Ethiopia,159.761,1.431230e+08,117.457,32.3
30,:MA: Marokko,Morocco,144.438,1.553500e+08,165.835,70.0
35,:EC: Ecuador,Ecuador,121.147,1.217280e+08,125.677,55.0
34,:DO: Dominikanische Republik,Dominican Republic,120.794,1.246130e+08,127.828,58.8
39,:AO: Angola,Angola,109.764,1.159460e+08,113.343,62.5
33,:KE: Kenia,Kenya,108.747,1.208990e+08,131.673,65.6
41,:OM: Oman,Oman,105.896,1.069430e+08,104.351,35.5
36,:GT: Guatemala,Guatemala,104.436,1.125750e+08,121.177,26.5
32,:UZ: Usbekistan,Uzbekistan,102.634,1.149620e+08,132.484,32.6
38,:BG: Bulgarien,Bulgaria,102.434,1.122320e+08,117.007,23.4
40,:VE: Venezuela,Venezuela,102.377,1.198080e+08,108.511,164.3
42,:CR: Costa Rica,Costa Rica,86.509,9.536500e+07,102.591,59.8
45,:PA: Panama,Panama,83.382,8.768800e+07,91.675,56.6
44,:RS: Serbien,Serbia,81.343,8.907400e+07,92.549,44.5
47,:GH: Ghana,Ghana,80.547,8.282500e+07,88.332,70.5
43,:CI: Elfenbeinküste,Côte d'Ivoire,79.630,8.709600e+07,94.483,59.3
48,:TZ: Tansania,Tanzania,79.138,8.017100e+07,85.977,48.2
49,:UY: Uruguay,Uruguay,77.997,8.096100e+07,79.731,68.7
46,:TM: Turkmenistan,Turkmenistan,77.876,8.251500e+07,89.054,4.6
50,:CD: Demokratische Republik Kongo,"Congo, Dem. Rep. of the",64.402,7.101100e+07,79.119,19.3

In [28]:
emerging_markets_debts_red[["iso2","2024_gdp_mio","2024_debts"]].to_csv("emerging_markets_gdp.csv", index=False)

In [29]:
# Expanded dictionary mapping IMF country names to World Bank country names
imf_to_world_bank_mapping = {
    "Afghanistan": "Afghanistan",
    "Albania": "Albania",
    "Algeria": "Algeria",
    "Angola": "Angola",
    "Antigua and Barbuda": "Antigua and Barbuda",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Azerbaijan": "Azerbaijan",
    "Bahamas, The": "Bahamas",
    "Bahrain": "Bahrain",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Belarus": "Belarus",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bhutan": "Bhutan",
    "Bolivia": "Bolivia",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    "Botswana": "Botswana",
    "Brazil": "Brazil",
    "Brunei Darussalam": "Brunei Darussalam",
    "Bulgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cabo Verde": "Cape Verde",
    "Cambodia": "Cambodia",
    "Cameroon": "Cameroon",
    "Central African Republic": "Central African Republic",
    "Chad": "Chad",
    "Chile": "Chile",
    "China, People's Republic of": "China",
    "Colombia": "Colombia",
    "Comoros": "Comoros",
    "Congo, Dem. Rep. of the": "Congo, Dem. Rep.",
    "Congo, Republic of": "Congo (Brazzaville)",
    "Costa Rica": "Costa Rica",
    "Curacao": "Curacao",
    "Côte d'Ivoire": "Ivory Coast",
    "Djibouti": "Djibouti",
    "Dominica": "Dominica",
    "Dominican Republic": "Dominican Republic",
    "Ecuador": "Ecuador",
    "Egypt": "Egypt, Arab Rep.",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Equatorial Guinea",
    "Eritrea": "Eritrea",
    "Eswatini": "Eswatini",
    "Ethiopia": "Ethiopia",
    "Fiji": "Fiji",
    "Gabon": "Gabon",
    "Gambia, The": "Gambia",
    "Georgia": "Georgia",
    "Ghana": "Ghana",
    "Grenada": "Grenada",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    "Guyana": "Guyana",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hungary": "Hungary",
    "India": "India",
    "Indonesia": "Indonesia",
    "Iran": "Iran, Islamic Rep.",
    "Iraq": "Iraq",
    "Jamaica": "Jamaica",
    "Jordan": "Jordan",
    "Kazakhstan": "Kazakhstan",
    "Kenya": "Kenya",
    "Kiribati": "Kiribati",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Kyrgyz Republic": "Kyrgyzstan",
    "Lao P.D.R.": "Lao PDR",
    "Lebanon": "Lebanon",
    "Lesotho": "Lesotho",
    "Liberia": "Liberia",
    "Libya": "Libya",
    "Madagascar": "Madagascar",
    "Malawi": "Malawi",
    "Malaysia": "Malaysia",
    "Maldives": "Maldives",
    "Mali": "Mali",
    "Marshall Islands": "Marshall Islands",
    "Mauritania": "Mauritania",
    "Mauritius": "Mauritius",
    "Mexico": "Mexico",
    "Micronesia, Fed. States of": "Micronesia, Fed. Sts.",
    "Moldova": "Moldova",
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Morocco": "Morocco",
    "Mozambique": "Mozambique",
    "Myanmar": "Myanmar",
    "Namibia": "Namibia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Nicaragua": "Nicaragua",
    "Niger": "Niger",
    "Nigeria": "Nigeria",
    "North Macedonia": "North Macedonia",
    "Oman": "Oman",
    "Pakistan": "Pakistan",
    "Palau": "Palau",
    "Panama": "Panama",
    "Papua New Guinea": "Papua New Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Peru",
    "Philippines": "Philippines",
    "Poland": "Poland",
    "Qatar": "Qatar",
    "Romania": "Romania",
    "Russian Federation": "Russia",
    "Rwanda": "Rwanda",
    "Saint Kitts and Nevis": "Saint Kitts and Nevis",
    "Saint Lucia": "Saint Lucia",
    "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    "Samoa": "Samoa",
    "Saudi Arabia": "Saudi Arabia",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Seychelles": "Seychelles",
    "Sierra Leone": "Sierra Leone",
    "Sint Maarten": "Sint Maarten",
    "Solomon Islands": "Solomon Islands",
    "Somalia": "Somalia",
    "South Africa": "South Africa",
    "South Sudan, Republic of": "South Sudan",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Sudan",
    "Suriname": "Suriname",
    "Syria": "Syria",
    "São Tomé and Príncipe": "São Tomé and Príncipe",
    "Tajikistan": "Tajikistan",
    "Tanzania": "Tanzania",
    "Thailand": "Thailand",
    "Timor-Leste": "Timor-Leste",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad and Tobago": "Trinidad and Tobago",
    "Tunisia": "Tunisia",
    "Turkmenistan": "Turkmenistan",
    "Tuvalu": "Tuvalu",
    "Türkiye, Republic of": "Turkiye",
    "Uganda": "Uganda",
    "Ukraine": "Ukraine",
    "United Arab Emirates": "United Arab Emirates",
    "Uruguay": "Uruguay",
    "Uzbekistan": "Uzbekistan",
    "Vanuatu": "Vanuatu",
    "Venezuela": "Venezuela",
    "Vietnam": "Viet Nam",
    "West Bank and Gaza": "West Bank and Gaza",
    "Yemen": "Yemen, Rep.",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwe"
}

imf_to_world_bank_mapping

{'Afghanistan': 'Afghanistan',
 'Albania': 'Albania',
 'Algeria': 'Algeria',
 'Angola': 'Angola',
 'Antigua and Barbuda': 'Antigua and Barbuda',
 'Argentina': 'Argentina',
 'Armenia': 'Armenia',
 'Azerbaijan': 'Azerbaijan',
 'Bahamas, The': 'Bahamas',
 'Bahrain': 'Bahrain',
 'Bangladesh': 'Bangladesh',
 'Barbados': 'Barbados',
 'Belarus': 'Belarus',
 'Belize': 'Belize',
 'Benin': 'Benin',
 'Bhutan': 'Bhutan',
 'Bolivia': 'Bolivia',
 'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
 'Botswana': 'Botswana',
 'Brazil': 'Brazil',
 'Brunei Darussalam': 'Brunei Darussalam',
 'Bulgaria': 'Bulgaria',
 'Burkina Faso': 'Burkina Faso',
 'Burundi': 'Burundi',
 'Cabo Verde': 'Cape Verde',
 'Cambodia': 'Cambodia',
 'Cameroon': 'Cameroon',
 'Central African Republic': 'Central African Republic',
 'Chad': 'Chad',
 'Chile': 'Chile',
 "China, People's Republic of": 'China',
 'Colombia': 'Colombia',
 'Comoros': 'Comoros',
 'Congo, Dem. Rep. of the': 'Congo, Dem. Rep.',
 'Congo, Republic of': 'Congo (Brazzaville)',
 'Costa Rica': 'Costa Rica',
 'Curacao': 'Curacao',
 "Côte d'Ivoire": 'Ivory Coast',
 'Djibouti': 'Djibouti',
 'Dominica': 'Dominica',
 'Dominican Republic': 'Dominican Republic',
 'Ecuador': 'Ecuador',
 'Egypt': 'Egypt, Arab Rep.',
 'El Salvador': 'El Salvador',
 'Equatorial Guinea': 'Equatorial Guinea',
 'Eritrea': 'Eritrea',
 'Eswatini': 'Eswatini',
 'Ethiopia': 'Ethiopia',
 'Fiji': 'Fiji',
 'Gabon': 'Gabon',
 'Gambia, The': 'Gambia',
 'Georgia': 'Georgia',
 'Ghana': 'Ghana',
 'Grenada': 'Grenada',
 'Guatemala': 'Guatemala',
 'Guinea': 'Guinea',
 'Guinea-Bissau': 'Guinea-Bissau',
 'Guyana': 'Guyana',
 'Haiti': 'Haiti',
 'Honduras': 'Honduras',
 'Hungary': 'Hungary',
 'India': 'India',
 'Indonesia': 'Indonesia',
 'Iran': 'Iran, Islamic Rep.',
 'Iraq': 'Iraq',
 'Jamaica': 'Jamaica',
 'Jordan': 'Jordan',
 'Kazakhstan': 'Kazakhstan',
 'Kenya': 'Kenya',
 'Kiribati': 'Kiribati',
 'Kosovo': 'Kosovo',
 'Kuwait': 'Kuwait',
 'Kyrgyz Republic': 'Kyrgyzstan',
 'Lao P.D.R.': 'Lao PDR',
 'Lebanon': 'Lebanon',
 'Lesotho': 'Lesotho',
 'Liberia': 'Liberia',
 'Libya': 'Libya',
 'Madagascar': 'Madagascar',
 'Malawi': 'Malawi',
 'Malaysia': 'Malaysia',
 'Maldives': 'Maldives',
 'Mali': 'Mali',
 'Marshall Islands': 'Marshall Islands',
 'Mauritania': 'Mauritania',
 'Mauritius': 'Mauritius',
 'Mexico': 'Mexico',
 'Micronesia, Fed. States of': 'Micronesia, Fed. Sts.',
 'Moldova': 'Moldova',
 'Mongolia': 'Mongolia',
 'Montenegro': 'Montenegro',
 'Morocco': 'Morocco',
 'Mozambique': 'Mozambique',
 'Myanmar': 'Myanmar',
 'Namibia': 'Namibia',
 'Nauru': 'Nauru',
 'Nepal': 'Nepal',
 'Nicaragua': 'Nicaragua',
 'Niger': 'Niger',
 'Nigeria': 'Nigeria',
 'North Macedonia': 'North Macedonia',
 'Oman': 'Oman',
 'Pakistan': 'Pakistan',
 'Palau': 'Palau',
 'Panama': 'Panama',
 'Papua New Guinea': 'Papua New Guinea',
 'Paraguay': 'Paraguay',
 'Peru': 'Peru',
 'Philippines': 'Philippines',
 'Poland': 'Poland',
 'Qatar': 'Qatar',
 'Romania': 'Romania',
 'Russian Federation': 'Russia',
 'Rwanda': 'Rwanda',
 'Saint Kitts and Nevis': 'Saint Kitts and Nevis',
 'Saint Lucia': 'Saint Lucia',
 'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
 'Samoa': 'Samoa',
 'Saudi Arabia': 'Saudi Arabia',
 'Senegal': 'Senegal',
 'Serbia': 'Serbia',
 'Seychelles': 'Seychelles',
 'Sierra Leone': 'Sierra Leone',
 'Sint Maarten': 'Sint Maarten',
 'Solomon Islands': 'Solomon Islands',
 'Somalia': 'Somalia',
 'South Africa': 'South Africa',
 'South Sudan, Republic of': 'South Sudan',
 'Sri Lanka': 'Sri Lanka',
 'Sudan': 'Sudan',
 'Suriname': 'Suriname',
 'Syria': 'Syria',
 'São Tomé and Príncipe': 'São Tomé and Príncipe',
 'Tajikistan': 'Tajikistan',
 'Tanzania': 'Tanzania',
 'Thailand': 'Thailand',
 'Timor-Leste': 'Timor-Leste',
 'Togo': 'Togo',
 'Tonga': 'Tonga',
 'Trinidad and Tobago': 'Trinidad and Tobago',
 'Tunisia': 'Tunisia',
 'Turkmenistan': 'Turkmenistan',
 'Tuvalu': 'Tuvalu',
 'Türkiye, Republic of': 'Turkiye',
 'Uganda': 'Uganda',
 'Ukraine': 'Ukraine',
 'United Arab Emirates': 'United Arab Emirates',
 'Uruguay': 'Uruguay',
 'Uzbekistan': 'Uzbekistan',
 'Vanuatu': 'Vanuatu',
 'Venezuela': 'Venezuela',
 'Vietnam': 'Viet Nam',
 'West Bank and Gaza': 'West Bank and Gaza',
 'Yemen': 'Yemen, Rep.',
 'Zambia': 'Zambia',
 'Zimbabwe': 'Zimbabwe'}

In [30]:
countries_of_interest=emerging_markets_debts[(emerging_markets_debts["change_of_debts_current_yony"]<1.01)&(emerging_markets_debts["change_of_debts_future_yony"]<1.01)]
countries_of_interest["World_Bank_Name"] = countries_of_interest["Country"].map(imf_to_world_bank_mapping)
countries_of_interest

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_2859/3495394067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  countries_of_interest["World_Bank_Name"] = countries_of_interest["Country"].map(imf_to_world_bank_mapping)

,Country,1980_gdp,1981_gdp,1982_gdp,1983_gdp,1984_gdp,1985_gdp,1986_gdp,1987_gdp,1988_gdp,...,2028_debts,2029_debts,2030_debts,change_of_debts_current,change_of_debts_future,change_of_debts_current_yony,change_of_debts_future_yony,iso2,2024_gdp_mio,World_Bank_Name
4,Mexico,242.153,311.012,225.706,184.010,217.001,230.272,159.434,174.840,213.893,...,61.1,61.2,61.3,9.7,0.6,1.009301,1.001197,:MX: Mexiko,1.852723e+09,Mexico
5,"Türkiye, Republic of",96.596,97.865,88.918,84.968,82.642,92.827,102.337,118.926,125.032,...,26.5,26.1,25.8,-0.5,-0.9,0.999499,0.998193,:TR: Türkei,1.322405e+09,Turkiye
13,Vietnam,35.357,17.617,23.369,35.204,61.171,19.045,43.009,53.385,29.501,...,36.1,36.6,37.1,-12.5,3.5,0.986736,1.006904,:VN: Vietnam,4.594720e+08,Viet Nam
19,Egypt,23.523,25.760,30.479,37.254,41.888,48.841,54.076,77.359,92.530,...,78.7,75.3,71.4,2.8,-15.2,1.002765,0.967563,:EG: Ägypten,3.831090e+08,"Egypt, Arab Rep."
16,Colombia,46.501,50.661,54.252,53.920,53.257,48.581,48.648,50.640,54.592,...,59.8,59.4,58.9,9.3,-0.8,1.008932,0.998395,:CO: Kolumbien,4.185420e+08,Colombia
22,Peru,20.190,24.398,24.259,18.863,19.442,16.823,25.241,41.681,32.978,...,35.9,35.9,36.0,9.8,2.3,1.009393,1.004558,:PE: Peru,2.890700e+08,Peru
26,Hungary,23.117,23.706,24.142,21.910,21.243,21.511,24.778,27.233,29.800,...,73.4,73.4,73.2,-2.2,-0.3,0.997778,0.999399,:HU: Ungarn,2.230600e+08,Hungary
27,Qatar,6.665,7.374,6.467,5.506,5.708,5.339,4.214,4.441,4.260,...,36.4,36.2,35.4,5.0,-5.1,1.004891,0.989585,:QA: Katar,2.214520e+08,Qatar
37,Ethiopia,7.385,7.578,7.973,8.863,8.375,9.808,10.188,10.890,11.285,...,32.7,31.0,29.5,-8.9,-12.3,0.990722,0.974092,:ET: Äthiopien,1.431230e+08,Ethiopia
36,Guatemala,7.718,8.431,8.539,8.864,9.276,10.951,5.921,6.857,7.426,...,28.3,28.3,28.3,2.4,1.1,1.002374,1.002190,:GT: Guatemala,1.125750e+08,Guatemala
44,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.0,43.7,43.2,-22.7,-1.2,0.974581,0.997588,:RS: Serbien,8.907400e+07,Serbia
48,Tanzania,10.873,13.005,14.932,15.294,13.915,12.556,15.874,7.821,7.474,...,42.9,41.5,40.4,7.6,-6.7,1.007352,0.986226,:TZ: Tansania,8.017100e+07,Tanzania
46,Turkmenistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.1,4.0,4.0,-10.0,-0.5,0.989519,0.998998,:TM: Turkmenistan,8.251500e+07,Turkmenistan
50,"Congo, Dem. Rep. of the",68.606,59.726,64.939,52.378,34.951,31.943,35.840,33.932,39.314,...,9.2,7.2,5.8,-9.2,-10.5,0.990395,0.978058,:CD: Demokratische Republik Kongo,7.101100e+07,"Congo, Dem. Rep."

In [31]:
countries_of_interest_red=countries_of_interest[["iso2","2024_gdp_mio","change_of_debts_current_yony","change_of_debts_future_yony"]]
countries_of_interest_red["change_of_debts_current_yony"]=(countries_of_interest_red["change_of_debts_current_yony"]-1)*100
countries_of_interest_red["change_of_debts_future_yony"]=(countries_of_interest_red["change_of_debts_future_yony"]-1)*100
countries_of_interest_red

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_2859/765664978.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  countries_of_interest_red["change_of_debts_current_yony"]=(countries_of_interest_red["change_of_debts_current_yony"]-1)*100
/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_2859/765664978.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  countries_of_interest_red["change_of_debts_future_yony"]=(countries_of_interest_red["change_of_debts_future_yony"]-1)*100

,iso2,2024_gdp_mio,change_of_debts_current_yony,change_of_debts_future_yony
4,:MX: Mexiko,1.852723e+09,0.930091,0.119713
5,:TR: Türkei,1.322405e+09,-0.050113,-0.180652
13,:VN: Vietnam,4.594720e+08,-1.326438,0.690401
19,:EG: Ägypten,3.831090e+08,0.276533,-3.243718
16,:CO: Kolumbien,4.185420e+08,0.893228,-0.160514
22,:PE: Peru,2.890700e+08,0.939287,0.455825
26,:HU: Ungarn,2.230600e+08,-0.222209,-0.060072
27,:QA: Katar,2.214520e+08,0.489094,-1.041468
37,:ET: Äthiopien,1.431230e+08,-0.927793,-2.590813
36,:GT: Guatemala,1.125750e+08,0.237447,0.219038
44,:RS: Serbien,8.907400e+07,-2.541898,-0.241160
48,:TZ: Tansania,8.017100e+07,0.735194,-1.377427
46,:TM: Turkmenistan,8.251500e+07,-1.048074,-0.100201
50,:CD: Demokratische Republik Kongo,7.101100e+07,-0.960467,-2.194201

In [32]:
countries_of_interest_red[["iso2","2024_gdp_mio","change_of_debts_current_yony","change_of_debts_future_yony"]].to_csv("emerging_markets_debts_quota.csv", index=False)

In [33]:
tickers_dict = {
 'Mexico':"D5BI.DE",
 'Türkiye, Republic of':"IQQ5.DE",
  'Vietnam':"XFVT.DE",
 "Hungary":"FHUBE.DE",
 "Qatar":"XGLF.DE",
 "Serbia":"ESNB.SG"}

In [34]:
data_dict={}
for country, ticker in tickers_dict.items():
    try:
        data = yfinance.download(ticker, start="2019-01-01")
        if not data.empty:
            print(f"{country} ({ticker}):")
            print(data['Close'].pct_change().dropna().head())
            data_dict[country] = data['Close'].dropna()
    except Exception as e:
        print(f"Error fetching data for {country} ({ticker}): {e}")

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Mexico (D5BI.DE):
Ticker       D5BI.DE
Date
2019-01-03 -0.004856
2019-01-04  0.015616
2019-01-07  0.001922
2019-01-08  0.023568
2019-01-09  0.016466

[*********************100%***********************]  1 of 1 completed

Türkiye, Republic of (IQQ5.DE):
Ticker       IQQ5.DE
Date
2019-01-03 -0.040348
2019-01-04  0.051735
2019-01-07 -0.011889
2019-01-08 -0.005565
2019-01-09 -0.000454

[*********************100%***********************]  1 of 1 completed

Vietnam (XFVT.DE):
Ticker       XFVT.DE
Date
2019-01-03 -0.015208
2019-01-04  0.019204
2019-01-07 -0.001554
2019-01-08 -0.011868
2019-01-09  0.009844

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['FHUBE.DE']: YFInvalidPeriodError("FHUBE.DE: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed

Qatar (XGLF.DE):
Ticker       XGLF.DE
Date
2019-01-03 -0.010326
2019-01-04  0.013729
2019-01-07  0.016658
2019-01-08 -0.007593
2019-01-09  0.006309

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ESNB.SG']: YFPricesMissingError('possibly delisted; no price data found  (1d 2019-01-01 -> 2025-06-10)')

In [35]:
((data_dict["Türkiye, Republic of"]-data_dict["Türkiye, Republic of"].shift(100))/data_dict["Türkiye, Republic of"].shift(100)).min()

Ticker
IQQ5.DE   -0.285083
dtype: float64

In [36]:
def calculate_change(shift_days):
    array_of_countries=[]
    for key in data_dict.keys():
        name_of_country=key
        max_change=(100*(data_dict[name_of_country]-data_dict[name_of_country].shift(shift_days))/data_dict[name_of_country].shift(shift_days)).max().values[0]
        min_change=(100*(data_dict[name_of_country]-data_dict[name_of_country].shift(shift_days))/data_dict[name_of_country].shift(shift_days)).min().values[0]
        median_change=(100*(data_dict[name_of_country]-data_dict[name_of_country].shift(shift_days))/data_dict[name_of_country].shift(shift_days)).median().values[0]

        row=[name_of_country,max_change,min_change,median_change]
        array_of_countries.append(row)
    df=pd.DataFrame(array_of_countries, columns=["Land", "Maximum", "Minimum","Median"])
    df["Tage"]=shift_days
    return df

In [37]:
array_of_days=[50,100,200]
df=pd.DataFrame(columns=["Land", "Maximum", "Minimum", "Median", "Tage"])
for days in array_of_days:
    calculate_change(days)
    df=pd.concat([df,calculate_change(days)])
df

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_2859/1909615769.py:5: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df=pd.concat([df,calculate_change(days)])

                   Land    Maximum    Minimum    Median Tage
0                Mexico  34.322345 -43.373778  2.645614   50
1  Türkiye, Republic of  50.511436 -35.657208  1.360477   50
2               Vietnam  32.722862 -37.339419 -0.144717   50
3                 Qatar  25.382010 -29.704685  1.796413   50
0                Mexico  33.693256 -40.344994  5.166310  100
1  Türkiye, Republic of  84.160603 -28.508294  1.382591  100
2               Vietnam  39.904893 -34.368601 -0.917784  100
3                 Qatar  39.142730 -24.778527  3.331193  100
0                Mexico  55.086326 -38.631431  9.421802  200
1  Türkiye, Republic of  92.287517 -46.282579  5.590247  200
2               Vietnam  66.978686 -43.544238 -5.131937  200
3                 Qatar  59.928650 -29.581083  4.053744  200

In [38]:
country_to_german_mapping = {
    "Hungary": "Ungarn",
    "Qatar": "Katar",
    "Vietnam": "Vietnam",
    "Peru": "Peru",
    "Mexico": "Mexiko",
    "Colombia": "Kolumbien",
    "Egypt": "Ägypten",
    "Türkiye, Republic of": "Türkei"
}

In [41]:
df["Land"] = df["Land"].replace(country_to_german_mapping)
df.sort_values(by="Median", ascending=True, inplace=True)
df

      Land    Maximum    Minimum    Median Tage
2  Vietnam  66.978686 -43.544238 -5.131937  200
2  Vietnam  39.904893 -34.368601 -0.917784  100
2  Vietnam  32.722862 -37.339419 -0.144717   50
1   Türkei  50.511436 -35.657208  1.360477   50
1   Türkei  84.160603 -28.508294  1.382591  100
3    Katar  25.382010 -29.704685  1.796413   50
0   Mexiko  34.322345 -43.373778  2.645614   50
3    Katar  39.142730 -24.778527  3.331193  100
3    Katar  59.928650 -29.581083  4.053744  200
0   Mexiko  33.693256 -40.344994  5.166310  100
1   Türkei  92.287517 -46.282579  5.590247  200
0   Mexiko  55.086326 -38.631431  9.421802  200

In [43]:
df.sort_values(by=["Median"], ascending=False, inplace=True)
low_performer=df[df["Land"].isin(["Türkei", "Vietnam"])]
custom_order = ["Türkei", "Vietnam"]  # your desired order

low_performer["Land"] = pd.Categorical(low_performer["Land"], categories=custom_order, ordered=True)

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_2859/2684853055.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  low_performer["Land"] = pd.Categorical(low_performer["Land"], categories=custom_order, ordered=True)

In [44]:

low_performer.sort_values(by=["Land","Tage"], ascending=[True,True], inplace=True)
low_performer

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_2859/294988649.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  low_performer.sort_values(by=["Land","Tage"], ascending=[True,True], inplace=True)

      Land    Maximum    Minimum    Median Tage
1   Türkei  50.511436 -35.657208  1.360477   50
1   Türkei  84.160603 -28.508294  1.382591  100
1   Türkei  92.287517 -46.282579  5.590247  200
2  Vietnam  32.722862 -37.339419 -0.144717   50
2  Vietnam  39.904893 -34.368601 -0.917784  100
2  Vietnam  66.978686 -43.544238 -5.131937  200

In [45]:
low_performer.to_csv("emerging_markets_low_performer.csv", index=False)

In [48]:
high_performer=df[~df["Land"].isin(["Türkei", "Vietnam"])]
high_performer.sort_values(by=["Land","Tage"], ascending=True, inplace=True)
high_performer

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_2859/2725539543.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  high_performer.sort_values(by=["Land","Tage"], ascending=True, inplace=True)

     Land    Maximum    Minimum    Median Tage
3   Katar  25.382010 -29.704685  1.796413   50
3   Katar  39.142730 -24.778527  3.331193  100
3   Katar  59.928650 -29.581083  4.053744  200
0  Mexiko  34.322345 -43.373778  2.645614   50
0  Mexiko  33.693256 -40.344994  5.166310  100
0  Mexiko  55.086326 -38.631431  9.421802  200

In [49]:
custom_order = ["Mexiko", "Katar"]  # your desired order

high_performer["Land"] = pd.Categorical(high_performer["Land"], categories=custom_order, ordered=True)
high_performer.sort_values(by=["Land","Tage"], ascending=True, inplace=True)
high_performer

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_2859/2838842073.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  high_performer["Land"] = pd.Categorical(high_performer["Land"], categories=custom_order, ordered=True)
/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_2859/2838842073.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  high_performer.sort_values(by=["Land","Tage"], ascending=True, inplace=True)

     Land    Maximum    Minimum    Median Tage
0  Mexiko  34.322345 -43.373778  2.645614   50
0  Mexiko  33.693256 -40.344994  5.166310  100
0  Mexiko  55.086326 -38.631431  9.421802  200
3   Katar  25.382010 -29.704685  1.796413   50
3   Katar  39.142730 -24.778527  3.331193  100
3   Katar  59.928650 -29.581083  4.053744  200

In [50]:
high_performer.to_csv("emerging_markets_high_performer.csv", index=False)