In [1]:
import pandas as pd
import glob

In [2]:
files=glob.glob('../data/*.xlsx')
files

['../data/SPARDA_Wohnen_in_Deutschland_2025_Handelsblatt.xlsx',
 '../data/AuszugGV2QAktuell.xlsx',
 '../data/250715_Handelsblatt_Umland_Metropolen_FINAL.xlsx']

In [3]:
metropolen_data_poll=pd.read_excel('../data/250715_Handelsblatt_Umland_Metropolen_FINAL.xlsx',skiprows=2)
metropolen_data_poll

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)

,Metropole,Stadt/Landkreis,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,durchschn. Kaufpreis 1. HJ 2024,Angebote 1. HJ 2024,Preisentwicklung,Angebotsentwicklung,Ø-Entfernung in km,indexiert im Bundesdurchschnitt (D = 100%),Ø-Entfernung in km.1,indexiert im Bundesdurchschnitt (D = 100%).1,Ø-Entfernung in km.2,indexiert im Bundesdurchschnitt (D = 100%).2,Einpendler aus Metropole,Einpendler pro 1.000 Ew.,Auspendler nach Metropole,Auspendler pro 1.000 Ew.,Pendersaldo zu Metropole,Pender pro 1.000 Ew.
0,Berlin,Potsdam,5324,499.0,4942.0,676.0,0.077297,-0.261834,6.78,76.20,2.31,61.16,1.04,50.06,15050.0,76.92,20760.0,110.10,-5710.0,-33.18
1,Berlin,Oder-Spree,2936,423.0,2838.0,716.0,0.034531,-0.409218,11.63,130.59,3.42,90.71,3.40,163.85,9670.0,53.38,14310.0,78.15,-4640.0,-24.77
2,Berlin,Potsdam-Mittelmark,3880,679.0,3779.0,1025.0,0.026727,-0.337561,6.50,73.05,4.42,117.18,4.30,208.00,9240.0,41.39,23070.0,102.40,-13830.0,-61.01
3,Berlin,Berlin,5527,13095.0,5480.0,17695.0,0.008577,-0.259960,4.47,50.17,1.84,48.69,0.59,28.57,NaN,NaN,NaN,NaN,NaN,NaN
4,Berlin,Dahme-Spreewald,3540,502.0,3545.0,708.0,-0.001410,-0.290960,7.02,78.89,4.42,117.22,3.36,162.27,15850.0,82.88,25220.0,139.40,-9370.0,-56.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,NaN,NaN,Pendlerströme (Spalten O-T): empirica regio (S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,NaN,NaN,"Einpendler aus Metropole: Anzahl an Personen, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,"Auspendler nach Metropole: Anzahl an Personen,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,Pendlersaldo: Summe von Aus- und Einpendlern j...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
metropolen_data_poll=metropolen_data_poll.dropna(subset=["Stadt/Landkreis"])

In [5]:
metropolen_data_poll["Stadt/Landkreis"].tolist()

['Potsdam',
 'Oder-Spree',
 'Potsdam-Mittelmark',
 'Berlin',
 'Dahme-Spreewald',
 'Oberhavel',
 'Teltow-Fläming',
 'Barnim',
 'Havelland',
 'Märkisch-Oderland',
 'Mönchengladbach',
 'Wuppertal',
 'Köln',
 'Rheinisch-Bergischer Kreis',
 'Remscheid',
 'Oberhausen',
 'Essen',
 'Rhein-Kreis Neuss',
 'Kreis Wesel',
 'Krefeld',
 'Duisburg',
 'Kreis Viersen',
 'Düsseldorf',
 'Leverkusen',
 'Rhein-Erft-Kreis',
 'Solingen',
 'Kreis Mettmann',
 'Mülheim an der Ruhr',
 'Mainz',
 'Wiesbaden',
 'Frankfurt am Main',
 'Offenbach am Main',
 'Darmstadt',
 'Darmstadt-Dieburg',
 'Wetteraukreis',
 'LK Offenbach',
 'Main-Kinzig-Kreis',
 'Rheingau-Taunus-Kreis',
 'Hochtaunuskreis',
 'Groß-Gerau',
 'Main-Taunus-Kreis',
 'Kreis Segeberg',
 'Lüneburg',
 'Hamburg',
 'Kreis Stormarn',
 'Kreis Pinneberg',
 'Kreis Herzogtum Lauenburg',
 'Harburg',
 'Stade',
 'Köln',
 'Rheinisch-Bergischer Kreis',
 'Remscheid',
 'Oberbergischer Kreis',
 'Rhein-Kreis Neuss',
 'Bonn',
 'Düsseldorf',
 'Leverkusen',
 'Rhein-Erft-Kreis',
 'Rhein-Sieg-Kreis',
 'Solingen',
 'Kreis Mettmann',
 'Leipzig',
 'Saalekreis',
 'Halle/Saale',
 'Nordsachsen',
 'Burgenlandkreis',
 'LK Leipzig',
 'Miesbach',
 'Bad Tölz-Wolfratshausen',
 'München',
 'Erding',
 'Freising',
 'Ebersberg',
 'Fürstenfeldbruck',
 'LK München',
 'Dachau',
 'Starnberg',
 'Tübingen',
 'Esslingen',
 'Enzkreis',
 'Stuttgart',
 'Rems-Murr-Kreis',
 'Reutlingen',
 'Ludwigsburg',
 'Böblingen']

In [6]:
metropolen_data_poll["Stadt/Landkreis"] = metropolen_data_poll["Stadt/Landkreis"].str.replace("LK", "").str.strip()
metropolen_data_poll["Stadt/Landkreis"] = metropolen_data_poll["Stadt/Landkreis"].str.replace("-", "-").str.strip()
metropolen_data_poll

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_64243/4145271482.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metropolen_data_poll["Stadt/Landkreis"] = metropolen_data_poll["Stadt/Landkreis"].str.replace("LK", "").str.strip()
/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_64243/4145271482.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metropolen_data_poll["Stadt/Landkreis"] = metropolen_data_poll["Stadt/Landkreis"].str.replace("-", "-").str.strip()

,Metropole,Stadt/Landkreis,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,durchschn. Kaufpreis 1. HJ 2024,Angebote 1. HJ 2024,Preisentwicklung,Angebotsentwicklung,Ø-Entfernung in km,indexiert im Bundesdurchschnitt (D = 100%),Ø-Entfernung in km.1,indexiert im Bundesdurchschnitt (D = 100%).1,Ø-Entfernung in km.2,indexiert im Bundesdurchschnitt (D = 100%).2,Einpendler aus Metropole,Einpendler pro 1.000 Ew.,Auspendler nach Metropole,Auspendler pro 1.000 Ew.,Pendersaldo zu Metropole,Pender pro 1.000 Ew.
0,Berlin,Potsdam,5324,499.0,4942.0,676.0,0.077297,-0.261834,6.78,76.20,2.31,61.16,1.04,50.06,15050.0,76.92,20760.0,110.10,-5710.0,-33.18
1,Berlin,Oder-Spree,2936,423.0,2838.0,716.0,0.034531,-0.409218,11.63,130.59,3.42,90.71,3.40,163.85,9670.0,53.38,14310.0,78.15,-4640.0,-24.77
2,Berlin,Potsdam-Mittelmark,3880,679.0,3779.0,1025.0,0.026727,-0.337561,6.50,73.05,4.42,117.18,4.30,208.00,9240.0,41.39,23070.0,102.40,-13830.0,-61.01
3,Berlin,Berlin,5527,13095.0,5480.0,17695.0,0.008577,-0.259960,4.47,50.17,1.84,48.69,0.59,28.57,NaN,NaN,NaN,NaN,NaN,NaN
4,Berlin,Dahme-Spreewald,3540,502.0,3545.0,708.0,-0.001410,-0.290960,7.02,78.89,4.42,117.22,3.36,162.27,15850.0,82.88,25220.0,139.40,-9370.0,-56.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,Stuttgart,Stuttgart,4759,2366.0,4679.0,3004.0,0.017098,-0.212383,8.08,90.78,2.40,63.56,0.74,35.90,NaN,NaN,NaN,NaN,NaN,NaN
81,Stuttgart,Rems-Murr-Kreis,3658,1771.0,3618.0,2415.0,0.011056,-0.266667,20.86,234.00,2.76,73.14,1.65,79.79,11230.0,25.40,38270.0,88.55,-27040.0,-63.15
82,Stuttgart,Reutlingen,3488,1034.0,3452.0,1411.0,0.010429,-0.267186,26.48,297.00,3.60,95.45,1.69,81.62,2510.0,7.90,5830.0,19.71,-3320.0,-11.81
83,Stuttgart,Ludwigsburg,3927,2464.0,3904.0,3307.0,0.005891,-0.254914,6.42,72.15,2.97,78.63,1.56,75.27,20520.0,36.29,53660.0,97.80,-33140.0,-61.51
84,Stuttgart,Böblingen,3982,1973.0,3981.0,2447.0,0.000251,-0.193707,4.97,55.86,2.46,65.32,1.21,58.35,15820.0,39.91,32120.0,80.08,-16300.0,-40.17

In [7]:
sparda_daten=pd.read_excel('../data/SPARDA_Wohnen_in_Deutschland_2025_Handelsblatt.xlsx')
sparda_daten["Kreiskennziffer"]= sparda_daten["Kreiskennziffer"].astype(str).str.zfill(5)
sparda_daten

,lfd. Nr.,Kreis,Kreiskennziffer,Metropole,Landkreis,Mittelstadt,Osten,"Preise je m² in € einer Eigentumswohnung in Städten und von Ein- und Zweifamilienhäusern in Landkreisen (jeweils Bestand),\n2025 (1. Quartal)","Anzahl der m² für eine Investitionssumme\nvon 360.000 €, 2025 (1. Quartal)","Kaufpreise für eine 117 m² große Immobilie im\nVerhältnis zum Jahreshaushaltseinkommen\n(netto), 2025 (1. Quartal)",...,"Neubaubedarf von Wohnungen\nje 10.000 Einwohner pro Jahr, 2023 bis 2030","Anteil der Pendler, die in eine Metropole pendeln, an allen Beschäftigten am Wohnort\nin %, 2024","Wanderungssaldo (Zuzüge minus Fortzüge)\nder 30- bis unter 50-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023","Wanderungssaldo (Zuzüge minus Fortzüge)\nder 18- bis unter 30-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023","Pendlersaldo (Einpendler minus Auspendler)\nje 100 Beschäftigte* am Arbeitsort, 2024",Entwicklung der Einwohnerzahl von 2012 bis 2023 in %,Prognostizierte Entwicklung der Einwohnerzahl von 2025 bis 2040 in %,Zukunftsindex_Kategorie,Regionalranking_Kategorie,Zukunftsampel_Kategorie
0,1,Flensburg,01001,0,0,0,0,2529.41,142.325681,7.535490,...,53.7,3.991131,-2.942836,20.927818,23.257099,15.538808,4.486701,1,6,2
1,2,Kiel,01002,0,0,1,0,3100.00,116.129032,8.464531,...,44.1,5.954964,-10.080858,58.235212,25.218651,4.954850,1.797912,1,6,2
2,3,Lübeck,01003,0,0,1,0,3672.00,98.039216,9.364078,...,35.9,7.586061,4.340809,45.467259,19.442346,2.526061,2.603264,2,6,3
3,4,Neumünster,01004,0,0,0,0,2076.92,173.333590,5.261571,...,31.5,6.825619,18.087855,40.585436,25.787879,3.261816,0.067413,4,6,4
4,5,Kreis Dithmarschen,01051,0,1,0,0,2136.36,168.510925,4.592417,...,29.0,5.466787,16.963674,5.083065,-16.056802,0.412891,1.472478,5,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,LK Saalfeld-Rudolstadt,16073,0,1,0,1,1051.58,342.342000,2.530576,...,6.8,1.231372,10.754134,8.362203,-17.330307,-9.287387,-12.502869,5,4,3
396,397,Saale-Holzland-Kreis,16074,0,1,0,1,1898.81,189.592429,4.358001,...,5.7,1.265190,25.036744,43.225380,-27.645756,-0.287131,-10.342968,5,4,4
397,398,Saale-Orla-Kreis,16075,0,1,0,1,923.08,389.998700,2.295704,...,6.0,0.999813,8.124964,-10.581222,-16.772429,-7.788239,-10.781915,5,5,4
398,399,LK Greiz,16076,0,1,0,1,1031.25,349.090909,2.512735,...,6.2,1.214430,10.902574,-5.865103,-25.706656,-8.527837,-13.736337,6,5,4
399,400,LK Altenburger Land,16077,0,1,0,1,1033.33,348.388221,2.647617,...,7.3,1.125030,22.012075,13.004791,-21.705512,-7.170524,-11.884750,6,5,4

In [8]:
sparda_daten["Kreis"] = sparda_daten["Kreis"].str.replace("LK", "").str.strip()
sparda_daten["Kreis"] = sparda_daten["Kreis"].str.replace("-", "-").str.strip()

In [9]:
metropolen_poll_sparda=pd.merge(metropolen_data_poll, sparda_daten, how='outer', left_on='Stadt/Landkreis', right_on='Kreis',indicator=True)
metropolen_poll_sparda

,Metropole_x,Stadt/Landkreis,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,durchschn. Kaufpreis 1. HJ 2024,Angebote 1. HJ 2024,Preisentwicklung,Angebotsentwicklung,Ø-Entfernung in km,indexiert im Bundesdurchschnitt (D = 100%),...,"Anteil der Pendler, die in eine Metropole pendeln, an allen Beschäftigten am Wohnort\nin %, 2024","Wanderungssaldo (Zuzüge minus Fortzüge)\nder 30- bis unter 50-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023","Wanderungssaldo (Zuzüge minus Fortzüge)\nder 18- bis unter 30-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023","Pendlersaldo (Einpendler minus Auspendler)\nje 100 Beschäftigte* am Arbeitsort, 2024",Entwicklung der Einwohnerzahl von 2012 bis 2023 in %,Prognostizierte Entwicklung der Einwohnerzahl von 2025 bis 2040 in %,Zukunftsindex_Kategorie,Regionalranking_Kategorie,Zukunftsampel_Kategorie,_merge
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.401448,19.852599,15.723702,-34.430588,2.152785,2.672579,4,3,3,right_only
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.529711,21.552348,12.665266,-50.322795,7.214145,4.630627,5,1,2,right_only
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.654368,12.464325,12.890581,-51.408003,7.826937,3.189417,4,2,2,right_only
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.125030,22.012075,13.004791,-21.705512,-7.170524,-11.884750,6,5,4,right_only
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.993727,17.521152,9.291078,-34.280521,2.309431,-0.307236,5,5,4,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.615302,-19.550737,56.526807,41.632133,5.765109,0.618336,1,3,1,right_only
409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.553313,15.126134,13.540487,-70.909002,1.805399,0.800539,3,2,2,right_only
410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.588554,11.733083,8.974572,-14.348730,4.701123,-2.471060,3,3,2,right_only
411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.841485,8.279783,33.107951,14.509631,-2.081376,-0.114514,3,5,4,right_only
412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.006904,15.536400,19.370460,-0.858985,-6.184793,-10.849122,4,5,4,right_only

In [10]:
metropolen_poll_sparda[metropolen_poll_sparda["Zukunftsindex_Kategorie"].isna()]

Empty DataFrame
Columns: [Metropole_x, Stadt/Landkreis, durchschn. Kaufpreis 1. HJ 2025, Angebote 1. HJ 2025, durchschn. Kaufpreis 1. HJ 2024, Angebote 1. HJ 2024, Preisentwicklung, Angebotsentwicklung, Ø-Entfernung in km, indexiert im Bundesdurchschnitt (D = 100%), Ø-Entfernung in km.1, indexiert im Bundesdurchschnitt (D = 100%).1, Ø-Entfernung in km.2, indexiert im Bundesdurchschnitt (D = 100%).2, Einpendler aus Metropole, Einpendler pro 1.000 Ew., Auspendler nach Metropole, Auspendler pro 1.000 Ew., Pendersaldo zu Metropole, Pender pro 1.000 Ew. , lfd. Nr., Kreis, Kreiskennziffer, Metropole_y, Landkreis, Mittelstadt, Osten, Preise je m² in € einer Eigentumswohnung in Städten und von Ein- und Zweifamilienhäusern in Landkreisen (jeweils Bestand),
2025 (1. Quartal), Anzahl der m² für eine Investitionssumme
von 360.000 €, 2025 (1. Quartal), Kaufpreise für eine 117 m² große Immobilie im
Verhältnis zum Jahreshaushaltseinkommen
(netto), 2025 (1. Quartal), Preisentwicklung in % für Eigentumswohnungen in
Städten und Ein- und Zweifamilienhäusern in Landkreisen (jeweils Bestand), 2012 bis 2025 (1. Quartal), Preisentwicklung in % für
Eigentumswohnungen in
Städten und Ein- und Zweifamilienhäusern in Landkreisen (jeweils Bestand), 2024 bis 2025 (1. Quartal), Neubaubedarf von Wohnungen
je 10.000 Einwohner pro Jahr, 2023 bis 2030, Anteil der Pendler, die in eine Metropole pendeln, an allen Beschäftigten am Wohnort
in %, 2024, Wanderungssaldo (Zuzüge minus Fortzüge)
der 30- bis unter 50-Jährigen
je 1.000 Einwohner der Altersgruppe, 2023, Wanderungssaldo (Zuzüge minus Fortzüge)
der 18- bis unter 30-Jährigen
je 1.000 Einwohner der Altersgruppe, 2023, Pendlersaldo (Einpendler minus Auspendler)
je 100 Beschäftigte* am Arbeitsort, 2024, Entwicklung der Einwohnerzahl von 2012 bis 2023 in %, Prognostizierte Entwicklung der Einwohnerzahl von 2025 bis 2040 in %, Zukunftsindex_Kategorie, Regionalranking_Kategorie, Zukunftsampel_Kategorie, _merge]
Index: []

[0 rows x 43 columns]

In [11]:
metropolen_poll_sparda[metropolen_poll_sparda["durchschn. Kaufpreis 1. HJ 2025"].isna()]["Kreis"].tolist()

['Ahrweiler',
 'Aichach-Friedberg',
 'Alb-Donau-Kreis',
 'Altenburger Land',
 'Altenkirchen (Westerwald)',
 'Altmarkkreis Salzwedel',
 'Altötting',
 'Alzey-Worms',
 'Amberg',
 'Amberg-Sulzbach',
 'Ammerland',
 'Anhalt-Bitterfeld',
 'Ansbach',
 'Ansbach',
 'Aschaffenburg',
 'Aschaffenburg',
 'Augsburg',
 'Augsburg',
 'Aurich',
 'Bad Dürkheim',
 'Bad Kissingen',
 'Bad Kreuznach',
 'Baden-Baden',
 'Bamberg',
 'Bamberg',
 'Bautzen',
 'Bayreuth',
 'Bayreuth',
 'Berchtesgadener Land',
 'Bergstraße',
 'Bernkastel-Wittlich',
 'Biberach',
 'Bielefeld',
 'Birkenfeld',
 'Bochum',
 'Bodenseekreis',
 'Bottrop',
 'Brandenburg an der Havel',
 'Braunschweig',
 'Breisgau-Hochschwarzwald',
 'Bremen',
 'Bremerhaven',
 'Börde',
 'Calw',
 'Celle',
 'Cham',
 'Chemnitz',
 'Cloppenburg',
 'Coburg',
 'Coburg',
 'Cochem-Zell',
 'Cottbus',
 'Cuxhaven',
 'Deggendorf',
 'Delmenhorst',
 'Dessau-Roßlau',
 'Diepholz',
 'Dillingen a.d. Donau',
 'Dingolfing-Landau',
 'Donau-Ries',
 'Donnersbergkreis',
 'Dortmund',
 'Dresden',
 'Eichsfeld',
 'Eichstätt',
 'Eifelkreis Bitburg-Prüm',
 'Elbe-Elster',
 'Emden',
 'Emmendingen',
 'Emsland',
 'Ennepe-Ruhr-Kreis',
 'Erfurt',
 'Erlangen',
 'Erlangen-Höchstadt',
 'Erzgebirgskreis',
 'Flensburg',
 'Forchheim',
 'Frankenthal (Pfalz)',
 'Frankfurt (Oder)',
 'Freiburg im Breisgau',
 'Freudenstadt',
 'Freyung-Grafenau',
 'Friesland',
 'Fulda',
 'Fürth',
 'Fürth',
 'Garmisch-Partenkirchen',
 'Gelsenkirchen',
 'Gera',
 'Germersheim',
 'Gießen',
 'Gifhorn',
 'Goslar',
 'Gotha',
 'Grafschaft Bentheim',
 'Greiz',
 'Göppingen',
 'Görlitz',
 'Göttingen',
 'Günzburg',
 'Hagen',
 'Hameln-Pyrmont',
 'Hamm',
 'Harz',
 'Haßberge',
 'Heidekreis',
 'Heidelberg',
 'Heidenheim',
 'Heilbronn',
 'Heilbronn',
 'Helmstedt',
 'Herne',
 'Hersfeld-Rotenburg',
 'Hildburghausen',
 'Hildesheim',
 'Hochsauerlandkreis',
 'Hof',
 'Hof',
 'Hohenlohekreis',
 'Holzminden',
 'Ilm-Kreis',
 'Ingolstadt',
 'Jena',
 'Jerichower Land',
 'Kaiserslautern',
 'Kaiserslautern',
 'Karlsruhe',
 'Karlsruhe',
 'Kassel',
 'Kassel',
 'Kaufbeuren',
 'Kelheim',
 'Kempten (Allgäu)',
 'Kiel',
 'Kitzingen',
 'Koblenz',
 'Konstanz',
 'Kreis Borken',
 'Kreis Coesfeld',
 'Kreis Dithmarschen',
 'Kreis Düren',
 'Kreis Euskirchen',
 'Kreis Gütersloh',
 'Kreis Heinsberg',
 'Kreis Herford',
 'Kreis Höxter',
 'Kreis Kleve',
 'Kreis Lippe',
 'Kreis Minden-Lübbecke',
 'Kreis Nordfriesland',
 'Kreis Olpe',
 'Kreis Ostholstein',
 'Kreis Paderborn',
 'Kreis Plön',
 'Kreis Recklinghausen',
 'Kreis Rendsburg-Eckernförde',
 'Kreis Schleswig-Flensburg',
 'Kreis Siegen-Wittgenstein',
 'Kreis Soest',
 'Kreis Steinburg',
 'Kreis Steinfurt',
 'Kreis Unna',
 'Kreis Warendorf',
 'Kronach',
 'Kulmbach',
 'Kusel',
 'Kyffhäuserkreis',
 'Lahn-Dill-Kreis',
 'Landau in der Pfalz',
 'Landsberg a. Lech',
 'Landshut',
 'Landshut',
 'Leer',
 'Lichtenfels',
 'Limburg-Weilburg',
 'Lindau (Bodensee)',
 'Ludwigshafen am Rhein',
 'Ludwigslust-Parchim',
 'Lörrach',
 'Lübeck',
 'Lüchow-Dannenberg',
 'Magdeburg',
 'Main-Spessart',
 'Main-Tauber-Kreis',
 'Mainz-Bingen',
 'Mannheim',
 'Mansfeld-Südharz',
 'Marburg-Biedenkopf',
 'Mayen-Koblenz',
 'Mecklenburgische Seenplatte',
 'Meißen',
 'Memmingen',
 'Merzig-Wadern',
 'Miltenberg',
 'Mittelsachsen',
 'Märkischer Kreis',
 'Mühldorf a. Inn',
 'Münster',
 'Neckar-Odenwald-Kreis',
 'Neu-Ulm',
 'Neuburg-Schrobenhausen',
 'Neumarkt i.d. OPf.',
 'Neumünster',
 'Neunkirchen',
 'Neustadt a. d. Weinstraße',
 'Neustadt a.d. Waldnaab',
 'Neustadt a.d.Aisch-Bad Windsheim',
 'Neuwied',
 'Nienburg (Weser)',
 'Nordhausen',
 'Nordwestmecklenburg',
 'Northeim',
 'Nürnberg',
 'Nürnberger Land',
 'Oberallgäu',
 'Oberspreewald-Lausitz',
 'Odenwaldkreis',
 'Oldenburg',
 'Oldenburg',
 'Ortenaukreis',
 'Osnabrück',
 'Osnabrück',
 'Ostalbkreis',
 'Ostallgäu',
 'Osterholz',
 'Ostprignitz-Ruppin',
 'Passau',
 'Passau',
 'Peine',
 'Pfaffenhofen a.d. Ilm',
 'Pforzheim',
 'Pirmasens',
 'Prignitz',
 'Rastatt',
 'Ravensburg',
 'Regen',
 'Regensburg',
 'Regensburg',
 'Region Hannover',
 'Regionalverband Saarbrücken',
 'Rhein-Hunsrück-Kreis',
 'Rhein-Lahn-Kreis',
 'Rhein-Neckar-Kreis',
 'Rhein-Pfalz-Kreis',
 'Rhön-Grabfeld',
 'Rosenheim',
 'Rosenheim',
 'Rostock',
 'Rostock',
 'Rotenburg (Wümme)',
 'Roth',
 'Rottal-Inn',
 'Rottweil',
 'Saale-Holzland-Kreis',
 'Saale-Orla-Kreis',
 'Saalfeld-Rudolstadt',
 'Saarlouis',
 'Saarpfalz-Kreis',
 'Salzgitter',
 'Salzlandkreis',
 'Sankt Wendel',
 'Schaumburg',
 'Schmalkalden-Meiningen',
 'Schwabach',
 'Schwalm-Eder-Kreis',
 'Schwandorf',
 'Schwarzwald-Baar-Kreis',
 'Schweinfurt',
 'Schweinfurt',
 'Schwerin',
 'Schwäbisch Hall',
 'Sigmaringen',
 'Sonneberg',
 'Speyer',
 'Spree-Neiße',
 'Stendal',
 'Straubing',
 'Straubing-Bogen',
 'Städteregion Aachen',
 'Suhl',
 'Sächsische Schweiz-Osterzgebirge',
 'Sömmerda',
 'Südliche Weinstraße',
 'Südwestpfalz',
 'Tirschenreuth',
 'Traunstein',
 'Trier',
 'Trier-Saarburg',
 'Tuttlingen',
 'Uckermark',
 'Uelzen',
 'Ulm',
 'Unstrut-Hainich-Kreis',
 'Unterallgäu',
 'Vechta',
 'Verden',
 'Vogelsbergkreis',
 'Vogtlandkreis',
 'Vorpommern-Greifswald',
 'Vorpommern-Rügen',
 'Vulkaneifel',
 'Waldeck-Frankenberg',
 'Waldshut',
 'Wartburgkreis',
 'Weiden i. d. OPf.',
 'Weilheim-Schongau',
 'Weimar',
 'Weimarer Land',
 'Weißenburg-Gunzenhausen',
 'Werra-Meißner-Kreis',
 'Wesermarsch',
 'Westerwaldkreis',
 'Wilhelmshaven',
 'Wittenberg',
 'Wittmund',
 'Wolfenbüttel',
 'Wolfsburg',
 'Worms',
 'Wunsiedel i. Fichtelgebirge',
 'Würzburg',
 'Würzburg',
 'Zollernalbkreis',
 'Zweibrücken',
 'Zwickau']

In [12]:
metropolen_poll_sparda_cleaned=metropolen_poll_sparda[metropolen_poll_sparda["_merge"]=="both"]
metropolen_poll_sparda_cleaned

,Metropole_x,Stadt/Landkreis,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,durchschn. Kaufpreis 1. HJ 2024,Angebote 1. HJ 2024,Preisentwicklung,Angebotsentwicklung,Ø-Entfernung in km,indexiert im Bundesdurchschnitt (D = 100%),...,"Anteil der Pendler, die in eine Metropole pendeln, an allen Beschäftigten am Wohnort\nin %, 2024","Wanderungssaldo (Zuzüge minus Fortzüge)\nder 30- bis unter 50-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023","Wanderungssaldo (Zuzüge minus Fortzüge)\nder 18- bis unter 30-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023","Pendlersaldo (Einpendler minus Auspendler)\nje 100 Beschäftigte* am Arbeitsort, 2024",Entwicklung der Einwohnerzahl von 2012 bis 2023 in %,Prognostizierte Entwicklung der Einwohnerzahl von 2025 bis 2040 in %,Zukunftsindex_Kategorie,Regionalranking_Kategorie,Zukunftsampel_Kategorie,_merge
22,München,Bad Tölz-Wolfratshausen,5689,391.0,5331.0,414.0,0.067154,-0.055556,12.55,140.93,...,16.863591,16.502463,13.040143,-40.325353,7.560664,4.186359,4,1,2,both
26,Berlin,Barnim,3317,535.0,3415.0,720.0,-0.028697,-0.256944,6.81,76.46,...,41.134607,24.730787,13.890545,-46.466925,11.307039,0.462604,5,3,2,both
32,Berlin,Berlin,5527,13095.0,5480.0,17695.0,0.008577,-0.259960,4.47,50.17,...,2.972945,0.934790,76.750818,10.912447,8.507855,7.080914,1,2,1,both
39,Köln,Bonn,3860,948.0,3707.0,1205.0,0.041273,-0.213278,2.36,26.46,...,13.774530,-11.661232,28.616767,33.250440,3.811611,0.809867,1,2,1,both
46,Leipzig,Burgenlandkreis,1207,353.0,1219.0,575.0,-0.009844,-0.386087,13.39,150.41,...,1.501034,22.126430,26.051433,-17.991848,-5.838318,-11.882415,6,6,4,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,Berlin,Teltow-Fläming,3119,482.0,3180.0,683.0,-0.019182,-0.294290,15.15,170.20,...,30.731746,32.885318,24.565293,-12.320727,11.105545,1.483037,4,1,1,both
374,Stuttgart,Tübingen,3992,605.0,3833.0,746.0,0.041482,-0.189008,17.28,194.04,...,7.003337,-1.611521,36.590685,-1.065178,8.377619,2.399563,1,2,1,both
398,Frankfurt,Wetteraukreis,3178,864.0,3080.0,1259.0,0.031818,-0.313741,7.14,80.22,...,23.899081,14.748621,12.456803,-41.133697,5.703545,3.656916,3,3,2,both
399,Frankfurt,Wiesbaden,4476,1083.0,4119.0,1571.0,0.086672,-0.310630,3.03,34.04,...,13.907001,6.977044,49.271014,21.998167,5.356959,-1.198746,2,3,1,both
407,Düsseldorf,Wuppertal,2369,1063.0,2184.0,1368.0,0.084707,-0.222953,2.57,28.86,...,10.097188,1.413606,26.538276,-2.279762,4.580836,1.922726,2,6,4,both

In [13]:
metropolen_poll_sparda_cleaned.columns

Index(['Metropole_x', 'Stadt/Landkreis', 'durchschn. Kaufpreis 1. HJ 2025',
       'Angebote 1. HJ 2025', 'durchschn. Kaufpreis 1. HJ 2024',
       'Angebote 1. HJ 2024', 'Preisentwicklung', 'Angebotsentwicklung',
       'Ø-Entfernung in km', 'indexiert im Bundesdurchschnitt (D = 100%)',
       'Ø-Entfernung in km.1', 'indexiert im Bundesdurchschnitt (D = 100%).1',
       'Ø-Entfernung in km.2', 'indexiert im Bundesdurchschnitt (D = 100%).2',
       'Einpendler aus Metropole', 'Einpendler pro 1.000 Ew.',
       'Auspendler nach Metropole', 'Auspendler pro 1.000 Ew.',
       'Pendersaldo zu Metropole', 'Pender pro 1.000 Ew. ', 'lfd. Nr.',
       'Kreis', 'Kreiskennziffer', 'Metropole_y', 'Landkreis', 'Mittelstadt',
       'Osten',
       'Preise je m² in € einer Eigentumswohnung in Städten und von Ein- und Zweifamilienhäusern in Landkreisen (jeweils Bestand),\n2025 (1. Quartal)',
       'Anzahl der m² für eine Investitionssumme\nvon 360.000 €, 2025 (1. Quartal)',
       'Kaufpreise für eine 117 m² große Immobilie im\nVerhältnis zum Jahreshaushaltseinkommen\n(netto), 2025 (1. Quartal)',
       'Preisentwicklung in % für Eigentumswohnungen in\nStädten und Ein- und Zweifamilienhäusern in Landkreisen (jeweils Bestand), 2012 bis 2025 (1. Quartal)',
       'Preisentwicklung in % für\nEigentumswohnungen in\nStädten und Ein- und Zweifamilienhäusern in Landkreisen (jeweils Bestand), 2024 bis 2025 (1. Quartal)',
       'Neubaubedarf von Wohnungen\nje 10.000 Einwohner pro Jahr, 2023 bis 2030',
       'Anteil der Pendler, die in eine Metropole pendeln, an allen Beschäftigten am Wohnort\nin %, 2024',
       'Wanderungssaldo (Zuzüge minus Fortzüge)\nder 30- bis unter 50-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023',
       'Wanderungssaldo (Zuzüge minus Fortzüge)\nder 18- bis unter 30-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023',
       'Pendlersaldo (Einpendler minus Auspendler)\nje 100 Beschäftigte* am Arbeitsort, 2024',
       'Entwicklung der Einwohnerzahl von 2012 bis 2023 in %',
       'Prognostizierte Entwicklung der Einwohnerzahl von 2025 bis 2040 in %',
       'Zukunftsindex_Kategorie', 'Regionalranking_Kategorie',
       'Zukunftsampel_Kategorie', '_merge'],
      dtype='object')

In [14]:
metropolen_poll_sparda_cleaned=metropolen_poll_sparda_cleaned.rename(columns={'Ø-Entfernung in km':"Durchschnittliche Entfernung zur Autobahn",
                                                                              'Ø-Entfernung in km.1':"Durchschnittliche Entfernung zum Zugverkehr",
                                                                              'Ø-Entfernung in km.2':"Durchschnittliche Entfernung zum Supermarkt",
                                                                              "Pender pro 1.000 Ew. ":"Pendler pro 1.000 Ew.",})
metropolen_poll_sparda_cleaned

,Metropole_x,Stadt/Landkreis,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,durchschn. Kaufpreis 1. HJ 2024,Angebote 1. HJ 2024,Preisentwicklung,Angebotsentwicklung,Durchschnittliche Entfernung zur Autobahn,indexiert im Bundesdurchschnitt (D = 100%),...,"Anteil der Pendler, die in eine Metropole pendeln, an allen Beschäftigten am Wohnort\nin %, 2024","Wanderungssaldo (Zuzüge minus Fortzüge)\nder 30- bis unter 50-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023","Wanderungssaldo (Zuzüge minus Fortzüge)\nder 18- bis unter 30-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023","Pendlersaldo (Einpendler minus Auspendler)\nje 100 Beschäftigte* am Arbeitsort, 2024",Entwicklung der Einwohnerzahl von 2012 bis 2023 in %,Prognostizierte Entwicklung der Einwohnerzahl von 2025 bis 2040 in %,Zukunftsindex_Kategorie,Regionalranking_Kategorie,Zukunftsampel_Kategorie,_merge
22,München,Bad Tölz-Wolfratshausen,5689,391.0,5331.0,414.0,0.067154,-0.055556,12.55,140.93,...,16.863591,16.502463,13.040143,-40.325353,7.560664,4.186359,4,1,2,both
26,Berlin,Barnim,3317,535.0,3415.0,720.0,-0.028697,-0.256944,6.81,76.46,...,41.134607,24.730787,13.890545,-46.466925,11.307039,0.462604,5,3,2,both
32,Berlin,Berlin,5527,13095.0,5480.0,17695.0,0.008577,-0.259960,4.47,50.17,...,2.972945,0.934790,76.750818,10.912447,8.507855,7.080914,1,2,1,both
39,Köln,Bonn,3860,948.0,3707.0,1205.0,0.041273,-0.213278,2.36,26.46,...,13.774530,-11.661232,28.616767,33.250440,3.811611,0.809867,1,2,1,both
46,Leipzig,Burgenlandkreis,1207,353.0,1219.0,575.0,-0.009844,-0.386087,13.39,150.41,...,1.501034,22.126430,26.051433,-17.991848,-5.838318,-11.882415,6,6,4,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,Berlin,Teltow-Fläming,3119,482.0,3180.0,683.0,-0.019182,-0.294290,15.15,170.20,...,30.731746,32.885318,24.565293,-12.320727,11.105545,1.483037,4,1,1,both
374,Stuttgart,Tübingen,3992,605.0,3833.0,746.0,0.041482,-0.189008,17.28,194.04,...,7.003337,-1.611521,36.590685,-1.065178,8.377619,2.399563,1,2,1,both
398,Frankfurt,Wetteraukreis,3178,864.0,3080.0,1259.0,0.031818,-0.313741,7.14,80.22,...,23.899081,14.748621,12.456803,-41.133697,5.703545,3.656916,3,3,2,both
399,Frankfurt,Wiesbaden,4476,1083.0,4119.0,1571.0,0.086672,-0.310630,3.03,34.04,...,13.907001,6.977044,49.271014,21.998167,5.356959,-1.198746,2,3,1,both
407,Düsseldorf,Wuppertal,2369,1063.0,2184.0,1368.0,0.084707,-0.222953,2.57,28.86,...,10.097188,1.413606,26.538276,-2.279762,4.580836,1.922726,2,6,4,both

In [15]:
metropolen_poll_sparda_cleaned.columns

Index(['Metropole_x', 'Stadt/Landkreis', 'durchschn. Kaufpreis 1. HJ 2025',
       'Angebote 1. HJ 2025', 'durchschn. Kaufpreis 1. HJ 2024',
       'Angebote 1. HJ 2024', 'Preisentwicklung', 'Angebotsentwicklung',
       'Durchschnittliche Entfernung zur Autobahn',
       'indexiert im Bundesdurchschnitt (D = 100%)',
       'Durchschnittliche Entfernung zum Zugverkehr',
       'indexiert im Bundesdurchschnitt (D = 100%).1',
       'Durchschnittliche Entfernung zum Supermarkt',
       'indexiert im Bundesdurchschnitt (D = 100%).2',
       'Einpendler aus Metropole', 'Einpendler pro 1.000 Ew.',
       'Auspendler nach Metropole', 'Auspendler pro 1.000 Ew.',
       'Pendersaldo zu Metropole', 'Pendler pro 1.000 Ew.', 'lfd. Nr.',
       'Kreis', 'Kreiskennziffer', 'Metropole_y', 'Landkreis', 'Mittelstadt',
       'Osten',
       'Preise je m² in € einer Eigentumswohnung in Städten und von Ein- und Zweifamilienhäusern in Landkreisen (jeweils Bestand),\n2025 (1. Quartal)',
       'Anzahl der m² für eine Investitionssumme\nvon 360.000 €, 2025 (1. Quartal)',
       'Kaufpreise für eine 117 m² große Immobilie im\nVerhältnis zum Jahreshaushaltseinkommen\n(netto), 2025 (1. Quartal)',
       'Preisentwicklung in % für Eigentumswohnungen in\nStädten und Ein- und Zweifamilienhäusern in Landkreisen (jeweils Bestand), 2012 bis 2025 (1. Quartal)',
       'Preisentwicklung in % für\nEigentumswohnungen in\nStädten und Ein- und Zweifamilienhäusern in Landkreisen (jeweils Bestand), 2024 bis 2025 (1. Quartal)',
       'Neubaubedarf von Wohnungen\nje 10.000 Einwohner pro Jahr, 2023 bis 2030',
       'Anteil der Pendler, die in eine Metropole pendeln, an allen Beschäftigten am Wohnort\nin %, 2024',
       'Wanderungssaldo (Zuzüge minus Fortzüge)\nder 30- bis unter 50-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023',
       'Wanderungssaldo (Zuzüge minus Fortzüge)\nder 18- bis unter 30-Jährigen\nje 1.000 Einwohner der Altersgruppe, 2023',
       'Pendlersaldo (Einpendler minus Auspendler)\nje 100 Beschäftigte* am Arbeitsort, 2024',
       'Entwicklung der Einwohnerzahl von 2012 bis 2023 in %',
       'Prognostizierte Entwicklung der Einwohnerzahl von 2025 bis 2040 in %',
       'Zukunftsindex_Kategorie', 'Regionalranking_Kategorie',
       'Zukunftsampel_Kategorie', '_merge'],
      dtype='object')

In [16]:
metropolen_poll_sparda_cleaned_red=metropolen_poll_sparda_cleaned[["Kreiskennziffer","Stadt/Landkreis",'Metropole_x','durchschn. Kaufpreis 1. HJ 2025',
       'Angebote 1. HJ 2025','Preisentwicklung','Angebotsentwicklung','Durchschnittliche Entfernung zur Autobahn',
       'Durchschnittliche Entfernung zum Zugverkehr',
       'Durchschnittliche Entfernung zum Supermarkt',"Pendler pro 1.000 Ew."]]
metropolen_poll_sparda_cleaned_red

,Kreiskennziffer,Stadt/Landkreis,Metropole_x,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,Preisentwicklung,Angebotsentwicklung,Durchschnittliche Entfernung zur Autobahn,Durchschnittliche Entfernung zum Zugverkehr,Durchschnittliche Entfernung zum Supermarkt,Pendler pro 1.000 Ew.
22,09173,Bad Tölz-Wolfratshausen,München,5689,391.0,0.067154,-0.055556,12.55,4.37,2.15,-51.84
26,12060,Barnim,Berlin,3317,535.0,-0.028697,-0.256944,6.81,2.96,2.58,-121.65
32,11000,Berlin,Berlin,5527,13095.0,0.008577,-0.259960,4.47,1.84,0.59,NaN
39,05314,Bonn,Köln,3860,948.0,0.041273,-0.213278,2.36,2.40,0.72,2.25
46,15084,Burgenlandkreis,Leipzig,1207,353.0,-0.009844,-0.386087,13.39,3.87,3.45,-10.56
...,...,...,...,...,...,...,...,...,...,...,...
368,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69
374,08416,Tübingen,Stuttgart,3992,605.0,0.041482,-0.189008,17.28,2.46,1.91,-15.87
398,06440,Wetteraukreis,Frankfurt,3178,864.0,0.031818,-0.313741,7.14,2.98,1.99,-75.09
399,06414,Wiesbaden,Frankfurt,4476,1083.0,0.086672,-0.310630,3.03,2.51,0.94,-30.49
407,05124,Wuppertal,Düsseldorf,2369,1063.0,0.084707,-0.222953,2.57,2.32,0.96,-15.63

In [17]:
pendel_data_stadt=pd.read_csv("../data/postbank_pendel.csv")
pendel_data_stadt

                 Kreis     city  sqm    PKW   ÖPNV
0    Ahrensburg, Stadt  Hamburg   70  138.0  364.0
1    Ahrensburg, Stadt  Hamburg  120  970.0  625.0
2               Alfter     Köln   70   72.0   96.0
3               Alfter     Köln  120  267.0  164.0
4      Altomünster, M.  München   70   71.0  100.0
..                 ...      ...  ...    ...    ...
425           Wülfrath     Köln  120  217.0  132.0
426            Zeuthen   Berlin   70   46.0   83.0
427            Zeuthen   Berlin  120    NaN  142.0
428             Zossen   Berlin   70   85.0  159.0
429             Zossen   Berlin  120    NaN  273.0

[430 rows x 5 columns]

In [18]:
pendel_data_stadt["Stadt"]=pendel_data_stadt["Kreis"].str.split(",").str[0]
pendel_data_stadt.sort_values(by="Stadt", inplace=True)
pendel_data_stadt

                 Kreis     city  sqm    PKW   ÖPNV        Stadt
0    Ahrensburg, Stadt  Hamburg   70  138.0  364.0   Ahrensburg
1    Ahrensburg, Stadt  Hamburg  120  970.0  625.0   Ahrensburg
2               Alfter     Köln   70   72.0   96.0       Alfter
3               Alfter     Köln  120  267.0  164.0       Alfter
4      Altomünster, M.  München   70   71.0  100.0  Altomünster
..                 ...      ...  ...    ...    ...          ...
425           Wülfrath     Köln  120  217.0  132.0     Wülfrath
426            Zeuthen   Berlin   70   46.0   83.0      Zeuthen
427            Zeuthen   Berlin  120    NaN  142.0      Zeuthen
428             Zossen   Berlin   70   85.0  159.0       Zossen
429             Zossen   Berlin  120    NaN  273.0       Zossen

[430 rows x 6 columns]

In [19]:
ags_schluessel=pd.read_excel("../data/AuszugGV2QAktuell.xlsx",sheet_name="Onlineprodukt_Gemeinden30062025",skiprows=3)
ags_schluessel

,Unnamed: 0,Unnamed: 1,Land,RB,Kreis,VB,Gem,Unnamed: 7,Unnamed: 8,insgesamt,männlich,weiblich,je km2,Unnamed: 13,Längengrad,Breitengrad,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,Gebietsstand am 30.06.2025 (2. Quartal),NaN,NaN,NaN,NaN,NaN,31.12.2023 (Jahr),am 31.12.2023 (Jahr),NaN,NaN,NaN,NaN,Zuordnungsstand am 31.12.2024,NaN,Schlüssel,Bezeichnung,Schlüssel,Bezeichnung
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10,NaN,01,NaN,NaN,NaN,NaN,Schleswig-Holstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,40,41.0,01,0.0,1.0,NaN,NaN,"Flensburg, Stadt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,50,50.0,01,0.0,1.0,0.0,NaN,"Flensburg, Stadt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16008,3) Die Gemeinde kann mehrere Postleitzahlen (P...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16010,© Daten (im Auftrag der Herausgebergemeinschaf...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16011,"Statistisches Bundesamt (Destatis), 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16012,"Vervielfältigung und Verbreitung, auch au...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
gemeinde_schluessel=ags_schluessel.dropna(subset=["Land","RB","Kreis","Gem"])
gemeinde_schluessel

,Unnamed: 0,Unnamed: 1,Land,RB,Kreis,VB,Gem,Unnamed: 7,Unnamed: 8,insgesamt,männlich,weiblich,je km2,Unnamed: 13,Längengrad,Breitengrad,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
5,60,61.0,01,0.0,1.0,0.0,0.0,"Flensburg, Stadt",56.73,96431,47553.0,48878.0,1700.0,24937.0,"9,43751","54,78252",F02,Ostsee,01,dicht besiedelt
8,60,61.0,01,0.0,2.0,0.0,0.0,"Kiel, Landeshauptstadt",118.65,251751,123080.0,128671.0,2122.0,24103.0,"10,13727","54,321775",F02,Ostsee,01,dicht besiedelt
11,60,61.0,01,0.0,3.0,0.0,0.0,"Lübeck, Hansestadt",214.19,217061,104263.0,112798.0,1013.0,23539.0,"10,683932","53,866269",F02,Ostsee,01,dicht besiedelt
14,60,61.0,01,0.0,4.0,0.0,0.0,"Neumünster, Stadt",71.66,79461,39444.0,40017.0,1109.0,24534.0,"9,988422","54,069895",F04,übrig. Schleswig-Holstein,01,dicht besiedelt
17,60,63.0,01,0.0,51.0,11.0,11.0,"Brunsbüttel, Stadt",65.21,12736,6451.0,6285.0,195.0,25541.0,"9,13735","53,896932",F01,Nordsee,02,mittlere Besiedlungsdichte
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,60,64.0,16,0.0,77.0,5051.0,11.0,Göpfersdorf,5.92,213,110.0,103.0,36.0,4618.0,"12,595897","50,912971",E30,Altenburger Land,03,gering besiedelt
15996,60,64.0,16,0.0,77.0,5051.0,23.0,Langenleuba-Niederhain,39.43,1709,871.0,838.0,43.0,4618.0,"12,589232","50,960103",E30,Altenburger Land,03,gering besiedelt
15997,60,64.0,16,0.0,77.0,5051.0,36.0,Nobitz,100.38,7012,3521.0,3491.0,70.0,4603.0,"12,48572","50,977188",E30,Altenburger Land,03,gering besiedelt
15999,60,64.0,16,0.0,77.0,5052.0,3.0,Dobitschen,6.55,407,204.0,203.0,62.0,4626.0,"12,280353","50,956532",E30,Altenburger Land,03,gering besiedelt
16000,60,63.0,16,0.0,77.0,5052.0,43.0,"Schmölln, Stadt",94.53,13621,6673.0,6948.0,144.0,4626.0,"12,354035","50,895281",E30,Altenburger Land,02,mittlere Besiedlungsdichte

In [21]:
gemeinde_schluessel["Land"]=gemeinde_schluessel["Land"].str.zfill(2)
gemeinde_schluessel["RB"]=gemeinde_schluessel["RB"].astype(int).astype(str)
gemeinde_schluessel["Kreis"]=gemeinde_schluessel["Kreis"].astype(int).astype(str).str.zfill(2)
gemeinde_schluessel["Gem"]=gemeinde_schluessel["Gem"].astype(int).astype(str).str.zfill(3)

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_64243/561474443.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gemeinde_schluessel["Land"]=gemeinde_schluessel["Land"].str.zfill(2)
/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_64243/561474443.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gemeinde_schluessel["RB"]=gemeinde_schluessel["RB"].astype(int).astype(str)
/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_64243/561474443.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gemeinde_schluessel["Kreis"]=gemeinde_schluessel["Kreis"].astype(int).astype(str).str.zfill(2)
/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_64243/561474443.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gemeinde_schluessel["Gem"]=gemeinde_schluessel["Gem"].astype(int).astype(str).str.zfill(3)

In [22]:
gemeinde_schluessel["AGS"]=gemeinde_schluessel["Land"]+gemeinde_schluessel["RB"]+gemeinde_schluessel["Kreis"]+gemeinde_schluessel["Gem"]
gemeinde_schluessel

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_64243/2140332285.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gemeinde_schluessel["AGS"]=gemeinde_schluessel["Land"]+gemeinde_schluessel["RB"]+gemeinde_schluessel["Kreis"]+gemeinde_schluessel["Gem"]

,Unnamed: 0,Unnamed: 1,Land,RB,Kreis,VB,Gem,Unnamed: 7,Unnamed: 8,insgesamt,...,weiblich,je km2,Unnamed: 13,Längengrad,Breitengrad,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,AGS
5,60,61.0,01,0,01,0.0,000,"Flensburg, Stadt",56.73,96431,...,48878.0,1700.0,24937.0,"9,43751","54,78252",F02,Ostsee,01,dicht besiedelt,01001000
8,60,61.0,01,0,02,0.0,000,"Kiel, Landeshauptstadt",118.65,251751,...,128671.0,2122.0,24103.0,"10,13727","54,321775",F02,Ostsee,01,dicht besiedelt,01002000
11,60,61.0,01,0,03,0.0,000,"Lübeck, Hansestadt",214.19,217061,...,112798.0,1013.0,23539.0,"10,683932","53,866269",F02,Ostsee,01,dicht besiedelt,01003000
14,60,61.0,01,0,04,0.0,000,"Neumünster, Stadt",71.66,79461,...,40017.0,1109.0,24534.0,"9,988422","54,069895",F04,übrig. Schleswig-Holstein,01,dicht besiedelt,01004000
17,60,63.0,01,0,51,11.0,011,"Brunsbüttel, Stadt",65.21,12736,...,6285.0,195.0,25541.0,"9,13735","53,896932",F01,Nordsee,02,mittlere Besiedlungsdichte,01051011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,60,64.0,16,0,77,5051.0,011,Göpfersdorf,5.92,213,...,103.0,36.0,4618.0,"12,595897","50,912971",E30,Altenburger Land,03,gering besiedelt,16077011
15996,60,64.0,16,0,77,5051.0,023,Langenleuba-Niederhain,39.43,1709,...,838.0,43.0,4618.0,"12,589232","50,960103",E30,Altenburger Land,03,gering besiedelt,16077023
15997,60,64.0,16,0,77,5051.0,036,Nobitz,100.38,7012,...,3491.0,70.0,4603.0,"12,48572","50,977188",E30,Altenburger Land,03,gering besiedelt,16077036
15999,60,64.0,16,0,77,5052.0,003,Dobitschen,6.55,407,...,203.0,62.0,4626.0,"12,280353","50,956532",E30,Altenburger Land,03,gering besiedelt,16077003
16000,60,63.0,16,0,77,5052.0,043,"Schmölln, Stadt",94.53,13621,...,6948.0,144.0,4626.0,"12,354035","50,895281",E30,Altenburger Land,02,mittlere Besiedlungsdichte,16077043

In [23]:
kreis_schluessel=ags_schluessel[(ags_schluessel["Gem"].isna()) ]
kreis_schluessel=kreis_schluessel.dropna(subset=["Land","RB","Kreis"])
kreis_schluessel

,Unnamed: 0,Unnamed: 1,Land,RB,Kreis,VB,Gem,Unnamed: 7,Unnamed: 8,insgesamt,männlich,weiblich,je km2,Unnamed: 13,Längengrad,Breitengrad,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
3,40,41.0,01,0.0,1.0,NaN,NaN,"Flensburg, Stadt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,50,50.0,01,0.0,1.0,0.0,NaN,"Flensburg, Stadt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,40,41.0,01,0.0,2.0,NaN,NaN,"Kiel, Landeshauptstadt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,50,50.0,01,0.0,2.0,0.0,NaN,"Kiel, Landeshauptstadt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,40,41.0,01,0.0,3.0,NaN,NaN,"Lübeck, Hansestadt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15974,50,54.0,16,0.0,77.0,5005.0,NaN,Rositz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15983,50,54.0,16,0.0,77.0,5009.0,NaN,Oberes Sprottental,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15990,50,58.0,16,0.0,77.0,5050.0,NaN,"Gößnitz, Stadt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15994,50,58.0,16,0.0,77.0,5051.0,NaN,Nobitz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15998,50,58.0,16,0.0,77.0,5052.0,NaN,"Schmölln, Stadt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
kreis_schluessel["Land"]=kreis_schluessel["Land"].str.zfill(2)
kreis_schluessel["RB"]=kreis_schluessel["RB"].astype(int).astype(str)
kreis_schluessel["Kreis"]=kreis_schluessel["Kreis"].astype(int).astype(str).str.zfill(2)

In [25]:
kreis_schluessel["AGS"]=kreis_schluessel["Land"]+kreis_schluessel["RB"]+kreis_schluessel["Kreis"]
kreis_schluessel

,Unnamed: 0,Unnamed: 1,Land,RB,Kreis,VB,Gem,Unnamed: 7,Unnamed: 8,insgesamt,...,weiblich,je km2,Unnamed: 13,Längengrad,Breitengrad,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,AGS
3,40,41.0,01,0,01,NaN,NaN,"Flensburg, Stadt",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01001
4,50,50.0,01,0,01,0.0,NaN,"Flensburg, Stadt",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01001
6,40,41.0,01,0,02,NaN,NaN,"Kiel, Landeshauptstadt",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01002
7,50,50.0,01,0,02,0.0,NaN,"Kiel, Landeshauptstadt",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01002
9,40,41.0,01,0,03,NaN,NaN,"Lübeck, Hansestadt",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15974,50,54.0,16,0,77,5005.0,NaN,Rositz,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16077
15983,50,54.0,16,0,77,5009.0,NaN,Oberes Sprottental,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16077
15990,50,58.0,16,0,77,5050.0,NaN,"Gößnitz, Stadt",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16077
15994,50,58.0,16,0,77,5051.0,NaN,Nobitz,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16077
15998,50,58.0,16,0,77,5052.0,NaN,"Schmölln, Stadt",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16077

In [26]:
gemeinde_schluessel["Stadt"]=gemeinde_schluessel["Unnamed: 7"].str.split(",").str[0]
gemeinde_schluessel

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_64243/2560136208.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gemeinde_schluessel["Stadt"]=gemeinde_schluessel["Unnamed: 7"].str.split(",").str[0]

,Unnamed: 0,Unnamed: 1,Land,RB,Kreis,VB,Gem,Unnamed: 7,Unnamed: 8,insgesamt,...,je km2,Unnamed: 13,Längengrad,Breitengrad,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,AGS,Stadt
5,60,61.0,01,0,01,0.0,000,"Flensburg, Stadt",56.73,96431,...,1700.0,24937.0,"9,43751","54,78252",F02,Ostsee,01,dicht besiedelt,01001000,Flensburg
8,60,61.0,01,0,02,0.0,000,"Kiel, Landeshauptstadt",118.65,251751,...,2122.0,24103.0,"10,13727","54,321775",F02,Ostsee,01,dicht besiedelt,01002000,Kiel
11,60,61.0,01,0,03,0.0,000,"Lübeck, Hansestadt",214.19,217061,...,1013.0,23539.0,"10,683932","53,866269",F02,Ostsee,01,dicht besiedelt,01003000,Lübeck
14,60,61.0,01,0,04,0.0,000,"Neumünster, Stadt",71.66,79461,...,1109.0,24534.0,"9,988422","54,069895",F04,übrig. Schleswig-Holstein,01,dicht besiedelt,01004000,Neumünster
17,60,63.0,01,0,51,11.0,011,"Brunsbüttel, Stadt",65.21,12736,...,195.0,25541.0,"9,13735","53,896932",F01,Nordsee,02,mittlere Besiedlungsdichte,01051011,Brunsbüttel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15995,60,64.0,16,0,77,5051.0,011,Göpfersdorf,5.92,213,...,36.0,4618.0,"12,595897","50,912971",E30,Altenburger Land,03,gering besiedelt,16077011,Göpfersdorf
15996,60,64.0,16,0,77,5051.0,023,Langenleuba-Niederhain,39.43,1709,...,43.0,4618.0,"12,589232","50,960103",E30,Altenburger Land,03,gering besiedelt,16077023,Langenleuba-Niederhain
15997,60,64.0,16,0,77,5051.0,036,Nobitz,100.38,7012,...,70.0,4603.0,"12,48572","50,977188",E30,Altenburger Land,03,gering besiedelt,16077036,Nobitz
15999,60,64.0,16,0,77,5052.0,003,Dobitschen,6.55,407,...,62.0,4626.0,"12,280353","50,956532",E30,Altenburger Land,03,gering besiedelt,16077003,Dobitschen
16000,60,63.0,16,0,77,5052.0,043,"Schmölln, Stadt",94.53,13621,...,144.0,4626.0,"12,354035","50,895281",E30,Altenburger Land,02,mittlere Besiedlungsdichte,16077043,Schmölln

In [27]:
gemeinde_schluessel_red=gemeinde_schluessel[["AGS","Stadt"]]
gemeinde_schluessel_red

            AGS                   Stadt
5      01001000               Flensburg
8      01002000                    Kiel
11     01003000                  Lübeck
14     01004000              Neumünster
17     01051011             Brunsbüttel
...         ...                     ...
15995  16077011             Göpfersdorf
15996  16077023  Langenleuba-Niederhain
15997  16077036                  Nobitz
15999  16077003              Dobitschen
16000  16077043                Schmölln

[10952 rows x 2 columns]

In [28]:
merge_gemeinde_pendel=pd.merge(gemeinde_schluessel_red, pendel_data_stadt, how='outer', left_on='Stadt', right_on='Stadt',indicator=True)
merge_gemeinde_pendel

            AGS                Stadt Kreis city  sqm  PKW  ÖPNV     _merge
0      07235001                 Aach   NaN  NaN  NaN  NaN   NaN  left_only
1      08335001                 Aach   NaN  NaN  NaN  NaN   NaN  left_only
2      05334002               Aachen   NaN  NaN  NaN  NaN   NaN  left_only
3      08136088                Aalen   NaN  NaN  NaN  NaN   NaN  left_only
4      06439001            Aarbergen   NaN  NaN  NaN  NaN   NaN  left_only
...         ...                  ...   ...  ...  ...  ...   ...        ...
11197  07233075            Üdersdorf   NaN  NaN  NaN  NaN   NaN  left_only
11198  08337128  Ühlingen-Birkendorf   NaN  NaN  NaN  NaN   NaN  left_only
11199  07231125                Ürzig   NaN  NaN  NaN  NaN   NaN  left_only
11200  07232333              Üttfeld   NaN  NaN  NaN  NaN   NaN  left_only
11201  07233076               Üxheim   NaN  NaN  NaN  NaN   NaN  left_only

[11202 rows x 8 columns]

In [29]:
merge_gemeinde_pendel=merge_gemeinde_pendel[merge_gemeinde_pendel["_merge"]=="both"]
merge_gemeinde_pendel.sort_values(by="AGS", inplace=True)
merge_gemeinde_pendel

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_64243/4042138446.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge_gemeinde_pendel.sort_values(by="AGS", inplace=True)

,AGS,Stadt,Kreis,city,sqm,PKW,ÖPNV,_merge
7917,01051089,Quickborn,"Quickborn, Stadt",Hamburg,120.0,537.0,331.0,both
7916,01051089,Quickborn,"Quickborn, Stadt",Hamburg,70.0,145.0,193.0,both
3031,01053032,Geesthacht,"Geesthacht, Stadt",Hamburg,120.0,755.0,468.0,both
3030,01053032,Geesthacht,"Geesthacht, Stadt",Hamburg,70.0,180.0,273.0,both
6547,01053090,Mölln,"Mölln, Stadt",Hamburg,120.0,511.0,312.0,both
...,...,...,...,...,...,...,...,...
5944,12072240,Ludwigsfelde,Ludwigsfelde,Berlin,70.0,116.0,344.0,both
11150,12072477,Zossen,Zossen,Berlin,70.0,85.0,159.0,both
11151,12072477,Zossen,Zossen,Berlin,120.0,NaN,273.0,both
6549,13071102,Mölln,"Mölln, Stadt",Hamburg,120.0,511.0,312.0,both
6548,13071102,Mölln,"Mölln, Stadt",Hamburg,70.0,114.0,182.0,both

In [30]:
merge_gemeinde_pendel["Kreisziffer"]=merge_gemeinde_pendel["AGS"].str[0:5]

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_64243/2012995022.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge_gemeinde_pendel["Kreisziffer"]=merge_gemeinde_pendel["AGS"].str[0:5]

In [32]:
to_drop_list=["09372","01051","13071","07332","09377","03357","09274","08226","07331","07337","09185"]

In [33]:
merge_gemeinde_pendel_clean=merge_gemeinde_pendel[~merge_gemeinde_pendel["Kreisziffer"].isin(to_drop_list)]
merge_gemeinde_pendel_clean

,AGS,Stadt,Kreis,city,sqm,PKW,ÖPNV,_merge,Kreisziffer
3031,01053032,Geesthacht,"Geesthacht, Stadt",Hamburg,120.0,755.0,468.0,both,01053
3030,01053032,Geesthacht,"Geesthacht, Stadt",Hamburg,70.0,180.0,273.0,both,01053
6547,01053090,Mölln,"Mölln, Stadt",Hamburg,120.0,511.0,312.0,both,01053
6546,01053090,Mölln,"Mölln, Stadt",Hamburg,70.0,114.0,182.0,both,01053
8014,01053100,Ratzeburg,"Ratzeburg, Stadt",Hamburg,70.0,99.0,163.0,both,01053
...,...,...,...,...,...,...,...,...,...
5937,12072232,Luckenwalde,Luckenwalde,Berlin,120.0,NaN,342.0,both,12072
5945,12072240,Ludwigsfelde,Ludwigsfelde,Berlin,120.0,NaN,590.0,both,12072
5944,12072240,Ludwigsfelde,Ludwigsfelde,Berlin,70.0,116.0,344.0,both,12072
11150,12072477,Zossen,Zossen,Berlin,70.0,85.0,159.0,both,12072
11151,12072477,Zossen,Zossen,Berlin,120.0,NaN,273.0,both,12072

In [34]:
merge_gemeinde_pendel_red=merge_gemeinde_pendel_clean[["Kreisziffer","Stadt","city","sqm","PKW","ÖPNV"]]
merge_gemeinde_pendel_red

      Kreisziffer         Stadt     city    sqm    PKW   ÖPNV
3031        01053    Geesthacht  Hamburg  120.0  755.0  468.0
3030        01053    Geesthacht  Hamburg   70.0  180.0  273.0
6547        01053         Mölln  Hamburg  120.0  511.0  312.0
6546        01053         Mölln  Hamburg   70.0  114.0  182.0
8014        01053     Ratzeburg  Hamburg   70.0   99.0  163.0
...           ...           ...      ...    ...    ...    ...
5937        12072   Luckenwalde   Berlin  120.0    NaN  342.0
5945        12072  Ludwigsfelde   Berlin  120.0    NaN  590.0
5944        12072  Ludwigsfelde   Berlin   70.0  116.0  344.0
11150       12072        Zossen   Berlin   70.0   85.0  159.0
11151       12072        Zossen   Berlin  120.0    NaN  273.0

[414 rows x 6 columns]

In [35]:
merge_gemeinde_pendel_red_by_kreis=merge_gemeinde_pendel_red.groupby(["Kreisziffer","Stadt","city","sqm"]).mean().reset_index()
merge_gemeinde_pendel_red_by_kreis

    Kreisziffer         Stadt     city    sqm    PKW   ÖPNV
0         01053    Geesthacht  Hamburg   70.0  180.0  273.0
1         01053    Geesthacht  Hamburg  120.0  755.0  468.0
2         01053         Mölln  Hamburg   70.0  114.0  182.0
3         01053         Mölln  Hamburg  120.0  511.0  312.0
4         01053     Ratzeburg  Hamburg   70.0   99.0  163.0
..          ...           ...      ...    ...    ...    ...
409       12072   Luckenwalde   Berlin  120.0    NaN  342.0
410       12072  Ludwigsfelde   Berlin   70.0  116.0  344.0
411       12072  Ludwigsfelde   Berlin  120.0    NaN  590.0
412       12072        Zossen   Berlin   70.0   85.0  159.0
413       12072        Zossen   Berlin  120.0    NaN  273.0

[414 rows x 6 columns]

In [36]:
metropolen_poll_sparda_cleaned_red

,Kreiskennziffer,Stadt/Landkreis,Metropole_x,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,Preisentwicklung,Angebotsentwicklung,Durchschnittliche Entfernung zur Autobahn,Durchschnittliche Entfernung zum Zugverkehr,Durchschnittliche Entfernung zum Supermarkt,Pendler pro 1.000 Ew.
22,09173,Bad Tölz-Wolfratshausen,München,5689,391.0,0.067154,-0.055556,12.55,4.37,2.15,-51.84
26,12060,Barnim,Berlin,3317,535.0,-0.028697,-0.256944,6.81,2.96,2.58,-121.65
32,11000,Berlin,Berlin,5527,13095.0,0.008577,-0.259960,4.47,1.84,0.59,NaN
39,05314,Bonn,Köln,3860,948.0,0.041273,-0.213278,2.36,2.40,0.72,2.25
46,15084,Burgenlandkreis,Leipzig,1207,353.0,-0.009844,-0.386087,13.39,3.87,3.45,-10.56
...,...,...,...,...,...,...,...,...,...,...,...
368,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69
374,08416,Tübingen,Stuttgart,3992,605.0,0.041482,-0.189008,17.28,2.46,1.91,-15.87
398,06440,Wetteraukreis,Frankfurt,3178,864.0,0.031818,-0.313741,7.14,2.98,1.99,-75.09
399,06414,Wiesbaden,Frankfurt,4476,1083.0,0.086672,-0.310630,3.03,2.51,0.94,-30.49
407,05124,Wuppertal,Düsseldorf,2369,1063.0,0.084707,-0.222953,2.57,2.32,0.96,-15.63

In [37]:
metropolen_poll_sparda_pendel=pd.merge(metropolen_poll_sparda_cleaned_red,merge_gemeinde_pendel_red_by_kreis,left_on="Kreiskennziffer", right_on="Kreisziffer", how="outer", indicator=True)
metropolen_poll_sparda_pendel

,Kreiskennziffer,Stadt/Landkreis,Metropole_x,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,Preisentwicklung,Angebotsentwicklung,Durchschnittliche Entfernung zur Autobahn,Durchschnittliche Entfernung zum Zugverkehr,Durchschnittliche Entfernung zum Supermarkt,Pendler pro 1.000 Ew.,Kreisziffer,Stadt,city,sqm,PKW,ÖPNV,_merge
0,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Geesthacht,Hamburg,70.0,180.0,273.0,both
1,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Geesthacht,Hamburg,120.0,755.0,468.0,both
2,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Mölln,Hamburg,70.0,114.0,182.0,both
3,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Mölln,Hamburg,120.0,511.0,312.0,both
4,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Ratzeburg,Hamburg,70.0,99.0,163.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,14729,Leipzig,Leipzig,2026,801.0,-0.034778,-0.299213,7.84,3.06,3.16,-71.24,NaN,NaN,NaN,NaN,NaN,NaN,left_only
558,14730,Nordsachsen,Leipzig,1687,459.0,-0.002955,-0.273734,19.63,4.80,2.84,-26.74,NaN,NaN,NaN,NaN,NaN,NaN,left_only
559,15002,Halle/Saale,Leipzig,2344,339.0,0.001282,-0.306748,7.50,1.88,0.81,-3.72,NaN,NaN,NaN,NaN,NaN,NaN,left_only
560,15084,Burgenlandkreis,Leipzig,1207,353.0,-0.009844,-0.386087,13.39,3.87,3.45,-10.56,NaN,NaN,NaN,NaN,NaN,NaN,left_only
561,15088,Saalekreis,Leipzig,1536,495.0,0.027425,-0.293866,6.29,3.22,3.88,-12.98,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [39]:
metropolen_poll_sparda_pendel[metropolen_poll_sparda_pendel["_merge"]=="both"]

,Kreiskennziffer,Stadt/Landkreis,Metropole_x,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,Preisentwicklung,Angebotsentwicklung,Durchschnittliche Entfernung zur Autobahn,Durchschnittliche Entfernung zum Zugverkehr,Durchschnittliche Entfernung zum Supermarkt,Pendler pro 1.000 Ew.,Kreisziffer,Stadt,city,sqm,PKW,ÖPNV,_merge
0,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Geesthacht,Hamburg,70.0,180.0,273.0,both
1,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Geesthacht,Hamburg,120.0,755.0,468.0,both
2,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Mölln,Hamburg,70.0,114.0,182.0,both
3,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Mölln,Hamburg,120.0,511.0,312.0,both
4,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Ratzeburg,Hamburg,70.0,99.0,163.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Luckenwalde,Berlin,120.0,NaN,342.0,both
550,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Ludwigsfelde,Berlin,70.0,116.0,344.0,both
551,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Ludwigsfelde,Berlin,120.0,NaN,590.0,both
552,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Zossen,Berlin,70.0,85.0,159.0,both
553,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Zossen,Berlin,120.0,NaN,273.0,both

In [41]:
metropolen_poll_sparda_pendel_70=metropolen_poll_sparda_pendel[metropolen_poll_sparda_pendel["sqm"]==70]
metropolen_poll_sparda_pendel_70

,Kreiskennziffer,Stadt/Landkreis,Metropole_x,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,Preisentwicklung,Angebotsentwicklung,Durchschnittliche Entfernung zur Autobahn,Durchschnittliche Entfernung zum Zugverkehr,Durchschnittliche Entfernung zum Supermarkt,Pendler pro 1.000 Ew.,Kreisziffer,Stadt,city,sqm,PKW,ÖPNV,_merge
0,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Geesthacht,Hamburg,70.0,180.0,273.0,both
2,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Mölln,Hamburg,70.0,114.0,182.0,both
4,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Ratzeburg,Hamburg,70.0,99.0,163.0,both
6,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Schwarzenbek,Hamburg,70.0,146.0,457.0,both
8,01056,Kreis Pinneberg,Hamburg,3558,1439.0,0.018317,-0.163372,5.37,2.60,1.95,-121.93,01056,Elmshorn,Hamburg,70.0,106.0,311.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,12069,Potsdam-Mittelmark,Berlin,3880,679.0,0.026727,-0.337561,6.50,4.42,4.30,-61.01,12069,Werder (Havel),Berlin,70.0,47.0,130.0,both
546,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Blankenfelde-Mahlow,Berlin,70.0,129.0,239.0,both
548,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Luckenwalde,Berlin,70.0,69.0,200.0,both
550,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Ludwigsfelde,Berlin,70.0,116.0,344.0,both
552,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Zossen,Berlin,70.0,85.0,159.0,both

In [42]:
metropolen_poll_sparda_pendel_70=metropolen_poll_sparda_pendel_70.rename(columns={"PKW":"PKW_70qm","ÖPNV":"ÖPNV_70qm"})
metropolen_poll_sparda_pendel_70

,Kreiskennziffer,Stadt/Landkreis,Metropole_x,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,Preisentwicklung,Angebotsentwicklung,Durchschnittliche Entfernung zur Autobahn,Durchschnittliche Entfernung zum Zugverkehr,Durchschnittliche Entfernung zum Supermarkt,Pendler pro 1.000 Ew.,Kreisziffer,Stadt,city,sqm,PKW_70qm,ÖPNV_70qm,_merge
0,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Geesthacht,Hamburg,70.0,180.0,273.0,both
2,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Mölln,Hamburg,70.0,114.0,182.0,both
4,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Ratzeburg,Hamburg,70.0,99.0,163.0,both
6,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,01053,Schwarzenbek,Hamburg,70.0,146.0,457.0,both
8,01056,Kreis Pinneberg,Hamburg,3558,1439.0,0.018317,-0.163372,5.37,2.60,1.95,-121.93,01056,Elmshorn,Hamburg,70.0,106.0,311.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,12069,Potsdam-Mittelmark,Berlin,3880,679.0,0.026727,-0.337561,6.50,4.42,4.30,-61.01,12069,Werder (Havel),Berlin,70.0,47.0,130.0,both
546,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Blankenfelde-Mahlow,Berlin,70.0,129.0,239.0,both
548,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Luckenwalde,Berlin,70.0,69.0,200.0,both
550,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Ludwigsfelde,Berlin,70.0,116.0,344.0,both
552,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,12072,Zossen,Berlin,70.0,85.0,159.0,both

In [44]:
metropolen_poll_sparda_pendel_70_red=metropolen_poll_sparda_pendel_70.drop(columns=["Kreisziffer","Stadt","city","sqm","_merge"])
metropolen_poll_sparda_pendel_70_red

,Kreiskennziffer,Stadt/Landkreis,Metropole_x,durchschn. Kaufpreis 1. HJ 2025,Angebote 1. HJ 2025,Preisentwicklung,Angebotsentwicklung,Durchschnittliche Entfernung zur Autobahn,Durchschnittliche Entfernung zum Zugverkehr,Durchschnittliche Entfernung zum Supermarkt,Pendler pro 1.000 Ew.,PKW_70qm,ÖPNV_70qm
0,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,180.0,273.0
2,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,114.0,182.0
4,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,99.0,163.0
6,01053,Kreis Herzogtum Lauenburg,Hamburg,3111,646.0,0.008428,-0.311301,8.88,6.75,3.34,-95.34,146.0,457.0
8,01056,Kreis Pinneberg,Hamburg,3558,1439.0,0.018317,-0.163372,5.37,2.60,1.95,-121.93,106.0,311.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,12069,Potsdam-Mittelmark,Berlin,3880,679.0,0.026727,-0.337561,6.50,4.42,4.30,-61.01,47.0,130.0
546,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,129.0,239.0
548,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,69.0,200.0
550,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,116.0,344.0
552,12072,Teltow-Fläming,Berlin,3119,482.0,-0.019182,-0.294290,15.15,3.35,2.89,-62.69,85.0,159.0

In [47]:
metropolen_poll_sparda_pendel_70_red_mean=metropolen_poll_sparda_pendel_70_red.groupby(["Kreiskennziffer","Stadt/Landkreis","Metropole_x"]).mean().reset_index()
metropolen_poll_sparda_pendel_70_red_mean.to_csv("Kreis_merged_data_vorlaeufig.csv", index=False)