In [1]:
import pandas as pd
import glob
import json

In [2]:
for file in glob.glob("robotics.json"):
    print(file)
    with open(file) as f:
        data = json.load(f)
        #print(data[0])
        article_df={
            "title": [],
            "pubmed_id": [],
            "firstname": [],
            "lastname": [],
            "country": [],
            "date":[]
        }
        
        for article in data:
            title=article["title"]
            date=article["publication_date"]
            pubmed_id=article["pubmed_id"]
            authors=article["authors"]
            for author in authors:
                authors_array=[]
                if"affiliation" in author:
                    if (author["affiliation"]!=None):
                        country=author["affiliation"].split(",")[-1].strip().split(".")[0]
                else:
                    country=None
                lastname=author["lastname"]
                firstname=author["firstname"]
                article_df["title"].append(title)
                article_df["pubmed_id"].append(pubmed_id)
        
                article_df["firstname"].append(firstname)
                article_df["lastname"].append(lastname)
                article_df["country"].append(country)
                article_df["date"].append(date)

        
        
        authors_df=pd.DataFrame(article_df)
        authors_df.to_csv(file[:-5]+".csv")

robotics.json

In [4]:
df=pd.DataFrame()

for file in glob.glob("robotics.csv"):
    print(file)
    data=pd.read_csv(file)
    data["searchterm"]=file[:-4]
    df=pd.concat([df,data])

robotics.csv

In [5]:
df

,Unnamed: 0,title,pubmed_id,firstname,lastname,country,date,searchterm
0,0,Application of continuous intraoperative neuro...,39695478\n34973664\n33394989\n29302755\n281498...,Chengxia,Wang,China,19/12/2024,robotics
1,1,Application of continuous intraoperative neuro...,39695478\n34973664\n33394989\n29302755\n281498...,Zhuofu,Li,China,19/12/2024,robotics
2,2,Application of continuous intraoperative neuro...,39695478\n34973664\n33394989\n29302755\n281498...,Woquan,Zhong,China,19/12/2024,robotics
3,3,Application of continuous intraoperative neuro...,39695478\n34973664\n33394989\n29302755\n281498...,Shuai,Jiang,China,19/12/2024,robotics
4,4,Application of continuous intraoperative neuro...,39695478\n34973664\n33394989\n29302755\n281498...,Weishi,Li,China,19/12/2024,robotics
...,...,...,...,...,...,...,...,...
69878,69878,Robotic Flexible Ureteroscopy: A Step-by-Step ...,38508534,Mehmet,Gurcan,Turkey,21/03/2024,robotics
69879,69879,Robotic Flexible Ureteroscopy: A Step-by-Step ...,38508534,Ahmet Baris,Aydin,Turkey,21/03/2024,robotics
69880,69880,Robotic Flexible Ureteroscopy: A Step-by-Step ...,38508534,İsmet,Nane,Turkey,21/03/2024,robotics
69881,69881,Robotic Flexible Ureteroscopy: A Step-by-Step ...,38508534,Faruk,Özcan,Turkey,21/03/2024,robotics
69882,69882,Robotic Flexible Ureteroscopy: A Step-by-Step ...,38508534,Tzevat,Tefik,Turkey,21/03/2024,robotics

In [6]:
counter_df=df[["firstname","lastname","title","country"]].groupby(["firstname","lastname"]).count().reset_index()
counter_df=counter_df.sort_values(by="title").tail(15)
counter_df

        firstname       lastname  title  country
40920      Simone     Crivellaro     21       21
3508      Antonio         Franco     21       21
17366     Husam H         Balkhy     21       21
12993   Francesco      Porpiglia     22       22
14391    Giuseppe         Simone     22       22
27945       Maria  Christodoulou     23       23
45481         Wei           Wang     23       23
36583    Riccardo        Bertolo     24       24
1421   Alessandro         Veccia     24       24
8967      Daniele       Amparore     27       27
12937   Francesco        Ditonno     27       27
18159     Iswanto        Sucandy     32       32
36581    Riccardo       Autorino     35       35
36586    Riccardo          Campi     40       40
1363   Alessandro      Antonelli     47       47

In [7]:
counter_df["name"]=counter_df["firstname"]+" "+counter_df["lastname"]
counter_df

        firstname       lastname  title  country                  name
40920      Simone     Crivellaro     21       21     Simone Crivellaro
3508      Antonio         Franco     21       21        Antonio Franco
17366     Husam H         Balkhy     21       21        Husam H Balkhy
12993   Francesco      Porpiglia     22       22   Francesco Porpiglia
14391    Giuseppe         Simone     22       22       Giuseppe Simone
27945       Maria  Christodoulou     23       23   Maria Christodoulou
45481         Wei           Wang     23       23              Wei Wang
36583    Riccardo        Bertolo     24       24      Riccardo Bertolo
1421   Alessandro         Veccia     24       24     Alessandro Veccia
8967      Daniele       Amparore     27       27      Daniele Amparore
12937   Francesco        Ditonno     27       27     Francesco Ditonno
18159     Iswanto        Sucandy     32       32       Iswanto Sucandy
36581    Riccardo       Autorino     35       35     Riccardo Autorino
36586    Riccardo          Campi     40       40        Riccardo Campi
1363   Alessandro      Antonelli     47       47  Alessandro Antonelli

In [8]:
counter_df[["name","title"]].to_csv("scientist_table.csv")

In [9]:
len(df["pubmed_id"].unique())

9977

In [10]:
df["date-format"]=pd.to_datetime(df["date"], format='%d/%m/%Y',errors="coerce")

In [11]:
for element in df["country"].unique():
    print(element)

China
Switzerland
Germany
P
The Netherlands
Japan
OH 44691
MI 49404
East Lansing 48824
IL 60605
Canada
United States
Italy
Colombia
USA
California
Republic of Korea
Ireland
University of Bisha
University Hospital of Patras
Hubert Koutoukou MAGA of Cotonou
Baku
Sweden
UK
Portugal
France
Ethiopia
Nigeria
Interdisciplinary Research Center "Health Science"Scuola Superiore Sant'Anna Pisa 56127 Italy
Medical SchoolUniversity of Minnesota Minneapolis MN 55455 USA
Centre for Neuroprosthetics and Institute of BioengineeringÉcole Polytechnique Fédérale de Lausanne (EPFL) Lausanne 1015 Switzerland
Cardiovascular Research CenterTemple University Philadelphia PA 19140 USA
GBR
CUW
Russia
New Zealand
100853
100034
Deutschland
New York
Maine
CHINA
Spain
India
United Kingdom
Australia
Denmark
Milan
Como
NC
NY
Indonesia
Malaysia
Ukraine
Vietnam
Taiwan
Singapore
Romania
Poland
Bulgaria
Austria
Brazil
Belgium
Kazakhstan
Algeria
Israel
Greece
United States of America
Türkiye
110029 India
710055 Shaanxi China
EX4 4QF UK
Bangladesh
IND
IRQ
Korea
Turkey
Philippines
Trinidad and Tobago
PR China
UK edmund
OH
TX
PA
UT
MA
CA
IL
FL
LA
PA 19096
Netherlands
Thailand
CT
THAILAND
University of Waterloo 200 University Avenue West Waterloo Ontario N2L 3G1 Canada peng
Pakistan
Tenn
South Korea
SC
MA 02215 USA
NH 03756 USA
PA (FS)
Memorial Sloan Kettering Cancer Center
GA 30332
CA 91125
Frankfurt am Main
Department of Urology
United Kingdom
United States
Saudi Arabia
Argentina
India jaithilak@aims
West Virginia University
People's Republic of China
Ann Arbor
the Netherlands
Egypt
University of Dhaka Dhaka-1000 Bangladesh mahabib@du
University of Dhaka Dhaka-1000 Bangladesh
Bangladesh Atomic Energy Commission Dhaka-1000 Bangladesh
Dhaka University of Engineering & Technology Gazipur-1707 Bangladesh
Senegal
Tianjin 301617
Northeastern University
Guangdong University of Technology
Tianjin University of TCM
Ohio
Slovenia
Oman
South Africa
Hungary
United Arab Emirates
JPN
IDN
Mexico
Turkiye
Baltimore
University of Sydney
Slovakia
Czech Republic
Hong Kong
RASID Laboratory of M42 Health and Abu Dhabi Quality and Conformity Council UAE
Professor at Poznan's Academy of Medicine Poland
Departments of1Neurological Surgery
Departments of2Neurological Surgery and
Pennsylvania
Illinois; and
Iran
Ecuador
Uzbekistan
Brunei
Uganda
Sri Lanka
Lebanon
Kenya
Ghana
430074
430022
India k26uday74@yahoo
DC
48201 USA
48108
Lithuania
U
Municipal Higashi Osaka Medical Center
Florida
Libya
Norway
Finland
Yokohama City University Hospital
Japanese Red Cross Wakayama Medical Center
Jordan
Illinois
Civil Aviation General Hospital
China - pineneedle@sina
EGY
PAK
Hong Kong SAR
NJ
National Cerebral and Cardiovascular Center Hospital
The netherlands
IL 60208
IL 60611
NV
Universidad del Pais Vasco (UPV)/EHU
Italia
Ludwigshafen Germany
Munich
Department of Orthopedics Peking University Third Hospital Beijing China
GA
University of Oklahoma Health Sciences Center
Washington
IN
MO
ME
AZ
VA
MI
KY
OK
WA
Shanghai; and
Humanitas University; and
Departments of1Neurosurgery
and
Rhode Island
Pennsylvania; and
Massachusetts
Arizona; and
Berkeley; and
Berlin
Heidelberg; and
Michigan; and
Florida; and
Taipei
Taipei; and
Salt Lake City; and
Utah
Kocaeli
Departments of2Neurosurgery and
Kocaeli; and
Peking University Third Hospital
China; and
US
Czechia
Brasil
Lao People's Democratic Republic
Republic of Singapore
ITALY
SWEDEN
Uruguay
South Korean
Morocco
University of Cambridge 27 Charles Babbage Road Cambridge CB3 0FS UK rce26@cam
Chalmers University of Technology Kemivagen 4 Gothenburg 412 96 Sweden
EEBE Eduard Maristany 10-14 08019 Barcelona Spain kasper
University of Louisville School of Medicine
Germany - harke
Zhejiang University
1211 Genève 14
113-8656
University of the Philippines Manila
Uppsala
Göteborgs universitet
Chile
Kobe City Medical Center General Hospital
N
United Kingdom (J
United Kingdom (U
A
C
R
United Kingdom (K
USA mbhimre1@jhmi
Brussels Health Campus
Antwerp
New Jeresey
Michigan
Maryland
West Virginia
Tunisia
Grenada
Serbia
Tokushima University
Tokushima University Hospital
Peru
Republic of China
TN; Vanderbilt Interventional Pulmonary Research Laboratory; Vanderbilt Center for Bioethics and Society
TN; Vanderbilt Interventional Pulmonary Research Laboratory
TN
Montefiore Medical Center
NH
Email: dr
Luxembourg
China pukexue@cqmu
Kyushu University
International Clinical Cancer Research Center
Houston
Boston
North Carolina
Texas
Italy - mario
UNITED STATES
Maharashtra India
South Carolina
Department of Mechanical EngineeringNorthern Arizona University Flagstaff AZ 86011 USA
Estonia
UAE
CT 06520 (J
Departments of Orthopaedic Surgery and
Bangalore India
160012 India
NY 10032
HI 96822
300387 China
300192 China
Department of Chemical Engineering Ben-Gurion University of the Negev Beer-Sheva Israel
Department of Neurosurgery Johns Hopkins University School of Medicine Baltimore Maryland USA
Tel Aviv University Tel Aviv Israel
BGD
Laos
Cyprus
Panamá
Vic
NSW
Iraq
Division of Urology University of Toronto Toronto Canada
Department of Urology Centre Hospitalier de l'Universite de Montreal Montreal Canada
Clemenceau Medical Center Beirut Lebanon
Department of Urology Frimley Park Hospital Frimley UK
San Diego Clinical Trials San Diego California USA
Department of Urology Bay of Plenty District Health Board Clinical School Tauranga New Zealand
Department of Urology Royal Melbourne Hospital Melbourne Australia
Department of Urology Wake Forest School of Medicine Winston-Salem North Carolina USA
Department of Urology Mayo Clinic Phoenix Arizona USA
Department of Urology Mount Sinai Hospital New York New York USA
Department of Urology Albany Medical College Albany New York USA
Department of Urology University of Southern California Los Angeles California USA
Department of Urology UT Southwestern Medical Centre Dallas Texas USA
Department of Surgery Hospital Nova of Central Finland Jyväskylä Finland
Department of Urology University of Turku Turku Finland
W2 1NY UK
Brazil pedrodicillo@gmail
Georgia
Sarvodaya Health and Research Centre
100084 China
100124 China
Arizona State University
Universidade do Porto
Instituto de Ciências Biomédicas Abel Salazar da Universidade do Porto
Sciensano
Parasitology and Hygiene (LMPH)
Universidade do Porto; tania
MO 63005
England
United Kingdom LE12 5RD
TX 75024
TX 77843
OH 45242
Colo
University of Edinburgh
Italy - antonino
chatziioannou@mdw
España
ESPAÑA
Department of Surgery National Defense Medical College Tokorozawa Japan
Department of Gastrointestinal Surgery Tokyo Medical and Dental University Tokyo Japan
Department of Surgery Edogawa Hospital Tokyo Japan
Graduate School of Medical and Dental Sciences Tokyo Medical and Dental University Tokyo Japan
SA
Tennessee
Curaçao
Qatar
Isahaya General Hospital Nagasaki Japan
Department of Surgical Oncology Nagasaki University Graduate School of Biomedical Sciences Nagasaki Japan
Nagasaki University Nagasaki Japan
Department of Urology Nagasaki University Graduate School of Biomedical Sciences Nagasaki Japan
Faculty of Medicine Oita University Yufu-city Oita Japan
Department of Urology Japanese Red Cross Aichi Medical Center Nagoya Daini Hospital Nagoya Aichi Japan
Department of Urology Saiseikai Yokohamashi Tobu Hospital Yokohama Japan
Robotic Surgery Center Saiseikai Yokohamashi Tobu Hospital Yokohama Japan
Department of Surgery Saiseikai Yokohamashi Tobu Hospital Yokohama Japan
Department of Urology Jichi Medical University Hospital Shimotsuke Japan
Graduate School of Medicine The University of Tokyo Bunkyo-ku Japan
National Cancer Center Hospital East Chiba Japan
Louisiana
Korea (the Republic of)
COL
Japan (all authors)
Brazil; cblanco88@uan
Brazil; eduardo
Brazil; denis
East China University of Technology Nanchang 330013 P
Jiangxi Normal University Nanchang 330022 P
Jilin University Changchun 130012 P
University of North Carolina at Chapel Hill Chapel Hill North Carolina USA
Fudan University Shanghai 200438 P
Italy; stefania
WV
Amiens
Institute Faire Faces and
Schweiz
Department of Informatics
USAbalaji1312@ucla
MD
Cardiology Ain Shams University Cairo Egypt
Texas Pulmonary Institute Nederland Nederland Texas USA
Pulmonary and Critical Care Pulmonary and Sleep Physicians of Houston Webster Texas USA
Tex
Mass
Greece; kozonis24@yahoo
Arizona
Costa Rica
Pesquisa e Inovação Liga Contra o Câncer - Natal (RN) - Brazil
Sri Lanka
NJ 08540
PA 15124
650-0047 Japan
Saitama 354-0044 Japan
Hyogo 650-0047 Japan
Osaka 565-0874 Japan
Tokyo 135-0064 Japan
Taiwan (R
USA paterson@pitt
Graduate School of Zhejiang Chinese Medical University; The Second Hospital of Jiaxing
The Second Hospital of Jiaxing
Tongji Zhejiang College
Graduate School of Zhejiang Chinese Medical University; The Second Hospital of Jiaxing; jxgxd@hotmail
The Second Hospital of Jiaxing; fjm_7758@163
85721 USA
Rutgers University
85724 USA
Tohoku University
Massachusetts Institute of Technology
Johns Hopkins University
Kyoto University
Iowa State University
Institute of Science Tokyo
221004
200240
200030
261053
200444
200082
200011
Okayama Saiseikai General Hospital
Bolivia
México
nan
München 85748 Germany
München 81675 Germany
Malta
USA - India
and Mehdizadeh)
Switzerland olivia
r
Venezuela
Weill Cornell Medicine
MVJ College of Engineering Bangalore 560067 Karnataka India
PES Institute of Technology and Management Shivamogga 577204 Karnataka India
GM University Davanagere 577006 Karnataka India
Symbiosis Institute of Technology (Symbiosis International University) Pune 412115 Maharashtra India
Universitas Pasundan Bandung 40261 West Java Indonesia deden
Universitas Diponegoro Semarang 50275 Central Java Indonesia
and Ghanem)
School of Mechanical Engineering and Automation Fuzhou University Fuzhou China
College of Physics and Electronic Information Engineering Minjiang University Fuzhou China
Swave Biotechnology (Suzhou) Co
Department of Materials Science and Engineering University of Connecticut Storrs Connecticut USA
State Key Laboratory of Explosion Science and Technology and Advanced Research Institute of Multidisciplinary Science Beijing Institute of Technology Beijing China
Department of Laboratory Medicine Shenzhen Children's Hospital Shenzhen People's Republic of China
International Collaborative Laboratory of 2D Materials for Optoelectronics Science and Technology of Ministry of Education Institute of Microscale Optoelectronics Shenzhen University Shenzhen People's Republic of China
USA Email: JCraig1@hfhs
USA epatorno@bwh
Grosseto- Italy
QC
University of Basel Basel Switzerland
Department of Personalised Orthopaedics (PersO) at Privatklinik Siloah Berne Switzerland
Department of Orthopaedics and Traumatology Çankaya Hospital Ankara Turkey
University of Bologna Bologna Italy
Regenerative Medicine & Biomechanics University of Basel Basel Switzerland
Technical University Munich (TUM) Munich Germany
Yale University School of Medicine
Connecticut
RI
Phillipines
ES
Yemen
School of Medicine (Drs
DC (Dr
Italy (Dr
McGill University
Jaber Al-Ahmad Al Sabah Hospital
DE 19716
China wscai66@163
Shanghai Jiao Tong University
Minhang
Italy - sabrinatitti
Department of Urology IRCCS Humanitas Research Hospital Rozzano Italy
Department of Urology UC San Diego Health System La Jolla California USA
Biomedical Science Humanitas University Pieve Emanuele Italy
MAR
Gunma 371-0014 Japan
Department of General Thoracic Surgery Maebashi Red Cross Hospital Japan
PRT
Syria
Nepal
London
Rwanda
the Netherlands (P
Pa
Daegu Gyeongbuk Institute of Science and Technology (DGIST) Daegu 42988 Republic of Korea sspritamrath93@gmail
Kalinga Institute of Industrial Technology Bhubaneswar 751003 Odisha India arunima7june@gmail
Parul University Ta
Uttaranchal University 22 Dehradun Uttarakhand India sarveshrustagi@uttaranchaluniversity
University Center for Research & Development (UCRD) Chandigarh University Ludhiana Highway Mohali 140413 Punjab India
Gainesville
606-8507 Japan
410083 China
110001 China
430022 China
100000 China
400016 China
250000 China
570102 China
210042 China
200032 China
350000 China
830001 China
210000 China
116021 China
215000 China
610000 China
200025 China
150000 China
310000 China
230000 China
200443 China
130000 China
510091 China
Syrian Arab Republic
Indiana
France - johannemensah@gmail
imas12 Institute of Health Investigation
Republic of Ireland
ROC
OR
Departments of1Neurosurgery and
Baltimore; and
and Immunology
Minnesota
Department of Otolaryngology-Head and Neck Surgery，Peking University First Hospital，Beijing，100034，China
ITA
Belgium - zeyu
WI
Baton Rouge LA
NM
Korea (the Republic of) paek
Rome Italy
Bari
44 0 75 4383 4
Hong Kong Special Administrative Region of China
New Jersey
34959
E1 4NS UK
Stone)
Missouri (Buczek)
Birmingham (Lin)
Missouri (Chernock)
Miami (Lora Gonzalez)
MYS
Raleigh North Carolina
SAU
Watford General Hospital
Centre hospitalier universitaire vaudois et Université de Lausanne
United Kingdom ian
Ohio 44106
Illinois 60637
California 91125
Michigan 48109
Pennsylvania 15213
IL 61801
NC 27599
University of Heidelberg
Magna Graecia University of Catanzaro
University of Florence
Trento
Florence
Calenzano (FI)
315201
University of Ljubljana Ljubljana Slovenia
CEU Universities Boadilla del Monte Spain
Institute for Biostatistics and Medical Informatics University of Ljubljana Ljubljana Slovenia
Ukmarjeva 2 Ljubljana Slovenia
Republic of Korea; mhpark@chonnam
TX 75080
Children's Hospital of Fudan University Shanghai China
Department of Neurological Rehabilitation Guizhou Branch of Shanghai Children's Medical Center Shanghai Jiao Tong University School of Medicine Guizhou China
Medical College of Guizhou University Guizhou China
KSA
USA 53706
53715
MI 48109
Moldova
Kanpur-U
LE1 5WW
LE1 7RH
Leicestershire
CO
The Royal Wolverhampton NHS Trust WV10 0QP Heath town Wolverhampton UK
Italy - imonsellato@libero
Maharashtra 411007 India
University of Melbourne Melbourne Victoria Australia
Department of Urology Austin Health Melbourne Victoria Australia
BELGIUM
FRANCE
Italy - alb
Italy - federico
Italy - riccardogiuseppe
USA - riccardo_autorino@rush
USA - ricautor@gmail
UK - francesco
Italy - alessandro
USA - kaoukj@ccf
Italy - veronica
Spain ramonroviran@gmail
Department of ICT and Natural Sciences Norwegian University of Science and Technology (NTNU) Ålesund Norway
Orthopedic Department Møre and Romsdal Hospital Trust Ålesund Norway
Hofseth BioCare Ålesund Norway
Department of Neuromedicine and Movement Science Norwegian University of Science and Technology (NTNU) Trondheim Norway
Department of Research and Innovation Møre and Romsdal Hospital Trust Ålesund Norway
08540
63130
02134
The People's Republic of China
Wenzhou Medical University
Taizhou Hospital Affiliated to Wenzhou Medical University
Affiliate Hospital of Shandong University of Traditional Chinese Medicine
Taizhou Hospital Affiliated to Wenzhou Medical University; czb1971@zju
MD 21218 USA
MD 21287 USA
Viet Nam
IRL
Israel (Dr
and Wright)
Canada (Dr
Department of Visceral and Digestive Surgery Fattouma Bourguiba Hospital University of Monastir Monastir Tunisia
Fiji
117576 Singapore
Mich
Calif
USA fernandez-bussy
Sint Maarten (Dutch Part)
JAMA Surgery
Kobe City Medical Center W
Taif Saudi Arabia
Oaxaca 69000 Mexico
UK t
NY Qureshi
Los Angeles
Chapel Hill
Irvine
Democratic Republic of Congo
University Hospital Zurich (USZ)
Michigan United States
GRD
MEX
MA 01605 USA
Kingdom of Saudi Arabia
Virginia
University of Louisville
Oklahoma State University System
49 3455574001
The Netherland
3000 Leuven Belgium
India - amathur@statsense
Hyderabad India
Missouri
Graduate School of Biomedical Sciences Nagasaki University Nagasaki Japan
Graduate School of Engineering Science Osaka University Osaka Japan
Department of Neuropsychiatry Keio University School of Medicine Tokyo Japan
Scotland
Italy - s
Oregon State University Corvallis OR 97331 USA
Disability and Mobility Do-it-Yourself Co-OpOregon State University Corvallis OR 97331 USA
JOR
SDN
NY 10027 USA
NY 10032 USA
USA jamie
Maharashtra 422002 India
Arkansas
MUS
Kaohsiung
Tokyo Japan
New Taipei City
Foshan University Foshan 528000 China
Shunde Polytechnic Foshan 528333 China
The 5th Electronics Research Institute of the Ministry of Industry and Information Technology Guangzhou 510610 China
Foshan University Foshan 528000 China pjp@fosu
and Peng)
Institute of Biomedical Sciences (Dr
Pharmaceuticals and Medical Devices Agency
Yumino Heart Clinic
Perry Point
Albuquerque
Newark
Richmond
Tampa
University of California Irvine
Dallas
Wisconsin
Milwaukee
San Antonio
Department of Surgery Yokohama City University Yokohama Japan
Department of Gastrointestinal Surgery Yokohama City University Medical Center Yokohama Japan
Department of Surgery Saiseikai Yokohama City Nanbu Hospital Yokohama Japan
Department of Surgery Hiratsuka Kyosai Hospital Hiratsuka Japan
Department of Surgery Fujisawa Shounandai Hospital Fujisawa Japan
Department of Surgery Yokohama Minami Kyosai Hospital Yokohama Japan
School of Medicine Yokohama City University Yokohama Japan
Department of Surgery Nagasaki University Graduate School of Biomedical Sciences Nagasaki Japan
Virginia 22030
California 95616
Virginia 22030 mwiener@gmu
Ruhr-University Bochum
Institute of Musculoskeletal Disorders and Orthopaedics Medanta-The Medicity Hospital Gurugram India
Institute of Education and Research Medanta-The Medicity Hospital Gurugram India
248140
Pelvis y Acetábulo
British Society of Sexual Medicine
Manchester
Romford
Surrey and Sussex Cancer Alliance
University of Hertfordshire
Liverpool
Londonderry
Bristol
Truro
Prostate Cancer UK
Novara
Riyadh
Naples
SGP
BRB
PHL
Campus Detmold
Pakistan msarwarkhan1@hotmail
IN 47907
UK abhisekh
University of Montpellier
IRCCS Polyclinic San Martino Hospital
Università di Genova
IRCCS Polyclinic San Martino
University of Genoa
IRCCS Ospedale Policlinico San Martino
University of Genova
Polyclinic San Martino Hospital
Italy nicolo
Principality of Liechtenstein
Department of Neurology and Stroke Center La Paz University Hospital
Department of Cardiology La Paz University Hospital
Croatia
Japan t-aoyama@lilac
Japan itarum1n1@hotmail
Japan; h
GA 30309
MA 02115
SC 29605
GA 30322
NY 11794-2300
TX 75390
IN 46202
School of Medicine
USA arati
OR 97331
Department of Rheumatology and Immunology Nanjing Drum Tower Hospital School of Biological Science and Medical Engineering Southeast University Nanjing China
Technology and Research (A*STAR) Singapore Singapore
Japan; kobari
Columbia
Swiss Federal Laboratories forMaterials Science and Technology (EMPA) 8600 Duebendorf Switzerland dorina
MI USA
RG6 6UR UK
GL7 6JS UK
NY 11794
Russian Federation
Finland; FICAN Mid
USA Isaac
China (Hong Kong)
710068 P
University Medical Center of the Johannes Gutenberg-Universität Mainz
DRK Kliniken Berlin Westend
Hospital Rüsselsheim
Mainz
Ludwig-Maximilians-University Medical Center Munich
Bina Nusantara University Jakarta Indonesia christian
Universitas Indonesia Kampus Baru UI Depok Jawa Barat Indonesia
National Institute for Materials Science (NIMS) 1-1 Namiki Tsukuba Ibaraki 305-0044 Japan
Serpong South Tangerang 15314 Banten Indonesia
Bina Nusantara University Jakarta 11480 Indonesia
Setu Regency South Tangerang Banten 15314 Indonesia
University of the Punjab Lahore Pakistan
Institute of Technology Bandung (ITB) Bandung 40132 Indonesia
University of Southampton Southampton UK
Tanzania
Congo
Puerto Rico
United States stephen
New Orleans LA
CA 92521 USA
CA 91010 USA
Affiliated Hospital of Medical School Nanjing University Nanjing Jiangsu China
Department of Urology The First People's Hospital of Yancheng Yancheng Jiangsu China
Affiliated Hospital of Medical School Southeast University Nanjing Jiangsu China
Tamil Nadu 600006 India
110076 India
Interdisciplinary Program in BioengineeringSeoul National University Graduate School Seoul 08826 South Korea
Seoul National University Seoul 08826 South Korea
Graduate School of Convergence Science and TechnologySeoul National University Seoul 08826 South Korea

In [12]:
us_states = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", 
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", 
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", 
    "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", 
    "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", 
    "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", 
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", 
    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", 
    "Washington", "West Virginia", "Wisconsin", "Wyoming"
]
largest_us_cities = [
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", 
    "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", 
    "Fort Worth", "Columbus", "Indianapolis", "Charlotte", "San Francisco", 
    "Seattle", "Denver", "Oklahoma City", "Nashville", "El Paso", "Washington", 
    "Boston", "Las Vegas", "Portland", "Detroit", "Louisville", "Memphis", 
    "Baltimore", "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Mesa", 
    "Sacramento", "Atlanta", "Kansas City", "Colorado Springs", "Miami", 
    "Raleigh", "Omaha", "Long Beach", "Virginia Beach", "Oakland", "Minneapolis", 
    "Tulsa", "Arlington", "Tampa", "New Orleans", "Wichita", "Bakersfield", 
    "Aurora", "Cleveland", "Anaheim", "Henderson", "Honolulu", "Riverside", 
    "Santa Ana", "Corpus Christi", "Lexington", "Stockton", "St. Louis", 
    "Pittsburgh", "Saint Paul", "Cincinnati", "Anchorage", "Greensboro", 
    "Plano", "Lincoln", "Orlando", "Irvine", "Newark", "Toledo", "Durham", 
    "Chula Vista", "Fort Wayne", "Jersey City", "St. Petersburg", "Laredo", 
    "Madison", "Chandler", "Lubbock", "Scottsdale", "Reno", "Buffalo", 
    "Gilbert", "Glendale", "North Las Vegas", "Winston–Salem", "Chesapeake", 
    "Norfolk", "Fremont", "Garland", "Irving", "Hialeah", "Richmond", 
    "Boise", "Spokane", "Baton Rouge", "Tacoma"
]

In [13]:
german_cities = [
    "Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt am Main", "Stuttgart", 
    "Düsseldorf", "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden", 
    "Hanover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal", "Bielefeld", 
    "Bonn", "Münster", "Karlsruhe", "Mannheim", "Augsburg", "Wiesbaden", 
    "Mönchengladbach", "Gelsenkirchen", "Braunschweig", "Chemnitz", "Kiel", 
    "Aachen", "Halle (Saale)", "Magdeburg", "Freiburg im Breisgau", "Krefeld", 
    "Lübeck", "Oberhausen", "Erfurt", "Rostock", "Mainz", "Kassel", "Hagen", 
    "Saarbrücken", "Hamm", "Ludwigshafen am Rhein", "Mülheim an der Ruhr", 
    "Potsdam", "Oldenburg", "Leverkusen", "Osnabrück", "Solingen", "Heidelberg", 
    "Herne", "Neuss", "Darmstadt", "Paderborn", "Regensburg", "Ingolstadt", 
    "Würzburg", "Wolfsburg", "Ulm", "Heilbronn", "Offenbach am Main", "Pforzheim", 
    "Fürth", "Göttingen", "Bottrop", "Reutlingen", "Koblenz", "Bremerhaven", 
    "Bergisch Gladbach", "Remscheid", "Jena", "Trier", "Erlangen", "Moers", 
    "Salzgitter", "Siegen", "Hildesheim", "Cottbus", "Kaiserslautern", 
    "Gütersloh", "Schwerin", "Witten", "Iserlohn", "Zwickau", "Marl", 
    "Lünen", "Esslingen am Neckar", "Ludwigsburg", "Tübingen", "Villingen-Schwenningen", 
    "Flensburg", "Gera", "Ratingen", "Lüneburg", "Wilhelmshaven", "Hanau", 
    "Düren", "Velbert", "Minden"
]

In [14]:
largest_chinese_cities = [
    "Chongqing", "Shanghai", "Beijing", "Chengdu", "Guangzhou", "Shenzhen",
    "Tianjin", "Wuhan", "Dongguan", "Foshan", "Hangzhou", "Xi'an", "Nanjing",
    "Shenyang", "Harbin", "Suzhou", "Qingdao", "Dalian", "Zhengzhou", "Jinan",
    "Changsha", "Kunming", "Changchun", "Ürümqi", "Shijiazhuang", "Ningbo",
    "Wuxi", "Hefei", "Fuzhou", "Nanning", "Xiamen", "Lanzhou", "Taiyuan",
    "Nanchang", "Guiyang", "Wenzhou", "Hohhot", "Haikou", "Zhongshan",
    "Tangshan", "Yantai", "Weifang", "Zibo", "Quanzhou", "Huizhou", "Baotou",
    "Handan", "Jilin", "Baoding", "Anshan", "Xuzhou", "Linyi", "Datong",
    "Yancheng", "Zhuhai", "Luoyang", "Jiangmen", "Huaian", "Liaocheng",
    "Taizhou", "Yichang", "Zaozhuang", "Jining", "Shaoxing", "Yangzhou",
    "Ganzhou", "Jiaxing", "Zhangzhou", "Puyang", "Xiangyang", "Hengyang",
    "Pingdingshan", "Jinzhou", "Chaozhou", "Maoming", "Zhanjiang", "Jinhua",
    "Lianyungang", "Changzhou", "Qinhuangdao", "Yingkou", "Jiangyin",
    "Luzhou", "Mianyang", "Luohe", "Leshan", "Liaoyang", "Zhoushan",
    "Chenzhou", "Xinyang", "Zhumadian", "Zhongwei", "Baoshan", "Beihai",
    "Liuzhou", "Qiqihar", "Shantou", "Huangshi"
]

In [15]:
len(largest_chinese_cities)

98

In [16]:
places_list=us_states+largest_us_cities+["USA","United States","US","United States of America"]

In [17]:
us_mentioned=df[df["country"].astype(str).str.contains('|'.join(places_list))]
us_mentioned

,Unnamed: 0,title,pubmed_id,firstname,lastname,country,date,searchterm,date-format
53,53,Effect of nonsteroidal anti-inflammatory drugs...,39694237,M C,Cantor,United States,19/12/2024,robotics,2024-12-19
54,54,Effect of nonsteroidal anti-inflammatory drugs...,39694237,H W,Neave,United States,19/12/2024,robotics,2024-12-19
55,55,Effect of nonsteroidal anti-inflammatory drugs...,39694237,J H C,Costa,United States,19/12/2024,robotics,2024-12-19
60,60,"Comment on ""Surgical, functional, and oncologi...",39693902,Andrea,Costantino,United States,19/12/2024,robotics,2024-12-19
75,75,AI-driven universal lower-limb exoskeleton sys...,39693442,Dawit,Lee,USA,18/12/2024,robotics,2024-12-18
...,...,...,...,...,...,...,...,...,...
69866,69866,Use of Simulation For Training Advanced Colore...,38508956,Julie M,Clanahan,Missouri,21/03/2024,robotics,2024-03-21
69867,69867,Use of Simulation For Training Advanced Colore...,38508956,Britta J,Han,Missouri,21/03/2024,robotics,2024-03-21
69868,69868,Use of Simulation For Training Advanced Colore...,38508956,Coen L,Klos,Missouri,21/03/2024,robotics,2024-03-21
69869,69869,Use of Simulation For Training Advanced Colore...,38508956,Paul E,Wise,Missouri,21/03/2024,robotics,2024-03-21
69870,69870,Use of Simulation For Training Advanced Colore...,38508956,Kerri A,Ohman,Missouri,21/03/2024,robotics,2024-03-21

In [18]:
len(us_mentioned["pubmed_id"].unique())/len(df["pubmed_id"].unique())

0.23433897965320236

In [19]:
places_list=german_cities+["Germany", "Deutschland"]
de_mentioned=df[df["country"].astype(str).str.contains('|'.join(places_list))]
de_mentioned

/var/folders/jf/2jm804y50jv2nrhclzdyvvdh0000gn/T/ipykernel_24475/3189811704.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  de_mentioned=df[df["country"].astype(str).str.contains('|'.join(places_list))]

,Unnamed: 0,title,pubmed_id,firstname,lastname,country,date,searchterm,date-format
11,11,Targeted memory reactivation during sleep impr...,39695124\n29553763\n20063969\n24864005\n278552...,Walter,Karlen,Germany,19/12/2024,robotics,2024-12-19
89,89,Counterfactual rewards promote collective tran...,39693403,Veit-Lorenz,Heuthe,Germany,18/12/2024,robotics,2024-12-18
91,91,Counterfactual rewards promote collective tran...,39693403,Hongri,Gu,Germany,18/12/2024,robotics,2024-12-18
92,92,Counterfactual rewards promote collective tran...,39693403,Clemens,Bechinger,Germany,18/12/2024,robotics,2024-12-18
327,327,[Navigated and minimally invasive screw osteos...,39690263\n36028373\n15309312\n29350644\n547948...,Dominik M,Haida,Deutschland,18/12/2024,robotics,2024-12-18
...,...,...,...,...,...,...,...,...,...
69795,69795,Best practices and future challenges in the tr...,38510366\n34562395\n35249159\n35344699\n352602...,Juliane,Kröplin,Germany,21/03/2024,robotics,2024-03-21
69796,69796,Best practices and future challenges in the tr...,38510366\n34562395\n35249159\n35344699\n352602...,Jil-Charlot,Reppenhagen,Germany,21/03/2024,robotics,2024-03-21
69797,69797,An update on liver surgery - a new terminology...,38510365\n33630445\n34866349\n34542590\n330748...,Verena,Tripke,Germany,21/03/2024,robotics,2024-03-21
69798,69798,An update on liver surgery - a new terminology...,38510365\n33630445\n34866349\n34542590\n330748...,Nils,Sommer,Germany,21/03/2024,robotics,2024-03-21
69805,69805,Toward next-generation endoscopes integrating ...,38510341\n30350310\n30207593\n25554788\n283366...,Martin,Goetz,Germany,21/03/2024,robotics,2024-03-21

In [20]:
len(de_mentioned["pubmed_id"].unique())/len(df["pubmed_id"].unique())

0.06895860479101934

In [21]:
places_list=largest_chinese_cities+["China"]

In [22]:
ch_mentioned=df[df["country"].astype(str).str.contains('|'.join(places_list))]
ch_mentioned

,Unnamed: 0,title,pubmed_id,firstname,lastname,country,date,searchterm,date-format
0,0,Application of continuous intraoperative neuro...,39695478\n34973664\n33394989\n29302755\n281498...,Chengxia,Wang,China,19/12/2024,robotics,2024-12-19
1,1,Application of continuous intraoperative neuro...,39695478\n34973664\n33394989\n29302755\n281498...,Zhuofu,Li,China,19/12/2024,robotics,2024-12-19
2,2,Application of continuous intraoperative neuro...,39695478\n34973664\n33394989\n29302755\n281498...,Woquan,Zhong,China,19/12/2024,robotics,2024-12-19
3,3,Application of continuous intraoperative neuro...,39695478\n34973664\n33394989\n29302755\n281498...,Shuai,Jiang,China,19/12/2024,robotics,2024-12-19
4,4,Application of continuous intraoperative neuro...,39695478\n34973664\n33394989\n29302755\n281498...,Weishi,Li,China,19/12/2024,robotics,2024-12-19
...,...,...,...,...,...,...,...,...,...
69871,69871,A novel data fusion based intelligent identifi...,38508952,Haoju,Song,China,21/03/2024,robotics,2024-03-21
69872,69872,A novel data fusion based intelligent identifi...,38508952,Guiqin,Li,China,21/03/2024,robotics,2024-03-21
69873,69873,A novel data fusion based intelligent identifi...,38508952,Xin,Xiong,China,21/03/2024,robotics,2024-03-21
69874,69874,A novel data fusion based intelligent identifi...,38508952,Ming,Li,China,21/03/2024,robotics,2024-03-21
69875,69875,A novel data fusion based intelligent identifi...,38508952,Qiang,Qin,China,21/03/2024,robotics,2024-03-21

In [23]:
len(ch_mentioned["pubmed_id"].unique())/len(df["pubmed_id"].unique())

0.25218001403227425

In [24]:
dict_of_us_years={}
for year in range(2000,2025,1):
    filtered_df = us_mentioned[us_mentioned['date-format'].dt.year == year]
    
    dict_of_us_years[year]=[len(filtered_df["pubmed_id"].unique())]
    len(filtered_df)

In [25]:
us_years=pd.DataFrame(dict_of_us_years).T
us_years.columns=["us"]

In [26]:
dict_of_ch_years={}
for year in range(2000,2025,1):
    filtered_df = ch_mentioned[ch_mentioned['date-format'].dt.year == year]
    
    dict_of_ch_years[year]=[len(filtered_df["pubmed_id"].unique())]
    len(filtered_df)

In [27]:
ch_years=pd.DataFrame(dict_of_ch_years).T
ch_years.columns=["ch"]
ch_years

        ch
2000     0
2001     0
2002     0
2003     0
2004     0
2005     0
2006     0
2007     0
2008     0
2009     0
2010     0
2011     0
2012     0
2013     0
2014     0
2015     0
2016     0
2017     0
2018     0
2019     0
2020     0
2021     0
2022     0
2023     0
2024  2516

In [184]:
dict_of_de_years={}
for year in range(2000,2025,1):
    filtered_df = de_mentioned[de_mentioned['date-format'].dt.year == year]
    
    dict_of_de_years[year]=[len(filtered_df["pubmed_id"].unique())]
    len(filtered_df)

In [205]:
de_years=pd.DataFrame(dict_of_de_years).T
de_years.columns=["de"]
de_years

      de
2000  11
2001  10
2002   9
2003  18
2004  11
2005  15
2006   7
2007   9
2008  19
2009  16
2010  14
2011  11
2012   7
2013  32
2014  30
2015  45
2016  62
2017  52
2018  72
2019  70
2020  69
2021  94
2022  70
2023  71
2024  67

In [206]:
dict_of_overall_years={}
for year in range(2000,2025,1):
    filtered_df = df[df['date-format'].dt.year == year]
    dict_of_overall_years[year]=[len(filtered_df["pubmed_id"].unique())]
    len(filtered_df)

In [207]:
overall_years=pd.DataFrame(dict_of_overall_years).T
overall_years.columns=["overall"]

In [208]:
combined_df=pd.concat([us_years,ch_years,de_years,overall_years],axis=1)
combined_df

       us   ch  de  overall
2000   89    1  11      188
2001   73    3  10      189
2002  108    4   9      245
2003  107    6  18      249
2004  103    1  11      246
2005  112    4  15      289
2006  130    6   7      292
2007  135   11   9      342
2008  152   15  19      344
2009  190   15  16      409
2010  182   18  14      473
2011  158   16  11      453
2012  195   27   7      456
2013  211   49  32      615
2014  222   62  30      676
2015  220   76  45      689
2016  267   92  62      777
2017  312  104  52      852
2018  329  151  72      989
2019  361  161  70     1027
2020  389  224  69     1240
2021  395  282  94     1312
2022  372  271  70     1242
2023  385  296  71     1297
2024  362  396  67     1379

In [220]:
combined_df["ch_share"]=combined_df["ch"]*100/combined_df["overall"]
combined_df["de_share"]=combined_df["de"]*100/combined_df["overall"]
combined_df["us_share"]=combined_df["us"]*100/combined_df["overall"]

In [221]:
combined_df

       us   ch  de  overall   ch_share  de_share   us_share
2000   89    1  11      188   0.531915  5.851064  47.340426
2001   73    3  10      189   1.587302  5.291005  38.624339
2002  108    4   9      245   1.632653  3.673469  44.081633
2003  107    6  18      249   2.409639  7.228916  42.971888
2004  103    1  11      246   0.406504  4.471545  41.869919
2005  112    4  15      289   1.384083  5.190311  38.754325
2006  130    6   7      292   2.054795  2.397260  44.520548
2007  135   11   9      342   3.216374  2.631579  39.473684
2008  152   15  19      344   4.360465  5.523256  44.186047
2009  190   15  16      409   3.667482  3.911980  46.454768
2010  182   18  14      473   3.805497  2.959831  38.477801
2011  158   16  11      453   3.532009  2.428256  34.878587
2012  195   27   7      456   5.921053  1.535088  42.763158
2013  211   49  32      615   7.967480  5.203252  34.308943
2014  222   62  30      676   9.171598  4.437870  32.840237
2015  220   76  45      689  11.030479  6.531205  31.930334
2016  267   92  62      777  11.840412  7.979408  34.362934
2017  312  104  52      852  12.206573  6.103286  36.619718
2018  329  151  72      989  15.267947  7.280081  33.265925
2019  361  161  70     1027  15.676728  6.815969  35.150925
2020  389  224  69     1240  18.064516  5.564516  31.370968
2021  395  282  94     1312  21.493902  7.164634  30.106707
2022  372  271  70     1242  21.819646  5.636071  29.951691
2023  385  296  71     1297  22.821897  5.474171  29.683886
2024  362  396  67     1379  28.716461  4.858593  26.250906

In [222]:
combined_df.to_csv("countries_share.csv")