In [1]:
import pandas as pd
import glob

In [57]:
files=glob.glob('../data/*/API*.csv')
files

['../data/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_104/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_104.csv',
 '../data/API_VC.IHR.PSRC.P5_DS2_en_csv_v2_8832/API_VC.IHR.PSRC.P5_DS2_en_csv_v2_8832.csv',
 '../data/API_EN.POP.DNST_DS2_en_csv_v2_5836/API_EN.POP.DNST_DS2_en_csv_v2_5836.csv',
 '../data/API_PA.NUS.PPPC.RF_DS2_en_csv_v2_563/API_PA.NUS.PPPC.RF_DS2_en_csv_v2_563.csv']

In [73]:
gdp_data=pd.read_csv("../data/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_104/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_104.csv",skiprows=3)
gdp_data

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27441.529662,28440.051964,30082.127645,31096.205074,22855.932320,27200.061079,30559.533535,33984.790620,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.121835,186.941781,197.402402,225.440494,208.999748,226.876513,...,1329.807285,1520.212231,1538.901679,1493.817938,1344.103210,1522.393346,1628.318944,1568.159891,1673.841139,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.939925,127.454189,133.827044,139.008291,148.549379,155.565216,...,1630.039447,1574.230560,1720.140280,1798.340685,1680.039332,1765.954788,1796.668633,1599.392983,1284.154441,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1807.952941,2437.259712,2538.591391,2189.855714,1449.922867,1925.874661,2929.694455,2309.534130,2122.083690,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3759.449591,4009.317993,4384.186241,4415.997161,4310.890655,5270.429653,5290.947472,6221.203652,7299.434981,NaN
262,"Yemen, Rep.",YEM,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,975.359417,811.165970,633.887202,623.376168,559.564676,522.173512,615.702078,426.354076,433.174015,NaN
263,South Africa,ZAF,GDP per capita (current US$),NY.GDP.PCAP.CD,532.147504,545.657512,563.423009,604.536855,645.873376,684.621228,...,5651.205852,6618.335083,6914.178032,6533.711210,5580.603831,6843.399419,6523.410978,6022.542542,6253.371582,NaN
264,Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,221.559849,209.693206,202.281031,203.219451,229.979246,287.425476,...,1239.085279,1483.465773,1463.899979,1258.986198,951.644317,1127.160779,1447.123101,1330.727806,1235.084665,NaN
265,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,276.419784,279.016489,275.545608,277.005701,281.744539,294.145359,...,1407.420964,3448.086991,2271.852504,1683.913136,1730.453910,1724.387271,2040.546587,2156.034093,2656.409377,NaN

In [74]:
gdp_data = gdp_data.fillna(method='ffill', axis=1)
gdp_data

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_58939/1476691378.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  gdp_data = gdp_data.fillna(method='ffill', axis=1)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,27441.529662,28440.051964,30082.127645,31096.205074,22855.93232,27200.061079,30559.533535,33984.79062,33984.79062,33984.79062
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.121835,186.941781,197.402402,225.440494,208.999748,226.876513,...,1329.807285,1520.212231,1538.901679,1493.817938,1344.10321,1522.393346,1628.318944,1568.159891,1673.841139,1673.841139
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,413.757895,413.757895
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.939925,127.454189,133.827044,139.008291,148.549379,155.565216,...,1630.039447,1574.23056,1720.14028,1798.340685,1680.039332,1765.954788,1796.668633,1599.392983,1284.154441,1284.154441
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,1807.952941,2437.259712,2538.591391,2189.855714,1449.922867,1925.874661,2929.694455,2309.53413,2122.08369,2122.08369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,3759.449591,4009.317993,4384.186241,4415.997161,4310.890655,5270.429653,5290.947472,6221.203652,7299.434981,7299.434981
262,"Yemen, Rep.",YEM,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,975.359417,811.16597,633.887202,623.376168,559.564676,522.173512,615.702078,426.354076,433.174015,433.174015
263,South Africa,ZAF,GDP per capita (current US$),NY.GDP.PCAP.CD,532.147504,545.657512,563.423009,604.536855,645.873376,684.621228,...,5651.205852,6618.335083,6914.178032,6533.71121,5580.603831,6843.399419,6523.410978,6022.542542,6253.371582,6253.371582
264,Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,221.559849,209.693206,202.281031,203.219451,229.979246,287.425476,...,1239.085279,1483.465773,1463.899979,1258.986198,951.644317,1127.160779,1447.123101,1330.727806,1235.084665,1235.084665
265,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,276.419784,279.016489,275.545608,277.005701,281.744539,294.145359,...,1407.420964,3448.086991,2271.852504,1683.913136,1730.45391,1724.387271,2040.546587,2156.034093,2656.409377,2656.409377

In [75]:
us_gdp=pd.to_numeric(gdp_data[gdp_data["Country Code"]=="USA"]["2024"],errors="coerce")

In [76]:
gdp_data["recent"]=pd.to_numeric(gdp_data["2024"],errors="coerce")
gdp_data

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69,recent
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,28440.051964,30082.127645,31096.205074,22855.93232,27200.061079,30559.533535,33984.79062,33984.79062,33984.79062,33984.790620
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.121835,186.941781,197.402402,225.440494,208.999748,226.876513,...,1520.212231,1538.901679,1493.817938,1344.10321,1522.393346,1628.318944,1568.159891,1673.841139,1673.841139,1673.841139
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,413.757895,413.757895,413.757895
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.939925,127.454189,133.827044,139.008291,148.549379,155.565216,...,1574.23056,1720.14028,1798.340685,1680.039332,1765.954788,1796.668633,1599.392983,1284.154441,1284.154441,1284.154441
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,2437.259712,2538.591391,2189.855714,1449.922867,1925.874661,2929.694455,2309.53413,2122.08369,2122.08369,2122.083690
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,4009.317993,4384.186241,4415.997161,4310.890655,5270.429653,5290.947472,6221.203652,7299.434981,7299.434981,7299.434981
262,"Yemen, Rep.",YEM,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,811.16597,633.887202,623.376168,559.564676,522.173512,615.702078,426.354076,433.174015,433.174015,433.174015
263,South Africa,ZAF,GDP per capita (current US$),NY.GDP.PCAP.CD,532.147504,545.657512,563.423009,604.536855,645.873376,684.621228,...,6618.335083,6914.178032,6533.71121,5580.603831,6843.399419,6523.410978,6022.542542,6253.371582,6253.371582,6253.371582
264,Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,221.559849,209.693206,202.281031,203.219451,229.979246,287.425476,...,1483.465773,1463.899979,1258.986198,951.644317,1127.160779,1447.123101,1330.727806,1235.084665,1235.084665,1235.084665
265,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,276.419784,279.016489,275.545608,277.005701,281.744539,294.145359,...,3448.086991,2271.852504,1683.913136,1730.45391,1724.387271,2040.546587,2156.034093,2656.409377,2656.409377,2656.409377

In [77]:
gdp_data["recent"]

0      33984.790620
1       1673.841139
2        413.757895
3       1284.154441
4       2122.083690
           ...
261     7299.434981
262      433.174015
263     6253.371582
264     1235.084665
265     2656.409377
Name: recent, Length: 266, dtype: float64

In [78]:
gdp_data["gdp_rel_us"]=gdp_data["recent"]/us_gdp.values[0]
gdp_data

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69,recent,gdp_rel_us
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,30082.127645,31096.205074,22855.93232,27200.061079,30559.533535,33984.79062,33984.79062,33984.79062,33984.790620,0.396047
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.121835,186.941781,197.402402,225.440494,208.999748,226.876513,...,1538.901679,1493.817938,1344.10321,1522.393346,1628.318944,1568.159891,1673.841139,1673.841139,1673.841139,0.019506
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,413.757895,413.757895,413.757895,0.004822
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.939925,127.454189,133.827044,139.008291,148.549379,155.565216,...,1720.14028,1798.340685,1680.039332,1765.954788,1796.668633,1599.392983,1284.154441,1284.154441,1284.154441,0.014965
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,2538.591391,2189.855714,1449.922867,1925.874661,2929.694455,2309.53413,2122.08369,2122.08369,2122.083690,0.024730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,4384.186241,4415.997161,4310.890655,5270.429653,5290.947472,6221.203652,7299.434981,7299.434981,7299.434981,0.085065
262,"Yemen, Rep.",YEM,GDP per capita (current US$),NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,NY.GDP.PCAP.CD,...,633.887202,623.376168,559.564676,522.173512,615.702078,426.354076,433.174015,433.174015,433.174015,0.005048
263,South Africa,ZAF,GDP per capita (current US$),NY.GDP.PCAP.CD,532.147504,545.657512,563.423009,604.536855,645.873376,684.621228,...,6914.178032,6533.71121,5580.603831,6843.399419,6523.410978,6022.542542,6253.371582,6253.371582,6253.371582,0.072875
264,Zambia,ZMB,GDP per capita (current US$),NY.GDP.PCAP.CD,221.559849,209.693206,202.281031,203.219451,229.979246,287.425476,...,1463.899979,1258.986198,951.644317,1127.160779,1447.123101,1330.727806,1235.084665,1235.084665,1235.084665,0.014393
265,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,276.419784,279.016489,275.545608,277.005701,281.744539,294.145359,...,2271.852504,1683.913136,1730.45391,1724.387271,2040.546587,2156.034093,2656.409377,2656.409377,2656.409377,0.030957

In [79]:
files[3]

'../data/API_PA.NUS.PPPC.RF_DS2_en_csv_v2_563/API_PA.NUS.PPPC.RF_DS2_en_csv_v2_563.csv'

In [80]:
ppp_data=pd.read_csv("../data/API_PA.NUS.PPPC.RF_DS2_en_csv_v2_563/API_PA.NUS.PPPC.RF_DS2_en_csv_v2_563.csv",skiprows=3)
ppp_data = ppp_data.fillna(method='ffill', axis=1)
ppp_data["ppp_rel_us"]=pd.to_numeric(ppp_data["2024"],errors="coerce")
ppp_data=ppp_data.dropna(subset=["ppp_rel_us"])
ppp_data

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_58939/738192548.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ppp_data = ppp_data.fillna(method='ffill', axis=1)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69,ppp_rel_us
0,Aruba,ABW,Price level ratio of PPP conversion factor (GD...,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,...,0.757898,0.765701,0.79509,0.788776,0.761985,0.733732,0.755766,0.755766,0.755766,0.755766
2,Afghanistan,AFG,Price level ratio of PPP conversion factor (GD...,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,...,0.224964,0.202007,0.192222,0.199372,0.166263,0.168282,0.187925,0.187925,0.187925,0.187925
4,Angola,AGO,Price level ratio of PPP conversion factor (GD...,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,...,0.348542,0.34549,0.29088,0.224768,0.259968,0.369683,0.287012,0.254204,0.254204,0.254204
5,Albania,ALB,Price level ratio of PPP conversion factor (GD...,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,...,0.354796,0.391741,0.369147,0.370095,0.397679,0.352097,0.403352,0.426244,0.426244,0.426244
6,Andorra,AND,Price level ratio of PPP conversion factor (GD...,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,...,0.766188,0.775094,0.717838,0.717161,0.715054,0.619454,0.652614,0.657913,0.657913,0.657913
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,Price level ratio of PPP conversion factor (GD...,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,...,0.42739,0.437599,0.40659,0.409294,0.426327,0.379255,0.393637,0.392025,0.392025,0.392025
262,"Yemen, Rep.",YEM,Price level ratio of PPP conversion factor (GD...,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,...,0.435717,0.435717,0.435717,0.435717,0.435717,0.435717,0.435717,0.435717,0.435717,0.435717
263,South Africa,ZAF,Price level ratio of PPP conversion factor (GD...,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,...,0.481739,0.518018,0.488996,0.44042,0.499107,0.441982,0.396371,0.404553,0.404553,0.404553
264,Zambia,ZMB,Price level ratio of PPP conversion factor (GD...,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,...,0.437391,0.425271,0.374542,0.301411,0.321767,0.376784,0.326399,0.2924,0.2924,0.292400
265,Zimbabwe,ZWE,Price level ratio of PPP conversion factor (GD...,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,PA.NUS.PPPC.RF,...,0.489412,0.868975,0.524379,0.492912,0.541445,0.573181,0.564354,0.677362,0.677362,0.677362

In [81]:
df_rel_us=pd.merge(ppp_data[["Country Name","Country Code","ppp_rel_us"]],gdp_data[["Country Code","gdp_rel_us"]],on="Country Code")
df_rel_us

     Country Name Country Code  ppp_rel_us  gdp_rel_us
0           Aruba          ABW    0.755766    0.396047
1     Afghanistan          AFG    0.187925    0.004822
2          Angola          AGO    0.254204    0.024730
3         Albania          ALB    0.426244    0.116672
4         Andorra          AND    0.657913    0.574569
..            ...          ...         ...         ...
198        Kosovo          XKX    0.392025    0.085065
199   Yemen, Rep.          YEM    0.435717    0.005048
200  South Africa          ZAF    0.404553    0.072875
201        Zambia          ZMB    0.292400    0.014393
202      Zimbabwe          ZWE    0.677362    0.030957

[203 rows x 4 columns]

In [82]:
df_rel_us["cost_to_gdp"]=df_rel_us["ppp_rel_us"]/df_rel_us["gdp_rel_us"]
df_rel_us

     Country Name Country Code  ppp_rel_us  gdp_rel_us  cost_to_gdp
0           Aruba          ABW    0.755766    0.396047     1.908271
1     Afghanistan          AFG    0.187925    0.004822    38.973978
2          Angola          AGO    0.254204    0.024730    10.279155
3         Albania          ALB    0.426244    0.116672     3.653352
4         Andorra          AND    0.657913    0.574569     1.145056
..            ...          ...         ...         ...          ...
198        Kosovo          XKX    0.392025    0.085065     4.608523
199   Yemen, Rep.          YEM    0.435717    0.005048    86.313739
200  South Africa          ZAF    0.404553    0.072875     5.551348
201        Zambia          ZMB    0.292400    0.014393    20.315083
202      Zimbabwe          ZWE    0.677362    0.030957    21.880803

[203 rows x 5 columns]

In [83]:
df_rel_us.sort_values("cost_to_gdp",ascending=False,inplace=True)
df_rel_us=df_rel_us.reset_index(drop=True)
df_rel_us.tail(10)

          Country Name Country Code  ppp_rel_us  gdp_rel_us  cost_to_gdp
193     Cayman Islands          CYM    1.127586    1.139140     0.989857
194  Brunei Darussalam          BRN    0.371280    0.389440     0.953368
195        Switzerland          CHE    1.105002    1.208134     0.914635
196             Norway          NOR    0.859234    1.011652     0.849337
197            Bermuda          BMU    1.160513    1.619102     0.716763
198              Qatar          QAT    0.604836    0.888894     0.680436
199   Macao SAR, China          MAC    0.569488    0.851264     0.668991
200            Ireland          IRL    0.818115    1.250629     0.654163
201          Singapore          SGP    0.601729    1.056685     0.569449
202         Luxembourg          LUX    0.912081    1.602573     0.569135

In [92]:
df_ppp_gdp_cost=df_rel_us.copy()

In [93]:
files

['../data/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_104/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_104.csv',
 '../data/API_VC.IHR.PSRC.P5_DS2_en_csv_v2_8832/API_VC.IHR.PSRC.P5_DS2_en_csv_v2_8832.csv',
 '../data/API_EN.POP.DNST_DS2_en_csv_v2_5836/API_EN.POP.DNST_DS2_en_csv_v2_5836.csv',
 '../data/API_PA.NUS.PPPC.RF_DS2_en_csv_v2_563/API_PA.NUS.PPPC.RF_DS2_en_csv_v2_563.csv']

In [94]:
popdensity=pd.read_csv( '../data/API_EN.POP.DNST_DS2_en_csv_v2_5836/API_EN.POP.DNST_DS2_en_csv_v2_5836.csv',skiprows=3)
popdensity = popdensity.fillna(method='ffill', axis=1)
popdensity["popdensity"]=pd.to_numeric(popdensity["2024"],errors="coerce")
popdensity_df=popdensity[["Country Code","popdensity"]]
popdensity_df

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_58939/1754727131.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  popdensity = popdensity.fillna(method='ffill', axis=1)

    Country Code  popdensity
0            ABW  596.166667
1            AFE   49.297201
2            AFG   62.215541
3            AFW   54.985592
4            AGO   28.583484
..           ...         ...
261          XKX         NaN
262          YEM   72.395924
263          ZAF   51.421090
264          ZMB   27.109509
265          ZWE   41.538209

[266 rows x 2 columns]

In [96]:
df_general=pd.merge(df_ppp_gdp_cost,popdensity_df,on="Country Code")
df_general

,Country Name,Country Code,ppp_rel_us,gdp_rel_us,cost_to_gdp,popdensity
0,Burundi,BDI,0.162060,0.001794,90.341939,518.734307
1,"Yemen, Rep.",YEM,0.435717,0.005048,86.313739,72.395924
2,Central African Republic,CAF,0.408493,0.006015,67.909309,8.183311
3,Somalia,SOM,0.397925,0.007423,53.605604,28.376792
4,South Sudan,SSD,0.666367,0.012588,52.938069,17.440503
...,...,...,...,...,...,...
198,Qatar,QAT,0.604836,0.888894,0.680436,231.273542
199,"Macao SAR, China",MAC,0.569488,0.851264,0.668991,20681.818182
200,Ireland,IRL,0.818115,1.250629,0.654163,75.668980
201,Singapore,SGP,0.601729,1.056685,0.569449,7851.005571
202,Luxembourg,LUX,0.912081,1.602573,0.569135,253.685433

In [99]:
homicides_df=pd.read_csv(  '../data/API_VC.IHR.PSRC.P5_DS2_en_csv_v2_8832/API_VC.IHR.PSRC.P5_DS2_en_csv_v2_8832.csv',skiprows=3)
homicides_df = homicides_df.fillna(method='ffill', axis=1)
homicides_df["homicides"]=pd.to_numeric(homicides_df["2024"],errors="coerce")
homicides_df=homicides_df[["Country Code","homicides"]]
homicides_df.sort_values("homicides",ascending=False,inplace=True)
homicides_df

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_58939/1930281644.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  homicides_df = homicides_df.fillna(method='ffill', axis=1)

    Country Code  homicides
117          JAM  52.127272
256          VIR  49.631107
263          ZAF  41.865728
133          LCA  38.964328
97           HND  38.342747
..           ...        ...
193          PRK        NaN
213          SOM        NaN
225          SXM        NaN
229          TCD        NaN
232          TGO        NaN

[266 rows x 2 columns]