In [1]:
import pandas as pd

In [9]:
berufsschluessel=pd.read_excel("../data/ew2024_bewerb/ab2017_klassifikation_berufe.xlsx",sheet_name="Berufshauptgruppen",skiprows=4,dtype=str)
berufsschluessel

   Berufs-schlüssel                                        Bezeichnung
0               NaN                                                NaN
1                01                                            Militär
2                04                  Schüler, Auszubildende, Studenten
3                05                                Rentner, Pensionäre
4                06                        Hausfrauen, Arbeitssuchende
5                09  Ohne nähere Tätigkeitsangabe, z. B. Selbststän...
6                11            Land-, Tier- und Forstwirtschaftsberufe
7                12                      Gartenbauberufe und Floristik
8                21  Rohstoffgewinnung und -aufbereitung, Glas- und...
9                22  Kunststoffherstellung und -verarbeitung, Holzb...
10               23  Papier- und Druckberufe, technische Mediengest...
11               24  Metallerzeugung und -bearbeitung, Metallbauberufe
12               25               Maschinen- und Fahrzeugtechnikberufe
13               26           Mechatronik-, Energie- und Elektroberufe
14               27  Technische Forschungs-, Entwicklungs-, Konstru...
15               28                            Textil- und Lederberufe
16               29          Lebensmittelherstellung und -verarbeitung
17               31   Bauplanungs-, Architektur- und Vermessungsberufe
18               32                            Hoch- und Tiefbauberufe
19               33                               (Innen-)Ausbauberufe
20               34          Gebäude- und versorgungstechnische Berufe
21               41   Mathematik-, Biologie-, Chemie- und Physikberufe
22               42       Geologie-, Geografie- und Umweltschutzberufe
23               43  Informatik-, Informations- und Kommunikationst...
24               51  Verkehrs- und Logistikberufe (außer Fahrzeugfü...
25               52    Führer/innen von Fahrzeug- und Transportgeräten
26               53       Schutz-, Sicherheits- und Überwachungsberufe
27               54                                   Reinigungsberufe
28               61            Einkaufs-, Vertriebs- und Handelsberufe
29               62                                     Verkaufsberufe
30               63           Tourismus-, Hotel- und Gaststättenberufe
31               71    Berufe in Unternehmensführung und -organisation
32               72  Berufe in Finanzdienstleistungen, Rechnungswes...
33               73                     Berufe in Recht und Verwaltung
34               81                     Medizinische Gesundheitsberufe
35               82  Nichtmedizinische Gesundheits-, Körperpflege- ...
36               83  Erziehung, soziale und hauswirtschaftliche Ber...
37               84                    Lehrende und ausbildende Berufe
38               91  Sprach-, literatur-, geistes-, gesellschafts- ...
39               92  Werbung, Marketing, kaufmännische und redaktio...
40               93  Produktdesign und kunsthandwerkliche Berufe, b...
41               94              Darstellende und unterhaltende Berufe

In [25]:
data_europa=pd.read_csv("../data/ew2024_bewerb/ew2024_bewerb_uft8.csv",sep=";",skiprows=8)
data_europa

,Wahlart,Wahltag,Titel,Namenszusatz,Name,Vornamen,Künstlername,Geschlecht,Geburtsjahr,PLZ,...,GruppennameLang,Listenplatz,VerknKennzeichen,VerknGebietsart,VerknGebietsnummer,VerknGebietsname,VerknGebietLandAbk,VerknGruppenname,VerknListenplatz,VorpGewaehlt
0,EU,09.06.2024,NaN,NaN,Abada,Marika,NaN,w,1960,55127,...,Christlich Demokratische Union Deutschlands,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,EU,09.06.2024,NaN,NaN,Acar-Gökce,Cemile,NaN,w,1975,33609,...,Bündnis für Innovation & Gerechtigkeit,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,EU,09.06.2024,NaN,NaN,Adam,Benjamin,NaN,m,1992,86150,...,Sozialdemokratische Partei Deutschlands,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,EU,09.06.2024,NaN,NaN,Adelmann,Johannes,NaN,m,1985,65623,...,Partei der Humanisten,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EU,09.06.2024,NaN,NaN,Aden,Timea Virág,NaN,w,1984,24214,...,Christlich Demokratische Union Deutschlands,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1439,EU,09.06.2024,NaN,NaN,Zobel,Katharina,NaN,w,1990,10709,...,Sozialdemokratische Partei Deutschlands,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1440,EU,09.06.2024,NaN,NaN,Zöllick,Claudia,NaN,w,1980,90765,...,Freie Demokratische Partei,157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1441,EU,09.06.2024,NaN,NaN,Zöls-Biber,Ronja Maria,NaN,w,1979,94036,...,"Ökologisch-Demokratische Partei, Die Naturschu...",18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1442,EU,09.06.2024,NaN,NaN,Zwickler,Christoph Bernard,NaN,m,1963,64367,...,Klimaliste Deutschland,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1443,EU,09.06.2024,NaN,NaN,Zwilling,Saskia,NaN,w,1999,28832,...,BÜNDNIS 90/DIE GRÜNEN,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
data_europa.columns

Index(['Wahlart', 'Wahltag', 'Titel', 'Namenszusatz', 'Name', 'Vornamen',
       'Künstlername', 'Geschlecht', 'Geburtsjahr', 'PLZ', 'Wohnort', 'Staat',
       'WohnortLand', 'Geburtsort', 'Staatsangehörigkeit', 'Beruf',
       'Berufsschluessel', 'Kennzeichen', 'Gebietsart', 'Gebietsnummer',
       'Gebietsname', 'GebietLandAbk', 'Gruppenname', 'GruppennameLang',
       'Listenplatz', 'VerknKennzeichen', 'VerknGebietsart',
       'VerknGebietsnummer', 'VerknGebietsname', 'VerknGebietLandAbk',
       'VerknGruppenname', 'VerknListenplatz', 'VorpGewaehlt'],
      dtype='object')

In [26]:
EU_born_years=data_europa[["Geburtsjahr","Gruppenname"]].groupby("Gruppenname").mean().reset_index()
EU_born_years

            Gruppenname  Geburtsjahr
0                   ABG  1969.111111
1                   AfD  1975.342857
2                   BIG  1977.217391
3                   BSW  1968.350000
4   BÜNDNIS DEUTSCHLAND  1972.090909
5             Bündnis C  1962.230769
6                   CDU  1980.476684
7                   CSU  1984.075758
8                  DAVA  1976.692308
9             DIE LINKE  1981.150000
10                  DKP  1972.209302
11           Die PARTEI  1982.184834
12              FAMILIE  1977.727273
13                  FDP  1984.123711
14         FREIE WÄHLER  1976.111111
15                GRÜNE  1984.650000
16               HEIMAT  1969.400000
17           KLIMALISTE  1976.928571
18    LETZTE GENERATION  1982.750000
19     MENSCHLICHE WELT  1974.000000
20               MERA25  1985.214286
21                 MLPD  1974.277778
22                  PDV  1973.384615
23              PIRATEN  1980.000000
24                  PdF  1991.200000
25                  PdH  1995.238095
26                  SGP  1975.909091
27                  SPD  1984.989418
28     TIERSCHUTZ hier!  1977.714286
29     Tierschutzpartei  1977.500000
30            V-Partei³  1985.947368
31                 Volt  1988.370370
32             dieBasis  1963.000000
33                  ÖDP  1970.609195

In [27]:
EU_born_years.sort_values(by="Geburtsjahr")

            Gruppenname  Geburtsjahr
5             Bündnis C  1962.230769
32             dieBasis  1963.000000
3                   BSW  1968.350000
0                   ABG  1969.111111
16               HEIMAT  1969.400000
33                  ÖDP  1970.609195
4   BÜNDNIS DEUTSCHLAND  1972.090909
10                  DKP  1972.209302
22                  PDV  1973.384615
19     MENSCHLICHE WELT  1974.000000
21                 MLPD  1974.277778
1                   AfD  1975.342857
26                  SGP  1975.909091
14         FREIE WÄHLER  1976.111111
8                  DAVA  1976.692308
17           KLIMALISTE  1976.928571
2                   BIG  1977.217391
29     Tierschutzpartei  1977.500000
28     TIERSCHUTZ hier!  1977.714286
12              FAMILIE  1977.727273
23              PIRATEN  1980.000000
6                   CDU  1980.476684
9             DIE LINKE  1981.150000
11           Die PARTEI  1982.184834
18    LETZTE GENERATION  1982.750000
7                   CSU  1984.075758
13                  FDP  1984.123711
15                GRÜNE  1984.650000
27                  SPD  1984.989418
20               MERA25  1985.214286
30            V-Partei³  1985.947368
31                 Volt  1988.370370
24                  PdF  1991.200000
25                  PdH  1995.238095

In [29]:
data_bund=pd.read_csv("../data/btw2021_bewerb/btw2021_bewerb_utf8.csv",sep=";",skiprows=8)
data_bund

,Wahlart,Wahltag,Titel,Namenszusatz,Nachname,Vornamen,Künstlername,Geschlecht,Geburtsjahr,PLZ,...,GruppennameLang,Listenplatz,VerknKennzeichen,VerknGebietsart,VerknGebietsnummer,VerknGebietsname,VerknGebietLandAbk,VerknGruppenname,VerknListenplatz,VorpGewaehlt
0,BT,26.09.2021,NaN,NaN,Nicolaisen,Petra,NaN,w,1965,24997,...,Christlich Demokratische Union Deutschlands,NaN,Landesliste,Land,1.0,Schleswig-Holstein,SH,CDU,4.0,X
1,BT,26.09.2021,NaN,NaN,Brzezicha,Franziska Maria,NaN,w,1993,24896,...,Sozialdemokratische Partei Deutschlands,NaN,Landesliste,Land,1.0,Schleswig-Holstein,SH,SPD,6.0,NaN
2,BT,26.09.2021,NaN,NaN,Anastasiadis,Christoph Georgios,NaN,m,1995,24943,...,Freie Demokratische Partei,NaN,Landesliste,Land,1.0,Schleswig-Holstein,SH,FDP,6.0,NaN
3,BT,26.09.2021,NaN,NaN,Habeck,Robert,NaN,m,1969,24939,...,BÜNDNIS 90/DIE GRÜNEN,NaN,Landesliste,Land,1.0,Schleswig-Holstein,SH,GRÜNE,2.0,NaN
4,BT,26.09.2021,NaN,NaN,Petersen-Brendel,Jan,NaN,m,1968,24997,...,Alternative für Deutschland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8282,BT,26.09.2021,NaN,NaN,Beutler,Benno,NaN,m,1967,99610,...,Team Todenhöfer – Die Gerechtigkeitspartei,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8283,BT,26.09.2021,NaN,NaN,Trautmann,Sophie,NaN,w,1998,7743,...,Volt Deutschland,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8284,BT,26.09.2021,NaN,NaN,Volz,Maximilian,NaN,m,1996,99423,...,Volt Deutschland,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8285,BT,26.09.2021,NaN,NaN,Arlaud,Leah Esther,NaN,w,1997,99086,...,Volt Deutschland,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8286,BT,26.09.2021,NaN,NaN,Gödel,Michael,NaN,m,1996,7743,...,Volt Deutschland,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
Bund_born_years=data_bund[["Geburtsjahr","Gruppenname"]].groupby("Gruppenname").mean().reset_index()
Bund_born_years

     Gruppenname  Geburtsjahr
0    #KLIMAfirst  1960.000000
1    #TeamFranka  1981.000000
2            AfD  1969.693790
3             B*  1982.000000
4             BP  1972.131148
..           ...          ...
232     dieBasis  1968.337500
233          du.  1983.729730
234     sonstige  1970.000000
235          ÖDP  1973.639053
236         ÖLDP  1980.000000

[237 rows x 2 columns]

In [32]:
pd.merge(Bund_born_years,EU_born_years,on="Gruppenname",suffixes=["_Bund","_EU"])

         Gruppenname  Geburtsjahr_Bund  Geburtsjahr_EU
0                AfD       1969.693790     1975.342857
1          Bündnis C       1968.500000     1962.230769
2                CDU       1973.656160     1980.476684
3                CSU       1977.405797     1984.075758
4          DIE LINKE       1977.156701     1981.150000
5                DKP       1961.385827     1972.209302
6         Die PARTEI       1983.910663     1982.184834
7            FAMILIE       1984.000000     1977.727273
8                FDP       1977.625194     1984.123711
9       FREIE WÄHLER       1971.661765     1976.111111
10             GRÜNE       1978.785408     1984.650000
11  MENSCHLICHE WELT       1968.400000     1974.000000
12              MLPD       1962.666667     1974.277778
13           PIRATEN       1975.678947     1980.000000
14               PdF       1995.777778     1991.200000
15               SGP       1966.250000     1975.909091
16               SPD       1976.417808     1984.989418
17  Tierschutzpartei       1974.090909     1977.500000
18         V-Partei³       1981.506173     1985.947368
19              Volt       1987.694561     1988.370370
20          dieBasis       1968.337500     1963.000000
21               ÖDP       1973.639053     1970.609195