In [5]:
import pandas as pd
!pip3 install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Collecting et-xmlfile
  Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.5
WARNING: You are using pip version 21.2.4; however, version 24.2 is available.
You should consider upgrading via the '/Users/maier-borst.h/Documents/CodeRelated/HBDataviz/2024/33_SonderwegD/Wrangle/bin/python3 -m pip install --upgrade pip' command.

In [119]:
xl = pd.read_excel('../data/Fiscal timebomb.xlsx',sheet_name=None);

sheet_names=pd.DataFrame([xl]).columns
sheet_names.tolist()

['Overview',
 'Global',
 'G-20',
 'G-7',
 'Advanced Economies',
 'Emerging Markets Ex China',
 'Argentina',
 'Australia',
 'Brazil',
 'Canada',
 'Chile',
 'China',
 'Colombia',
 'France',
 'Germany',
 'India',
 'Indonesia',
 'Italy',
 'Japan',
 'Mexico',
 'New Zealand',
 'Nigeria',
 'Pakistan',
 'Peru',
 'Philippines',
 'Poland',
 'Russia',
 'Saudi Arabia',
 'South Africa',
 'South Korea',
 'Spain',
 'Sri Lanka',
 'Sweden',
 'Thailand',
 'Turkey',
 'UK',
 'US']

In [120]:
df = pd.read_excel('../data/Fiscal timebomb.xlsx',sheet_name="Germany");
overall_df=df[(df["Indicator"]=="Debt (% GDP)")&(df["Source"]=="IMF")]
overall_df=overall_df[["indicator_date","Value"]]
overall_df
for sheet in sheet_names.tolist()[1:]:
    df = pd.read_excel('../data/Fiscal timebomb.xlsx',sheet_name=sheet);
    try:
        reduced_df=df[(df["Indicator"]=="Debt (% GDP)")&(df["Source"]=="IMF")]
        reduced_df=reduced_df.reset_index(drop=True)
        reduced_df[sheet]=reduced_df["Value"]
        reduced_df=reduced_df[["indicator_date",sheet]]
        overall_df=pd.merge(overall_df,reduced_df,on="indicator_date",how="outer")
    except:
        pass
overall_df

,indicator_date,Value,Global,G-20,G-7,Advanced Economies,Emerging Markets Ex China,Argentina,Australia,Brazil,...,Saudi Arabia,South Africa,South Korea,Spain,Sri Lanka,Sweden,Thailand,Turkey,UK,US
0,1995,54.902000,NaN,NaN,NaN,NaN,NaN,NaN,31.154000,NaN,...,NaN,NaN,NaN,63.384000,NaN,68.325000,NaN,NaN,43.653000,NaN
1,1996,57.794000,NaN,NaN,NaN,NaN,NaN,NaN,29.339000,NaN,...,NaN,NaN,NaN,67.526000,NaN,68.679000,NaN,NaN,43.714000,NaN
2,1997,58.867000,NaN,NaN,NaN,NaN,NaN,NaN,25.907000,NaN,...,NaN,NaN,NaN,66.206000,NaN,67.429000,NaN,NaN,44.132000,NaN
3,1998,59.535000,NaN,NaN,NaN,NaN,NaN,NaN,23.698000,NaN,...,NaN,NaN,NaN,64.212000,NaN,65.131000,NaN,NaN,41.970000,NaN
4,1999,60.387000,NaN,NaN,NaN,NaN,NaN,NaN,22.539000,NaN,...,NaN,NaN,NaN,62.459000,NaN,60.067000,NaN,NaN,40.410000,NaN
5,2000,59.340000,NaN,NaN,NaN,NaN,NaN,NaN,19.497000,NaN,...,NaN,NaN,NaN,57.815000,NaN,50.229000,NaN,NaN,37.686000,NaN
6,2001,58.193000,NaN,NaN,NaN,NaN,NaN,NaN,17.111000,NaN,...,NaN,NaN,NaN,54.050000,NaN,51.763000,NaN,NaN,34.958000,53.146000
7,2002,59.946000,NaN,NaN,NaN,NaN,NaN,NaN,15.011000,NaN,...,NaN,NaN,NaN,51.250000,NaN,49.767000,NaN,NaN,35.435000,55.538000
8,2003,63.538000,NaN,NaN,NaN,NaN,NaN,NaN,13.182000,NaN,...,NaN,NaN,NaN,47.712000,NaN,49.271000,NaN,NaN,36.764000,58.625000
9,2004,65.201000,NaN,NaN,NaN,NaN,NaN,NaN,11.904000,NaN,...,NaN,NaN,NaN,45.366000,NaN,48.476000,NaN,NaN,39.802000,66.102000
10,2005,67.546000,NaN,NaN,NaN,NaN,NaN,NaN,10.859000,NaN,...,NaN,NaN,NaN,42.430000,NaN,48.768000,NaN,NaN,41.000000,65.450000
11,2006,66.887000,NaN,NaN,NaN,NaN,NaN,NaN,9.939000,NaN,...,NaN,NaN,NaN,39.064000,NaN,43.667000,NaN,NaN,42.058000,64.186000
12,2007,64.158000,NaN,NaN,NaN,NaN,NaN,NaN,9.666000,NaN,...,NaN,NaN,NaN,35.765000,NaN,38.977000,NaN,NaN,43.174000,64.580000
13,2008,65.682000,NaN,NaN,NaN,NaN,NaN,NaN,11.740000,NaN,...,NaN,NaN,NaN,39.712000,NaN,37.511000,NaN,NaN,50.827000,73.428000
14,2009,73.157000,NaN,NaN,NaN,NaN,NaN,NaN,16.620000,NaN,...,NaN,NaN,NaN,53.261000,NaN,40.739000,NaN,NaN,64.915000,86.595000
15,2010,81.995000,NaN,NaN,NaN,NaN,NaN,NaN,20.347000,NaN,...,NaN,NaN,NaN,60.515000,NaN,38.066000,NaN,NaN,75.860000,95.157000
16,2011,79.417000,NaN,NaN,NaN,NaN,NaN,NaN,24.041000,NaN,...,NaN,NaN,NaN,69.850000,NaN,37.149000,NaN,NaN,81.425000,99.493000
17,2012,80.745000,NaN,NaN,NaN,NaN,NaN,NaN,27.520000,NaN,...,NaN,NaN,NaN,89.983000,NaN,37.499000,NaN,NaN,84.483000,103.059000
18,2013,78.322000,NaN,NaN,NaN,NaN,NaN,NaN,30.461000,NaN,...,NaN,NaN,NaN,100.488000,NaN,40.161000,NaN,NaN,85.316000,104.335000
19,2014,75.279000,NaN,NaN,NaN,NaN,NaN,NaN,34.021000,NaN,...,NaN,NaN,NaN,105.059000,NaN,44.872000,NaN,NaN,87.094000,104.228000
20,2015,71.947000,NaN,NaN,NaN,NaN,NaN,NaN,37.708000,NaN,...,NaN,NaN,NaN,103.299000,NaN,43.739000,NaN,NaN,87.867000,104.646000
21,2016,68.955000,NaN,NaN,NaN,NaN,NaN,NaN,40.582000,NaN,...,NaN,NaN,NaN,102.749000,NaN,42.255000,NaN,NaN,87.825000,106.563000
22,2017,65.204000,NaN,NaN,NaN,NaN,NaN,NaN,41.151000,NaN,...,NaN,NaN,NaN,101.800000,NaN,40.730000,NaN,NaN,86.723000,105.512000
23,2018,61.914000,NaN,NaN,NaN,NaN,NaN,NaN,41.702000,NaN,...,NaN,NaN,NaN,100.415000,NaN,39.193000,NaN,NaN,86.345000,106.828000
24,2019,59.580000,NaN,NaN,NaN,NaN,NaN,NaN,46.656000,NaN,...,NaN,NaN,NaN,98.221000,NaN,35.581000,NaN,NaN,85.658000,108.074000
25,2020,68.773000,NaN,NaN,NaN,NaN,NaN,NaN,57.004000,NaN,...,NaN,NaN,NaN,120.266000,NaN,39.942000,NaN,NaN,105.800000,131.991000
26,2021,68.986000,NaN,NaN,NaN,NaN,NaN,NaN,55.484000,NaN,...,NaN,NaN,NaN,116.841000,NaN,36.476000,NaN,NaN,105.196000,124.956000
27,2022,66.077000,NaN,NaN,NaN,NaN,NaN,NaN,50.108000,NaN,...,NaN,NaN,NaN,111.618000,NaN,32.940000,NaN,NaN,100.432000,120.026000
28,2023,64.151922,NaN,NaN,NaN,NaN,NaN,NaN,49.380759,NaN,...,NaN,NaN,NaN,107.458566,NaN,35.789465,NaN,NaN,101.140574,122.134255
29,2024,63.538584,NaN,NaN,NaN,NaN,NaN,NaN,49.559497,NaN,...,NaN,NaN,NaN,104.748675,NaN,36.148560,NaN,NaN,103.218018,122.462388
30,2025,62.154674,NaN,NaN,NaN,NaN,NaN,NaN,48.936922,NaN,...,NaN,NaN,NaN,103.291955,NaN,35.630055,NaN,NaN,104.719736,124.867667
31,2026,61.183499,NaN,NaN,NaN,NaN,NaN,NaN,48.262497,NaN,...,NaN,NaN,NaN,102.471763,NaN,34.833875,NaN,NaN,105.031467,126.590178
32,2027,60.353782,NaN,NaN,NaN,NaN,NaN,NaN,46.583299,NaN,...,NaN,NaN,NaN,102.083179,NaN,34.381538,NaN,NaN,105.401315,128.268075
33,2028,59.433956,NaN,NaN,NaN,NaN,NaN,NaN,44.400726,NaN,...,NaN,NaN,NaN,101.590876,NaN,34.142464,NaN,NaN,105.622249,130.408182
34,2029,58.582320,NaN,NaN,NaN,NaN,NaN,NaN,42.206079,NaN,...,NaN,NaN,NaN,101.080061,NaN,33.843104,NaN,NaN,105.780245,133.007962
35,2030,57.712138,NaN,NaN,NaN,NaN,NaN,NaN,40.114570,NaN,...,NaN,NaN,NaN,100.852657,NaN,32.909984,NaN,NaN,106.798335,134.994588
36,2031,56.835519,NaN,NaN,NaN,NaN,NaN,NaN,38.124996,NaN,...,NaN,NaN,NaN,100.985856,NaN,32.035210,NaN,NaN,107.888549,137.333933
37,2032,55.937430,NaN,NaN,NaN,NaN,NaN,NaN,36.269754,NaN,...,NaN,NaN,NaN,101.352061,NaN,31.215753,NaN,NaN,109.002976,140.104552
38,2033,55.017952,NaN,NaN,NaN,NaN,NaN,NaN,34.484649,NaN,...,NaN,NaN,NaN,101.899787,NaN,30.438425,NaN,NaN,110.213746,143.261125
39,2034,54.173372,NaN,NaN,NaN,NaN,NaN,NaN,32.743942,NaN,...,NaN,NaN,NaN,102.626523,NaN,29.701731,NaN,NaN,111.505726,146.710553
40,2035,53.391282,NaN,NaN,NaN,NaN,NaN,NaN,31.046248,NaN,...,NaN,NaN,NaN,103.488872,NaN,29.002724,NaN,NaN,112.880138,150.379673
41,2036,52.629489,NaN,NaN,NaN,NaN,NaN,NaN,29.380596,NaN,...,NaN,NaN,NaN,104.519495,NaN,28.337937,NaN,NaN,114.310525,154.216722
42,2037,51.873875,NaN,NaN,NaN,NaN,NaN,NaN,27.741182,NaN,...,NaN,NaN,NaN,105.672604,NaN,27.705973,NaN,NaN,115.798638,158.218854
43,2038,51.129111,NaN,NaN,NaN,NaN,NaN,NaN,26.126688,NaN,...,NaN,NaN,NaN,106.956080,NaN,27.103656,NaN,NaN,117.354758,162.385579
44,2039,50.387208,NaN,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,...,NaN,NaN,NaN,108.337179,NaN,26.530992,NaN,NaN,118.944513,166.670318
45,2040,49.620003,NaN,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,...,NaN,NaN,NaN,109.807463,NaN,25.987256,NaN,NaN,120.555215,171.054364
46,2041,48.843335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,111.386169,NaN,NaN,NaN,NaN,122.168532,175.531046
47,2042,48.063283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,113.026055,NaN,NaN,NaN,NaN,123.799065,180.064108
48,2043,47.283454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,114.729609,NaN,NaN,NaN,NaN,125.441411,184.619070
49,2044,46.506048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,116.478233,NaN,NaN,NaN,NaN,127.093926,189.224355
50,2045,45.728758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,118.245674,NaN,NaN,NaN,NaN,128.746483,193.791484
51,2046,44.965672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,120.036456,NaN,NaN,NaN,NaN,130.396508,198.368176
52,2047,44.214428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,121.834282,NaN,NaN,NaN,NaN,132.037975,202.928527
53,2048,43.469122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,123.640115,NaN,NaN,NaN,NaN,133.674180,207.476826
54,2049,42.749856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,125.452338,NaN,NaN,NaN,NaN,135.308286,211.999625
55,2050,42.054036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,127.268447,NaN,NaN,NaN,NaN,136.928794,216.525989

In [121]:
span_20_years=overall_df[(overall_df["indicator_date"]<2035)&(overall_df["indicator_date"]>2014)]
span_20_years

,indicator_date,Value,Global,G-20,G-7,Advanced Economies,Emerging Markets Ex China,Argentina,Australia,Brazil,...,Saudi Arabia,South Africa,South Korea,Spain,Sri Lanka,Sweden,Thailand,Turkey,UK,US
20,2015,71.947000,NaN,NaN,NaN,NaN,NaN,NaN,37.708000,NaN,...,NaN,NaN,NaN,103.299000,NaN,43.739000,NaN,NaN,87.867000,104.646000
21,2016,68.955000,NaN,NaN,NaN,NaN,NaN,NaN,40.582000,NaN,...,NaN,NaN,NaN,102.749000,NaN,42.255000,NaN,NaN,87.825000,106.563000
22,2017,65.204000,NaN,NaN,NaN,NaN,NaN,NaN,41.151000,NaN,...,NaN,NaN,NaN,101.800000,NaN,40.730000,NaN,NaN,86.723000,105.512000
23,2018,61.914000,NaN,NaN,NaN,NaN,NaN,NaN,41.702000,NaN,...,NaN,NaN,NaN,100.415000,NaN,39.193000,NaN,NaN,86.345000,106.828000
24,2019,59.580000,NaN,NaN,NaN,NaN,NaN,NaN,46.656000,NaN,...,NaN,NaN,NaN,98.221000,NaN,35.581000,NaN,NaN,85.658000,108.074000
25,2020,68.773000,NaN,NaN,NaN,NaN,NaN,NaN,57.004000,NaN,...,NaN,NaN,NaN,120.266000,NaN,39.942000,NaN,NaN,105.800000,131.991000
26,2021,68.986000,NaN,NaN,NaN,NaN,NaN,NaN,55.484000,NaN,...,NaN,NaN,NaN,116.841000,NaN,36.476000,NaN,NaN,105.196000,124.956000
27,2022,66.077000,NaN,NaN,NaN,NaN,NaN,NaN,50.108000,NaN,...,NaN,NaN,NaN,111.618000,NaN,32.940000,NaN,NaN,100.432000,120.026000
28,2023,64.151922,NaN,NaN,NaN,NaN,NaN,NaN,49.380759,NaN,...,NaN,NaN,NaN,107.458566,NaN,35.789465,NaN,NaN,101.140574,122.134255
29,2024,63.538584,NaN,NaN,NaN,NaN,NaN,NaN,49.559497,NaN,...,NaN,NaN,NaN,104.748675,NaN,36.148560,NaN,NaN,103.218018,122.462388
30,2025,62.154674,NaN,NaN,NaN,NaN,NaN,NaN,48.936922,NaN,...,NaN,NaN,NaN,103.291955,NaN,35.630055,NaN,NaN,104.719736,124.867667
31,2026,61.183499,NaN,NaN,NaN,NaN,NaN,NaN,48.262497,NaN,...,NaN,NaN,NaN,102.471763,NaN,34.833875,NaN,NaN,105.031467,126.590178
32,2027,60.353782,NaN,NaN,NaN,NaN,NaN,NaN,46.583299,NaN,...,NaN,NaN,NaN,102.083179,NaN,34.381538,NaN,NaN,105.401315,128.268075
33,2028,59.433956,NaN,NaN,NaN,NaN,NaN,NaN,44.400726,NaN,...,NaN,NaN,NaN,101.590876,NaN,34.142464,NaN,NaN,105.622249,130.408182
34,2029,58.582320,NaN,NaN,NaN,NaN,NaN,NaN,42.206079,NaN,...,NaN,NaN,NaN,101.080061,NaN,33.843104,NaN,NaN,105.780245,133.007962
35,2030,57.712138,NaN,NaN,NaN,NaN,NaN,NaN,40.114570,NaN,...,NaN,NaN,NaN,100.852657,NaN,32.909984,NaN,NaN,106.798335,134.994588
36,2031,56.835519,NaN,NaN,NaN,NaN,NaN,NaN,38.124996,NaN,...,NaN,NaN,NaN,100.985856,NaN,32.035210,NaN,NaN,107.888549,137.333933
37,2032,55.937430,NaN,NaN,NaN,NaN,NaN,NaN,36.269754,NaN,...,NaN,NaN,NaN,101.352061,NaN,31.215753,NaN,NaN,109.002976,140.104552
38,2033,55.017952,NaN,NaN,NaN,NaN,NaN,NaN,34.484649,NaN,...,NaN,NaN,NaN,101.899787,NaN,30.438425,NaN,NaN,110.213746,143.261125
39,2034,54.173372,NaN,NaN,NaN,NaN,NaN,NaN,32.743942,NaN,...,NaN,NaN,NaN,102.626523,NaN,29.701731,NaN,NaN,111.505726,146.710553

In [122]:
span_20_years=span_20_years.dropna(axis=1)
span_20_years

,indicator_date,Value,Australia,Canada,France,Germany,Italy,Japan,New Zealand,Spain,Sweden,UK,US
20,2015,71.947000,37.708000,92.029000,95.582000,71.947000,135.283000,228.278000,34.192000,103.299000,43.739000,87.867000,104.646000
21,2016,68.955000,40.582000,92.397000,97.958000,68.955000,134.787000,232.421000,33.373000,102.749000,42.255000,87.825000,106.563000
22,2017,65.204000,41.151000,90.942000,98.131000,65.204000,134.167000,231.321000,31.127000,101.800000,40.730000,86.723000,105.512000
23,2018,61.914000,41.702000,90.776000,97.783000,61.914000,134.450000,232.380000,28.100000,100.415000,39.193000,86.345000,106.828000
24,2019,59.580000,46.656000,90.210000,97.426000,59.580000,134.157000,236.378000,31.849000,98.221000,35.581000,85.658000,108.074000
25,2020,68.773000,57.004000,118.200000,114.650000,68.773000,154.917000,258.297000,43.300000,120.266000,39.942000,105.800000,131.991000
26,2021,68.986000,55.484000,113.483000,112.968000,68.986000,147.091000,253.919000,47.531000,116.841000,36.476000,105.196000,124.956000
27,2022,66.077000,50.108000,107.368000,111.788000,66.077000,140.487000,257.194000,47.184000,111.618000,32.940000,100.432000,120.026000
28,2023,64.151922,49.380759,107.128962,110.634936,64.151922,137.148462,252.389615,45.905948,107.458566,35.789465,101.140574,122.134255
29,2024,63.538584,49.559497,105.168120,111.317106,63.538584,138.748984,253.986803,47.332830,104.748675,36.148560,103.218018,122.462388
30,2025,62.154674,48.936922,103.452006,112.037942,62.154674,139.178614,251.812357,48.422051,103.291955,35.630055,104.719736,124.867667
31,2026,61.183499,48.262497,101.729578,112.690153,61.183499,140.411638,252.453271,48.678747,102.471763,34.833875,105.031467,126.590178
32,2027,60.353782,46.583299,100.119101,113.488767,60.353782,140.507743,253.643610,48.460259,102.083179,34.381538,105.401315,128.268075
33,2028,59.433956,44.400726,98.182100,114.208108,59.433956,142.572476,254.410794,47.099277,101.590876,34.142464,105.622249,130.408182
34,2029,58.582320,42.206079,96.288696,114.979932,58.582320,143.729767,254.917950,44.932390,101.080061,33.843104,105.780245,133.007962
35,2030,57.712138,40.114570,93.174455,115.947914,57.712138,143.767469,255.653204,42.793605,100.852657,32.909984,106.798335,134.994588
36,2031,56.835519,38.124996,90.174995,117.163241,56.835519,144.129539,256.245902,40.712810,100.985856,32.035210,107.888549,137.333933
37,2032,55.937430,36.269754,87.185278,118.575517,55.937430,144.786665,257.700582,38.671524,101.352061,31.215753,109.002976,140.104552
38,2033,55.017952,34.484649,84.377035,120.199387,55.017952,145.664800,259.267242,36.659963,101.899787,30.438425,110.213746,143.261125
39,2034,54.173372,32.743942,81.653235,121.991350,54.173372,146.756941,261.447512,34.700419,102.626523,29.701731,111.505726,146.710553

In [123]:
df = pd.read_excel('../data/Fiscal timebomb.xlsx',sheet_name="China");
df.Source.unique()

array(['Bloomberg Economics'], dtype=object)

In [124]:
df = pd.read_excel('../data/Fiscal timebomb.xlsx',sheet_name="Germany");
overall_df_bloomberg=df[(df["Indicator"]=="Debt (% GDP)")&(df["Source"]=="Bloomberg Economics")]
overall_df_bloomberg=overall_df_bloomberg[["indicator_date","Value"]]
overall_df_bloomberg
for sheet in sheet_names.tolist()[1:]:
    df = pd.read_excel('../data/Fiscal timebomb.xlsx',sheet_name=sheet);
    try:
        reduced_df=df[(df["Indicator"]=="Debt (% GDP)")&(df["Source"]=="Bloomberg Economics")]
        reduced_df=reduced_df.reset_index(drop=True)
        reduced_df[sheet]=reduced_df["Value"]
        reduced_df=reduced_df[["indicator_date",sheet]]
        overall_df_bloomberg=pd.merge(overall_df_bloomberg,reduced_df,on="indicator_date",how="outer")
    except:
        pass
overall_df_bloomberg

,indicator_date,Value,Global,G-20,G-7,Advanced Economies,Emerging Markets Ex China,Argentina,Australia,Brazil,...,Saudi Arabia,South Africa,South Korea,Spain,Sri Lanka,Sweden,Thailand,Turkey,UK,US
0,1995,NaN,NaN,NaN,NaN,NaN,NaN,30.748700,NaN,NaN,...,NaN,43.663509,8.779648,NaN,77.807153,NaN,NaN,NaN,NaN,NaN
1,1996,NaN,NaN,NaN,NaN,NaN,NaN,32.552255,NaN,NaN,...,NaN,43.198917,8.079735,NaN,76.227921,NaN,NaN,NaN,NaN,NaN
2,1997,NaN,NaN,NaN,NaN,NaN,NaN,31.676032,NaN,NaN,...,NaN,42.801002,10.024793,NaN,70.146431,NaN,NaN,NaN,NaN,NaN
3,1998,NaN,NaN,NaN,NaN,NaN,NaN,34.146123,NaN,NaN,...,NaN,42.724037,14.320562,NaN,74.242680,NaN,NaN,NaN,NaN,NaN
4,1999,NaN,NaN,NaN,NaN,NaN,NaN,38.917981,NaN,NaN,...,NaN,40.725297,16.335104,NaN,77.695008,NaN,NaN,NaN,NaN,NaN
5,2000,NaN,80.580563,81.996387,94.395288,86.256043,41.023560,40.832704,NaN,NaN,...,NaN,37.996848,16.681988,NaN,79.202194,NaN,57.825919,NaN,NaN,NaN
6,2001,NaN,69.024688,69.664814,74.914939,71.763811,38.888571,48.006125,NaN,NaN,...,NaN,38.104877,17.229427,NaN,84.364238,NaN,57.469036,NaN,NaN,NaN
7,2002,NaN,70.338016,71.283246,76.667829,72.930477,42.342854,147.200206,NaN,NaN,...,NaN,31.840697,17.041285,NaN,96.301099,NaN,54.901917,NaN,NaN,NaN
8,2003,NaN,72.297173,73.403074,79.779678,75.329253,45.865457,125.163578,NaN,NaN,...,81.563859,31.551261,19.803192,NaN,86.450245,NaN,47.500989,65.160853,NaN,NaN
9,2004,NaN,75.329928,76.744356,84.993561,79.693593,40.457529,117.875989,NaN,NaN,...,62.928227,30.761364,22.421644,NaN,86.499129,NaN,46.266040,57.158789,NaN,NaN
10,2005,NaN,73.678846,75.240078,85.028421,79.355129,33.002448,80.281182,NaN,NaN,...,37.343289,29.636908,25.899271,NaN,76.589182,NaN,45.461960,50.195508,NaN,NaN
11,2006,NaN,70.097346,71.850789,82.547055,76.774431,28.055683,70.793407,NaN,NaN,...,25.830860,28.030366,28.120781,NaN,74.289437,NaN,39.177015,44.224389,NaN,NaN
12,2007,NaN,67.143411,68.941646,80.856435,74.601691,32.662179,62.132935,NaN,63.025226,...,17.114759,24.326167,27.430753,NaN,71.848781,NaN,35.985038,37.758953,NaN,NaN
13,2008,NaN,68.796062,70.492978,88.771424,81.849261,31.066960,53.813769,NaN,61.420027,...,12.055981,24.044754,26.948670,NaN,68.782353,NaN,34.946991,37.747816,NaN,NaN
14,2009,NaN,79.430033,81.488993,103.703863,96.200560,41.166399,55.397338,NaN,64.701894,...,13.989100,26.994557,29.983796,NaN,72.750063,NaN,42.364011,43.211741,NaN,NaN
15,2010,NaN,81.908536,84.236928,111.842496,103.040831,39.733910,43.453771,NaN,62.432930,...,8.426016,31.185590,29.489959,NaN,68.730721,NaN,39.830961,39.510645,NaN,NaN
16,2011,NaN,83.464300,85.958827,116.775166,107.459915,38.522249,38.934934,NaN,60.634131,...,5.340154,34.741888,33.061250,NaN,69.427966,NaN,39.115992,35.912110,NaN,NaN
17,2012,NaN,84.442906,87.313058,120.848812,111.955585,37.258110,40.436179,NaN,61.614078,...,3.011927,37.407855,35.038956,NaN,67.503921,NaN,41.929978,32.226775,NaN,NaN
18,2013,NaN,82.825637,85.502297,118.472932,110.297588,37.729495,43.495973,NaN,59.595020,...,2.126997,40.355888,37.686088,NaN,69.456924,NaN,42.190031,30.891781,NaN,NaN
19,2014,NaN,84.344579,87.060043,117.293465,109.748947,40.291754,44.697090,NaN,61.617076,...,1.540993,43.253416,39.707500,NaN,69.560505,NaN,43.334996,28.276802,NaN,NaN
20,2015,NaN,84.687118,87.117609,116.268344,109.314883,43.620791,52.563015,NaN,71.729997,...,5.668036,45.195542,40.783575,NaN,76.333774,NaN,42.559017,27.163177,NaN,NaN
21,2016,NaN,86.525194,89.027627,119.359875,112.133871,46.466482,53.059979,NaN,77.421989,...,12.675876,47.133979,41.217165,NaN,75.000332,NaN,41.745018,27.746939,NaN,NaN
22,2017,NaN,83.649825,86.062847,117.218705,109.876793,47.639265,57.028038,NaN,82.744918,...,16.531965,48.588178,40.050156,NaN,72.260296,NaN,41.777985,27.777069,NaN,NaN
23,2018,NaN,84.343768,86.736031,117.059174,109.743923,48.696384,85.245995,NaN,84.777003,...,17.638888,51.536306,40.022282,NaN,83.584996,NaN,41.940985,29.860123,NaN,NaN
24,2019,NaN,85.205656,87.656743,118.017617,111.044352,50.093702,89.839988,NaN,87.117969,...,21.560066,56.101372,42.125269,NaN,82.594033,NaN,41.063001,32.390031,NaN,NaN
25,2020,NaN,100.186843,103.039839,139.583725,131.401905,59.111169,103.816013,NaN,96.007017,...,31.001046,68.862620,48.698266,NaN,96.881106,NaN,49.420003,39.446021,NaN,NaN
26,2021,NaN,95.345084,97.752292,132.765129,124.961907,56.628365,80.819993,NaN,88.934038,...,28.616054,68.797463,51.254724,NaN,102.668636,NaN,58.337004,40.384006,NaN,NaN
27,2022,NaN,92.360778,94.464736,126.710716,119.683257,53.650040,84.684999,NaN,83.938974,...,23.932983,71.120683,53.803334,NaN,129.315577,NaN,60.522027,30.802010,NaN,NaN
28,2023,NaN,94.130162,96.429906,126.119004,119.339189,56.003703,154.535998,NaN,84.674989,...,26.226945,73.929580,55.819754,NaN,112.674238,NaN,62.439980,28.881985,NaN,NaN
29,2024,NaN,94.797278,97.168850,125.861576,119.167619,54.896055,72.616726,NaN,87.875864,...,27.518107,75.438561,57.332484,NaN,103.901855,NaN,62.521305,22.082786,NaN,NaN
30,2025,NaN,95.727595,98.101774,127.174536,120.240809,54.807971,71.419370,NaN,90.649571,...,27.616903,77.856227,59.101913,NaN,102.260387,NaN,61.851480,20.112288,NaN,NaN
31,2026,NaN,96.559268,98.959571,128.168944,121.100709,54.974279,71.847501,NaN,93.281959,...,28.354093,79.979429,60.585598,NaN,99.713542,NaN,60.641661,20.729155,NaN,NaN
32,2027,NaN,97.342422,99.783899,129.138337,121.902153,55.221270,72.224333,NaN,95.372576,...,29.537000,81.899812,62.055901,NaN,96.976357,NaN,59.500770,22.087540,NaN,NaN
33,2028,NaN,98.154265,100.632226,130.524047,123.035112,55.228977,72.546652,NaN,96.947710,...,30.735922,83.810456,63.466968,NaN,91.629297,NaN,58.460417,23.307943,NaN,NaN
34,2029,NaN,98.820424,101.340575,132.041541,124.257838,54.970299,72.811252,NaN,98.330642,...,31.467997,85.728196,65.149844,NaN,90.568218,NaN,57.468256,22.753928,NaN,NaN
35,2030,NaN,99.194942,101.747715,133.062892,125.042274,54.761996,73.087758,NaN,99.764467,...,33.888072,83.499987,67.009280,NaN,89.718924,NaN,56.539400,22.687713,NaN,NaN
36,2031,NaN,99.710877,102.305328,134.343412,126.069956,54.482644,73.376707,NaN,100.751342,...,36.329468,80.999955,68.897728,NaN,89.020759,NaN,55.648235,22.650855,NaN,NaN
37,2032,NaN,100.355907,102.997895,135.957709,127.402518,54.142042,73.678659,NaN,101.368338,...,38.792600,78.500023,70.751676,NaN,88.800456,NaN,54.832801,22.641497,NaN,NaN
38,2033,NaN,101.062254,103.755484,137.867796,129.002651,53.832976,73.994199,NaN,102.196812,...,41.277333,76.000022,72.679442,NaN,88.373691,NaN,54.056461,22.657915,NaN,NaN
39,2034,NaN,101.871239,104.621471,140.032897,130.832519,53.533493,74.323938,NaN,103.057076,...,43.783924,73.499977,74.689359,NaN,87.944268,NaN,53.357871,22.698546,NaN,NaN
40,2035,NaN,102.762913,105.574938,142.382324,132.829411,53.297363,74.742839,NaN,103.950435,...,46.312773,72.893455,76.787171,NaN,87.511507,NaN,52.679178,22.761933,NaN,NaN
41,2036,NaN,103.710967,106.588205,144.886739,134.964997,53.096420,75.181009,NaN,104.974775,...,48.863947,72.393460,78.942758,NaN,87.073086,NaN,52.050906,22.846755,NaN,NaN
42,2037,NaN,104.755537,107.705515,147.543575,137.235089,52.956650,75.639336,NaN,106.039066,...,51.437555,72.686717,81.157123,NaN,86.627388,NaN,51.447662,22.951788,NaN,NaN
43,2038,NaN,105.820119,108.844717,150.346097,139.633953,52.876460,76.194385,NaN,107.243732,...,54.033879,73.236679,83.429475,NaN,85.974733,NaN,50.911511,23.075921,NaN,NaN
44,2039,NaN,106.949211,110.052131,153.257703,142.149996,52.865957,76.775521,NaN,108.496240,...,56.653189,73.800503,85.758631,NaN,85.910553,NaN,50.397975,23.218126,NaN,NaN
45,2040,NaN,108.154998,111.336835,156.262917,144.804982,52.921363,77.460746,NaN,109.798693,...,59.295556,74.486511,88.167667,NaN,85.855340,NaN,49.908841,23.377469,NaN,NaN
46,2041,NaN,109.384547,112.647120,159.325455,147.511779,52.967277,78.178861,NaN,110.153271,...,61.961293,74.931691,90.559425,NaN,85.715834,NaN,49.441233,23.553098,NaN,NaN
47,2042,NaN,110.727252,114.080805,162.461236,150.279477,53.080902,79.009626,NaN,110.521028,...,64.650579,75.112965,92.934073,NaN,85.598437,NaN,49.041540,23.744227,NaN,NaN
48,2043,NaN,111.990423,115.429103,165.617488,153.071017,53.274963,79.881097,NaN,111.005971,...,67.363473,75.079786,95.484071,NaN,85.410825,NaN,48.663779,23.950146,NaN,NaN
49,2044,NaN,113.301652,116.831220,168.815890,155.903452,53.535328,80.795271,NaN,111.509405,...,70.100414,74.839213,98.212190,NaN,85.258814,NaN,48.293361,24.170206,NaN,NaN
50,2045,NaN,114.661611,118.287474,172.011662,158.736187,53.842057,81.835035,NaN,112.136448,...,72.861554,74.393450,101.121929,NaN,85.148662,NaN,47.904839,24.403818,NaN,NaN
51,2046,NaN,116.097923,119.828536,175.216983,161.581504,54.203429,82.926786,NaN,112.787938,...,75.646990,73.893445,104.218659,NaN,84.985858,NaN,47.516533,24.650446,NaN,NaN
52,2047,NaN,117.587867,121.431554,178.421381,164.429369,54.612823,84.073126,NaN,113.464991,...,78.457130,73.393453,107.508409,NaN,84.873717,NaN,47.085463,24.909605,NaN,NaN
53,2048,NaN,119.154701,123.118659,181.616832,167.272973,55.081220,85.276782,NaN,114.275127,...,81.291891,73.052112,110.997018,NaN,84.816178,NaN,46.591943,25.180857,NaN,NaN
54,2049,NaN,120.690040,124.774620,184.807705,170.115355,55.586756,86.625898,NaN,115.117855,...,84.151819,72.712358,114.686371,NaN,84.716384,NaN,46.016897,25.463805,NaN,NaN
55,2050,NaN,122.275491,126.488263,188.010184,172.968396,56.130701,88.043819,NaN,115.994719,...,87.036956,72.374185,118.582389,NaN,84.674704,NaN,45.380505,25.758096,NaN,NaN

In [125]:
span_20_years_bloomberg=overall_df_bloomberg[(overall_df_bloomberg["indicator_date"]<2035)&(overall_df_bloomberg["indicator_date"]>2014)]
span_20_years_bloomberg=span_20_years_bloomberg.dropna(axis=1)

In [126]:
imf_data=span_20_years[span_20_years.columns[span_20_years.columns!="Value"]]
imf_data

,indicator_date,Australia,Canada,France,Germany,Italy,Japan,New Zealand,Spain,Sweden,UK,US
20,2015,37.708000,92.029000,95.582000,71.947000,135.283000,228.278000,34.192000,103.299000,43.739000,87.867000,104.646000
21,2016,40.582000,92.397000,97.958000,68.955000,134.787000,232.421000,33.373000,102.749000,42.255000,87.825000,106.563000
22,2017,41.151000,90.942000,98.131000,65.204000,134.167000,231.321000,31.127000,101.800000,40.730000,86.723000,105.512000
23,2018,41.702000,90.776000,97.783000,61.914000,134.450000,232.380000,28.100000,100.415000,39.193000,86.345000,106.828000
24,2019,46.656000,90.210000,97.426000,59.580000,134.157000,236.378000,31.849000,98.221000,35.581000,85.658000,108.074000
25,2020,57.004000,118.200000,114.650000,68.773000,154.917000,258.297000,43.300000,120.266000,39.942000,105.800000,131.991000
26,2021,55.484000,113.483000,112.968000,68.986000,147.091000,253.919000,47.531000,116.841000,36.476000,105.196000,124.956000
27,2022,50.108000,107.368000,111.788000,66.077000,140.487000,257.194000,47.184000,111.618000,32.940000,100.432000,120.026000
28,2023,49.380759,107.128962,110.634936,64.151922,137.148462,252.389615,45.905948,107.458566,35.789465,101.140574,122.134255
29,2024,49.559497,105.168120,111.317106,63.538584,138.748984,253.986803,47.332830,104.748675,36.148560,103.218018,122.462388
30,2025,48.936922,103.452006,112.037942,62.154674,139.178614,251.812357,48.422051,103.291955,35.630055,104.719736,124.867667
31,2026,48.262497,101.729578,112.690153,61.183499,140.411638,252.453271,48.678747,102.471763,34.833875,105.031467,126.590178
32,2027,46.583299,100.119101,113.488767,60.353782,140.507743,253.643610,48.460259,102.083179,34.381538,105.401315,128.268075
33,2028,44.400726,98.182100,114.208108,59.433956,142.572476,254.410794,47.099277,101.590876,34.142464,105.622249,130.408182
34,2029,42.206079,96.288696,114.979932,58.582320,143.729767,254.917950,44.932390,101.080061,33.843104,105.780245,133.007962
35,2030,40.114570,93.174455,115.947914,57.712138,143.767469,255.653204,42.793605,100.852657,32.909984,106.798335,134.994588
36,2031,38.124996,90.174995,117.163241,56.835519,144.129539,256.245902,40.712810,100.985856,32.035210,107.888549,137.333933
37,2032,36.269754,87.185278,118.575517,55.937430,144.786665,257.700582,38.671524,101.352061,31.215753,109.002976,140.104552
38,2033,34.484649,84.377035,120.199387,55.017952,145.664800,259.267242,36.659963,101.899787,30.438425,110.213746,143.261125
39,2034,32.743942,81.653235,121.991350,54.173372,146.756941,261.447512,34.700419,102.626523,29.701731,111.505726,146.710553

In [127]:
additions_from_bloomberg=[]
for entry in span_20_years_bloomberg:
    if(entry not in(imf_data.columns.tolist())):
        additions_from_bloomberg.append(entry)

In [128]:
span_20_years_bloomberg_addition=span_20_years_bloomberg[additions_from_bloomberg]

In [131]:
imf_bloomberg=pd.concat([imf_data,span_20_years_bloomberg_addition],axis=1)
imf_bloomberg=imf_bloomberg.reset_index(drop=True)
imf_bloomberg

,indicator_date,Australia,Canada,France,Germany,Italy,Japan,New Zealand,Spain,Sweden,...,Peru,Philippines,Poland,Russia,Saudi Arabia,South Africa,South Korea,Sri Lanka,Thailand,Turkey
0,2015,37.708000,92.029000,95.582000,71.947000,135.283000,228.278000,34.192000,103.299000,43.739000,...,23.692135,39.688013,46.403332,12.987374,5.668036,45.195542,40.783575,76.333774,42.559017,27.163177
1,2016,40.582000,92.397000,97.958000,68.955000,134.787000,232.421000,33.373000,102.749000,42.255000,...,24.443003,37.376011,50.111699,13.067525,12.675876,47.133979,41.217165,75.000332,41.745018,27.746939
2,2017,41.151000,90.942000,98.131000,65.204000,134.167000,231.321000,31.127000,101.800000,40.730000,...,25.134086,38.129996,46.826442,12.640050,16.531965,48.588178,40.050156,72.260296,41.777985,27.777069
3,2018,41.702000,90.776000,97.783000,61.914000,134.450000,232.380000,28.100000,100.415000,39.193000,...,26.007737,37.146999,44.874936,12.020441,17.638888,51.536306,40.022282,83.584996,41.940985,29.860123
4,2019,46.656000,90.210000,97.426000,59.580000,134.157000,236.378000,31.849000,98.221000,35.581000,...,26.771044,36.973008,42.531975,12.429571,21.560066,56.101372,42.125269,82.594033,41.063001,32.390031
5,2020,57.004000,118.200000,114.650000,68.773000,154.917000,258.297000,43.300000,120.266000,39.942000,...,35.298045,51.643978,46.947602,17.602303,31.001046,68.862620,48.698266,96.881106,49.420003,39.446021
6,2021,55.484000,113.483000,112.968000,68.986000,147.091000,253.919000,47.531000,116.841000,36.476000,...,36.213256,57.004980,43.249724,15.384017,28.616054,68.797463,51.254724,102.668636,58.337004,40.384006
7,2022,50.108000,107.368000,111.788000,66.077000,140.487000,257.194000,47.184000,111.618000,32.940000,...,34.083336,57.398981,40.278067,14.519504,23.932983,71.120683,53.803334,129.315577,60.522027,30.802010
8,2023,49.380759,107.128962,110.634936,64.151922,137.148462,252.389615,45.905948,107.458566,35.789465,...,32.982652,56.607010,39.476385,14.901288,26.226945,73.929580,55.819754,112.674238,62.439980,28.881985
9,2024,49.559497,105.168120,111.317106,63.538584,138.748984,253.986803,47.332830,104.748675,36.148560,...,33.845892,57.541122,38.207928,13.734128,27.518107,75.438561,57.332484,103.901855,62.521305,22.082786
10,2025,48.936922,103.452006,112.037942,62.154674,139.178614,251.812357,48.422051,103.291955,35.630055,...,34.120509,57.932259,40.951905,14.017885,27.616903,77.856227,59.101913,102.260387,61.851480,20.112288
11,2026,48.262497,101.729578,112.690153,61.183499,140.411638,252.453271,48.678747,102.471763,34.833875,...,33.871587,58.562782,43.559251,14.408321,28.354093,79.979429,60.585598,99.713542,60.641661,20.729155
12,2027,46.583299,100.119101,113.488767,60.353782,140.507743,253.643610,48.460259,102.083179,34.381538,...,33.712514,58.349260,45.956553,14.895526,29.537000,81.899812,62.055901,96.976357,59.500770,22.087540
13,2028,44.400726,98.182100,114.208108,59.433956,142.572476,254.410794,47.099277,101.590876,34.142464,...,33.675571,57.336304,48.129722,15.446611,30.735922,83.810456,63.466968,91.629297,58.460417,23.307943
14,2029,42.206079,96.288696,114.979932,58.582320,143.729767,254.917950,44.932390,101.080061,33.843104,...,33.639425,55.912613,50.067146,16.057412,31.467997,85.728196,65.149844,90.568218,57.468256,22.753928
15,2030,40.114570,93.174455,115.947914,57.712138,143.767469,255.653204,42.793605,100.852657,32.909984,...,33.578426,54.481084,51.759438,16.725071,33.888072,83.499987,67.009280,89.718924,56.539400,22.687713
16,2031,38.124996,90.174995,117.163241,56.835519,144.129539,256.245902,40.712810,100.985856,32.035210,...,33.529212,53.033850,53.236974,17.447744,36.329468,80.999955,68.897728,89.020759,55.648235,22.650855
17,2032,36.269754,87.185278,118.575517,55.937430,144.786665,257.700582,38.671524,101.352061,31.215753,...,33.526734,51.690124,54.524820,18.224388,38.792600,78.500023,70.751676,88.800456,54.832801,22.641497
18,2033,34.484649,84.377035,120.199387,55.017952,145.664800,259.267242,36.659963,101.899787,30.438425,...,33.564514,50.533597,55.644205,19.054607,41.277333,76.000022,72.679442,88.373691,54.056461,22.657915
19,2034,32.743942,81.653235,121.991350,54.173372,146.756941,261.447512,34.700419,102.626523,29.701731,...,33.616038,49.470356,56.612398,19.938544,43.783924,73.499977,74.689359,87.944268,53.357871,22.698546

In [135]:
(imf_bloomberg.iloc[-1]-imf_bloomberg.iloc[9]).sort_values()

Canada                      -23.514885
India                       -23.237761
Australia                   -16.815555
Sri Lanka                   -15.957587
New Zealand                 -12.632410
Germany                      -9.365212
Thailand                     -9.163435
Chile                        -8.242019
Philippines                  -8.070766
Sweden                       -6.446829
Nigeria                      -5.588359
Spain                        -2.122151
Indonesia                    -2.119825
South Africa                 -1.938583
Emerging Markets Ex China    -1.362562
Peru                         -0.229854
Pakistan                     -0.131736
Turkey                        0.615760
Argentina                     1.707212
Mexico                        4.960652
Russia                        6.204416
Global                        7.073961
G-20                          7.452620
Japan                         7.460708
Italy                         8.007957
UK                            8.287708
indicator_date               10.000000
France                       10.674244
Advanced Economies           11.664900
G-7                          14.171321
Brazil                       15.181213
Saudi Arabia                 16.265817
South Korea                  17.356875
Poland                       18.404470
Colombia                     20.711579
China                        23.803033
US                           24.248165
dtype: float64

In [139]:
imf_bloomberg[["indicator_date","Global","G-7","US","China","Germany","Japan","UK","France","Italy"]].to_csv("bloomberg.csv",index=False)

In [156]:
collist=["indicator_date"]
collist2=(imf_bloomberg.iloc[-1]-imf_bloomberg.iloc[9]).sort_values().index[:17].tolist()
collist.extend(collist2)
collist

['indicator_date',
 'Canada',
 'India',
 'Australia',
 'Sri Lanka',
 'New Zealand',
 'Germany',
 'Thailand',
 'Chile',
 'Philippines',
 'Sweden',
 'Nigeria',
 'Spain',
 'Indonesia',
 'South Africa',
 'Emerging Markets Ex China',
 'Peru',
 'Pakistan']

In [159]:
imf_bloomberg[collist].to_csv("other_neg.csv",index=False)