In [69]:
import pandas as pd

In [97]:
file_world=pd.read_excel('../data/David _ Adam PR Request 2025-06.xlsx', sheet_name="Worldwide + AI Referrals")
file_world

,country,site,main_category,yearmonth,ai_referrals,total_monthly_ai_referrals,search_traffic,total_monthly_search_trafic
0,Worldwide,google.com*,Computers_Electronics_and_Technology,2021-01,11614.146576,2.907524e+05,1.276212e+10,2.597674e+11
1,Worldwide,youtube.com*,Arts_and_Entertainment,2021-01,5412.506948,2.907524e+05,8.058103e+09,2.597674e+11
2,Worldwide,wikipedia.org*,Reference_Materials,2021-01,4048.006131,2.907524e+05,5.340349e+09,2.597674e+11
3,Worldwide,facebook.com*,Computers_Electronics_and_Technology,2021-01,392.660049,2.907524e+05,4.434677e+09,2.597674e+11
4,Worldwide,reddit.com*,Computers_Electronics_and_Technology,2021-01,389.592921,2.907524e+05,1.427108e+09,2.597674e+11
...,...,...,...,...,...,...,...,...
50766,Worldwide,usnews.com*,News_and_Media,2025-05,77758.892999,1.329318e+09,2.114487e+07,1.964069e+11
50767,Worldwide,webmd.com*,Health,2025-05,272974.124311,1.329318e+09,3.637230e+07,1.964069e+11
50768,Worldwide,wetter.com*,Science_and_Education,2025-05,20472.00746,1.329318e+09,3.945464e+07,1.964069e+11
50769,Worldwide,wiki.gg*,Games,2025-05,24171.529771,1.329318e+09,1.752168e+07,1.964069e+11
50770,Worldwide,wowhead.com*,Games,2025-05,5123.63175,1.329318e+09,2.316617e+07,1.964069e+11

In [104]:
def filecleaner(file):
    file["search_traffic"]=pd.to_numeric(file["search_traffic"], errors='coerce')
    file["ai_referrals"]=pd.to_numeric(file["ai_referrals"], errors='coerce')
    df_2025=file[file["yearmonth"]>="2025-01"]
    df_2024=file[(file["yearmonth"]>="2024-01")&(file["yearmonth"]<="2024-05")]

    return {"2024":df_2024,"2025":df_2025}

In [105]:
dict_of_files=filecleaner(file_world)

In [106]:
mean_2025_world=dict_of_files["2025"][["site","main_category","ai_referrals","search_traffic","total_monthly_search_trafic"]].groupby(["site","main_category"]).mean().reset_index()
mean_2025_world

,site,main_category,ai_referrals,search_traffic,total_monthly_search_trafic
0,123av.com*,Arts_and_Entertainment,1260.258921,2.986086e+07,1.997169e+11
1,163.com*,News_and_Media,271683.026581,6.470649e+07,1.997169e+11
2,1mg.com*,Health,44361.843697,3.996439e+07,1.997169e+11
3,20minutes.fr*,News_and_Media,12208.982899,2.657425e+07,1.997169e+11
4,20minutos.es*,News_and_Media,65971.673426,3.113946e+07,1.997169e+11
...,...,...,...,...,...
999,zara.com*,Lifestyle,240257.373412,3.339181e+07,1.997169e+11
1000,zdf.de*,Arts_and_Entertainment,128652.110028,2.792602e+07,1.997169e+11
1001,zhihu.com*,Computers_Electronics_and_Technology,88990.086517,1.701714e+08,1.997169e+11
1002,zillow.com*,Business_and_Consumer_Services,530258.457658,1.544663e+08,1.997169e+11
1003,zoom.us*,Computers_Electronics_and_Technology,40285.986635,1.370282e+08,1.997169e+11

In [107]:
mean_2024_world=dict_of_files["2024"][["site","search_traffic","ai_referrals","main_category","total_monthly_search_trafic"]].groupby(["site","main_category"]).mean().reset_index()
mean_2024_world

,site,main_category,search_traffic,ai_referrals,total_monthly_search_trafic
0,163.com*,News_and_Media,8.013160e+07,2651.854759,2.301684e+11
1,1mg.com*,Health,3.871039e+07,568.763319,2.301684e+11
2,20minutes.fr*,News_and_Media,2.567792e+07,777.339151,2.301684e+11
3,20minutos.es*,News_and_Media,3.732997e+07,8018.503103,2.301684e+11
4,24h.com.vn*,News_and_Media,2.568620e+07,NaN,2.301684e+11
...,...,...,...,...,...
973,zara.com*,Lifestyle,3.686275e+07,139.881688,2.301684e+11
974,zdf.de*,Arts_and_Entertainment,2.676779e+07,2574.417074,2.301684e+11
975,zhihu.com*,Computers_Electronics_and_Technology,2.988605e+08,42978.753122,2.301684e+11
976,zillow.com*,Business_and_Consumer_Services,1.494194e+08,3558.371838,2.301684e+11
977,zoom.us*,Computers_Electronics_and_Technology,1.508450e+08,306.824184,2.301684e+11

In [108]:
df_24_25_world=pd.merge(mean_2024_world,mean_2025_world,on="site",suffixes=["_2024","_2025"])
df_24_25_world

,site,main_category_2024,search_traffic_2024,ai_referrals_2024,total_monthly_search_trafic_2024,main_category_2025,ai_referrals_2025,search_traffic_2025,total_monthly_search_trafic_2025
0,163.com*,News_and_Media,8.013160e+07,2651.854759,2.301684e+11,News_and_Media,271683.026581,6.470649e+07,1.997169e+11
1,1mg.com*,Health,3.871039e+07,568.763319,2.301684e+11,Health,44361.843697,3.996439e+07,1.997169e+11
2,20minutes.fr*,News_and_Media,2.567792e+07,777.339151,2.301684e+11,News_and_Media,12208.982899,2.657425e+07,1.997169e+11
3,20minutos.es*,News_and_Media,3.732997e+07,8018.503103,2.301684e+11,News_and_Media,65971.673426,3.113946e+07,1.997169e+11
4,24h.com.vn*,News_and_Media,2.568620e+07,NaN,2.301684e+11,News_and_Media,64482.303341,2.556135e+07,1.997169e+11
...,...,...,...,...,...,...,...,...,...
977,zara.com*,Lifestyle,3.686275e+07,139.881688,2.301684e+11,Lifestyle,240257.373412,3.339181e+07,1.997169e+11
978,zdf.de*,Arts_and_Entertainment,2.676779e+07,2574.417074,2.301684e+11,Arts_and_Entertainment,128652.110028,2.792602e+07,1.997169e+11
979,zhihu.com*,Computers_Electronics_and_Technology,2.988605e+08,42978.753122,2.301684e+11,Computers_Electronics_and_Technology,88990.086517,1.701714e+08,1.997169e+11
980,zillow.com*,Business_and_Consumer_Services,1.494194e+08,3558.371838,2.301684e+11,Business_and_Consumer_Services,530258.457658,1.544663e+08,1.997169e+11
981,zoom.us*,Computers_Electronics_and_Technology,1.508450e+08,306.824184,2.301684e+11,Computers_Electronics_and_Technology,40285.986635,1.370282e+08,1.997169e+11

In [109]:
df_24_25_world[["main_category_2025","search_traffic_2024","search_traffic_2025"]].groupby("main_category_2025").mean()

                                      search_traffic_2024  search_traffic_2025
main_category_2025
Arts_and_Entertainment                       1.102212e+08         1.137691e+08
Business_and_Consumer_Services               3.821873e+07         3.679315e+07
Community_and_Society                        8.356756e+07         7.554750e+07
Computers_Electronics_and_Technology         1.789290e+08         1.902903e+08
E-commerce_and_Shopping                      6.393685e+07         6.492956e+07
Finance                                      2.677003e+07         2.925178e+07
Food_and_Drink                               3.831638e+07         3.744708e+07
Gambling                                     1.818270e+07         2.362424e+07
Games                                        3.932020e+07         4.136569e+07
Health                                       5.122869e+07         3.776840e+07
Hobbies_and_Leisure                          2.101142e+07         2.495075e+07
Home_and_Garden                              4.129390e+07         3.763387e+07
Jobs_and_Career                              6.434095e+07         5.518448e+07
Law_and_Government                           3.258373e+07         3.144397e+07
Lifestyle                                    2.807791e+07         2.747605e+07
News_and_Media                               5.677042e+07         5.371154e+07
Reference_Materials                          2.509663e+08         2.207036e+08
Science_and_Education                        4.682832e+07         4.155276e+07
Sports                                       3.581830e+07         3.379335e+07
Travel_and_Tourism                           3.445066e+07         3.164496e+07
Vehicles                                     2.312155e+07         2.400774e+07

In [110]:
df_24_25_world["search_perc_diff"]=(df_24_25_world["search_traffic_2025"]-df_24_25_world["search_traffic_2024"])*100/df_24_25["search_traffic_2024"]
df_24_25_world.sort_values("search_perc_diff", ascending=False, inplace=True)
df_24_25_world

,site,main_category_2024,search_traffic_2024,ai_referrals_2024,total_monthly_search_trafic_2024,main_category_2025,ai_referrals_2025,search_traffic_2025,total_monthly_search_trafic_2025,search_perc_diff
843,threads.com*,Lifestyle,4.226957e+04,NaN,2.301684e+11,Computers_Electronics_and_Technology,502267.364145,6.905497e+07,1.964069e+11,163268.056720
212,deepseek.com*,Computers_Electronics_and_Technology,1.196877e+05,NaN,2.301684e+11,Computers_Electronics_and_Technology,835080.941003,1.543150e+08,1.997169e+11,128831.404260
844,threads.com*,Lifestyle,4.226957e+04,NaN,2.301684e+11,Lifestyle,50115.339340,2.831391e+06,2.005444e+11,6598.415193
622,novelbin.com*,Arts_and_Entertainment,9.860743e+05,50.095695,2.301684e+11,Arts_and_Entertainment,7305.339618,2.318682e+07,1.997169e+11,2251.426968
572,missav123.com*,Computers_Electronics_and_Technology,1.018540e+06,NaN,2.301684e+11,Computers_Electronics_and_Technology,2671.178131,1.992990e+07,1.997169e+11,1856.711715
...,...,...,...,...,...,...,...,...,...,...
772,snaptik.app*,Computers_Electronics_and_Technology,6.333261e+07,6339.734215,2.301684e+11,Computers_Electronics_and_Technology,59169.631173,2.950393e+07,1.997169e+11,-53.414318
852,tinyurl.com*,Computers_Electronics_and_Technology,4.086002e+07,127.566043,2.301684e+11,Computers_Electronics_and_Technology,273824.330795,1.756985e+07,1.997169e+11,-56.999894
581,msdmanuals.com*,Health,4.978505e+07,39676.089823,2.301684e+11,Health,176991.166403,2.093490e+07,1.997169e+11,-57.949432
849,timesbull.com*,News_and_Media,4.872909e+07,NaN,2.301684e+11,News_and_Media,83473.017723,1.453411e+07,1.997169e+11,-70.173641
330,gmail.com*,Computers_Electronics_and_Technology,9.193728e+07,NaN,2.301684e+11,Computers_Electronics_and_Technology,86983.666124,2.237111e+07,1.997169e+11,-75.666988

In [111]:
df_24_25_world["search_perc_diff"]=(df_24_25_world["search_traffic_2025"]-df_24_25_world["search_traffic_2024"])*100/df_24_25["search_traffic_2024"]
df_24_25_world.sort_values("search_perc_diff", ascending=False, inplace=True)
df_24_25_world

,site,main_category_2024,search_traffic_2024,ai_referrals_2024,total_monthly_search_trafic_2024,main_category_2025,ai_referrals_2025,search_traffic_2025,total_monthly_search_trafic_2025,search_perc_diff
843,threads.com*,Lifestyle,4.226957e+04,NaN,2.301684e+11,Computers_Electronics_and_Technology,502267.364145,6.905497e+07,1.964069e+11,163268.056720
212,deepseek.com*,Computers_Electronics_and_Technology,1.196877e+05,NaN,2.301684e+11,Computers_Electronics_and_Technology,835080.941003,1.543150e+08,1.997169e+11,128831.404260
844,threads.com*,Lifestyle,4.226957e+04,NaN,2.301684e+11,Lifestyle,50115.339340,2.831391e+06,2.005444e+11,6598.415193
622,novelbin.com*,Arts_and_Entertainment,9.860743e+05,50.095695,2.301684e+11,Arts_and_Entertainment,7305.339618,2.318682e+07,1.997169e+11,2251.426968
572,missav123.com*,Computers_Electronics_and_Technology,1.018540e+06,NaN,2.301684e+11,Computers_Electronics_and_Technology,2671.178131,1.992990e+07,1.997169e+11,1856.711715
...,...,...,...,...,...,...,...,...,...,...
772,snaptik.app*,Computers_Electronics_and_Technology,6.333261e+07,6339.734215,2.301684e+11,Computers_Electronics_and_Technology,59169.631173,2.950393e+07,1.997169e+11,-53.414318
852,tinyurl.com*,Computers_Electronics_and_Technology,4.086002e+07,127.566043,2.301684e+11,Computers_Electronics_and_Technology,273824.330795,1.756985e+07,1.997169e+11,-56.999894
581,msdmanuals.com*,Health,4.978505e+07,39676.089823,2.301684e+11,Health,176991.166403,2.093490e+07,1.997169e+11,-57.949432
849,timesbull.com*,News_and_Media,4.872909e+07,NaN,2.301684e+11,News_and_Media,83473.017723,1.453411e+07,1.997169e+11,-70.173641
330,gmail.com*,Computers_Electronics_and_Technology,9.193728e+07,NaN,2.301684e+11,Computers_Electronics_and_Technology,86983.666124,2.237111e+07,1.997169e+11,-75.666988

In [112]:
df_24_25_world["ai_perc_diff"]=(df_24_25_world["ai_referrals_2025"]-df_24_25_world["ai_referrals_2024"])*100/df_24_25["ai_referrals_2024"]
df_24_25_world.sort_values("ai_perc_diff", ascending=False, inplace=True)
df_24_25_world

,site,main_category_2024,search_traffic_2024,ai_referrals_2024,total_monthly_search_trafic_2024,main_category_2025,ai_referrals_2025,search_traffic_2025,total_monthly_search_trafic_2025,search_perc_diff,ai_perc_diff
397,idealo.de*,E-commerce_and_Shopping,2.533319e+07,225.796345,2.301684e+11,E-commerce_and_Shopping,560778.469975,2.821111e+07,1.997169e+11,11.360294,248255.866456
852,tinyurl.com*,Computers_Electronics_and_Technology,4.086002e+07,127.566043,2.301684e+11,Computers_Electronics_and_Technology,273824.330795,1.756985e+07,1.997169e+11,-56.999894,214552.994922
929,wetransfer.com*,Computers_Electronics_and_Technology,2.412509e+07,99.347406,2.301684e+11,Computers_Electronics_and_Technology,202953.241486,1.803721e+07,1.997169e+11,-25.234645,204186.402688
977,zara.com*,Lifestyle,3.686275e+07,139.881688,2.301684e+11,Lifestyle,240257.373412,3.339181e+07,1.997169e+11,-9.415853,171657.559217
662,perplexity.ai*,Reference_Materials,1.184480e+07,128.221826,2.301684e+11,Reference_Materials,192919.461629,3.270057e+07,1.997169e+11,176.075260,150357.584594
...,...,...,...,...,...,...,...,...,...,...,...
202,cybozu.com*,Business_and_Consumer_Services,2.777570e+07,NaN,2.301684e+11,Business_and_Consumer_Services,5572.386201,1.837663e+07,1.997169e+11,-33.839194,NaN
459,jut.su*,Arts_and_Entertainment,3.799008e+07,NaN,2.301684e+11,Arts_and_Entertainment,27438.041856,2.418323e+07,1.997169e+11,-36.343296,NaN
166,clarosva.com*,Computers_Electronics_and_Technology,3.379352e+07,NaN,2.301684e+11,Computers_Electronics_and_Technology,6868.604182,1.704854e+07,1.997169e+11,-49.550869,NaN
849,timesbull.com*,News_and_Media,4.872909e+07,NaN,2.301684e+11,News_and_Media,83473.017723,1.453411e+07,1.997169e+11,-70.173641,NaN
330,gmail.com*,Computers_Electronics_and_Technology,9.193728e+07,NaN,2.301684e+11,Computers_Electronics_and_Technology,86983.666124,2.237111e+07,1.997169e+11,-75.666988,NaN

In [116]:
file_US=pd.read_excel('../data/David _ Adam PR Request 2025-06.xlsx', sheet_name="US + AI Referrals")
file_US

,country,site,main_category,yearmonth,ai_referrals,total_monthly_ai_referrals,referral_share,search_traffic,total_monthly_search_trafic
0,United States,google.com*,Computers_Electronics_and_Technology,2023-07,3059962.22841,3.811955e+06,0.802728,1.855784e+09,3.695124e+10
1,United States,google.com*,Computers_Electronics_and_Technology,2023-08,3146386.090678,3.990082e+06,0.788552,1.813394e+09,3.728764e+10
2,United States,google.com*,Computers_Electronics_and_Technology,2023-05,355944.483626,5.679688e+05,0.626697,1.874579e+09,3.669643e+10
3,United States,google.com*,Computers_Electronics_and_Technology,2023-10,1869829.8,3.438250e+06,0.543832,1.784745e+09,3.685892e+10
4,United States,google.com*,Computers_Electronics_and_Technology,2023-09,1943179.099818,3.639954e+06,0.533847,1.720230e+09,3.583514e+10
...,...,...,...,...,...,...,...,...,...
51510,United States,kindred.co*,Lifestyle,2021-01,0,0.000000e+00,0.000000,2.861732e+02,3.970617e+10
51511,United States,supercarblondie.com*,Vehicles,2021-01,0,0.000000e+00,0.000000,2.456700e+02,3.970617e+10
51512,United States,kick.com*,Computers_Electronics_and_Technology,2021-01,0,0.000000e+00,0.000000,1.391591e+02,3.970617e+10
51513,United States,geeksided.com*,Games,2021-01,0,0.000000e+00,0.000000,1.350697e+02,3.970617e+10
51514,United States,glassalmanac.com*,Computers_Electronics_and_Technology,2021-01,0,0.000000e+00,0.000000,1.132530e+02,3.970617e+10

In [117]:
dict_of_files_US=filecleaner(file_US)

In [118]:
mean_2025_US=dict_of_files_US["2025"][["site","main_category","ai_referrals","search_traffic","total_monthly_search_trafic"]].groupby(["site","main_category"]).mean().reset_index()
mean_2025_US

,site,main_category,ai_referrals,search_traffic,total_monthly_search_trafic
0,0123movie.net*,Arts_and_Entertainment,445.224743,5.625064e+06,3.203203e+10
1,247sports.com*,Sports,3117.734488,1.149042e+07,3.203203e+10
2,9animetv.to*,Arts_and_Entertainment,401.669300,4.744075e+06,3.203203e+10
3,9news.com*,Arts_and_Entertainment,2602.599373,3.739682e+06,3.203203e+10
4,a.co*,Computers_Electronics_and_Technology,14684.942504,8.825927e+06,3.203203e+10
...,...,...,...,...,...
1003,zillow.com*,Business_and_Consumer_Services,466590.121654,1.498841e+08,3.203203e+10
1004,ziprecruiter.com*,Jobs_and_Career,188991.467808,1.423933e+07,3.203203e+10
1005,zocdoc.com*,Health,13794.750285,3.252870e+06,3.203203e+10
1006,zola.com*,Lifestyle,26255.317464,3.794068e+06,3.203203e+10
1007,zoom.us*,Computers_Electronics_and_Technology,5483.731691,4.561453e+07,3.203203e+10

In [ ]:
mean_2025_US

,site,main_category,ai_referrals,search_traffic,total_monthly_search_trafic
0,0123movie.net*,Arts_and_Entertainment,445.224743,5.625064e+06,3.203203e+10
1,247sports.com*,Sports,3117.734488,1.149042e+07,3.203203e+10
2,9animetv.to*,Arts_and_Entertainment,401.669300,4.744075e+06,3.203203e+10
3,9news.com*,Arts_and_Entertainment,2602.599373,3.739682e+06,3.203203e+10
4,a.co*,Computers_Electronics_and_Technology,14684.942504,8.825927e+06,3.203203e+10
...,...,...,...,...,...
1003,zillow.com*,Business_and_Consumer_Services,466590.121654,1.498841e+08,3.203203e+10
1004,ziprecruiter.com*,Jobs_and_Career,188991.467808,1.423933e+07,3.203203e+10
1005,zocdoc.com*,Health,13794.750285,3.252870e+06,3.203203e+10
1006,zola.com*,Lifestyle,26255.317464,3.794068e+06,3.203203e+10
1007,zoom.us*,Computers_Electronics_and_Technology,5483.731691,4.561453e+07,3.203203e+10

In [119]:
mean_2024_US=dict_of_files_US["2024"][["site","main_category","ai_referrals","search_traffic","total_monthly_search_trafic"]].groupby(["site","main_category"]).mean().reset_index()
mean_2024_US

,site,main_category,ai_referrals,search_traffic,total_monthly_search_trafic
0,0123movie.net*,Arts_and_Entertainment,0.000000,6.312116e+06,3.645166e+10
1,247sports.com*,Sports,63.391457,1.478075e+07,3.645166e+10
2,9animetv.to*,Arts_and_Entertainment,272.798856,6.043610e+06,3.645166e+10
3,9news.com*,Arts_and_Entertainment,0.000000,3.480082e+06,3.645166e+10
4,a.co*,Computers_Electronics_and_Technology,0.000000,8.806471e+06,3.645166e+10
...,...,...,...,...,...
987,zillow.com*,Business_and_Consumer_Services,3075.112248,1.449428e+08,3.645166e+10
988,ziprecruiter.com*,Jobs_and_Career,5248.642879,1.495082e+07,3.645166e+10
989,zocdoc.com*,Health,603.235548,3.674407e+06,3.645166e+10
990,zola.com*,Lifestyle,0.000000,4.031962e+06,3.645166e+10
991,zoom.us*,Computers_Electronics_and_Technology,96.256290,4.927052e+07,3.645166e+10

In [92]:
# Was sind Hypothesen?
# 1. USA seit einem Jahr AI Zusammenfassung und darum deutlich grÃ¶ÃŸerer Einbruch
# 2. Englische AI-Zusammenfassungen sind besser und darum gibt es mehr Zerotraffics
# 3. In Deutschland geringe Auswirkungen, selten AI-Zusammenfassungen bei aktuellen Themen
# 4. So gigantisch ist der Traffic von Google im Vergleich zu OpenAI, trotz VertrÃ¤ge
# 5. Wie gut sind die Daten von Similarweb im Vergleich zu Google, Cloudflare?
# 6. Crawler vs echte Klicks

In [93]:
#Branchenweise Unterschiede in den Daten anschaut

In [ ]:
#Welche Branchen sind am unabhÃ¤ngigsten von Schwankungen im Traffic?
#Reise abhÃ¤ngiger
#Banken unabhÃ¤ngiger

In [ ]:
#Wie groÃŸ ist USA vs. Rest der Welt? Diff bei Schwankungen?
#AI-Zeroclicks?

In [ ]:
#Kleinere Anbieter kapern

In [ ]:
#US raus der Welt filtern
#FrÃ¼here Schwankungen versus Schwankungen durch AI