In [1]:
import pandas as pd

In [2]:
file_us=pd.read_excel('../data/David _ Adam PR Request 2025-06.xlsx', sheet_name="US + AI Referrals")
file_us

,country,site,main_category,yearmonth,ai_referrals,total_monthly_ai_referrals,referral_share,search_traffic,total_monthly_search_trafic
0,United States,google.com*,Computers_Electronics_and_Technology,2023-07,3059962.22841,3.811955e+06,0.802728,1.855784e+09,3.695124e+10
1,United States,google.com*,Computers_Electronics_and_Technology,2023-08,3146386.090678,3.990082e+06,0.788552,1.813394e+09,3.728764e+10
2,United States,google.com*,Computers_Electronics_and_Technology,2023-05,355944.483626,5.679688e+05,0.626697,1.874579e+09,3.669643e+10
3,United States,google.com*,Computers_Electronics_and_Technology,2023-10,1869829.8,3.438250e+06,0.543832,1.784745e+09,3.685892e+10
4,United States,google.com*,Computers_Electronics_and_Technology,2023-09,1943179.099818,3.639954e+06,0.533847,1.720230e+09,3.583514e+10
...,...,...,...,...,...,...,...,...,...
51510,United States,kindred.co*,Lifestyle,2021-01,0,0.000000e+00,0.000000,2.861732e+02,3.970617e+10
51511,United States,supercarblondie.com*,Vehicles,2021-01,0,0.000000e+00,0.000000,2.456700e+02,3.970617e+10
51512,United States,kick.com*,Computers_Electronics_and_Technology,2021-01,0,0.000000e+00,0.000000,1.391591e+02,3.970617e+10
51513,United States,geeksided.com*,Games,2021-01,0,0.000000e+00,0.000000,1.350697e+02,3.970617e+10
51514,United States,glassalmanac.com*,Computers_Electronics_and_Technology,2021-01,0,0.000000e+00,0.000000,1.132530e+02,3.970617e+10

In [3]:
file_world=pd.read_excel('../data/David _ Adam PR Request 2025-06.xlsx', sheet_name="Worldwide + AI Referrals")
file_world

,country,site,main_category,yearmonth,ai_referrals,total_monthly_ai_referrals,search_traffic,total_monthly_search_trafic
0,Worldwide,google.com*,Computers_Electronics_and_Technology,2021-01,11614.146576,2.907524e+05,1.276212e+10,2.597674e+11
1,Worldwide,youtube.com*,Arts_and_Entertainment,2021-01,5412.506948,2.907524e+05,8.058103e+09,2.597674e+11
2,Worldwide,wikipedia.org*,Reference_Materials,2021-01,4048.006131,2.907524e+05,5.340349e+09,2.597674e+11
3,Worldwide,facebook.com*,Computers_Electronics_and_Technology,2021-01,392.660049,2.907524e+05,4.434677e+09,2.597674e+11
4,Worldwide,reddit.com*,Computers_Electronics_and_Technology,2021-01,389.592921,2.907524e+05,1.427108e+09,2.597674e+11
...,...,...,...,...,...,...,...,...
50766,Worldwide,usnews.com*,News_and_Media,2025-05,77758.892999,1.329318e+09,2.114487e+07,1.964069e+11
50767,Worldwide,webmd.com*,Health,2025-05,272974.124311,1.329318e+09,3.637230e+07,1.964069e+11
50768,Worldwide,wetter.com*,Science_and_Education,2025-05,20472.00746,1.329318e+09,3.945464e+07,1.964069e+11
50769,Worldwide,wiki.gg*,Games,2025-05,24171.529771,1.329318e+09,1.752168e+07,1.964069e+11
50770,Worldwide,wowhead.com*,Games,2025-05,5123.63175,1.329318e+09,2.316617e+07,1.964069e+11

In [4]:
us_world_concat=pd.concat([file_us, file_world], ignore_index=True)

In [5]:
file_world_categories=us_world_concat[["site","main_category"]]
file_world_categories.drop_duplicates(inplace=True)
file_world_categories

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_90029/3695824424.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  file_world_categories.drop_duplicates(inplace=True)

                        site                         main_category
0                google.com*  Computers_Electronics_and_Technology
7                github.com*  Computers_Electronics_and_Technology
11               openai.com*  Computers_Electronics_and_Technology
18              chatgpt.com*  Computers_Electronics_and_Technology
31                 live.com*  Computers_Electronics_and_Technology
...                      ...                                   ...
98534            amedia.lol*                Arts_and_Entertainment
99421               bato.si*                Arts_and_Entertainment
100418            banxia.cc*  Computers_Electronics_and_Technology
100972     businesstoday.in*                        News_and_Media
101813  oantagonista.com.br*                        News_and_Media

[1708 rows x 2 columns]

In [6]:
file_world_categories[file_world_categories.site.str.contains("truthsocial.com", regex=True, na=False)]

                   site                         main_category
11771  truthsocial.com*  Computers_Electronics_and_Technology
12583  truthsocial.com*                        News_and_Media

In [7]:
double_categories_world=file_world_categories[file_world_categories.duplicated(subset=["site"],keep=False)]
double_categories_world.sort_values(by="site", inplace=True)
double_categories_world

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_90029/2682089888.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  double_categories_world.sort_values(by="site", inplace=True)

                  site                         main_category
52281       amazon.sa*  Computers_Electronics_and_Technology
85283       amazon.sa*               E-commerce_and_Shopping
35013        app.link*                                 Games
9984         app.link*  Computers_Electronics_and_Technology
51619        auone.jp*  Computers_Electronics_and_Technology
...                ...                                   ...
314         yahoo.com*                        News_and_Media
38284  yardbarker.com*                        News_and_Media
5995   yardbarker.com*                                Sports
12965        yt1d.com*  Computers_Electronics_and_Technology
13607        yt1d.com*                 Community_and_Society

[98 rows x 2 columns]

In [8]:
double_categories_world[double_categories_world.site.str.contains("truthsocial.com", regex=True, na=False)]

                   site                         main_category
11771  truthsocial.com*  Computers_Electronics_and_Technology
12583  truthsocial.com*                        News_and_Media

In [9]:
double_categories_world.to_csv("../data/double_categories.csv", index=False)

In [10]:
file_us

,country,site,main_category,yearmonth,ai_referrals,total_monthly_ai_referrals,referral_share,search_traffic,total_monthly_search_trafic
0,United States,google.com*,Computers_Electronics_and_Technology,2023-07,3059962.22841,3.811955e+06,0.802728,1.855784e+09,3.695124e+10
1,United States,google.com*,Computers_Electronics_and_Technology,2023-08,3146386.090678,3.990082e+06,0.788552,1.813394e+09,3.728764e+10
2,United States,google.com*,Computers_Electronics_and_Technology,2023-05,355944.483626,5.679688e+05,0.626697,1.874579e+09,3.669643e+10
3,United States,google.com*,Computers_Electronics_and_Technology,2023-10,1869829.8,3.438250e+06,0.543832,1.784745e+09,3.685892e+10
4,United States,google.com*,Computers_Electronics_and_Technology,2023-09,1943179.099818,3.639954e+06,0.533847,1.720230e+09,3.583514e+10
...,...,...,...,...,...,...,...,...,...
51510,United States,kindred.co*,Lifestyle,2021-01,0,0.000000e+00,0.000000,2.861732e+02,3.970617e+10
51511,United States,supercarblondie.com*,Vehicles,2021-01,0,0.000000e+00,0.000000,2.456700e+02,3.970617e+10
51512,United States,kick.com*,Computers_Electronics_and_Technology,2021-01,0,0.000000e+00,0.000000,1.391591e+02,3.970617e+10
51513,United States,geeksided.com*,Games,2021-01,0,0.000000e+00,0.000000,1.350697e+02,3.970617e+10
51514,United States,glassalmanac.com*,Computers_Electronics_and_Technology,2021-01,0,0.000000e+00,0.000000,1.132530e+02,3.970617e+10

In [11]:
file_categories=pd.read_csv('../data/double_categories_cleaned.csv', encoding='utf-8')
file_categories.rename(columns={"main_category":"cleaned_main_category"}, inplace=True)
file_categories

                         site                 cleaned_main_category
0                  amazon.sa*               E-commerce_and_Shopping
1                   app.link*  Computers_Electronics_and_Technology
2                   auone.jp*                        News_and_Media
3    bestproductsreviews.com*               E-commerce_and_Shopping
4                   bsky.app*                        News_and_Media
5           businesstoday.in*                        News_and_Media
6                 capcut.com*  Computers_Electronics_and_Technology
7   clickpetroleoegas.com.br*                        News_and_Media
8              etvbharat.com*                        News_and_Media
9                    fubo.tv*                                Sports
10           gamingbible.com*                                 Games
11             gunbroker.com*               E-commerce_and_Shopping
12             irecommend.ru*        Business_and_Consumer_Services
13       journaldesfemmes.fr*                        News_and_Media
14                kindred.co*        Business_and_Consumer_Services
15                  kwai.com*  Computers_Electronics_and_Technology
16                 linktr.ee*        Business_and_Consumer_Services
17              liputan6.com*                        News_and_Media
18                 login.gov*                    Law_and_Government
19                   max.com*                Arts_and_Entertainment
20                medium.com*        Business_and_Consumer_Services
21       metrobyt-mobile.com*  Computers_Electronics_and_Technology
22             moneywise.com*                               Finance
23                 mynavi.jp*                       Jobs_and_Career
24                   ndtv.in*                        News_and_Media
25       oantagonista.com.br*                        News_and_Media
26             perplexity.ai*                   Reference_Materials
27                  pluto.tv*                Arts_and_Entertainment
28            realsimple.com*                       Home_and_Garden
29        reclameaqui.com.br*               E-commerce_and_Shopping
30                  shop.app*               E-commerce_and_Shopping
31            solitaired.com*                                 Games
32        southernliving.com*                       Home_and_Garden
33              spectrum.net*  Computers_Electronics_and_Technology
34            studentaid.gov*                    Law_and_Government
35                  suno.com*  Computers_Electronics_and_Technology
36                 super.com*                    Travel_and_Tourism
37                  tbank.ru*                               Finance
38                  temu.com*               E-commerce_and_Shopping
39             themirror.com*                        News_and_Media
40               threads.com*  Computers_Electronics_and_Technology
41             tokyvideo.com*                Arts_and_Entertainment
42              trendyol.com*               E-commerce_and_Shopping
43           truthsocial.com*                        News_and_Media
44                  wise.com*                               Finance
45           xiaohongshu.com*                             Lifestyle
46                 yahoo.com*                        News_and_Media
47            yardbarker.com*                                Sports
48                  yt1d.com*                 Community_and_Society

In [12]:
file_us=pd.merge(file_us, file_categories, how='left', on='site')
file_us['cleaned_main_category'] = file_us['cleaned_main_category'].fillna(file_us['main_category'])
file_us

,country,site,main_category,yearmonth,ai_referrals,total_monthly_ai_referrals,referral_share,search_traffic,total_monthly_search_trafic,cleaned_main_category
0,United States,google.com*,Computers_Electronics_and_Technology,2023-07,3059962.22841,3.811955e+06,0.802728,1.855784e+09,3.695124e+10,Computers_Electronics_and_Technology
1,United States,google.com*,Computers_Electronics_and_Technology,2023-08,3146386.090678,3.990082e+06,0.788552,1.813394e+09,3.728764e+10,Computers_Electronics_and_Technology
2,United States,google.com*,Computers_Electronics_and_Technology,2023-05,355944.483626,5.679688e+05,0.626697,1.874579e+09,3.669643e+10,Computers_Electronics_and_Technology
3,United States,google.com*,Computers_Electronics_and_Technology,2023-10,1869829.8,3.438250e+06,0.543832,1.784745e+09,3.685892e+10,Computers_Electronics_and_Technology
4,United States,google.com*,Computers_Electronics_and_Technology,2023-09,1943179.099818,3.639954e+06,0.533847,1.720230e+09,3.583514e+10,Computers_Electronics_and_Technology
...,...,...,...,...,...,...,...,...,...,...
51510,United States,kindred.co*,Lifestyle,2021-01,0,0.000000e+00,0.000000,2.861732e+02,3.970617e+10,Business_and_Consumer_Services
51511,United States,supercarblondie.com*,Vehicles,2021-01,0,0.000000e+00,0.000000,2.456700e+02,3.970617e+10,Vehicles
51512,United States,kick.com*,Computers_Electronics_and_Technology,2021-01,0,0.000000e+00,0.000000,1.391591e+02,3.970617e+10,Computers_Electronics_and_Technology
51513,United States,geeksided.com*,Games,2021-01,0,0.000000e+00,0.000000,1.350697e+02,3.970617e+10,Games
51514,United States,glassalmanac.com*,Computers_Electronics_and_Technology,2021-01,0,0.000000e+00,0.000000,1.132530e+02,3.970617e+10,Computers_Electronics_and_Technology

In [13]:
file_world=pd.merge(file_world, file_categories, how='left', on='site')
file_world['cleaned_main_category'] = file_world['cleaned_main_category'].fillna(file_world['main_category'])
file_world

,country,site,main_category,yearmonth,ai_referrals,total_monthly_ai_referrals,search_traffic,total_monthly_search_trafic,cleaned_main_category
0,Worldwide,google.com*,Computers_Electronics_and_Technology,2021-01,11614.146576,2.907524e+05,1.276212e+10,2.597674e+11,Computers_Electronics_and_Technology
1,Worldwide,youtube.com*,Arts_and_Entertainment,2021-01,5412.506948,2.907524e+05,8.058103e+09,2.597674e+11,Arts_and_Entertainment
2,Worldwide,wikipedia.org*,Reference_Materials,2021-01,4048.006131,2.907524e+05,5.340349e+09,2.597674e+11,Reference_Materials
3,Worldwide,facebook.com*,Computers_Electronics_and_Technology,2021-01,392.660049,2.907524e+05,4.434677e+09,2.597674e+11,Computers_Electronics_and_Technology
4,Worldwide,reddit.com*,Computers_Electronics_and_Technology,2021-01,389.592921,2.907524e+05,1.427108e+09,2.597674e+11,Computers_Electronics_and_Technology
...,...,...,...,...,...,...,...,...,...
50766,Worldwide,usnews.com*,News_and_Media,2025-05,77758.892999,1.329318e+09,2.114487e+07,1.964069e+11,News_and_Media
50767,Worldwide,webmd.com*,Health,2025-05,272974.124311,1.329318e+09,3.637230e+07,1.964069e+11,Health
50768,Worldwide,wetter.com*,Science_and_Education,2025-05,20472.00746,1.329318e+09,3.945464e+07,1.964069e+11,Science_and_Education
50769,Worldwide,wiki.gg*,Games,2025-05,24171.529771,1.329318e+09,1.752168e+07,1.964069e+11,Games
50770,Worldwide,wowhead.com*,Games,2025-05,5123.63175,1.329318e+09,2.316617e+07,1.964069e+11,Games

In [14]:
def filecleaner(file):
    file["search_traffic"]=pd.to_numeric(file["search_traffic"], errors='coerce')
    file["ai_referrals"]=pd.to_numeric(file["ai_referrals"], errors='coerce')
    df_2025=file[file["yearmonth"]>="2025-01"]
    df_2024=file[(file["yearmonth"]>="2024-01")&(file["yearmonth"]<="2024-05")]

    return {"2024":df_2024,"2025":df_2025}

In [30]:
dict_of_files_world=filecleaner(file_world)

In [31]:
def mean_calc_comparer(dict_of_files):
    mean_2025_world=dict_of_files["2025"][["site","cleaned_main_category","search_traffic","ai_referrals","total_monthly_search_trafic"]].groupby(["site","cleaned_main_category"]).mean().reset_index()
    mean_2024_world=dict_of_files["2024"][["site","cleaned_main_category","search_traffic","ai_referrals","total_monthly_search_trafic"]].groupby(["site","cleaned_main_category"]).mean().reset_index()

    df_24_25_world=pd.merge(mean_2024_world, mean_2025_world, how="outer", on=["site","cleaned_main_category"], suffixes=("_2024", "_2025"))
    df_24_25_world

    return df_24_25_world

In [32]:
df_world=mean_calc_comparer(dict_of_files_world)
df_world

,site,cleaned_main_category,search_traffic_2024,ai_referrals_2024,total_monthly_search_trafic_2024,search_traffic_2025,ai_referrals_2025,total_monthly_search_trafic_2025
0,123av.com*,Arts_and_Entertainment,NaN,NaN,NaN,2.986086e+07,1260.258921,1.997169e+11
1,163.com*,News_and_Media,8.013160e+07,2651.854759,2.301684e+11,6.470649e+07,271683.026581,1.997169e+11
2,1mg.com*,Health,3.871039e+07,568.763319,2.301684e+11,3.996439e+07,44361.843697,1.997169e+11
3,20minutes.fr*,News_and_Media,2.567792e+07,777.339151,2.301684e+11,2.657425e+07,12208.982899,1.997169e+11
4,20minutos.es*,News_and_Media,3.732997e+07,8018.503103,2.301684e+11,3.113946e+07,65971.673426,1.997169e+11
...,...,...,...,...,...,...,...,...
995,zara.com*,Lifestyle,3.686275e+07,139.881688,2.301684e+11,3.339181e+07,240257.373412,1.997169e+11
996,zdf.de*,Arts_and_Entertainment,2.676779e+07,2574.417074,2.301684e+11,2.792602e+07,128652.110028,1.997169e+11
997,zhihu.com*,Computers_Electronics_and_Technology,2.988605e+08,42978.753122,2.301684e+11,1.701714e+08,88990.086517,1.997169e+11
998,zillow.com*,Business_and_Consumer_Services,1.494194e+08,3558.371838,2.301684e+11,1.544663e+08,530258.457658,1.997169e+11
999,zoom.us*,Computers_Electronics_and_Technology,1.508450e+08,306.824184,2.301684e+11,1.370282e+08,40285.986635,1.997169e+11

In [18]:
df_24_25_world_categories=df_world[["cleaned_main_category","search_traffic_2024","search_traffic_2025"]].groupby("cleaned_main_category").mean()
df_24_25_world_categories

                                      search_traffic_2024  search_traffic_2025
cleaned_main_category
Arts_and_Entertainment                       1.102212e+08         1.062078e+08
Business_and_Consumer_Services               3.870602e+07         3.745675e+07
Community_and_Society                        8.356756e+07         6.931235e+07
Computers_Electronics_and_Technology         1.807347e+08         1.880362e+08
E-commerce_and_Shopping                      6.353700e+07         6.446405e+07
Finance                                      2.695209e+07         2.896298e+07
Food_and_Drink                               3.831638e+07         3.669660e+07
Gambling                                     1.818270e+07         6.438385e+07
Games                                        3.932020e+07         4.151084e+07
Health                                       5.122869e+07         3.776840e+07
Hobbies_and_Leisure                          2.101142e+07         2.495075e+07
Home_and_Garden                              4.129390e+07         3.562779e+07
Jobs_and_Career                              6.325279e+07         5.361390e+07
Law_and_Government                           3.312114e+07         3.191364e+07
Lifestyle                                    3.070272e+07         2.940446e+07
News_and_Media                               5.376138e+07         5.095206e+07
Reference_Materials                          2.509663e+08         2.207036e+08
Science_and_Education                        4.682832e+07         4.155276e+07
Sports                                       3.581830e+07         3.336245e+07
Travel_and_Tourism                           3.445066e+07         3.164496e+07
Vehicles                                     2.312155e+07         2.400774e+07

In [20]:
df_world["search_perc_diff"]=(df_world["search_traffic_2025"]-df_world["search_traffic_2024"])*100/df_world["search_traffic_2024"]
df_world.sort_values("search_perc_diff", ascending=False, inplace=True)
df_world

,site,cleaned_main_category,search_traffic_2024,ai_referrals_2024,total_monthly_search_trafic_2024,search_traffic_2025,ai_referrals_2025,total_monthly_search_trafic_2025,search_perc_diff
216,deepseek.com*,Computers_Electronics_and_Technology,1.196877e+05,NaN,2.301684e+11,1.543150e+08,835080.941003,1.997169e+11,128831.404260
858,threads.com*,Computers_Electronics_and_Technology,4.226957e+04,NaN,2.301684e+11,1.607611e+07,276191.351743,1.997169e+11,37932.343499
636,novelbin.com*,Arts_and_Entertainment,9.860743e+05,50.095695,2.301684e+11,2.318682e+07,7305.339618,1.997169e+11,2251.426968
585,missav123.com*,Computers_Electronics_and_Technology,1.018540e+06,NaN,2.301684e+11,1.992990e+07,2671.178131,1.997169e+11,1856.711715
130,bsky.app*,News_and_Media,3.089862e+06,83.877712,2.301684e+11,3.145847e+07,10235.527283,1.997169e+11,918.119071
...,...,...,...,...,...,...,...,...,...
897,uakino.me*,Arts_and_Entertainment,NaN,NaN,NaN,2.819204e+07,12943.798807,1.997169e+11,NaN
907,unionrayo.com*,Sports,NaN,NaN,NaN,1.612651e+07,773.178980,1.997169e+11,NaN
927,vkvideo.ru*,Computers_Electronics_and_Technology,NaN,NaN,NaN,1.464181e+07,148.569593,1.997169e+11,NaN
993,yt1d.com*,Community_and_Society,NaN,NaN,NaN,1.943113e+07,16369.058287,1.997169e+11,NaN
994,ytmp3.la*,Food_and_Drink,NaN,NaN,NaN,2.093649e+07,18663.210277,1.997169e+11,NaN

In [22]:
df_world["ai_perc_diff"]=(df_world["ai_referrals_2025"]-df_world["ai_referrals_2024"])*100/df_world["ai_referrals_2024"]
df_world.sort_values("ai_perc_diff", ascending=False, inplace=True)
df_world

,site,cleaned_main_category,search_traffic_2024,ai_referrals_2024,total_monthly_search_trafic_2024,search_traffic_2025,ai_referrals_2025,total_monthly_search_trafic_2025,search_perc_diff,ai_perc_diff
406,idealo.de*,E-commerce_and_Shopping,2.533319e+07,225.796345,2.301684e+11,2.821111e+07,560778.469975,1.997169e+11,11.360294,248255.866456
866,tinyurl.com*,Computers_Electronics_and_Technology,4.086002e+07,127.566043,2.301684e+11,1.756985e+07,273824.330795,1.997169e+11,-56.999894,214552.994922
946,wetransfer.com*,Computers_Electronics_and_Technology,2.412509e+07,99.347406,2.301684e+11,1.803721e+07,202953.241486,1.997169e+11,-25.234645,204186.402688
995,zara.com*,Lifestyle,3.686275e+07,139.881688,2.301684e+11,3.339181e+07,240257.373412,1.997169e+11,-9.415853,171657.559217
675,perplexity.ai*,Reference_Materials,1.184480e+07,128.221826,2.301684e+11,3.270057e+07,192919.461629,1.997169e+11,176.075260,150357.584594
...,...,...,...,...,...,...,...,...,...,...
897,uakino.me*,Arts_and_Entertainment,NaN,NaN,NaN,2.819204e+07,12943.798807,1.997169e+11,NaN,NaN
907,unionrayo.com*,Sports,NaN,NaN,NaN,1.612651e+07,773.178980,1.997169e+11,NaN,NaN
927,vkvideo.ru*,Computers_Electronics_and_Technology,NaN,NaN,NaN,1.464181e+07,148.569593,1.997169e+11,NaN,NaN
993,yt1d.com*,Community_and_Society,NaN,NaN,NaN,1.943113e+07,16369.058287,1.997169e+11,NaN,NaN
994,ytmp3.la*,Food_and_Drink,NaN,NaN,NaN,2.093649e+07,18663.210277,1.997169e+11,NaN,NaN

In [24]:
dict_of_files_us=filecleaner(file_us)

In [25]:
df_us=mean_calc_comparer(dict_of_files_us)
df_us

,site,cleaned_main_category,search_traffic_2024,ai_referrals_2024,total_monthly_search_trafic_2024,search_traffic_2025,ai_referrals_2025,total_monthly_search_trafic_2025
0,0123movie.net*,Arts_and_Entertainment,6.312116e+06,0.000000,3.645166e+10,5.625064e+06,445.224743,3.203203e+10
1,247sports.com*,Sports,1.478075e+07,63.391457,3.645166e+10,1.149042e+07,3117.734488,3.203203e+10
2,9animetv.to*,Arts_and_Entertainment,6.043610e+06,272.798856,3.645166e+10,4.744075e+06,401.669300,3.203203e+10
3,9news.com*,Arts_and_Entertainment,3.480082e+06,0.000000,3.645166e+10,3.739682e+06,2602.599373,3.203203e+10
4,a.co*,Computers_Electronics_and_Technology,8.806471e+06,0.000000,3.645166e+10,8.825927e+06,14684.942504,3.203203e+10
...,...,...,...,...,...,...,...,...
995,zillow.com*,Business_and_Consumer_Services,1.449428e+08,3075.112248,3.645166e+10,1.498841e+08,466590.121654,3.203203e+10
996,ziprecruiter.com*,Jobs_and_Career,1.495082e+07,5248.642879,3.645166e+10,1.423933e+07,188991.467808,3.203203e+10
997,zocdoc.com*,Health,3.674407e+06,603.235548,3.645166e+10,3.252870e+06,13794.750285,3.203203e+10
998,zola.com*,Lifestyle,4.031962e+06,0.000000,3.645166e+10,3.794068e+06,26255.317464,3.203203e+10
999,zoom.us*,Computers_Electronics_and_Technology,4.927052e+07,96.256290,3.645166e+10,4.561453e+07,5483.731691,3.203203e+10

In [37]:
df_24_25_us_categories=df_us[["cleaned_main_category","search_traffic_2024","search_traffic_2025"]].groupby("cleaned_main_category").mean()
df_24_25_us_categories

                                      search_traffic_2024  search_traffic_2025
cleaned_main_category
Arts_and_Entertainment                       2.173160e+07         2.157926e+07
Business_and_Consumer_Services               2.087392e+07         1.865195e+07
Community_and_Society                        8.854770e+06         7.870280e+06
Computers_Electronics_and_Technology         4.141861e+07         4.459505e+07
E-commerce_and_Shopping                      3.223999e+07         3.042607e+07
Finance                                      9.754394e+06         9.070001e+06
Food_and_Drink                               8.508900e+06         7.441120e+06
Gambling                                     5.128967e+06         5.242786e+06
Games                                        7.975105e+06         7.914383e+06
Health                                       1.718859e+07         1.251206e+07
Heavy_Industry_and_Engineering               4.989884e+06         4.926688e+06
Hobbies_and_Leisure                          5.400305e+06         5.319805e+06
Home_and_Garden                              1.238134e+07         1.000099e+07
Jobs_and_Career                              3.687910e+07         3.228164e+07
Law_and_Government                           7.000241e+06         6.906512e+06
Lifestyle                                    6.317563e+06         5.754246e+06
News_and_Media                               2.150334e+07         2.019815e+07
Pets_and_Animals                             4.941602e+06         4.772425e+06
Reference_Materials                          5.506258e+07         4.583845e+07
Science_and_Education                        1.084287e+07         1.027031e+07
Sports                                       1.075040e+07         1.043012e+07
Travel_and_Tourism                           9.936237e+06         8.583767e+06
Vehicles                                     8.077666e+06         7.566121e+06

In [38]:
dict_of_files_us

{'2024':              country                       site  \
 19     United States                openai.com*
 31     United States                  live.com*
 32     United States                  live.com*
 34     United States                google.com*
 36     United States                google.com*
 ...              ...                        ...
 19258  United States               threads.com*
 19259  United States  sustainability-times.com*
 19260  United States              deepseek.com*
 19261  United States           dailygalaxy.com*
 19262  United States          glassalmanac.com*

                               main_category yearmonth  ai_referrals  \
 19     Computers_Electronics_and_Technology   2024-05  6.481627e+06
 31     Computers_Electronics_and_Technology   2024-04  2.125344e+06
 32     Computers_Electronics_and_Technology   2024-02  1.652755e+06
 34     Computers_Electronics_and_Technology   2024-03  2.509238e+06
 36     Computers_Electronics_and_Technology   2024-01  1.267002e+06
 ...                                     ...       ...           ...
 19258                             Lifestyle   2024-01  0.000000e+00
 19259                        News_and_Media   2024-01  0.000000e+00
 19260  Computers_Electronics_and_Technology   2024-01  0.000000e+00
 19261                 Science_and_Education   2024-01  0.000000e+00
 19262  Computers_Electronics_and_Technology   2024-01  0.000000e+00

        total_monthly_ai_referrals  referral_share  search_traffic  \
 19                   1.867632e+07        0.347051    3.040353e+07
 31                   9.069070e+06        0.234351    2.502649e+07
 32                   7.259674e+06        0.227662    2.377261e+07
 34                   1.107047e+07        0.226660    1.675197e+09
 36                   5.638232e+06        0.224716    1.774378e+09
 ...                           ...             ...             ...
 19258                0.000000e+00        0.000000    6.864007e+03
 19259                0.000000e+00        0.000000    6.420891e+03
 19260                0.000000e+00        0.000000    3.691866e+03
 19261                0.000000e+00        0.000000    1.744245e+03
 19262                0.000000e+00        0.000000    4.345064e+00

        total_monthly_search_trafic                 cleaned_main_category
 19                    3.721678e+10  Computers_Electronics_and_Technology
 31                    3.630256e+10  Computers_Electronics_and_Technology
 32                    3.461905e+10  Computers_Electronics_and_Technology
 34                    3.685474e+10  Computers_Electronics_and_Technology
 36                    3.726517e+10  Computers_Electronics_and_Technology
 ...                            ...                                   ...
 19258                 3.726517e+10  Computers_Electronics_and_Technology
 19259                 3.726517e+10                        News_and_Media
 19260                 3.726517e+10  Computers_Electronics_and_Technology
 19261                 3.726517e+10                 Science_and_Education
 19262                 3.726517e+10  Computers_Electronics_and_Technology

 [4931 rows x 10 columns],
 '2025':              country                       site  \
 44     United States               chatgpt.com*
 45     United States               chatgpt.com*
 51     United States               chatgpt.com*
 52     United States               chatgpt.com*
 67     United States               chatgpt.com*
 ...              ...                        ...
 15002  United States  farmingdale-observer.com*
 15003  United States     solitairetripeaks.com*
 15004  United States             geeksided.com*
 15005  United States                 tork.buzz*
 15006  United States               threads.com*

                               main_category yearmonth  ai_referrals  \
 44     Computers_Electronics_and_Technology   2025-01  2.966546e+07
 45     Computers_Electronics_and_Technology   2025-02  3.327415e+07
 51     Computers_Electronics_and_Technology   2025-03  3.535950e+07
 52     Computers_Electronics_and_Technology   2025-04  4.304672e+07
 67     Computers_Electronics_and_Technology   2025-05  3.582909e+07
 ...                                     ...       ...           ...
 15002                        News_and_Media   2025-01  0.000000e+00
 15003                      Pets_and_Animals   2025-01  0.000000e+00
 15004                                 Games   2025-01  0.000000e+00
 15005                              Vehicles   2025-01  0.000000e+00
 15006                             Lifestyle   2025-01  0.000000e+00

        total_monthly_ai_referrals  referral_share  search_traffic  \
 44                   1.479879e+08        0.200459    7.333290e+07
 45                   1.683533e+08        0.197645    8.333784e+07
 51                   1.848813e+08        0.191255    9.937780e+07
 52                   2.265999e+08        0.189968    1.089255e+08
 67                   2.472329e+08        0.144920    1.231989e+08
 ...                           ...             ...             ...
 15002                0.000000e+00        0.000000    5.443910e+05
 15003                0.000000e+00        0.000000    2.141582e+05
 15004                0.000000e+00        0.000000    2.404073e+04
 15005                0.000000e+00        0.000000    9.815885e+03
 15006                0.000000e+00        0.000000    8.729919e+02

        total_monthly_search_trafic                 cleaned_main_category
 44                    3.393098e+10  Computers_Electronics_and_Technology
 45                    3.009552e+10  Computers_Electronics_and_Technology
 51                    3.265752e+10  Computers_Electronics_and_Technology
 52                    3.158540e+10  Computers_Electronics_and_Technology
 67                    3.189073e+10  Computers_Electronics_and_Technology
 ...                            ...                                   ...
 15002                 3.393098e+10                        News_and_Media
 15003                 3.393098e+10                      Pets_and_Animals
 15004                 3.393098e+10                                 Games
 15005                 3.393098e+10                              Vehicles
 15006                 3.393098e+10  Computers_Electronics_and_Technology

 [4993 rows x 10 columns]}

In [39]:
dict_of_files_world

{'2024':          country                       site  \
 34017  Worldwide               3bmeteo.com*
 34018  Worldwide                abc.net.au*
 34019  Worldwide              abril.com.br*
 34020  Worldwide             acesso.gov.br*
 34021  Worldwide  agenciatributaria.gob.es*
 ...          ...                        ...
 38884  Worldwide            wiktionary.org*
 38885  Worldwide                 word.tips*
 38886  Worldwide              wordwall.net*
 38887  Worldwide                   wps.com*
 38888  Worldwide                 yandex.ru*

                               main_category yearmonth  ai_referrals  \
 34017                 Science_and_Education   2024-01           NaN
 34018                        News_and_Media   2024-01    391.679310
 34019                        News_and_Media   2024-01    152.861099
 34020                    Law_and_Government   2024-01           NaN
 34021                    Law_and_Government   2024-01           NaN
 ...                                     ...       ...           ...
 38884                   Reference_Materials   2024-05   2294.889350
 38885                   Reference_Materials   2024-05           NaN
 38886                 Science_and_Education   2024-05           NaN
 38887  Computers_Electronics_and_Technology   2024-05   4966.506446
 38888  Computers_Electronics_and_Technology   2024-05  77640.424000

        total_monthly_ai_referrals  search_traffic  \
 34017                         NaN    2.253429e+07
 34018                3.474923e+07    2.630263e+07
 34019                3.474923e+07    3.039119e+07
 34020                         NaN    3.737559e+07
 34021                         NaN    8.646302e+06
 ...                           ...             ...
 38884                1.520941e+08    5.008998e+07
 38885                         NaN    1.661602e+07
 38886                         NaN    2.324823e+07
 38887                1.520941e+08    1.165110e+07
 38888                1.520941e+08    4.792004e+08

        total_monthly_search_trafic                 cleaned_main_category
 34017                 2.350224e+11                 Science_and_Education
 34018                 2.350224e+11                        News_and_Media
 34019                 2.350224e+11                        News_and_Media
 34020                 2.350224e+11                    Law_and_Government
 34021                 2.350224e+11                    Law_and_Government
 ...                            ...                                   ...
 38884                 2.351901e+11                   Reference_Materials
 38885                 2.351901e+11                   Reference_Materials
 38886                 2.351901e+11                 Science_and_Education
 38887                 2.351901e+11  Computers_Electronics_and_Technology
 38888                 2.351901e+11  Computers_Electronics_and_Technology

 [4872 rows x 9 columns],
 '2025':          country                    site            main_category yearmonth  \
 45783  Worldwide            3bmeteo.com*    Science_and_Education   2025-01
 45784  Worldwide  agenziaentrate.gov.it*       Law_and_Government   2025-01
 45785  Worldwide             akakce.com*  E-commerce_and_Shopping   2025-01
 45786  Worldwide            allocine.fr*   Arts_and_Entertainment   2025-01
 45787  Worldwide         allrecipes.com*           Food_and_Drink   2025-01
 ...          ...                     ...                      ...       ...
 50766  Worldwide             usnews.com*           News_and_Media   2025-05
 50767  Worldwide              webmd.com*                   Health   2025-05
 50768  Worldwide             wetter.com*    Science_and_Education   2025-05
 50769  Worldwide                wiki.gg*                    Games   2025-05
 50770  Worldwide            wowhead.com*                    Games   2025-05

         ai_referrals  total_monthly_ai_referrals  search_traffic  \
 45783    3786.852557                7.899983e+08    3.193717e+07
 45784   37938.718793                7.899983e+08    1.088195e+07
 45785   23918.246031                7.899983e+08    3.008359e+07
 45786    3501.008890                7.899983e+08    3.657230e+07
 45787  137127.948341                7.899983e+08    8.147896e+07
 ...              ...                         ...             ...
 50766   77758.892999                1.329318e+09    2.114487e+07
 50767  272974.124311                1.329318e+09    3.637230e+07
 50768   20472.007460                1.329318e+09    3.945464e+07
 50769   24171.529771                1.329318e+09    1.752168e+07
 50770    5123.631750                1.329318e+09    2.316617e+07

        total_monthly_search_trafic    cleaned_main_category
 45783                 2.149571e+11    Science_and_Education
 45784                 2.149571e+11       Law_and_Government
 45785                 2.149571e+11  E-commerce_and_Shopping
 45786                 2.149571e+11   Arts_and_Entertainment
 45787                 2.149571e+11           Food_and_Drink
 ...                            ...                      ...
 50766                 1.964069e+11           News_and_Media
 50767                 1.964069e+11                   Health
 50768                 1.964069e+11    Science_and_Education
 50769                 1.964069e+11                    Games
 50770                 1.964069e+11                    Games

 [4988 rows x 9 columns]}

In [45]:
df_24_25_us_categories_red=df_24_25_us_categories.reset_index()
df_24_25_us_categories_red["perc_change"]=(df_24_25_us_categories_red["search_traffic_2025"]-df_24_25_us_categories_red["search_traffic_2024"])*100/df_24_25_us_categories_red["search_traffic_2024"]
df_24_25_us_categories_red.sort_values("perc_change", ascending=False, inplace=True)
df_24_25_us_categories_red

,cleaned_main_category,search_traffic_2024,search_traffic_2025,perc_change
3,Computers_Electronics_and_Technology,4.141861e+07,4.459505e+07,7.669104
7,Gambling,5.128967e+06,5.242786e+06,2.219128
0,Arts_and_Entertainment,2.173160e+07,2.157926e+07,-0.701032
8,Games,7.975105e+06,7.914383e+06,-0.761388
10,Heavy_Industry_and_Engineering,4.989884e+06,4.926688e+06,-1.266482
14,Law_and_Government,7.000241e+06,6.906512e+06,-1.338939
11,Hobbies_and_Leisure,5.400305e+06,5.319805e+06,-1.490658
20,Sports,1.075040e+07,1.043012e+07,-2.979233
17,Pets_and_Animals,4.941602e+06,4.772425e+06,-3.423519
19,Science_and_Education,1.084287e+07,1.027031e+07,-5.280469
4,E-commerce_and_Shopping,3.223999e+07,3.042607e+07,-5.626309
16,News_and_Media,2.150334e+07,2.019815e+07,-6.069701
22,Vehicles,8.077666e+06,7.566121e+06,-6.332842
5,Finance,9.754394e+06,9.070001e+06,-7.016247
15,Lifestyle,6.317563e+06,5.754246e+06,-8.916689
1,Business_and_Consumer_Services,2.087392e+07,1.865195e+07,-10.644712
2,Community_and_Society,8.854770e+06,7.870280e+06,-11.118195
13,Jobs_and_Career,3.687910e+07,3.228164e+07,-12.466302
6,Food_and_Drink,8.508900e+06,7.441120e+06,-12.548974
21,Travel_and_Tourism,9.936237e+06,8.583767e+06,-13.611491
18,Reference_Materials,5.506258e+07,4.583845e+07,-16.752079
12,Home_and_Garden,1.238134e+07,1.000099e+07,-19.225329
9,Health,1.718859e+07,1.251206e+07,-27.207166

In [128]:
df_24_25_world_categories_red=df_24_25_world_categories.reset_index()
df_24_25_world_categories_red["perc_change"]=(df_24_25_world_categories_red["search_traffic_2025"]-df_24_25_world_categories_red["search_traffic_2024"])*100/df_24_25_world_categories_red["search_traffic_2024"]
df_24_25_world_categories_red.sort_values("perc_change", ascending=False, inplace=True)
df_24_25_world_categories_red

,cleaned_main_category,search_traffic_2024,search_traffic_2025,perc_change
7,Gambling,1.818270e+07,6.438385e+07,254.094087
10,Hobbies_and_Leisure,2.101142e+07,2.495075e+07,18.748527
5,Finance,2.695209e+07,2.896298e+07,7.460975
8,Games,3.932020e+07,4.151084e+07,5.571279
3,Computers_Electronics_and_Technology,1.807347e+08,1.880362e+08,4.039870
20,Vehicles,2.312155e+07,2.400774e+07,3.832742
4,E-commerce_and_Shopping,6.353700e+07,6.446405e+07,1.459075
1,Business_and_Consumer_Services,3.870602e+07,3.745675e+07,-3.227574
0,Arts_and_Entertainment,1.102212e+08,1.062078e+08,-3.641212
13,Law_and_Government,3.312114e+07,3.191364e+07,-3.645694
6,Food_and_Drink,3.831638e+07,3.669660e+07,-4.227401
14,Lifestyle,3.070272e+07,2.940446e+07,-4.228496
15,News_and_Media,5.376138e+07,5.095206e+07,-5.225552
18,Sports,3.581830e+07,3.336245e+07,-6.856387
19,Travel_and_Tourism,3.445066e+07,3.164496e+07,-8.144098
17,Science_and_Education,4.682832e+07,4.155276e+07,-11.265744
16,Reference_Materials,2.509663e+08,2.207036e+08,-12.058452
11,Home_and_Garden,4.129390e+07,3.562779e+07,-13.721439
12,Jobs_and_Career,6.325279e+07,5.361390e+07,-15.238670
2,Community_and_Society,8.356756e+07,6.931235e+07,-17.058305
9,Health,5.122869e+07,3.776840e+07,-26.274904

In [138]:
df_world_2025_red=dict_of_files_world["2025"][["site","cleaned_main_category","yearmonth","search_traffic","ai_referrals","total_monthly_search_trafic"]]

In [139]:
df_world_2024_red=dict_of_files_world["2024"][["site","cleaned_main_category","yearmonth","search_traffic","ai_referrals","total_monthly_search_trafic"]]

In [140]:
df_us_2025_red=dict_of_files_us["2025"][["site","cleaned_main_category","yearmonth","search_traffic","ai_referrals","total_monthly_search_trafic"]]

In [141]:
df_us_2024_red=dict_of_files_us["2024"][["site","cleaned_main_category","yearmonth","search_traffic","ai_referrals","total_monthly_search_trafic"]]

In [143]:
df_merge_world_us_2025=pd.merge(df_world_2025_red,df_us_2025_red,how="left",on=["site","cleaned_main_category","yearmonth"],  suffixes=("_world", "_us"))
df_merge_world_us_2025["search_traffic_rest_of_world"]=df_merge_world_us_2025["search_traffic_world"]- df_merge_world_us_2025["search_traffic_us"].fillna(0)
df_merge_world_us_2025["ai_referrals_rest_of_world"]=df_merge_world_us_2025["ai_referrals_world"]- df_merge_world_us_2025["ai_referrals_us"].fillna(0)
df_merge_world_us_2025["total_monthly_search_trafic_rest_of_world"]=df_merge_world_us_2025["total_monthly_search_trafic_world"]- df_merge_world_us_2025["total_monthly_search_trafic_us"].fillna(0)

df_merge_world_us_2025

,site,cleaned_main_category,yearmonth,search_traffic_world,ai_referrals_world,total_monthly_search_trafic_world,search_traffic_us,ai_referrals_us,total_monthly_search_trafic_us,search_traffic_rest_of_world,ai_referrals_rest_of_world,total_monthly_search_trafic_rest_of_world
0,3bmeteo.com*,Science_and_Education,2025-01,3.193717e+07,3786.852557,2.149571e+11,NaN,NaN,NaN,3.193717e+07,3786.852557,2.149571e+11
1,agenziaentrate.gov.it*,Law_and_Government,2025-01,1.088195e+07,37938.718793,2.149571e+11,NaN,NaN,NaN,1.088195e+07,37938.718793,2.149571e+11
2,akakce.com*,E-commerce_and_Shopping,2025-01,3.008359e+07,23918.246031,2.149571e+11,NaN,NaN,NaN,3.008359e+07,23918.246031,2.149571e+11
3,allocine.fr*,Arts_and_Entertainment,2025-01,3.657230e+07,3501.008890,2.149571e+11,NaN,NaN,NaN,3.657230e+07,3501.008890,2.149571e+11
4,allrecipes.com*,Food_and_Drink,2025-01,8.147896e+07,137127.948341,2.149571e+11,6.266291e+07,61733.888932,3.393098e+10,1.881605e+07,75394.059410,1.810261e+11
...,...,...,...,...,...,...,...,...,...,...,...,...
4983,usnews.com*,News_and_Media,2025-05,2.114487e+07,77758.892999,1.964069e+11,1.851610e+07,43964.115377,3.189073e+10,2.628773e+06,33794.777622,1.645162e+11
4984,webmd.com*,Health,2025-05,3.637230e+07,272974.124311,1.964069e+11,2.220205e+07,105927.536697,3.189073e+10,1.417025e+07,167046.587613,1.645162e+11
4985,wetter.com*,Science_and_Education,2025-05,3.945464e+07,20472.007460,1.964069e+11,NaN,NaN,NaN,3.945464e+07,20472.007460,1.964069e+11
4986,wiki.gg*,Games,2025-05,1.752168e+07,24171.529771,1.964069e+11,5.332517e+06,2650.273499,3.189073e+10,1.218916e+07,21521.256272,1.645162e+11
4987,wowhead.com*,Games,2025-05,2.316617e+07,5123.631750,1.964069e+11,7.383889e+06,2118.654507,3.189073e+10,1.578228e+07,3004.977243,1.645162e+11

In [153]:
df_merge_world_us_2025_red=df_merge_world_us_2025[["site","cleaned_main_category","yearmonth","search_traffic_rest_of_world","ai_referrals_rest_of_world","total_monthly_search_trafic_rest_of_world"]]
df_merge_world_us_2025_red

,site,cleaned_main_category,yearmonth,search_traffic_rest_of_world,ai_referrals_rest_of_world,total_monthly_search_trafic_rest_of_world
0,3bmeteo.com*,Science_and_Education,2025-01,3.193717e+07,3786.852557,2.149571e+11
1,agenziaentrate.gov.it*,Law_and_Government,2025-01,1.088195e+07,37938.718793,2.149571e+11
2,akakce.com*,E-commerce_and_Shopping,2025-01,3.008359e+07,23918.246031,2.149571e+11
3,allocine.fr*,Arts_and_Entertainment,2025-01,3.657230e+07,3501.008890,2.149571e+11
4,allrecipes.com*,Food_and_Drink,2025-01,1.881605e+07,75394.059410,1.810261e+11
...,...,...,...,...,...,...
4983,usnews.com*,News_and_Media,2025-05,2.628773e+06,33794.777622,1.645162e+11
4984,webmd.com*,Health,2025-05,1.417025e+07,167046.587613,1.645162e+11
4985,wetter.com*,Science_and_Education,2025-05,3.945464e+07,20472.007460,1.964069e+11
4986,wiki.gg*,Games,2025-05,1.218916e+07,21521.256272,1.645162e+11
4987,wowhead.com*,Games,2025-05,1.578228e+07,3004.977243,1.645162e+11

In [155]:
df_merge_world_us_2025_red.rename(columns={"search_traffic_rest_of_world":"search_traffic","ai_referrals_rest_of_world":"ai_referrals","total_monthly_search_trafic_rest_of_world":"total_monthly_search_trafic"}, inplace=True)
df_merge_world_us_2025_red

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_90029/220839158.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge_world_us_2025_red.rename(columns={"search_traffic_rest_of_world":"search_traffic","ai_referrals_rest_of_world":"ai_referrals","total_monthly_search_trafic_rest_of_world":"total_monthly_search_trafic"}, inplace=True)

,site,cleaned_main_category,yearmonth,search_traffic,ai_referrals,total_monthly_search_trafic
0,3bmeteo.com*,Science_and_Education,2025-01,3.193717e+07,3786.852557,2.149571e+11
1,agenziaentrate.gov.it*,Law_and_Government,2025-01,1.088195e+07,37938.718793,2.149571e+11
2,akakce.com*,E-commerce_and_Shopping,2025-01,3.008359e+07,23918.246031,2.149571e+11
3,allocine.fr*,Arts_and_Entertainment,2025-01,3.657230e+07,3501.008890,2.149571e+11
4,allrecipes.com*,Food_and_Drink,2025-01,1.881605e+07,75394.059410,1.810261e+11
...,...,...,...,...,...,...
4983,usnews.com*,News_and_Media,2025-05,2.628773e+06,33794.777622,1.645162e+11
4984,webmd.com*,Health,2025-05,1.417025e+07,167046.587613,1.645162e+11
4985,wetter.com*,Science_and_Education,2025-05,3.945464e+07,20472.007460,1.964069e+11
4986,wiki.gg*,Games,2025-05,1.218916e+07,21521.256272,1.645162e+11
4987,wowhead.com*,Games,2025-05,1.578228e+07,3004.977243,1.645162e+11

In [156]:
df_merge_world_us_2024=pd.merge(df_world_2024_red,df_us_2024_red,how="left",on=["site","cleaned_main_category","yearmonth"],  suffixes=("_world", "_us"))
df_merge_world_us_2024["search_traffic_rest_of_world"]=df_merge_world_us_2024["search_traffic_world"]- df_merge_world_us_2024["search_traffic_us"].fillna(0)
df_merge_world_us_2024["ai_referrals_rest_of_world"]=df_merge_world_us_2024["ai_referrals_world"]- df_merge_world_us_2024["ai_referrals_us"].fillna(0)
df_merge_world_us_2024["total_monthly_search_trafic_rest_of_world"]=df_merge_world_us_2024["total_monthly_search_trafic_world"]- df_merge_world_us_2024["total_monthly_search_trafic_us"].fillna(0)


df_merge_world_us_2024

,site,cleaned_main_category,yearmonth,search_traffic_world,ai_referrals_world,total_monthly_search_trafic_world,search_traffic_us,ai_referrals_us,total_monthly_search_trafic_us,search_traffic_rest_of_world,ai_referrals_rest_of_world,total_monthly_search_trafic_rest_of_world
0,3bmeteo.com*,Science_and_Education,2024-01,2.253429e+07,NaN,2.350224e+11,NaN,NaN,NaN,2.253429e+07,NaN,2.350224e+11
1,abc.net.au*,News_and_Media,2024-01,2.630263e+07,391.679310,2.350224e+11,NaN,NaN,NaN,2.630263e+07,391.679310,2.350224e+11
2,abril.com.br*,News_and_Media,2024-01,3.039119e+07,152.861099,2.350224e+11,NaN,NaN,NaN,3.039119e+07,152.861099,2.350224e+11
3,acesso.gov.br*,Law_and_Government,2024-01,3.737559e+07,NaN,2.350224e+11,NaN,NaN,NaN,3.737559e+07,NaN,2.350224e+11
4,agenciatributaria.gob.es*,Law_and_Government,2024-01,8.646302e+06,NaN,2.350224e+11,NaN,NaN,NaN,8.646302e+06,NaN,2.350224e+11
...,...,...,...,...,...,...,...,...,...,...,...,...
4867,wiktionary.org*,Reference_Materials,2024-05,5.008998e+07,2294.889350,2.351901e+11,5.412874e+06,0.0,3.721678e+10,4.467710e+07,2294.889350,1.979733e+11
4868,word.tips*,Reference_Materials,2024-05,1.661602e+07,NaN,2.351901e+11,1.179956e+07,0.0,3.721678e+10,4.816466e+06,NaN,1.979733e+11
4869,wordwall.net*,Science_and_Education,2024-05,2.324823e+07,NaN,2.351901e+11,NaN,NaN,NaN,2.324823e+07,NaN,2.351901e+11
4870,wps.com*,Computers_Electronics_and_Technology,2024-05,1.165110e+07,4966.506446,2.351901e+11,NaN,NaN,NaN,1.165110e+07,4966.506446,2.351901e+11
4871,yandex.ru*,Computers_Electronics_and_Technology,2024-05,4.792004e+08,77640.424000,2.351901e+11,NaN,NaN,NaN,4.792004e+08,77640.424000,2.351901e+11

In [157]:
df_merge_world_us_2024_red=df_merge_world_us_2024[["site","cleaned_main_category","yearmonth","search_traffic_rest_of_world","ai_referrals_rest_of_world","total_monthly_search_trafic_rest_of_world"]]
df_merge_world_us_2024_red

,site,cleaned_main_category,yearmonth,search_traffic_rest_of_world,ai_referrals_rest_of_world,total_monthly_search_trafic_rest_of_world
0,3bmeteo.com*,Science_and_Education,2024-01,2.253429e+07,NaN,2.350224e+11
1,abc.net.au*,News_and_Media,2024-01,2.630263e+07,391.679310,2.350224e+11
2,abril.com.br*,News_and_Media,2024-01,3.039119e+07,152.861099,2.350224e+11
3,acesso.gov.br*,Law_and_Government,2024-01,3.737559e+07,NaN,2.350224e+11
4,agenciatributaria.gob.es*,Law_and_Government,2024-01,8.646302e+06,NaN,2.350224e+11
...,...,...,...,...,...,...
4867,wiktionary.org*,Reference_Materials,2024-05,4.467710e+07,2294.889350,1.979733e+11
4868,word.tips*,Reference_Materials,2024-05,4.816466e+06,NaN,1.979733e+11
4869,wordwall.net*,Science_and_Education,2024-05,2.324823e+07,NaN,2.351901e+11
4870,wps.com*,Computers_Electronics_and_Technology,2024-05,1.165110e+07,4966.506446,2.351901e+11
4871,yandex.ru*,Computers_Electronics_and_Technology,2024-05,4.792004e+08,77640.424000,2.351901e+11

In [158]:
df_merge_world_us_2024_red.rename(columns={"search_traffic_rest_of_world":"search_traffic","ai_referrals_rest_of_world":"ai_referrals","total_monthly_search_trafic_rest_of_world":"total_monthly_search_trafic"}, inplace=True)
df_merge_world_us_2024_red

/var/folders/m2/_syds9sn2bjctwpf6p3_w19r0000gn/T/ipykernel_90029/3725958313.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merge_world_us_2024_red.rename(columns={"search_traffic_rest_of_world":"search_traffic","ai_referrals_rest_of_world":"ai_referrals","total_monthly_search_trafic_rest_of_world":"total_monthly_search_trafic"}, inplace=True)

,site,cleaned_main_category,yearmonth,search_traffic,ai_referrals,total_monthly_search_trafic
0,3bmeteo.com*,Science_and_Education,2024-01,2.253429e+07,NaN,2.350224e+11
1,abc.net.au*,News_and_Media,2024-01,2.630263e+07,391.679310,2.350224e+11
2,abril.com.br*,News_and_Media,2024-01,3.039119e+07,152.861099,2.350224e+11
3,acesso.gov.br*,Law_and_Government,2024-01,3.737559e+07,NaN,2.350224e+11
4,agenciatributaria.gob.es*,Law_and_Government,2024-01,8.646302e+06,NaN,2.350224e+11
...,...,...,...,...,...,...
4867,wiktionary.org*,Reference_Materials,2024-05,4.467710e+07,2294.889350,1.979733e+11
4868,word.tips*,Reference_Materials,2024-05,4.816466e+06,NaN,1.979733e+11
4869,wordwall.net*,Science_and_Education,2024-05,2.324823e+07,NaN,2.351901e+11
4870,wps.com*,Computers_Electronics_and_Technology,2024-05,1.165110e+07,4966.506446,2.351901e+11
4871,yandex.ru*,Computers_Electronics_and_Technology,2024-05,4.792004e+08,77640.424000,2.351901e+11

In [159]:
dict_rest_of_world={"2024":df_merge_world_us_2024_red,
                   "2025":df_merge_world_us_2025_red}
dict_rest_of_world

{'2024':                            site                 cleaned_main_category  \
 0                  3bmeteo.com*                 Science_and_Education
 1                   abc.net.au*                        News_and_Media
 2                 abril.com.br*                        News_and_Media
 3                acesso.gov.br*                    Law_and_Government
 4     agenciatributaria.gob.es*                    Law_and_Government
 ...                         ...                                   ...
 4867            wiktionary.org*                   Reference_Materials
 4868                 word.tips*                   Reference_Materials
 4869              wordwall.net*                 Science_and_Education
 4870                   wps.com*  Computers_Electronics_and_Technology
 4871                 yandex.ru*  Computers_Electronics_and_Technology

      yearmonth  search_traffic  ai_referrals  total_monthly_search_trafic
 0      2024-01    2.253429e+07           NaN                 2.350224e+11
 1      2024-01    2.630263e+07    391.679310                 2.350224e+11
 2      2024-01    3.039119e+07    152.861099                 2.350224e+11
 3      2024-01    3.737559e+07           NaN                 2.350224e+11
 4      2024-01    8.646302e+06           NaN                 2.350224e+11
 ...        ...             ...           ...                          ...
 4867   2024-05    4.467710e+07   2294.889350                 1.979733e+11
 4868   2024-05    4.816466e+06           NaN                 1.979733e+11
 4869   2024-05    2.324823e+07           NaN                 2.351901e+11
 4870   2024-05    1.165110e+07   4966.506446                 2.351901e+11
 4871   2024-05    4.792004e+08  77640.424000                 2.351901e+11

 [4872 rows x 6 columns],
 '2025':                         site    cleaned_main_category yearmonth  \
 0               3bmeteo.com*    Science_and_Education   2025-01
 1     agenziaentrate.gov.it*       Law_and_Government   2025-01
 2                akakce.com*  E-commerce_and_Shopping   2025-01
 3               allocine.fr*   Arts_and_Entertainment   2025-01
 4            allrecipes.com*           Food_and_Drink   2025-01
 ...                      ...                      ...       ...
 4983             usnews.com*           News_and_Media   2025-05
 4984              webmd.com*                   Health   2025-05
 4985             wetter.com*    Science_and_Education   2025-05
 4986                wiki.gg*                    Games   2025-05
 4987            wowhead.com*                    Games   2025-05

       search_traffic   ai_referrals  total_monthly_search_trafic
 0       3.193717e+07    3786.852557                 2.149571e+11
 1       1.088195e+07   37938.718793                 2.149571e+11
 2       3.008359e+07   23918.246031                 2.149571e+11
 3       3.657230e+07    3501.008890                 2.149571e+11
 4       1.881605e+07   75394.059410                 1.810261e+11
 ...              ...            ...                          ...
 4983    2.628773e+06   33794.777622                 1.645162e+11
 4984    1.417025e+07  167046.587613                 1.645162e+11
 4985    3.945464e+07   20472.007460                 1.964069e+11
 4986    1.218916e+07   21521.256272                 1.645162e+11
 4987    1.578228e+07    3004.977243                 1.645162e+11

 [4988 rows x 6 columns]}

In [160]:
dict_rest_of_world["2025"]

,site,cleaned_main_category,yearmonth,search_traffic,ai_referrals,total_monthly_search_trafic
0,3bmeteo.com*,Science_and_Education,2025-01,3.193717e+07,3786.852557,2.149571e+11
1,agenziaentrate.gov.it*,Law_and_Government,2025-01,1.088195e+07,37938.718793,2.149571e+11
2,akakce.com*,E-commerce_and_Shopping,2025-01,3.008359e+07,23918.246031,2.149571e+11
3,allocine.fr*,Arts_and_Entertainment,2025-01,3.657230e+07,3501.008890,2.149571e+11
4,allrecipes.com*,Food_and_Drink,2025-01,1.881605e+07,75394.059410,1.810261e+11
...,...,...,...,...,...,...
4983,usnews.com*,News_and_Media,2025-05,2.628773e+06,33794.777622,1.645162e+11
4984,webmd.com*,Health,2025-05,1.417025e+07,167046.587613,1.645162e+11
4985,wetter.com*,Science_and_Education,2025-05,3.945464e+07,20472.007460,1.964069e+11
4986,wiki.gg*,Games,2025-05,1.218916e+07,21521.256272,1.645162e+11
4987,wowhead.com*,Games,2025-05,1.578228e+07,3004.977243,1.645162e+11

In [161]:
df_rest_of_world=mean_calc_comparer(dict_rest_of_world)
df_rest_of_world

,site,cleaned_main_category,search_traffic_2024,ai_referrals_2024,total_monthly_search_trafic_2024,search_traffic_2025,ai_referrals_2025,total_monthly_search_trafic_2025
0,123av.com*,Arts_and_Entertainment,NaN,NaN,NaN,2.986086e+07,1260.258921,1.997169e+11
1,163.com*,News_and_Media,8.013160e+07,2651.854759,2.301684e+11,6.470649e+07,271683.026581,1.997169e+11
2,1mg.com*,Health,3.871039e+07,568.763319,2.301684e+11,3.996439e+07,44361.843697,1.997169e+11
3,20minutes.fr*,News_and_Media,2.567792e+07,777.339151,2.301684e+11,2.657425e+07,12208.982899,1.997169e+11
4,20minutos.es*,News_and_Media,3.732997e+07,8018.503103,2.301684e+11,3.113946e+07,65971.673426,1.997169e+11
...,...,...,...,...,...,...,...,...
995,zara.com*,Lifestyle,3.219533e+07,0.000000,1.937167e+11,2.985439e+07,215613.283634,1.676849e+11
996,zdf.de*,Arts_and_Entertainment,2.676779e+07,2574.417074,2.301684e+11,2.792602e+07,128652.110028,1.997169e+11
997,zhihu.com*,Computers_Electronics_and_Technology,2.932434e+08,34454.079680,1.937167e+11,1.673908e+08,73203.806905,1.676849e+11
998,zillow.com*,Business_and_Consumer_Services,4.476647e+06,483.259590,1.937167e+11,4.582161e+06,63668.336004,1.676849e+11
999,zoom.us*,Computers_Electronics_and_Technology,1.015745e+08,186.503822,1.937167e+11,9.141365e+07,34802.254945,1.676849e+11

In [162]:
df_24_25_rest_of_world_categories=df_rest_of_world[["cleaned_main_category","search_traffic_2024","search_traffic_2025"]].groupby("cleaned_main_category").mean()
df_24_25_rest_of_world_categories

                                      search_traffic_2024  search_traffic_2025
cleaned_main_category
Arts_and_Entertainment                       9.167781e+07         8.884406e+07
Business_and_Consumer_Services               2.133106e+07         2.075560e+07
Community_and_Society                        7.690680e+07         6.309796e+07
Computers_Electronics_and_Technology         1.537365e+08         1.593863e+08
E-commerce_and_Shopping                      4.794284e+07         4.945038e+07
Finance                                      1.776933e+07         2.022208e+07
Food_and_Drink                               3.282960e+07         3.112648e+07
Gambling                                     1.818270e+07         6.438385e+07
Games                                        3.194343e+07         3.436023e+07
Health                                       3.284233e+07         2.450035e+07
Hobbies_and_Leisure                          1.818166e+07         2.141924e+07
Home_and_Garden                              2.161841e+07         2.044832e+07
Jobs_and_Career                              4.730504e+07         3.984631e+07
Law_and_Government                           3.128032e+07         3.008882e+07
Lifestyle                                    2.300945e+07         2.267783e+07
News_and_Media                               4.658877e+07         4.409304e+07
Reference_Materials                          1.948070e+08         1.739026e+08
Science_and_Education                        3.697875e+07         3.209931e+07
Sports                                       2.779567e+07         2.554595e+07
Travel_and_Tourism                           2.432002e+07         2.302804e+07
Vehicles                                     1.781396e+07         1.896984e+07

In [163]:
df_24_25_rest_of_world_categories_red=df_24_25_rest_of_world_categories.reset_index()
df_24_25_rest_of_world_categories_red["perc_change"]=(df_24_25_rest_of_world_categories_red["search_traffic_2025"]-df_24_25_rest_of_world_categories_red["search_traffic_2024"])*100/df_24_25_rest_of_world_categories_red["search_traffic_2024"]
df_24_25_rest_of_world_categories_red.sort_values("perc_change", ascending=False, inplace=True)
df_24_25_rest_of_world_categories_red

,cleaned_main_category,search_traffic_2024,search_traffic_2025,perc_change
7,Gambling,1.818270e+07,6.438385e+07,254.094087
10,Hobbies_and_Leisure,1.818166e+07,2.141924e+07,17.806841
5,Finance,1.776933e+07,2.022208e+07,13.803266
8,Games,3.194343e+07,3.436023e+07,7.565892
20,Vehicles,1.781396e+07,1.896984e+07,6.488668
3,Computers_Electronics_and_Technology,1.537365e+08,1.593863e+08,3.674986
4,E-commerce_and_Shopping,4.794284e+07,4.945038e+07,3.144450
14,Lifestyle,2.300945e+07,2.267783e+07,-1.441234
1,Business_and_Consumer_Services,2.133106e+07,2.075560e+07,-2.697728
0,Arts_and_Entertainment,9.167781e+07,8.884406e+07,-3.090981
13,Law_and_Government,3.128032e+07,3.008882e+07,-3.809115
6,Food_and_Drink,3.282960e+07,3.112648e+07,-5.187764
19,Travel_and_Tourism,2.432002e+07,2.302804e+07,-5.312427
15,News_and_Media,4.658877e+07,4.409304e+07,-5.356935
11,Home_and_Garden,2.161841e+07,2.044832e+07,-5.412454
18,Sports,2.779567e+07,2.554595e+07,-8.093759
16,Reference_Materials,1.948070e+08,1.739026e+08,-10.730804
17,Science_and_Education,3.697875e+07,3.209931e+07,-13.195277
12,Jobs_and_Career,4.730504e+07,3.984631e+07,-15.767319
2,Community_and_Society,7.690680e+07,6.309796e+07,-17.955291
9,Health,3.284233e+07,2.450035e+07,-25.400089

In [ ]:
# Was sind Hypothesen?
# 1. USA seit einem Jahr AI Zusammenfassung und darum deutlich grÃ¶ÃŸerer Einbruch
# 2. Englische AI-Zusammenfassungen sind besser und darum gibt es mehr Zerotraffics
# 3. In Deutschland geringe Auswirkungen, selten AI-Zusammenfassungen bei aktuellen Themen
# 4. So gigantisch ist der Traffic von Google im Vergleich zu OpenAI, trotz VertrÃ¤ge
# 5. Wie gut sind die Daten von Similarweb im Vergleich zu Google, Cloudflare?
# 6. Crawler vs echte Klicks

In [ ]:
#Branchenweise Unterschiede in den Daten anschaut

In [ ]:
#Welche Branchen sind am unabhÃ¤ngigsten von Schwankungen im Traffic?
#Reise abhÃ¤ngiger
#Banken unabhÃ¤ngiger

In [ ]:
#Wie groÃŸ ist USA vs. Rest der Welt? Diff bei Schwankungen?
#AI-Zeroclicks?

In [ ]:
#Kleinere Anbieter kapern

In [ ]:
#US sind selbst im selben Monat, selbe Seite der Traffic, der nur aus den USA kommt

In [ ]:
#FrÃ¼here Schwankungen versus Schwankungen durch AI