In [2]:
import pandas as pd

In [4]:
nuts_codes=pd.read_excel("/Users/halukamaier-borst/Documents/CodeRelated/HBDataviz_new/2025/08_Trumptracker/Wrangle/data/NUTS2021-NUTS2024.xlsx")
nuts_codes

,Country code,NUTS Code,NUTS label,NUTS level,Country order,#
0,BE,BE1,Région de Bruxelles-Capitale/Brussels Hoofdste...,1,1,1
1,BE,BE10,Région de Bruxelles-Capitale/Brussels Hoofdste...,2,1,2
2,BE,BE100,Arr. de Bruxelles-Capitale/Arr. Brussel-Hoofdstad,3,1,3
3,BE,BE2,Vlaams Gewest,1,1,4
4,BE,BE21,Prov. Antwerpen,2,1,5
...,...,...,...,...,...,...
1577,SE,SE331,Västerbottens län,3,27,1578
1578,SE,SE332,Norrbottens län,3,27,1579
1579,SE,SEZ,Extra-Regio NUTS 1,1,27,1580
1580,SE,SEZZ,Extra-Regio NUTS 2,2,27,1581
1581,SE,SEZZZ,Extra-Regio NUTS 3,3,27,1582

In [6]:
nuts_codes_2=nuts_codes[nuts_codes["NUTS level"]==2]
nuts_codes_2

,Country code,NUTS Code,NUTS label,NUTS level,Country order,#
1,BE,BE10,Région de Bruxelles-Capitale/Brussels Hoofdste...,2,1,2
4,BE,BE21,Prov. Antwerpen,2,1,5
8,BE,BE22,Prov. Limburg (BE),2,1,9
12,BE,BE23,Prov. Oost-Vlaanderen,2,1,13
19,BE,BE24,Prov. Vlaams-Brabant,2,1,20
...,...,...,...,...,...,...
1565,SE,SE23,Västsverige,2,27,1566
1569,SE,SE31,Norra Mellansverige,2,27,1570
1573,SE,SE32,Mellersta Norrland,2,27,1574
1576,SE,SE33,Övre Norrland,2,27,1577
1580,SE,SEZZ,Extra-Regio NUTS 2,2,27,1581

In [14]:
nuts2_mapping = {
    'Southern Ireland': 'IE05',
    'Hovedstaden': 'DK01',
    'Eastern and Midland Ireland': 'IE06',
    'Prov. Antwerpen': 'BE21',
    'Rhône-Alpes': 'FRK2',
    'Stockholm': 'SE11',
    'Darmstadt': 'DE71',
    'Île de France': 'FR10',
    'Prov. Brabant wallon': 'BE31',
    'Cataluña': 'ES51',
    'Northern and Western': 'IE04',
    'Lombardia': 'ITC4',
    'Västsverige': 'SE23',
    'Sjælland': 'DK02',
    'Tübingen': 'DE14',
    'Noord-Brabant': 'NL41',
    'Karlsruhe': 'DE12',
    'Östra Mellansverige': 'SE12',
    'Rheinhessen-Pfalz': 'DEB3',
    'Lazio': 'ITI4',
    'Berlin': 'DE30',
    'Zuid-Holland': 'NL33',
    'Comunidad de Madrid': 'ES30',
    'Attiki': 'EL30',
    'Köln': 'DEA2',
    'Noord-Holland': 'NL32',
    'Gießen': 'DE72',
    'Schleswig-Holstein': 'DEF0',
    'Freiburg': 'DE13',
    'Toscana': 'ITI1',
    'Sachsen-Anhalt': 'DEE0',
    'Budapest': 'HU11',
    'Sydsverige': 'SE22',
    'Tirol': 'AT33',
    'Oberbayern': 'DE21',
    'Wien': 'AT13',
    'Haute-Normandie': 'FRD1',
    'Alsace': 'FRF1',
    'Emilia-Romagna': 'ITH5',
    'Nordjylland': 'DK05',
    'Veneto': 'ITH3',
    'Zahodna Slovenija': 'SI04',
    'Vzhodna Slovenija': 'SI03',
    'Kassel': 'DE73',
    'Centre - Val de Loire': 'FRB0',
    "Provence-Alpes-Côte d'Azur": 'FRL0',
    'Prov. Hainaut': 'BE32',
    'Arnsberg': 'DEA5',
    'Área Metropolitana de Lisboa': 'PT17',
    'Koblenz': 'DEB1',
    'Helsinki-Uusimaa': 'FI1B',
    'Basse-Normandie': 'FRD2',
    'Etelä-Suomi': 'FI1C',
    'Syddanmark': 'DK03',
    'Nord-Pas-de-Calais': 'FRC1',
    'Castilla y León': 'ES41',
    'Hannover': 'DE92',
    'Hamburg': 'DE60',
    'Gelderland': 'NL22',
    'Brandenburg': 'DE40',
    'Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest': 'BE10',
    'Prov. Oost-Vlaanderen': 'BE23',
    'Piemonte': 'ITC1',
    'Detmold': 'DEA4',
    'Mazowiecki regionalny': 'PL91',
    'Oberpfalz': 'DE23',
    'Prov. Vlaams-Brabant': 'BE24',
    'Utrecht': 'NL31',
    'Münster': 'DEA3',
    'Drenthe': 'NL13',
    'Düsseldorf': 'DEA1',
    'Thüringen': 'DEG0',
    'Praha': 'CZ01',
    'Oberösterreich': 'AT31',
    'Picardie': 'FRC2',
    'Marche': 'ITI3',
    'Steiermark': 'AT22',
    'Castilla-la Mancha': 'ES42',
    'Mecklenburg-Vorpommern': 'DE80',
    'Comunidad Foral de Navarra': 'ES22',
    'Jihovýchod': 'CZ06',
    'Languedoc-Roussillon': 'FRJ1',
    'Campania': 'ITF3',
    'Aragón': 'ES24',
    'Moravskoslezsko': 'CZ08',
    'Overijssel': 'NL21',
    'Lüneburg': 'DE93',
    'Zeeland': 'NL34',
    'Lorraine': 'FRF3',
    'Yugozapaden': 'BG41',
    'Abruzzo': 'ITF1',
    'Sterea Ellada': 'EL24',
    'Észak-Alföld': 'HU32',
    'Centro (PT)': 'PT16',
    'Auvergne': 'FRK1',
    'Warszawski stoleczny': 'PL92',
    'Weser-Ems': 'DE94',
    'Bucuresti - Ilfov': 'RO32',
    'Bourgogne': 'FRD4',
    'Lódzkie': 'PL71',
    'Grad Zagreb': 'HR04',
    'Norte': 'PT11',
    'Pomorskie': 'PL63',
    'Limousin': 'FRI2',
    'Sicilia': 'ITG1',
    'Strední Cechy': 'CZ02',
    'Niederösterreich': 'AT12',
    'Sjeverna Hrvatska': 'HR05',
    'Pest': 'HU12',
    'Kärnten': 'AT21',
    'Oberfranken': 'DE24',
    'Övre Norrland': 'SE33',
    'Mellersta Norrland': 'SE32',
    'País Vasco': 'ES21',
    'Pohjois- ja Itä-Suomi': 'FI1D',
    'Dolnoslaskie': 'PL51',
    'Champagne-Ardenne': 'FRF2',
    'Flevoland': 'NL23',
    'Prov. Liège': 'BE33',
    'Bratislavský kraj': 'SK01',
    'Cantabria': 'ES13',
    'Braunschweig': 'DE91',
    'Puglia': 'ITF4',
    'Bretagne': 'FRH0',
    'Schwaben': 'DE27',
    'Saarland': 'DEC0',
    'Andalucía': 'ES61',
    'Galicia': 'ES11',
    'Limburg (NL)': 'NL42',
    'Länsi-Suomi': 'FI19',
    'La Réunion': 'FRY4',
    'Niederbayern': 'DE22',
    'Wielkopolskie': 'PL52',
    'Aquitaine': 'FRI1',
    'Prov. Namur': 'BE35',
    'Friuli-Venezia Giulia': 'ITH4',
    'Közép-Dunántúl': 'HU21',
    'Liguria': 'ITC3',
    'Región de Murcia': 'ES62',
    'Midtjylland': 'DK04',
    'Salzburg': 'AT32',
    'Norra Mellansverige': 'SE31',
    'Friesland (NL)': 'NL12',
    'Kentriki Makedonia': 'EL52',
    'Centru': 'RO12',
    'Prov. Luxembourg (BE)': 'BE34',
    'Chemnitz': 'DED4',
    'Stuttgart': 'DE11',
    'Prov. West-Vlaanderen': 'BE25',
    'Comunitat Valenciana': 'ES52',
    'Malopolskie': 'PL62',
    'Provincia Autonoma di Trento': 'ITD2',
    'Yugoiztochen': 'BG34',
    'Leipzig': 'DED5',
    'Severovýchod': 'CZ05',
    'Jadranska Hrvatska': 'HR03',
    'Dél-Dunántúl': 'HU23',
    'Nyugat-Dunántúl': 'HU22',
    'Bremen': 'DE50',
    'Észak-Magyarország': 'HU31',
    'Podkarpackie': 'PL62',
    'Severen tsentralen': 'BG32',
    'Mittelfranken': 'DE25',
    'Pays-de-la-Loire': 'FRG0',
    'Molise': 'ITF2',
    'Guadeloupe': 'FRY1',
    'Martinique': 'FRY2',
    'Groningen': 'NL11',
    'Yuzhen tsentralen': 'BG42',
    'La Rioja': 'ES23',
    'Principado de Asturias': 'ES12',
    'Nord-Vest': 'RO11',
    'Dresden': 'DED2',
    'Strední Morava': 'CZ07',
    'Stredné Slovensko': 'SK03',
    'Opolskie': 'PL52',
    'Západné Slovensko': 'SK02',
    'Sud - Muntenia': 'RO31',
    'Burgenland (AT)': 'AT11',
    'Umbria': 'ITI2',
    'Guyane': 'FRY3',
    'Prov. Limburg (BE)': 'BE22',
    'Lubelskie': 'PL81',
    'Severozapaden': 'BG31',
    'Dél-Alföld': 'HU33',
    'Basilicata': 'ITF5',
    'Småland med öarna': 'SE21',
    'Severozápad': 'CZ04',
    'Lubuskie': 'PL43',
    'Vest': 'RO42',
    'Mayotte': 'FRY5',
    'Illes Balears': 'ES53',
    'Slaskie': 'PL22',
    'Midi-Pyrénées': 'FRJ2',
    'Kujawsko-Pomorskie': 'PL61',
    'Jihozápad': 'CZ03',
    'Alentejo': 'PT18',
    'Panonska Hrvatska': 'HR06',
    'Vorarlberg': 'AT34',
    'Warminsko-Mazurskie': 'PL62',
    'Swietokrzyskie': 'PL72',
    'Dytiki Ellada': 'EL23',
    'Sardegna': 'ITG2',
    'Východné Slovensko': 'SK04',
    'Canarias': 'ES70',
    'Calabria': 'ITF6',
    'Peloponnisos': 'EL25',
    'Thessalia': 'EL14',
    'Zachodniopomorskie': 'PL42',
    'Voreio Aigaio': 'EL41',
    'Ionia Nisia': 'EL42',
    'Kriti': 'EL43',
    'Dytiki Makedonia': 'EL53',
    'Ipeiros': 'EL54',
    'Anatoliki Makedonia, Thraki': 'EL51',
    'Notio Aigaio': 'EL42',
    'Franche-Comté': 'FRF4',
    'Poitou-Charentes': 'FRI3',
    'Åland': 'FI20',
    'Ciudad de Ceuta': 'ES63',
    'Ciudad de Melilla': 'ES64',
    'Extremadura': 'ES43',
    'Corse': 'FRM0',
    'Sud-Est': 'RO22',
    'Severoiztochen': 'BG33',
    'Algarve': 'PT15',
    "Valle d'Aosta/Vallée d'Aoste": 'ITC2',
    'Região Autónoma dos Açores (PT)': 'PT20',
    'Trier': 'DEB2',
    'Região Autónoma da Madeira (PT)': 'PT30',
    'Nord-Est': 'RO21',
    'Provincia Autonoma di Bolzano/Bozen': 'ITD1',
    'Unterfranken': 'DE26',
    'Sud-Vest Oltenia': 'RO41',
    'Podlaskie': 'PL84',
    'Vidurio ir vakaru Lietuvos regionas': 'LT01',
    'Sostines regionas': 'LT02'
}

In [15]:
pharma_share=pd.read_excel("/Users/halukamaier-borst/Documents/CodeRelated/HBDataviz_new/2025/08_Trumptracker/Wrangle/data/Trump_Tariffs_RB_0325.xlsx",sheet_name="Chart 4")
pharma_share

,NUTS2,"Pharmaceutical Manufacturing, GVA, 2023, level, €bn","Pharmaceutical Manufacturing, share of GDP, 2023"
0,Southern Ireland,6.317104e+01,3.714373e+01
1,Hovedstaden,2.345101e+01,1.455935e+01
2,Eastern and Midland Ireland,1.964800e+01,8.339854e+00
3,Prov. Antwerpen,6.820217e+00,7.325747e+00
4,Rhône-Alpes,5.325956e+00,2.215931e+00
...,...,...,...
234,Podlaskie,1.833939e-07,1.464221e-06
235,Vidurio ir vakaru Lietuvos regionas,9.916776e-08,3.694194e-07
236,Sostines regionas,1.053298e-12,4.889712e-12
237,NaN,NaN,NaN
238,Source: Oxford Economics,NaN,NaN

In [38]:
auto_share=pd.read_excel("/Users/halukamaier-borst/Documents/CodeRelated/HBDataviz_new/2025/08_Trumptracker/Wrangle/data/Trump_Tariffs_RB_0325.xlsx",sheet_name="Chart 6")
auto_share

,"NUTS2, Germany","Vehicle Manufacturing, GVA, 2023, level, €bn","Regional Location Quotient for Vehicle Manufacturing, 2023"
0,Stuttgart,35.731643,3.240571
1,Karlsruhe,7.841677,1.233498
2,Freiburg,1.616638,0.366213
3,Tübingen,4.577075,1.092624
4,Oberbayern,29.710958,2.015373
...,...,...,...
234,NaN,NaN,NaN
235,NaN,NaN,NaN
236,NaN,NaN,NaN
237,NaN,NaN,NaN
238,Source: Oxford Economics,NaN,NaN

In [39]:
auto_share["Vehicle Manufacturing, GVA, 2023, level, €bn"]=auto_share["Vehicle Manufacturing, GVA, 2023, level, €bn"].round(1)
auto_share["Regional Location Quotient for Vehicle Manufacturing, 2023"]=auto_share["Regional Location Quotient for Vehicle Manufacturing, 2023"].round(1)

In [34]:
pharma_share["Pharmaceutical Manufacturing, GVA, 2023, level, €bn"]=pharma_share["Pharmaceutical Manufacturing, GVA, 2023, level, €bn"].round(1)
pharma_share["Pharmaceutical Manufacturing, share of GDP, 2023"]=pharma_share["Pharmaceutical Manufacturing, share of GDP, 2023"].round(1)

In [35]:
pharma_share['NUTS2_Code'] = pharma_share['NUTS2'].map(nuts2_mapping)
pharma_share

,NUTS2,"Pharmaceutical Manufacturing, GVA, 2023, level, €bn","Pharmaceutical Manufacturing, share of GDP, 2023",NUTS2_Code
0,Southern Ireland,63.2,37.1,IE05
1,Hovedstaden,23.5,14.6,DK01
2,Eastern and Midland Ireland,19.6,8.3,IE06
3,Prov. Antwerpen,6.8,7.3,BE21
4,Rhône-Alpes,5.3,2.2,FRK2
...,...,...,...,...
232,Unterfranken,0.0,0.0,DE26
233,Sud-Vest Oltenia,0.0,0.0,RO41
234,Podlaskie,0.0,0.0,PL84
235,Vidurio ir vakaru Lietuvos regionas,0.0,0.0,LT01
236,Sostines regionas,0.0,0.0,LT02

In [41]:
auto_share['NUTS2_Code'] = auto_share['NUTS2, Germany'].map(nuts2_mapping)
auto_share

,"NUTS2, Germany","Vehicle Manufacturing, GVA, 2023, level, €bn","Regional Location Quotient for Vehicle Manufacturing, 2023",NUTS2_Code
0,Stuttgart,35.7,3.2,DE11
1,Karlsruhe,7.8,1.2,DE12
2,Freiburg,1.6,0.4,DE13
3,Tübingen,4.6,1.1,DE14
4,Oberbayern,29.7,2.0,DE21
...,...,...,...,...
234,NaN,NaN,NaN,NaN
235,NaN,NaN,NaN,NaN
236,NaN,NaN,NaN,NaN
237,NaN,NaN,NaN,NaN
238,Source: Oxford Economics,NaN,NaN,NaN

In [36]:
pharma_share=pharma_share.dropna(subset=["Pharmaceutical Manufacturing, share of GDP, 2023"])
pharma_share

,NUTS2,"Pharmaceutical Manufacturing, GVA, 2023, level, €bn","Pharmaceutical Manufacturing, share of GDP, 2023",NUTS2_Code
0,Southern Ireland,63.2,37.1,IE05
1,Hovedstaden,23.5,14.6,DK01
2,Eastern and Midland Ireland,19.6,8.3,IE06
3,Prov. Antwerpen,6.8,7.3,BE21
4,Rhône-Alpes,5.3,2.2,FRK2
...,...,...,...,...
232,Unterfranken,0.0,0.0,DE26
233,Sud-Vest Oltenia,0.0,0.0,RO41
234,Podlaskie,0.0,0.0,PL84
235,Vidurio ir vakaru Lietuvos regionas,0.0,0.0,LT01
236,Sostines regionas,0.0,0.0,LT02

In [37]:
pharma_share.to_csv("/Users/halukamaier-borst/Documents/CodeRelated/HBDataviz_new/2025/08_Trumptracker/Wrangle/scripts/nuts_pharma.csv",index=False)

In [44]:
auto_share=auto_share.dropna(subset=["Vehicle Manufacturing, GVA, 2023, level, €bn"])
auto_share.to_csv("/Users/halukamaier-borst/Documents/CodeRelated/HBDataviz_new/2025/08_Trumptracker/Wrangle/scripts/nuts_auto.csv",index=False)

In [13]:
pharma_share.NUTS2.tolist()

['Southern Ireland',
 'Hovedstaden',
 'Eastern and Midland Ireland',
 'Prov. Antwerpen',
 'Rhône-Alpes',
 'Stockholm',
 'Darmstadt',
 'Île de France',
 'Prov. Brabant wallon',
 'Cataluña',
 'Northern and Western',
 'Lombardia',
 'Västsverige',
 'Sjælland',
 'Tübingen',
 'Noord-Brabant',
 'Karlsruhe',
 'Östra Mellansverige',
 'Rheinhessen-Pfalz',
 'Lazio',
 'Berlin',
 'Zuid-Holland',
 'Comunidad de Madrid',
 'Attiki',
 'Köln',
 'Noord-Holland',
 'Gießen',
 'Schleswig-Holstein',
 'Freiburg',
 'Toscana',
 'Sachsen-Anhalt',
 'Budapest',
 'Sydsverige',
 'Tirol',
 'Oberbayern',
 'Wien',
 'Haute-Normandie',
 'Alsace',
 'Emilia-Romagna',
 'Nordjylland',
 'Veneto',
 'Zahodna Slovenija',
 'Vzhodna Slovenija',
 'Kassel',
 'Centre - Val de Loire',
 "Provence-Alpes-Côte d'Azur",
 'Prov. Hainaut',
 'Arnsberg',
 'Área Metropolitana de Lisboa',
 'Koblenz',
 'Helsinki-Uusimaa',
 'Basse-Normandie',
 'Etelä-Suomi',
 'Syddanmark',
 'Nord-Pas-de-Calais',
 'Castilla y León',
 'Hannover',
 'Hamburg',
 'Gelderland',
 'Brandenburg',
 'Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest',
 'Prov. Oost-Vlaanderen',
 'Piemonte',
 'Detmold',
 'Mazowiecki regionalny',
 'Oberpfalz',
 'Prov. Vlaams-Brabant',
 'Utrecht',
 'Münster',
 'Drenthe',
 'Düsseldorf',
 'Thüringen',
 'Praha',
 'Oberösterreich',
 'Picardie',
 'Marche',
 'Steiermark',
 'Castilla-la Mancha',
 'Mecklenburg-Vorpommern',
 'Comunidad Foral de Navarra',
 'Jihovýchod',
 'Languedoc-Roussillon',
 'Campania',
 'Aragón',
 'Moravskoslezsko',
 'Overijssel',
 'Lüneburg',
 'Zeeland',
 'Lorraine',
 'Yugozapaden',
 'Abruzzo',
 'Sterea Ellada',
 'Észak-Alföld',
 'Centro (PT)',
 'Auvergne',
 'Warszawski stoleczny',
 'Weser-Ems',
 'Bucuresti - Ilfov',
 'Bourgogne',
 'Lódzkie',
 'Grad Zagreb',
 'Norte',
 'Pomorskie',
 'Limousin',
 'Sicilia',
 'Strední Cechy',
 'Niederösterreich',
 'Sjeverna Hrvatska',
 'Pest',
 'Kärnten',
 'Oberfranken',
 'Övre Norrland',
 'Mellersta Norrland',
 'País Vasco',
 'Pohjois- ja Itä-Suomi',
 'Dolnoslaskie',
 'Champagne-Ardenne',
 'Flevoland',
 'Prov. Liège',
 'Bratislavský kraj',
 'Cantabria',
 'Braunschweig',
 'Puglia',
 'Bretagne',
 'Schwaben',
 'Saarland',
 'Andalucía',
 'Galicia',
 'Limburg (NL)',
 'Länsi-Suomi',
 'La Réunion',
 'Niederbayern',
 'Wielkopolskie',
 'Aquitaine',
 'Prov. Namur',
 'Friuli-Venezia Giulia',
 'Közép-Dunántúl',
 'Liguria',
 'Región de Murcia',
 'Midtjylland',
 'Salzburg',
 'Norra Mellansverige',
 'Friesland (NL)',
 'Kentriki Makedonia',
 'Centru',
 'Prov. Luxembourg (BE)',
 'Chemnitz',
 'Stuttgart',
 'Prov. West-Vlaanderen',
 'Comunitat Valenciana',
 'Malopolskie',
 'Provincia Autonoma di Trento',
 'Yugoiztochen',
 'Leipzig',
 'Severovýchod',
 'Jadranska Hrvatska',
 'Dél-Dunántúl',
 'Nyugat-Dunántúl',
 'Bremen',
 'Észak-Magyarország',
 'Podkarpackie',
 'Severen tsentralen',
 'Mittelfranken',
 'Pays-de-la-Loire',
 'Molise',
 'Guadeloupe',
 'Martinique',
 'Groningen',
 'Yuzhen tsentralen',
 'La Rioja',
 'Principado de Asturias',
 'Nord-Vest',
 'Dresden',
 'Strední Morava',
 'Stredné Slovensko',
 'Opolskie',
 'Západné Slovensko',
 'Sud - Muntenia',
 'Burgenland (AT)',
 'Umbria',
 'Guyane',
 'Prov. Limburg (BE)',
 'Lubelskie',
 'Severozapaden',
 'Dél-Alföld',
 'Basilicata',
 'Småland med öarna',
 'Severozápad',
 'Lubuskie',
 'Vest',
 'Mayotte',
 'Illes Balears',
 'Slaskie',
 'Midi-Pyrénées',
 'Kujawsko-Pomorskie',
 'Jihozápad',
 'Alentejo',
 'Panonska Hrvatska',
 'Vorarlberg',
 'Warminsko-Mazurskie',
 'Swietokrzyskie',
 'Dytiki Ellada',
 'Sardegna',
 'Východné Slovensko',
 'Canarias',
 'Calabria',
 'Peloponnisos',
 'Thessalia',
 'Zachodniopomorskie',
 'Voreio Aigaio',
 'Ionia Nisia',
 'Kriti',
 'Dytiki Makedonia',
 'Ipeiros',
 'Anatoliki Makedonia, Thraki',
 'Notio Aigaio',
 'Franche-Comté',
 'Poitou-Charentes',
 'Åland',
 'Ciudad de Ceuta',
 'Ciudad de Melilla',
 'Extremadura',
 'Corse',
 'Sud-Est',
 'Severoiztochen',
 'Algarve',
 "Valle d'Aosta/Vallée d'Aoste",
 'Região Autónoma dos Açores (PT)',
 'Trier',
 'Região Autónoma da Madeira (PT)',
 'Nord-Est',
 'Provincia Autonoma di Bolzano/Bozen',
 'Unterfranken',
 'Sud-Vest Oltenia',
 'Podlaskie',
 'Vidurio ir vakaru Lietuvos regionas',
 'Sostines regionas',
 nan,
 'Source: Oxford Economics']

In [11]:
pharma_nuts2=pd.merge(nuts_codes_2,pharma_share,left_on="NUTS label",right_on="NUTS2",how="left")
pharma_nuts2

,Country code,NUTS Code,NUTS label,NUTS level,Country order,#,NUTS2,"Pharmaceutical Manufacturing, GVA, 2023, level, €bn","Pharmaceutical Manufacturing, share of GDP, 2023"
0,BE,BE10,Région de Bruxelles-Capitale/Brussels Hoofdste...,2,1,2,Région de Bruxelles-Capitale/Brussels Hoofdste...,0.446963,0.532748
1,BE,BE21,Prov. Antwerpen,2,1,5,Prov. Antwerpen,6.820217,7.325747
2,BE,BE22,Prov. Limburg (BE),2,1,9,Prov. Limburg (BE),0.018031,0.061459
3,BE,BE23,Prov. Oost-Vlaanderen,2,1,13,Prov. Oost-Vlaanderen,0.432742,0.735866
4,BE,BE24,Prov. Vlaams-Brabant,2,1,20,Prov. Vlaams-Brabant,0.353790,0.639124
...,...,...,...,...,...,...,...,...,...
266,SE,SE23,Västsverige,2,27,1566,Västsverige,3.572278,3.496906
267,SE,SE31,Norra Mellansverige,2,27,1570,Norra Mellansverige,0.062887,0.194677
268,SE,SE32,Mellersta Norrland,2,27,1574,Mellersta Norrland,0.143465,0.907857
269,SE,SE33,Övre Norrland,2,27,1577,Övre Norrland,0.146377,0.594791
270,SE,SEZZ,Extra-Regio NUTS 2,2,27,1581,NaN,NaN,NaN