In [1]:
import pandas as pd

In [29]:
current_europe_election=pd.read_csv("../data/kerg.csv",skiprows=2, sep=';',dtype=str)
current_europe_election=current_europe_election[(current_europe_election["Nr"].str.len()>4)]
current_europe_election[current_europe_election["Nr"]=="03159"]

,Nr,Gebiet,gehört zu,Wahlberechtigte,Unnamed: 4,Wählende,Unnamed: 6,Ungültige Stimmen,Unnamed: 8,Gültige Stimmen,...,Unnamed: 74,Partei der Vernunft,Unnamed: 76,Partei des Fortschritts,Unnamed: 78,"V-Partei³ - Partei für Veränderung, Vegetarier und Veganer",Unnamed: 80,Übrige,Unnamed: 82,Unnamed: 83
31,03159,Göttingen,03,248651,253354,158769,152703,923,745,157846,...,NaN,93,NaN,797,NaN,194,NaN,NaN,2807,NaN

In [3]:
columnarray=[]
for columnname in current_europe_election.columns:
    
    if("Unnamed" in columnname):
        columnarray.append(previousrow+"_2019")
    else:
        columnarray.append(columnname+"_2024")
    previousrow=columnname
current_europe_election.columns=columnarray
current_europe_election=current_europe_election.dropna(subset=["Gebiet_2024"])
current_europe_election

,Nr_2024,Gebiet_2024,gehört zu_2024,Wahlberechtigte_2024,Wahlberechtigte_2019,Wählende_2024,Wählende_2019,Ungültige Stimmen_2024,Ungültige Stimmen_2019,Gültige Stimmen_2024,...,Parlament aufmischen – Stimme der Letzten Generation_2019,Partei der Vernunft_2024,Partei der Vernunft_2019,Partei des Fortschritts_2024,Partei des Fortschritts_2019,"V-Partei³ - Partei für Veränderung, Vegetarier und Veganer_2024","V-Partei³ - Partei für Veränderung, Vegetarier und Veganer_2019",Übrige_2024,Übrige_2019,Unnamed: 82_2019
2,01001,"Flensburg, Stadt",01,70929,70431,41851,39647,299,237,41552,...,NaN,43,NaN,340,NaN,87,NaN,NaN,732,NaN
3,01002,"Kiel, Landeshauptstadt",01,187041,186195,117097,109595,550,577,116547,...,NaN,63,NaN,832,NaN,210,NaN,NaN,1733,NaN
4,01003,"Lübeck, Hansestadt",01,166429,166530,96558,90946,604,461,95954,...,NaN,79,NaN,604,NaN,158,NaN,NaN,1401,NaN
5,01004,"Neumünster, Stadt",01,59983,60215,33019,29036,282,231,32737,...,NaN,24,NaN,313,NaN,53,NaN,NaN,582,NaN
6,01051,Dithmarschen,01,108756,107045,68033,58244,506,475,67527,...,NaN,55,NaN,421,NaN,77,NaN,NaN,1055,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,16073,Saalfeld-Rudolstadt,16,84724,88342,49575,53882,329,1034,49246,...,NaN,38,NaN,172,NaN,41,NaN,NaN,1736,NaN
428,16074,Saale-Holzland-Kreis,16,67684,68278,45600,45101,411,1003,45189,...,NaN,31,NaN,145,NaN,52,NaN,NaN,1500,NaN
429,16075,Saale-Orla-Kreis,16,64882,67029,38507,42514,183,884,38324,...,NaN,27,NaN,98,NaN,29,NaN,NaN,1359,NaN
430,16076,Greiz,16,80024,82940,52514,53197,509,1139,52005,...,NaN,37,NaN,147,NaN,49,NaN,NaN,1833,NaN
431,16077,Altenburger Land,16,72674,75936,43444,42954,386,1053,43058,...,NaN,36,NaN,112,NaN,50,NaN,NaN,1461,NaN

In [4]:
current_europe_election_afd=current_europe_election[["Nr_2024","Gebiet_2024","Gültige Stimmen_2024","Alternative für Deutschland_2024"]]
election_dict={"2024":current_europe_election_afd}
current_europe_election_afd[current_europe_election_afd["Nr_2024"]=="11000"]

,Nr_2024,Gebiet_2024,Gültige Stimmen_2024,Alternative für Deutschland_2024
346,11000,"Berlin, Stadt",1545022,179298

In [5]:
latest_german_election=pd.read_csv("../data/btw2021kreis.csv",skiprows=4, sep=';',dtype=str)
latest_german_election=latest_german_election[(latest_german_election["Statistische Kennziffer"].str.len()>4)]

berlin_latest_election=latest_german_election[latest_german_election["Kreisfreie Stadt bzw. Stadtkreis, Landkreis bzw. Kreis"].astype(str).str.contains("Berlin")]
berlin_latest_election[berlin_latest_election.columns[3:]]=berlin_latest_election[berlin_latest_election.columns[3:]].astype(int)
berlin_df_added=pd.DataFrame(berlin_latest_election.sum()).T
berlin_df_added["Land"]="BE"
berlin_df_added["Statistische Kennziffer"]="11000"
berlin_df_added["Kreisfreie Stadt bzw. Stadtkreis, Landkreis bzw. Kreis"]="Berlin"
berlin_df_added[""]

/var/folders/55/79cxhkf56b38c317w6g5zkr0mmx5lp/T/ipykernel_11373/4293317095.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  berlin_latest_election[berlin_latest_election.columns[3:]]=berlin_latest_election[berlin_latest_election.columns[3:]].astype(int)

,Land,Statistische Kennziffer,"Kreisfreie Stadt bzw. Stadtkreis, Landkreis bzw. Kreis",Wahlberechtigte,Wähler,Ungültige,Gültige,CDU,SPD,AfD,...,III. Weg.1,Bündnis21.1,LIEBE.1,LKR.1,PdF,LfK,SSW.1,Team Todenhöfer.1,UNABHÄNGIGE.1,Volt.1
0,BE,11000,Berlin,2468919,1856903,31631,1825272,344838,417163,147134,...,0,0,0,1232,0,0,0,20168,0,11645

In [6]:
latest_german_election_columns=[]
for column in latest_german_election.columns:
    column=column.replace(".1","_Zweitstimme")
    latest_german_election_columns.append(column+"_2021")
latest_german_election=pd.concat([latest_german_election,berlin_df_added]).reset_index(drop=True)
latest_german_election.columns=latest_german_election_columns

latest_german_election_afd=latest_german_election[["Statistische Kennziffer_2021","Gültige_Zweitstimme_2021",'AfD_Zweitstimme_2021']]
latest_german_election_afd=latest_german_election_afd.dropna(subset=["Statistische Kennziffer_2021"])
latest_german_election_afd
election_dict["2021"]=latest_german_election_afd
latest_german_election_afd

    Statistische Kennziffer_2021 Gültige_Zweitstimme_2021 AfD_Zweitstimme_2021
0                          01001                    50818                 2756
1                          01002                   139961                 7023
2                          01003                   117674                 7807
3                          01004                    39971                 3751
4                          01051                    80616                 7098
..                           ...                      ...                  ...
397                        16074                    52510                12865
398                        16075                    49552                15071
399                        16076                    61146                16908
400                        16077                    52844                15576
401                        11000                  1826581               153694

[402 rows x 3 columns]

In [7]:
european_election_2019=pd.read_csv("../data/ew19_kerg.csv",skiprows=2, sep=';',dtype=str)
european_election_2019=european_election_2019[(european_election_2019["Nr"].str.len()>4)]

columnarray=[]
for columnname in european_election_2019.columns:
    
    if("Unnamed" in columnname):
        columnarray.append(previousrow+"_2014")
    else:
        columnarray.append(columnname+"_2019")
    previousrow=columnname
european_election_2019.columns=columnarray
european_election_2019=european_election_2019.dropna(subset=["Gebiet_2019"])
european_election_2019_afd=european_election_2019[["Nr_2019","Gültige_2019","Alternative für Deutschland_2019","Gültige_2014","Alternative für Deutschland_2014"]]
european_election_2019_afd[european_election_2019_afd["Nr_2019"]=="11000"]

,Nr_2019,Gültige_2019,Alternative für Deutschland_2019,Gültige_2014,Alternative für Deutschland_2014
346,11000,1507357,149177,1159666,91759

In [8]:
election_dict["2019"]=european_election_2019_afd

In [9]:
german_election_2017=pd.read_csv("../data/btw2017kreis.csv",skiprows=4, sep=';',dtype=str,encoding="latin")
german_election_2017=german_election_2017[(german_election_2017["Statistische Kennziffer"].str.len()>4)]

berlin_2017_election=german_election_2017[german_election_2017["Kreisfreie Stadt bzw. Stadtkreis, Landkreis bzw. Kreis"].astype(str).str.contains("Berlin")]
berlin_2017_election[berlin_2017_election.columns[3:]]=berlin_2017_election[berlin_2017_election.columns[3:]].astype(int)
berlin_2017_election=pd.DataFrame(berlin_2017_election.sum()).T
berlin_2017_election["Land"]="BE"
berlin_2017_election["Statistische Kennziffer"]="11000"
berlin_2017_election["Kreisfreie Stadt bzw. Stadtkreis, Landkreis bzw. Kreis"]="Berlin"
berlin_2017_election
german_election_2017_columns=[]
for column in german_election_2017.columns:
    column=column.replace(".1","_Zweitstimme")
    german_election_2017_columns.append(column+"_2017")
german_election_2017=pd.concat([german_election_2017,berlin_2017_election]).reset_index(drop=True)

german_election_2017.columns=german_election_2017_columns
german_election_2017_afd=german_election_2017[["Statistische Kennziffer_2017","Gültige_Zweitstimme_2017",'AfD_Zweitstimme_2017']]
german_election_2017_afd=german_election_2017_afd.dropna(subset=["Statistische Kennziffer_2017"])
election_dict["2017"]=german_election_2017_afd

/var/folders/55/79cxhkf56b38c317w6g5zkr0mmx5lp/T/ipykernel_11373/65852515.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  berlin_2017_election[berlin_2017_election.columns[3:]]=berlin_2017_election[berlin_2017_election.columns[3:]].astype(int)

In [10]:
german_election_2017_afd[german_election_2017_afd["Statistische Kennziffer_2017"]=="11000"]

    Statistische Kennziffer_2017 Gültige_Zweitstimme_2017 AfD_Zweitstimme_2017
402                        11000                  1869042               225170

In [11]:
german_election_2013=pd.read_csv("../data/btw2013kreis.csv",skiprows=4, sep=';',dtype=str,encoding="latin")
german_election_2013=german_election_2013[(german_election_2013["Statistische Kennziffer"].str.len()>4)]
german_election_2013[german_election_2013["Statistische Kennziffer"]=="11000"]

,Land,Statistische Kennziffer,"Kreisfreie Stadt bzw. Stadtkreis, Landkreis bzw. Kreis",Wahlbe-rechtigte,Wähler,Ungültige,Gültige,CDU,SPD,FDP,...,PSG,AfD.1,BIG.1,pro Deutschland.1,DIE RECHTE,DIE FRAUEN,FREIE WÄHLER.1,Nicht-\nwähler,PARTEI DER VERNUNFT.1,Die PARTEI.1
326,BE,11000,"Berlin, Stadt",2505718,1815415,29655,1785760,536332,455138,25867,...,965,88060,3509,5665,0,0,7531,0,0,18673

In [12]:

german_election_2013_columns=[]
for column in german_election_2013.columns:
    column=column.replace(".1","_Zweitstimme")
    german_election_2013_columns.append(column+"_2013")

german_election_2013.columns=german_election_2013_columns
german_election_2013_afd=german_election_2013[["Statistische Kennziffer_2013","Gültige_Zweitstimme_2013",'AfD_Zweitstimme_2013']]
german_election_2013_afd=german_election_2013_afd.dropna(subset=["Statistische Kennziffer_2013"])
election_dict["2013"]=german_election_2013_afd
german_election_2013_afd[german_election_2013_afd["Statistische Kennziffer_2013"]=="11000"]

    Statistische Kennziffer_2013 Gültige_Zweitstimme_2013 AfD_Zweitstimme_2013
326                        11000                  1787721                88060

In [40]:
german_election_2013_afd["Statistische Kennziffer_2013"]=german_election_2013_afd["Statistische Kennziffer_2013"].str.replace("03152","03159")

In [41]:
latest_german_election_afd

    Statistische Kennziffer_2021 Gültige_Zweitstimme_2021 AfD_Zweitstimme_2021
0                          01001                    50818                 2756
1                          01002                   139961                 7023
2                          01003                   117674                 7807
3                          01004                    39971                 3751
4                          01051                    80616                 7098
..                           ...                      ...                  ...
397                        16074                    52510                12865
398                        16075                    49552                15071
399                        16076                    61146                16908
400                        16077                    52844                15576
401                        11000                  1826581               153694

[402 rows x 3 columns]

In [42]:
german_elections_2013_2017=pd.merge(german_election_2013_afd,german_election_2017_afd,left_on="Statistische Kennziffer_2013",right_on="Statistische Kennziffer_2017", how="outer")
german_elections_2013_2017[german_elections_2013_2017["Statistische Kennziffer_2013"]=="11000"]

,Statistische Kennziffer_2013,Gültige_Zweitstimme_2013,AfD_Zweitstimme_2013,Statistische Kennziffer_2017,Gültige_Zweitstimme_2017,AfD_Zweitstimme_2017
325,11000,1787721,88060,11000,1869042,225170

In [43]:
german_elections_2013_2017_2021=pd.merge(german_elections_2013_2017,latest_german_election_afd,left_on="Statistische Kennziffer_2017",right_on="Statistische Kennziffer_2021", how="outer")
german_elections_2013_2017_2021[german_elections_2013_2017_2021["Statistische Kennziffer_2013"]=="11000"]

,Statistische Kennziffer_2013,Gültige_Zweitstimme_2013,AfD_Zweitstimme_2013,Statistische Kennziffer_2017,Gültige_Zweitstimme_2017,AfD_Zweitstimme_2017,Statistische Kennziffer_2021,Gültige_Zweitstimme_2021,AfD_Zweitstimme_2021
324,11000,1787721,88060,11000,1869042,225170,11000,1826581,153694

In [44]:
europe_elections=pd.merge(current_europe_election_afd,european_election_2019_afd,left_on="Nr_2024",right_on="Nr_2019",how="outer")
europe_elections

,Nr_2024,Gebiet_2024,Gültige Stimmen_2024,Alternative für Deutschland_2024,Nr_2019,Gültige_2019,Alternative für Deutschland_2019,Gültige_2014,Alternative für Deutschland_2014
0,01001,"Flensburg, Stadt",41552,4273,01001,39410,2477,25174,1583
1,01002,"Kiel, Landeshauptstadt",116547,9351,01002,109018,6459,75336,4418
2,01003,"Lübeck, Hansestadt",95954,10290,01003,90485,6773,62509,4334
3,01004,"Neumünster, Stadt",32737,5697,01004,28805,2761,27250,1960
4,01051,Dithmarschen,67527,11005,01051,57769,5121,42350,2325
...,...,...,...,...,...,...,...,...,...
396,16073,Saalfeld-Rudolstadt,49246,17307,16073,52848,14592,46150,4107
397,16074,Saale-Holzland-Kreis,45189,14404,16074,44098,10210,40150,3920
398,16075,Saale-Orla-Kreis,38324,14426,16075,41630,11264,37348,3114
399,16076,Greiz,52005,18399,16076,52058,13297,47189,4559
400,16077,Altenburger Land,43058,15893,16077,41901,11371,37657,3023

## THIS IS THE PROBLEM

In [45]:
europe_elections[europe_elections["Gebiet_2024"].astype(str).str.contains("Berlin")]

,Nr_2024,Gebiet_2024,Gültige Stimmen_2024,Alternative für Deutschland_2024,Nr_2019,Gültige_2019,Alternative für Deutschland_2019,Gültige_2014,Alternative für Deutschland_2014
324,11000,"Berlin, Stadt",1545022,179298,11000,1507357,149177,1159666,91759

In [46]:
afd_europe_elections=europe_elections[["Nr_2024","Gebiet_2024","Alternative für Deutschland_2014","Gültige_2014","Alternative für Deutschland_2019","Gültige_2019","Alternative für Deutschland_2024","Gültige Stimmen_2024"]]
afd_europe_elections

,Nr_2024,Gebiet_2024,Alternative für Deutschland_2014,Gültige_2014,Alternative für Deutschland_2019,Gültige_2019,Alternative für Deutschland_2024,Gültige Stimmen_2024
0,01001,"Flensburg, Stadt",1583,25174,2477,39410,4273,41552
1,01002,"Kiel, Landeshauptstadt",4418,75336,6459,109018,9351,116547
2,01003,"Lübeck, Hansestadt",4334,62509,6773,90485,10290,95954
3,01004,"Neumünster, Stadt",1960,27250,2761,28805,5697,32737
4,01051,Dithmarschen,2325,42350,5121,57769,11005,67527
...,...,...,...,...,...,...,...,...
396,16073,Saalfeld-Rudolstadt,4107,46150,14592,52848,17307,49246
397,16074,Saale-Holzland-Kreis,3920,40150,10210,44098,14404,45189
398,16075,Saale-Orla-Kreis,3114,37348,11264,41630,14426,38324
399,16076,Greiz,4559,47189,13297,52058,18399,52005
400,16077,Altenburger Land,3023,37657,11371,41901,15893,43058

In [47]:
german_elections_2013_2017_2021

,Statistische Kennziffer_2013,Gültige_Zweitstimme_2013,AfD_Zweitstimme_2013,Statistische Kennziffer_2017,Gültige_Zweitstimme_2017,AfD_Zweitstimme_2017,Statistische Kennziffer_2021,Gültige_Zweitstimme_2021,AfD_Zweitstimme_2021
0,01001,46265,1855,01001,49271,3702,01001,50818,2756
1,01002,130686,4778,01002,137368,9524,01002,139961,7023
2,01003,112029,4792,01003,117879,10461,01003,117674,7807
3,01004,39388,1965,01004,39861,4124,01004,39971,3751
4,01051,73649,3041,01051,77337,6626,01051,80616,7098
...,...,...,...,...,...,...,...,...,...
399,16074,49974,3594,16074,52285,12278,16074,52510,12865
400,16075,48979,3527,16075,50721,13452,16075,49552,15071
401,16076,61725,4714,16076,63402,16203,16076,61146,16908
402,16077,52148,3809,16077,54846,15061,16077,52844,15576
403,03156,44104,1557,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
europe_german_afd=pd.merge(afd_europe_elections,german_elections_2013_2017_2021,right_on="Statistische Kennziffer_2021",left_on="Nr_2024",how="outer")
europe_german_afd

,Nr_2024,Gebiet_2024,Alternative für Deutschland_2014,Gültige_2014,Alternative für Deutschland_2019,Gültige_2019,Alternative für Deutschland_2024,Gültige Stimmen_2024,Statistische Kennziffer_2013,Gültige_Zweitstimme_2013,AfD_Zweitstimme_2013,Statistische Kennziffer_2017,Gültige_Zweitstimme_2017,AfD_Zweitstimme_2017,Statistische Kennziffer_2021,Gültige_Zweitstimme_2021,AfD_Zweitstimme_2021
0,01001,"Flensburg, Stadt",1583,25174,2477,39410,4273,41552,01001,46265,1855,01001,49271,3702,01001,50818,2756
1,01002,"Kiel, Landeshauptstadt",4418,75336,6459,109018,9351,116547,01002,130686,4778,01002,137368,9524,01002,139961,7023
2,01003,"Lübeck, Hansestadt",4334,62509,6773,90485,10290,95954,01003,112029,4792,01003,117879,10461,01003,117674,7807
3,01004,"Neumünster, Stadt",1960,27250,2761,28805,5697,32737,01004,39388,1965,01004,39861,4124,01004,39971,3751
4,01051,Dithmarschen,2325,42350,5121,57769,11005,67527,01051,73649,3041,01051,77337,6626,01051,80616,7098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,16075,Saale-Orla-Kreis,3114,37348,11264,41630,14426,38324,16075,48979,3527,16075,50721,13452,16075,49552,15071
400,16076,Greiz,4559,47189,13297,52058,18399,52005,16076,61725,4714,16076,63402,16203,16076,61146,16908
401,16077,Altenburger Land,3023,37657,11371,41901,15893,43058,16077,52148,3809,16077,54846,15061,16077,52844,15576
402,NaN,NaN,879,17417,3874,19341,NaN,NaN,16056,22768,1130,16056,24248,4615,NaN,NaN,NaN
403,NaN,NaN,879,17417,3874,19341,NaN,NaN,03156,44104,1557,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
europe_german_afd=europe_german_afd.rename(columns={"Gültige Stimmen_2024":'Gültige_2024'})

In [50]:
perc_summed=europe_german_afd[europe_german_afd.columns[:2]]
for columnname in europe_german_afd.columns[2:]:
    if "Alternative" in columnname:
        perc_summed["eu_"+columnname[-4:]]=pd.to_numeric(europe_german_afd[columnname])*100/pd.to_numeric(europe_german_afd["Gültige_"+columnname[-4:]])
    if "AfD" in columnname:
        perc_summed["btw_"+columnname[-4:]]=pd.to_numeric(europe_german_afd[columnname])*100/pd.to_numeric(europe_german_afd["Gültige_Zweitstimme_"+columnname[-4:]])

europe_german_afd

/var/folders/55/79cxhkf56b38c317w6g5zkr0mmx5lp/T/ipykernel_11373/657282062.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  perc_summed["eu_"+columnname[-4:]]=pd.to_numeric(europe_german_afd[columnname])*100/pd.to_numeric(europe_german_afd["Gültige_"+columnname[-4:]])
/var/folders/55/79cxhkf56b38c317w6g5zkr0mmx5lp/T/ipykernel_11373/657282062.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  perc_summed["eu_"+columnname[-4:]]=pd.to_numeric(europe_german_afd[columnname])*100/pd.to_numeric(europe_german_afd["Gültige_"+columnname[-4:]])
/var/folders/55/79cxhkf56b38c317w6g5zkr0mmx5lp/T/ipykernel_11373/657282062.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  perc_summed["eu_"+columnname[-4:]]=pd.to_numeric(europe_german_afd[columnname])*100/pd.to_numeric(europe_german_afd["Gültige_"+columnname[-4:]])
/var/folders/55/79cxhkf56b38c317w6g5zkr0mmx5lp/T/ipykernel_11373/657282062.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  perc_summed["btw_"+columnname[-4:]]=pd.to_numeric(europe_german_afd[columnname])*100/pd.to_numeric(europe_german_afd["Gültige_Zweitstimme_"+columnname[-4:]])
/var/folders/55/79cxhkf56b38c317w6g5zkr0mmx5lp/T/ipykernel_11373/657282062.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  perc_summed["btw_"+columnname[-4:]]=pd.to_numeric(europe_german_afd[columnname])*100/pd.to_numeric(europe_german_afd["Gültige_Zweitstimme_"+columnname[-4:]])
/var/folders/55/79cxhkf56b38c317w6g5zkr0mmx5lp/T/ipykernel_11373/657282062.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  perc_summed["btw_"+columnname[-4:]]=pd.to_numeric(europe_german_afd[columnname])*100/pd.to_numeric(europe_german_afd["Gültige_Zweitstimme_"+columnname[-4:]])

,Nr_2024,Gebiet_2024,Alternative für Deutschland_2014,Gültige_2014,Alternative für Deutschland_2019,Gültige_2019,Alternative für Deutschland_2024,Gültige_2024,Statistische Kennziffer_2013,Gültige_Zweitstimme_2013,AfD_Zweitstimme_2013,Statistische Kennziffer_2017,Gültige_Zweitstimme_2017,AfD_Zweitstimme_2017,Statistische Kennziffer_2021,Gültige_Zweitstimme_2021,AfD_Zweitstimme_2021
0,01001,"Flensburg, Stadt",1583,25174,2477,39410,4273,41552,01001,46265,1855,01001,49271,3702,01001,50818,2756
1,01002,"Kiel, Landeshauptstadt",4418,75336,6459,109018,9351,116547,01002,130686,4778,01002,137368,9524,01002,139961,7023
2,01003,"Lübeck, Hansestadt",4334,62509,6773,90485,10290,95954,01003,112029,4792,01003,117879,10461,01003,117674,7807
3,01004,"Neumünster, Stadt",1960,27250,2761,28805,5697,32737,01004,39388,1965,01004,39861,4124,01004,39971,3751
4,01051,Dithmarschen,2325,42350,5121,57769,11005,67527,01051,73649,3041,01051,77337,6626,01051,80616,7098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,16075,Saale-Orla-Kreis,3114,37348,11264,41630,14426,38324,16075,48979,3527,16075,50721,13452,16075,49552,15071
400,16076,Greiz,4559,47189,13297,52058,18399,52005,16076,61725,4714,16076,63402,16203,16076,61146,16908
401,16077,Altenburger Land,3023,37657,11371,41901,15893,43058,16077,52148,3809,16077,54846,15061,16077,52844,15576
402,NaN,NaN,879,17417,3874,19341,NaN,NaN,16056,22768,1130,16056,24248,4615,NaN,NaN,NaN
403,NaN,NaN,879,17417,3874,19341,NaN,NaN,03156,44104,1557,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
perc_summed_resorted=perc_summed[["Nr_2024","Gebiet_2024","btw_2013","eu_2014","btw_2017","btw_2021","eu_2024"]]
perc_summed_resorted["11years"]=perc_summed_resorted["eu_2024"]/perc_summed_resorted["btw_2013"]
perc_summed_resorted["6years"]=perc_summed_resorted["eu_2024"]/perc_summed_resorted["btw_2017"]
perc_summed_resorted["3years"]=perc_summed_resorted["eu_2024"]/perc_summed_resorted["btw_2021"]

perc_summed_resorted

,Nr_2024,Gebiet_2024,btw_2013,eu_2014,btw_2017,btw_2021,eu_2024,11years,6years,3years
0,01001,"Flensburg, Stadt",4.009510,6.288234,7.513548,5.423275,10.283500,2.564777,1.368661,1.896179
1,01002,"Kiel, Landeshauptstadt",3.656092,5.864394,6.933201,5.017826,8.023373,2.194522,1.157239,1.598974
2,01003,"Lübeck, Hansestadt",4.277464,6.933402,8.874354,6.634431,10.723889,2.507067,1.208413,1.616399
3,01004,"Neumünster, Stadt",4.988829,7.192661,10.345952,9.384304,17.402328,3.488259,1.682042,1.854408
4,01051,Dithmarschen,4.129045,5.489965,8.567697,8.804704,16.297185,3.946963,1.902166,1.850963
...,...,...,...,...,...,...,...,...,...,...
399,16075,Saale-Orla-Kreis,7.201045,8.337796,26.521559,30.414514,37.642209,5.227326,1.419306,1.237640
400,16076,Greiz,7.637100,9.661150,25.555976,27.651850,35.379290,4.632556,1.384384,1.279455
401,16077,Altenburger Land,7.304211,8.027724,27.460526,29.475437,36.910679,5.053342,1.344136,1.252252
402,NaN,NaN,4.963106,5.046793,19.032498,NaN,NaN,NaN,NaN,NaN
403,NaN,NaN,3.530292,5.046793,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
perc_summed_resorted.sort_values(by=["11years"]).dropna().tail(50)

,Nr_2024,Gebiet_2024,btw_2013,eu_2014,btw_2017,btw_2021,eu_2024,11years,6years,3years
356,14523,Vogtlandkreis,6.653499,10.172211,26.421082,25.056007,34.105875,5.126006,1.290858,1.361186
385,16061,Eichsfeld,5.214995,5.913818,18.182986,19.683959,26.903442,5.158862,1.479594,1.366770
256,09279,Dingolfing-Landau,3.597576,6.485380,18.299781,13.673836,18.791576,5.223399,1.026874,1.374272
399,16075,Saale-Orla-Kreis,7.201045,8.337796,26.521559,30.414514,37.642209,5.227326,1.419306,1.237640
351,13075,Vorpommern-Greifswald,6.401912,7.842417,22.715704,21.978553,33.623840,5.252156,1.480202,1.529848
361,14627,Meißen,7.119960,12.159943,32.876558,29.770858,37.689096,5.293442,1.146382,1.265973
265,09376,Schwandorf,3.330487,7.336153,16.805760,13.219614,17.869863,5.365541,1.063318,1.351769
342,12071,Spree-Neiße,6.972134,9.546176,28.884640,27.394695,37.844710,5.427995,1.310202,1.381461
50,03452,Aurich,3.145421,4.428735,8.924106,8.226367,17.087931,5.432638,1.914806,2.077215
107,05915,"Hamm, Stadt",3.073981,4.469575,11.137809,9.236656,16.778533,5.458241,1.506448,1.816516
359,14625,Bautzen,7.174274,10.819729,32.450788,31.374122,39.226450,5.467655,1.208798,1.250280
45,03402,"Emden, Stadt",3.019058,4.761219,9.985245,8.103586,16.525706,5.473796,1.655012,2.039308
249,09272,Freyung-Grafenau,3.592971,7.343759,20.086699,15.082383,19.743366,5.494997,0.982907,1.309035
164,07317,"Pirmasens, kreisfreie Stadt",4.600859,6.303806,16.129948,15.412603,25.289436,5.496677,1.567856,1.640828
357,14524,Zwickau,6.312210,9.606917,25.982086,25.278081,34.804157,5.513783,1.339544,1.376851
348,13072,Landkreis Rostock,5.092020,6.707022,18.164781,17.996368,28.213684,5.540765,1.553208,1.567743
327,12051,"Brandenburg an der Havel, Stadt",4.433240,7.797844,17.255853,15.765175,24.699833,5.571509,1.431389,1.566734
17,03102,"Salzgitter, Stadt",3.917159,5.789967,16.437597,13.472299,22.032575,5.624632,1.340377,1.635398
352,13076,Ludwigslust-Parchim,5.095536,5.832088,17.708401,17.897150,28.988022,5.688905,1.636964,1.619700
355,14522,Mittelsachsen,6.365300,9.411100,30.357096,29.425865,36.465521,5.728799,1.201219,1.239234
388,16064,Unstrut-Hainich-Kreis,5.320471,6.140186,23.218600,24.732097,30.506007,5.733704,1.313861,1.233458
298,09674,Haßberge,2.871812,4.799725,12.860026,11.737942,16.505084,5.747273,1.283441,1.406131
261,09372,Cham,3.205563,6.934076,18.009561,13.794964,18.553510,5.787910,1.030203,1.344948
383,16054,"Suhl, Stadt",5.333718,7.864328,19.855286,22.522481,31.147237,5.839686,1.568713,1.382940
333,12062,Elbe-Elster,5.949794,7.243253,24.196712,24.603276,35.069231,5.894192,1.449339,1.425389
347,13071,Mecklenburgische Seenplatte,5.384794,6.141909,19.584691,20.716851,31.942322,5.931949,1.630984,1.541852
365,14730,Nordsachsen,6.138177,8.123994,26.853290,27.230653,36.960093,6.021347,1.376371,1.357297
337,12066,Oberspreewald-Lausitz,5.825636,8.230509,25.853797,25.093587,35.438194,6.083146,1.370715,1.412241
392,16068,Sömmerda,5.815935,6.778461,24.246034,27.019912,35.381037,6.083465,1.459251,1.309443
339,12068,Ostprignitz-Ruppin,4.891873,6.697613,18.484107,18.234081,29.964131,6.125288,1.621075,1.643304
386,16062,Nordhausen,4.994486,5.535335,21.123099,21.989252,32.644528,6.536114,1.545442,1.484567
387,16063,Wartburgkreis,4.993155,6.280176,22.540941,24.302150,32.730381,6.555050,1.452041,1.346810
390,16066,Schmalkalden-Meiningen,5.154885,6.675022,21.624943,25.487334,33.816433,6.560075,1.563770,1.326794
370,15082,Anhalt-Bitterfeld,5.223536,8.067167,22.395410,22.059389,34.630945,6.629790,1.546341,1.569896
379,15091,Wittenberg,4.669506,6.644315,19.935446,19.864251,31.385424,6.721359,1.574353,1.579995
51,03453,Cloppenburg,2.442619,3.701259,9.060422,9.549417,16.635052,6.810333,1.836013,1.741997
344,12073,Uckermark,4.709158,6.416065,20.790719,21.157973,32.771886,6.959181,1.576275,1.548914
341,12070,Prignitz,4.340865,6.016523,18.344784,19.222908,31.363186,7.225100,1.709651,1.631553
396,16072,Sonneberg,5.250094,6.837607,25.572187,27.982879,38.398025,7.313778,1.501554,1.372197
389,16065,Kyffhäuserkreis,4.859735,4.907607,24.990595,26.939715,35.670425,7.339994,1.427354,1.324083
393,16069,Hildburghausen,4.843328,6.565227,25.218531,28.809226,36.386693,7.512746,1.442855,1.263022
373,15085,Harz,3.809874,5.453199,16.462188,17.825236,29.765958,7.812846,1.808141,1.669877
369,15081,Altmarkkreis Salzwedel,3.727223,5.051071,15.550902,17.738373,29.151317,7.821189,1.874574,1.643404
376,15088,Saalekreis,4.282031,6.744952,23.996481,23.583283,34.863700,8.141861,1.452867,1.478323
371,15083,Börde,3.913043,5.379913,18.772037,20.710929,32.062358,8.193714,1.707985,1.548089
374,15086,Jerichower Land,3.767512,5.050367,18.975840,19.055941,30.897449,8.201023,1.628252,1.621408
372,15084,Burgenlandkreis,4.255473,6.865122,24.334219,24.979944,36.061320,8.474103,1.481918,1.443611
375,15087,Mansfeld-Südharz,4.126103,6.087456,23.893544,23.967010,36.310290,8.800142,1.519669,1.515011
377,15089,Salzlandkreis,3.894165,5.312654,20.407634,21.735104,34.370885,8.826253,1.684217,1.581354
378,15090,Stendal,3.507087,5.263678,17.682868,20.220931,33.050758,9.423991,1.869084,1.634482

In [53]:
perc_summed_resorted.sort_values(by=["6years"]).dropna()

,Nr_2024,Gebiet_2024,btw_2013,eu_2014,btw_2017,btw_2021,eu_2024,11years,6years,3years
223,09162,"München, Landeshauptstadt",4.497582,7.792685,8.365956,4.543810,6.662299,1.481307,0.796358,1.466236
224,09163,"Rosenheim, kreisfreie Stadt",5.264340,10.887149,14.691492,8.696648,11.770223,2.235840,0.801159,1.353421
203,08311,"Freiburg im Breisgau, Stadtkreis",3.693911,5.695366,7.246919,4.353852,5.885669,1.593344,0.812162,1.351830
233,09179,Fürstenfeldbruck,5.261929,9.183247,10.886503,6.221682,9.122998,1.733775,0.838010,1.466323
162,07315,"Mainz, kreisfreie Stadt",4.314629,6.000879,7.331953,4.351049,6.219183,1.441418,0.848230,1.429353
...,...,...,...,...,...,...,...,...,...,...
369,15081,Altmarkkreis Salzwedel,3.727223,5.051071,15.550902,17.738373,29.151317,7.821189,1.874574,1.643404
55,03457,Leer,3.399653,5.292650,9.220794,8.851753,17.367766,5.108688,1.883543,1.962071
4,01051,Dithmarschen,4.129045,5.489965,8.567697,8.804704,16.297185,3.946963,1.902166,1.850963
50,03452,Aurich,3.145421,4.428735,8.924106,8.226367,17.087931,5.432638,1.914806,2.077215
60,03462,Wittmund,3.583448,4.963483,8.603443,8.543195,16.528545,4.612469,1.921155,1.934703

In [54]:
perc_summed_resorted[perc_summed_resorted["Nr_2024"]=="03159"]

,Nr_2024,Gebiet_2024,btw_2013,eu_2014,btw_2017,btw_2021,eu_2024,11years,6years,3years
25,03159,Göttingen,3.71789,5.021836,8.098812,6.349654,10.797233,2.904129,1.333187,1.700444

In [55]:
threeyears=perc_summed_resorted.sort_values(by=["3years"])
threeyears[threeyears["Gebiet_2024"].astype(str).str.contains("Berlin")]

,Nr_2024,Gebiet_2024,btw_2013,eu_2014,btw_2017,btw_2021,eu_2024,11years,6years,3years
324,11000,"Berlin, Stadt",4.925825,7.912537,12.047348,8.4143,11.604883,2.355927,0.963273,1.379186

In [56]:
threeyears.to_csv("afd_three_years.csv",index=False)
threeyears[threeyears["Nr_2024"]=="03159"]

,Nr_2024,Gebiet_2024,btw_2013,eu_2014,btw_2017,btw_2021,eu_2024,11years,6years,3years
25,03159,Göttingen,3.71789,5.021836,8.098812,6.349654,10.797233,2.904129,1.333187,1.700444

In [78]:
landwirtschaft=pd.read_csv("../data/landwirtschaft.csv",sep=";")
ags_filtered=landwirtschaft[landwirtschaft["Unnamed: 0"].str.len()==5]
ags_filtered["Unnamed: 2"]=pd.to_numeric(ags_filtered["Unnamed: 2"])
ags_filtered_landwirtschaft=ags_filtered[ags_filtered["Unnamed: 2"]<100]
ags_filtered_landwirtschaft["ags_number"]=pd.to_numeric(ags_filtered_landwirtschaft["Unnamed: 0"])
landwirtschaft_west=ags_filtered_landwirtschaft[ags_filtered_landwirtschaft["ags_number"]<11000]

/var/folders/55/79cxhkf56b38c317w6g5zkr0mmx5lp/T/ipykernel_11373/3909104930.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ags_filtered["Unnamed: 2"]=pd.to_numeric(ags_filtered["Unnamed: 2"])
/var/folders/55/79cxhkf56b38c317w6g5zkr0mmx5lp/T/ipykernel_11373/3909104930.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ags_filtered_landwirtschaft["ags_number"]=pd.to_numeric(ags_filtered_landwirtschaft["Unnamed: 0"])

In [79]:
landwirtschaft_west.to_csv("landwirtschaft_west.csv",index=False)

In [98]:
landwirtschaft_west["bl"]=landwirtschaft_west["Unnamed: 0"].str[:2]
landwirtschaft_west["bl"].str.contains(|)

/var/folders/55/79cxhkf56b38c317w6g5zkr0mmx5lp/T/ipykernel_11373/4206359253.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  landwirtschaft_west["bl"]=landwirtschaft_west["Unnamed: 0"].str[:2]

,Unnamed: 0,"Anteil ET Land- u. Forstwirtschaft, Fischerei (%)",Unnamed: 2,ags_number,bl
10,01002,Kiel,0.1,1002,01
11,01003,Lübeck,0.2,1003,01
12,01004,Neumünster,0.7,1004,01
13,01051,Dithmarschen,5.5,1051,01
14,01053,Herzogtum Lauenburg,2.6,1053,01
...,...,...,...,...,...
328,10042,Merzig-Wadern,1.4,10042,10
329,10043,Neunkirchen,0.4,10043,10
330,10044,Saarlouis,0.5,10044,10
331,10045,Saarpfalz-Kreis,0.4,10045,10
332,10046,St. Wendel,1.0,10046,10

In [93]:
landwirtschaft_west_merged=pd.merge(perc_summed_resorted,landwirtschaft_west,left_on="Nr_2024",right_on="Unnamed: 0")
landwirtschaft_west_merged

,Nr_2024,Gebiet_2024,btw_2013,eu_2014,btw_2017,btw_2021,eu_2024,11years,6years,3years,Unnamed: 0,"Anteil ET Land- u. Forstwirtschaft, Fischerei (%)",Unnamed: 2,ags_number
0,01002,"Kiel, Landeshauptstadt",3.656092,5.864394,6.933201,5.017826,8.023373,2.194522,1.157239,1.598974,01002,Kiel,0.1,1002
1,01003,"Lübeck, Hansestadt",4.277464,6.933402,8.874354,6.634431,10.723889,2.507067,1.208413,1.616399,01003,Lübeck,0.2,1003
2,01004,"Neumünster, Stadt",4.988829,7.192661,10.345952,9.384304,17.402328,3.488259,1.682042,1.854408,01004,Neumünster,0.7,1004
3,01051,Dithmarschen,4.129045,5.489965,8.567697,8.804704,16.297185,3.946963,1.902166,1.850963,01051,Dithmarschen,5.5,1051
4,01053,Herzogtum Lauenburg,5.519451,7.506120,10.218959,8.354725,14.298118,2.590496,1.399176,1.711381,01053,Herzogtum Lauenburg,2.6,1053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,10042,Merzig-Wadern,5.061501,6.097973,9.262831,9.681663,15.402580,3.043086,1.662837,1.590902,10042,Merzig-Wadern,1.4,10042
312,10043,Neunkirchen,5.784983,7.222517,10.904781,11.328987,17.895145,3.093379,1.641037,1.579589,10043,Neunkirchen,0.4,10043
313,10044,Saarlouis,5.291062,6.669882,10.063032,10.193649,15.804553,2.987029,1.570556,1.550431,10044,Saarlouis,0.5,10044
314,10045,Saarpfalz-Kreis,5.599991,7.345558,11.290848,10.687327,16.321361,2.914534,1.445539,1.527170,10045,Saarpfalz-Kreis,0.4,10045
315,10046,St. Wendel,4.808067,5.875297,8.254967,8.649913,13.310161,2.768298,1.612382,1.538762,10046,St. Wendel,1.0,10046

In [94]:
!pip install scipy

Requirement already satisfied: scipy in /Users/maier-borst.h/Documents/CodeRelated/HBDataviz/2024/23_EuropawahlAfD/Wrangle/lib/python3.9/site-packages (1.13.1)
Requirement already satisfied: numpy<2.3,>=1.22.4 in /Users/maier-borst.h/Documents/CodeRelated/HBDataviz/2024/23_EuropawahlAfD/Wrangle/lib/python3.9/site-packages (from scipy) (1.26.4)
WARNING: You are using pip version 21.2.4; however, version 24.0 is available.
You should consider upgrading via the '/Users/maier-borst.h/Documents/CodeRelated/HBDataviz/2024/23_EuropawahlAfD/Wrangle/bin/python3 -m pip install --upgrade pip' command.

In [95]:
import scipy

In [96]:
from scipy import stats
res = stats.spearmanr(landwirtschaft_west_merged["Unnamed: 2"], landwirtschaft_west_merged["11years"])
res

SignificanceResult(statistic=0.35845332241072636, pvalue=5.160408241438454e-11)

In [97]:
res = stats.spearmanr(landwirtschaft_west_merged["Unnamed: 2"], landwirtschaft_west_merged["6years"])
res

SignificanceResult(statistic=0.27877926949661447, pvalue=4.7475732503974817e-07)